### ISSUE TITLE
Unable to see @ symbol

### ISSUE THREAD

**Issue by Powerhelmsman** [MicrosoftDocs/vsts-docs#1023]
The issue is submitted by @nitu1702 from https://github.com/MicrosoftDocs/feedback/issues/427

Using Version 15.117.27414.0
I created some tasks in TFS and assigned to my team members.
Team member could see it in his list and change status, update comments.
But the team member cannot see '@' for tagging. Because of this, I as a manager do not get mails on what he has updated.
What could be the reason that he cannot tag people in discussions ?
To Reproduce
Go to '...'
Click on '....'
Scroll down to '....'
See error
Expected behavior
Screenshots
Desktop (please complete the following information):
Smartphone (please complete the following information):
Additional context

**Comment by steved0x** [comment]
@Powerhelmsman The GitHub issues in this repo are for documentation feedback for VSTS issues, similar to the doc feedback repo as the original issue: https://github.com/MicrosoftDocs/feedback/issues/427 . Please submit this bug report here: https://developercommunity.visualstudio.com/spaces/21/index.html

If I have misunderstood, and this issue is related to documentation feedback, please let me know which article it goes with so I can assign it to the right author for review.

Thank you

Steve

**Comment by Powerhelmsman** [comment]
@nitu1702 for awareness. He is original user.
