### ISSUE TITLE
Need higher version

### ISSUE THREAD

**Issue by adnanebrahimi** [MicrosoftDocs/vsts-docs#1041]
Hello,
For building angular 6, need a higher version of Node.js, see the error log:

You are running version v6.9.1 of Node.js, which is not supported by Angular CLI v6.
The official Node.js version that is supported is 8.9 and greater.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c00d3b8-64c1-9f1b-83f8-62d8cf07817b
* Version Independent ID: 5fcdebed-cfb8-c5a6-d807-1315b2db5e57
* Content: [npm](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/package/npm?view=vsts)
* Content Source: [docs/pipelines/tasks/package/npm.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/package/npm.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by JohannesEH** [comment]
@adnanebrahimi you can use a newer version of Node run the "Node Tool Installer" task before running your NPM tasks.

**Comment by thomps23** [comment]
Please accept our apology for the significant delay in addressing this issue.

It looks like you're working through an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
