### ISSUE TITLE
Variable inside variable?

### ISSUE THREAD

**Issue by thomasmktong** [MicrosoftDocs/vsts-docs#1054]
I would like to get Release.TriggeringArtifact.Alias first and use its value to get the build ID, is this possible? thanks.
```
$(Release.Artifacts.$(Release.TriggeringArtifact.Alias).BuildId)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 611642f0-881f-10b9-ae94-3c562001d1f0
* Version Independent ID: 41efb94b-4c7a-64a3-b23b-70c8634ae727
* Content: [Variables in Release Management](https://docs.microsoft.com/en-us/vsts/pipelines/release/variables?view=vsts&tabs=batch#default-variables)
* Content Source: [docs/pipelines/release/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/variables.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by thomasmktong** [comment]
Thanks, I am currently using the following Powershell as workaround:

```
$a = "$(Release.TriggeringArtifact.Alias)"
$x = ("RELEASE_ARTIFACTS_" + $a + "_DEFINITIONID")
Write-Host "Get Env Var $x"
$buildId = (get-item env:$x).Value
Write-Host "Build ID is $buildId"
Write-Host "##vso[task.setvariable variable=buildId]$buildId"
```

**Comment by andreasblueher** [comment]
I ran into the same issue/question, struggeled for quite some time and found help on stackoverflow https://stackoverflow.com/questions/53191250/access-sourcebranchname-in-release-pipeline and I would really appreciate if you could add the (Get-Item env:$x) example into this docu, because it is no obvious on how to get it given the examples.

**Comment by andreasblueher** [comment]
Since this isn't resovled in my opinion, I'm not sure on how to reactivate it.

**Comment by thomps23** [comment]
Marking as doc-bug for triage, see the following:

> @azooinmyluggage I ran into the same issue/question, struggeled for quite some time and found help on stackoverflow https://stackoverflow.com/questions/53191250/access-sourcebranchname-in-release-pipeline and I would really appreciate if you could add the (Get-Item env:$x) example into this docu, because it is no obvious on how to get it given the examples.

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
