### ISSUE TITLE
Link to an existing work item - TOPIC UNDER REVISION

### ISSUE THREAD

**Issue by chataylor** [MicrosoftDocs/vsts-docs#1078]
We have recently made updates to the existing "Add a link" experience, including separating link types based on the artifact the user chooses to link to first. We have also modernized the linking experience to leverage our Search APIs. Now, you can easily add a work item link via recent-activity based suggestions and inline add. To add multiple work item links, you CANNOT do so by using comma separated IDs. Instead, please add them one at a time using the new inline add experience.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ff7ea40-1067-7e76-e04e-5cbf79ca5dd7
* Version Independent ID: 5cea6861-0031-f51f-522b-a8b2488eaf50
* Content: [Add links to several work items - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/work/backlogs/add-link?view=vsts&tabs=browser#link-to-an-existing-work-item)
* Content Source: [docs/work/backlogs/add-link.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/work/backlogs/add-link.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by savyk** [comment]
I already miss adding multiple items at the same time via comma separated IDs.  Many times I am working with batches of data which are much faster to input all at once instead of waiting for the new search API to find each one individually and allow it to link.  Also, I see that the query function is no longer working.  Again, with batches of data, I use the query to generate results once and then want to link all items in the query at one time.  The search API makes me type in my search criteria for every item I want to link (type in, search, select it to link, then type in again, search again, select to link again, etc.).  Is there going to be an acceptable manner to quickly link many items at once?

**Comment by KathrynEE** [comment]
Closing this issue. Topic has been updated. @savyk - My understanding is that the product team is looking at further improvements to address your issue.

**Comment by chataylor** [comment]
@savyk Thank you for reaching out to the team. I certainly apologize for any frustration you're experiencing with the new Add a Link experience. We understand this change in behavior and decision to remove query support does force some of our users into a new way of working. Our hope, however, is as we continue to improve the simplicity of quickly finding and linking a work item that this new way of working supports the majority of our users linking needs. As @KathrynEE mentioned, we are also continuing to monitor feedback, such as yours, to determine what continuous improvements we can make.
