### ISSUE TITLE
Linking a work item to a git branch from the command line

### ISSUE THREAD

**Issue by seangwright** [MicrosoftDocs/vsts-docs#1079]
In the documentation here it is stated

`The recommended method is to drive development from the work item or add the work item ID when creating branches, commits (git), changesets (TFVC), pull requests (git). `

I know there is a convention for linking a work item to a commit using `#workItemId` in the commit message, but often a work item is not a single commit, but instead multiple commits (basically a branch).

Is there a way from the command line (using git) to link a work item to a branch?

Example: `git checkout -b fix/add-new-user-account-button-#34` where 34 is the work item id? Or do I have to use the VS Team Explorer to make these connections?

Are the rules for how work items and git history is connected and are those rules documented here?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3167d770-e6d3-dde7-2a9f-89967fb49c58
* Version Independent ID: 66c7f3b8-6de6-47ad-c1fa-94fb98bdac69
* Content: [Link work items to support traceability - VSTS & TFS](https://docs.microsoft.com/en-us/vsts/work/track/link-work-items-support-traceability?view=vsts&tabs=new-web-form)
* Content Source: [docs/work/track/link-work-items-support-traceability.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/work/track/link-work-items-support-traceability.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by steved0x** [comment]
@sgwatgit Let me see if I can find out, I personally associate my branches with work items by creating the branch from within the work item, so to me that means it must be possible, let me find out if/how we can do it from the command line.

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
