### ISSUE TITLE
priority and who is working on it

### ISSUE THREAD

**Issue by rogatec** [MicrosoftDocs/vsts-docs#1082]
As you recommend at least two reviewers should be added to the branch policy.
We created a review-team with 3 members and the policy says that the team must accept the pull request.
Now, how can one of the reviewer from the team see, if another guy is already working on reviewing the pull request?
Is there an option to set a "flag" that the pull request is already "under review".

The second (every important) question is: How can we prioritize open pull requests?

Additional note: we are working on a TFS 2017 server with update 3 (not VSTS)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 028e7b61-62e4-a10e-e420-3535f7843f0e
* Version Independent ID: 1a6fdbe7-5ba4-a7f8-1b2e-271289a7b9fd
* Content: [Review and merge code with pull requests](https://docs.microsoft.com/en-us/vsts/git/pull-requests?view=vsts)
* Content Source: [docs/git/pull-requests.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/git/pull-requests.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@rogatec Good questions, there is not a "built-in" way to set a PR as being under review, but you could use Pull Request labels to indicate you are starting a review, such as `In review by Steve`, and you could also indicate priorities in a pull request label. This is a relatively new feature and is documented here: [Help reviewers using pull request labels](https://docs.microsoft.com/en-us/vsts/git/pull-requests?view=vsts#help-reviewers-using-pull-request-labels). Let me see if I can find out any other information, or if there are any related upcoming features on the [VSTS Features Timeline](https://docs.microsoft.com/en-us/vsts/release-notes/#features-under-development)

**Comment by rogatec** [comment]
@steved0x Thanks for your reply and sorry for the dumb question, but where is the label section in the pull request? ;) - when creating a pull request I don't see this option which is shown on the documentation screen [Add pull request label](https://docs.microsoft.com/en-us/vsts/git/_img/pull-requests/add-pull-request-label.png?view=vsts)

**Comment by steved0x** [comment]
@rogatec My apologies, I saw that you were on TFS 2017 Update 3 but neglected to verify that when I was looking up Pull Request Labels - the Pull Request Labels were added in [TFS 2018 Update 2](https://docs.microsoft.com/en-us/visualstudio/releasenotes/tfs2018-update2#help-reviewers-using-pull-request-labels).

I guess an alternative would be to update the PR title for one you are reviewing and put your initials or something like that, so that the title would contain the pending reviewer information. Kind if like putting a "WIP" prefix for PRs that are a "Work in progress" and not ready for review.

Let me check with our product group team to see if they have any suggestions for managing PR priority - right now I think it just provides a list without many (or any) sorting capability, although there is some filtering.

**Comment by mmitrik** [comment]
@rogatec The suggestions that @steved0x made are the best options we have right now.

The feature you've suggested (a flag to indicate "in review") is something we've heard before, but it isn't currently a priority fo us.  I'd encourage you to [file a suggestion on our UserVoice site](https://visualstudio.uservoice.com/forums/330519-visual-studio-team-services/) to help us gauge the interest from others in the community.

Thanks!

**Comment by rogatec** [comment]
@mmitrik  I created a [suggestion](https://visualstudio.uservoice.com/forums/330519-visual-studio-team-services/suggestions/34743457-code-review-needs-a-flag-for-being-under-review), maybe there will be enough upvotes to encourage you to implement this feature.
@steved0x We will then upgrade our tfs server to 2018 in the upcoming weeks. Thank you for your suggestions and we will then stick to it.
