### ISSUE TITLE
Migrate TFS Release notes from Visual Studio docs to here

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/vsts-docs#1123]
Right now they live with the Visual Studio release notes like https://docs.microsoft.com/en-us/visualstudio/releasenotes/tfs2017-update2 although not in the actual visualstudio-docs repo.

It seems like every time I need to find these pages it takes quite awhile since it's not found in any site navigation and the vsts-docs repo might be a better home.

**Comment by steved0x** [comment]
@nschonni That seems like a better place, I will pass this along, I don't use those pages very often (unless I am providing a link to a question asking when feature XYZ was added) and then I always just Bing "TFS Release notes".

**Comment by nschonni** [comment]
@steved0x any movement on getting these migrated?

**Comment by steved0x** [comment]
Coming back to this after a delay, it looks like the TFS release notes are now on docs here:

https://docs.microsoft.com/en-us/azure/devops/server/release-notes/tfs?view=azure-devops

But clicking through, the individual pages are still on the /visualstudio/ path except for the 2019 release notes which are on /azure/devops/. I'm not sure of the status of that.

That is owned by another team now and it looks like they have started up the process of creating a new public repo here: https://github.com/MicrosoftDocs/azure-devops-server-docs to tracl issues and contributions to this content (which is a gap that we have had since the TFS server content wasn't included in the public vsts-docs repo)

**Comment by steved0x** [comment]
OK I tried to use the move issue feature but I don't have the right permissions apparently, I recommend to file this issue over on that repo, and I greatly apologize for this long delay in responding.

**Comment by nschonni** [comment]
That page is still just a list of the releases. The content is over on the /visualstudio/ URL. When you click through to any of the acutal release notes there, they aren't even shown in the left hand menu any more
