### ISSUE TITLE
How to Create Artifacts for Console Application Solution

### ISSUE THREAD

**Issue by Mahek1331** [MicrosoftDocs/vsts-docs#1138]
Hi , 

I am facing an Issue , I am trying to create a build definition for my console application (which is used for deploy webjob- we are doing it manually since log , solution not upgraded to VS Webjob). I Could not able to create Artifacts for the same solution . Could you please help me on this .

Please let me know if you need any other Information . 

Regards
Mahek

**Comment by steved0x** [comment]
@Mahek1331 The GitHub issues in this repository are intended for documentation feedback. Can you let me know which article your feedback goes with, so I can forward your comments to the right author? Thank you.

**Comment by steved0x** [comment]
I'm closing this issue since it is not associated with a topic. To continue the discussion, please open a new issue that is associated with a topic by browsing to the topic on docs.microsoft.com and choosing **Content feedback** at the bottom. Thank you for your feedback.

![image](https://user-images.githubusercontent.com/1580889/42953695-fd174150-8b48-11e8-94de-26924ca79c71.png)
