### ISSUE TITLE
VSTS extension`s key (certificate)

### ISSUE THREAD

**Issue by sashmen5** [MicrosoftDocs/vsts-docs#1141]
Hello! 
I am developing VSTS extension. 
I ran into a problem automatic fetching my extension’s key. 

This guide: 
https://docs.microsoft.com/en-us/vsts/extend/develop/auth?view=vsts#get-your-extensions-key
explains how to get key from UI.
After every update of extension this key updating too.
How can I get new generated key from some code or api (without using UI)?

Thanks a lot.

**Comment by elbatk** [comment]
Hi @sashmen5 , I know it's been a while here but it's a good question. Pinging @matthewisabel here to see if we can get an answer for ya!

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
