### ISSUE TITLE
My build didn't run. What happened? is confusing

### ISSUE THREAD

**Issue by thatnerdyguy** [MicrosoftDocs/vsts-docs#1174]
What does "signed in" here mean? Not explicitly signed out? If I signed in with my user name/pw a week ago, and didn't explicitly sign out, do my builds keep working? We are configured with CI build triggers on a VSTS hosted git, and haven't seen any issues with builds not running.... from this section it seems like that is just a happy accident.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build definition triggers](https://docs.microsoft.com/en-us/vsts/pipelines/build/triggers?view=vsts#build-completion-triggers)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by andyjlewis** [comment]
Thank you for the feedback. "Sign in" just means to view any page in your VSTS account. I made a small change to the doc that should be published in next day or so.

**Comment by cocowalla** [comment]
Any chance you could add the _reasoning_ behind this (very annoying) 'feature'?

**Comment by andyjlewis** [comment]
In short we are conserving resources for active teams rather than spending them on accounts that are not active or abandoned. That said, we've made some improvements to this story so I've added a backlog item to update this passage.

**Comment by cocowalla** [comment]
This *kind of* makes, some sense, but what about teams that are regularly pushing code to Azure DevOps git repos? They might not need to login the web portal very often, but are not inactive or abandoned - they'd still expect scheduled builds/releases to run, and would be rather confused when they didn't.

I'd like to make a couple of suggestions:

1. For now, it would be good to at least show some kind of text when setting up a scheduled build - this would let users know that scheduled builds are finicky and don't work as they expect. That's something that can be done quickly, and would be helpful now

2. Change this oddball policy! At the least, it would be good to extend the inactivity timeout to something like 2 weeks instead of 2 days. Longer term, it would be good to consider other things as "activity", such as pushing code to a git repo

**Comment by thomps23** [comment]
@cocowalla You can submit this feature improvement idea for consideration at the [following location](https://developercommunity.visualstudio.com/content/idea/post.html?space=21).

**Comment by cocowalla** [comment]
[Done](https://developercommunity.visualstudio.com/idea/579192/dont-prevent-scheduled-builds-from-running-if-the.html)

**Comment by andyjlewis** [comment]
Thanks @cocowalla for the feedback and for taking the time to request the feature improvement! I've got the doc concern on our backlog, so closing this issue.
