### ISSUE TITLE
How to describe a inputDescriptors in action which need to get from outside service?

### ISSUE THREAD

**Issue by LarryZhangy** [MicrosoftDocs/vsts-docs#1189]
Like the jenkins consumer, in triggerGenericBuild action ,the inputValues of build is get from the jenkins instance. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 758bed7c-374d-996e-ebff-c68528a823ca
* Version Independent ID: 81777b37-38ab-a7df-6eaa-7aa6bcd1058c
* Content: [Create a consumer service for service hooks](https://docs.microsoft.com/en-us/vsts/extend/develop/add-service-hook?view=vsts)
* Content Source: [docs/extend/develop/add-service-hook.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/add-service-hook.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Adding @willsmythe to take a look at this.

**Comment by thomps23** [comment]
Please accept our apology for the significant delay in addressing this issue.

It looks like you're working through an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
