### ISSUE TITLE
Is there a release variable which can be used to identify if the CI build was a scheduled build?

### ISSUE THREAD

**Issue by karann-jain** [MicrosoftDocs/vsts-docs#1191]
I want to run security tests which takes a couple of hours to run, I want to run static tests as part of build and dynamic as part of deployment. I plan to schedule this to run nightly. I am using custom variables in my build definition to run the phase only for nightly build.

How do i do the same for release? is there a variable which i use to differentiate between if the build was scheduled or due to a commit?

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by thomps23** [comment]
Please accept our apology for the significant delay in addressing this issue.

It looks like you're working through an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
