### ISSUE TITLE
Variable Group Links to Build settings Keeps disappearing

### ISSUE THREAD

**Issue by PgxBaku** [MicrosoftDocs/vsts-docs#1196]
I created a variable group.  I then create a build.  Then link the variable group to the build.  I then do a build and it builds fine.  The second time I do a build, the link disappears and I lose all my variables.   
Why is this happening?  I can't seem to save the link variable groups to make it last more than 1 build.  
I would go  back to my build and refresh and the link to the variable group would be gone??? 

Is this how it is supposed to work?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4827aa99-ae62-bd63-6f2f-a87a4065ed27
* Version Independent ID: c9e461ee-7f42-3503-9460-18fa3a807bbb
* Content: [Variable groups for VSTS and TFS](https://docs.microsoft.com/en-us/vsts/pipelines/library/variable-groups?view=vsts)
* Content Source: [docs/pipelines/library/variable-groups.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/variable-groups.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by PgxBaku** [comment]
Sorry, I forgot to mention I have TFS 2018 Update 2 installed.

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by ashokirla** [comment]
Hi @PgxBaku 
Can you please share some snapshots about the issue.
Can you also verify the build definition history to see if variable group has been unlinked.
Can you also check if you see the same issue in Release.

**Comment by Paul7Peterson** [comment]
This keeps happening...

**Comment by Paul7Peterson** [comment]
In order to provide a little bit more context:
- I'm deploying two Node apps to the **same agent** (own server). [And I think the issue can come from here]
- I'm using ENV variables with the same name (like 'PORT', or TypeORM ENV config variables) in different libraries (one per app).
- The apps have different repos within the same project, different build pipelines, and different release pipelines. Each one pointing two its corresponding library. I'm never using libraries with the same ENV variables at the same time (neither for build nor release)
- Once I run a build that involves one of the libraries, both have the variables gone.
- In addition, when I try to modify of add variables to one of the libraries, the 'Save' button is not working. This happens, but not always, so that's why I was able to have two libraries with variables with the same name.

**Comment by forgondolin** [comment]
Hello, this is also happens to me, but instead of builds, it happens often with the Releases. The link to the variable group gones for no reason. Obs: I'm using on premise azure devops Dev17.M153.5

**Comment by gokusupa** [comment]
Same thing Happens at least 3 times a year for the last 5 years at least.
