### ISSUE TITLE
How to Archive multiple file and folder

### ISSUE THREAD

**Issue by PoppyPham** [MicrosoftDocs/vsts-docs#1213]
How to Archive multiple file and folder
My working directory is /Root
I want to archive folder "/Root/folder1" and files "/Root/file1.js", "/Root/file2.json" in one.zip file without create multiple task.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: add63018-4f2c-f258-76ea-9f76aa43ff09
* Version Independent ID: c71f17c9-9a78-396e-7a0f-ad8b52b01724
* Content: [Archive Files](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/utility/archive-files?view=vsts#q--a)
* Content Source: [docs/pipelines/tasks/utility/archive-files.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/archive-files.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by andywarren** [comment]
I am running into the same issue. I have two Archive Files tasks setup, and that works fine, but in the Extract Files task on the release it fails with what is described here: https://github.com/Microsoft/azure-pipelines-tasks/issues/7243

It throws this error: ERROR: Can't allocate required memory! 

Which I understand to be because the Extract Files has two zips in the same location.

**Comment by alohaninja** [comment]
Getting this same error - `ERROR: Can't allocate required memory!` - for now just going to use powershell script with [7z node package](https://www.npmjs.com/package/7zip).

![image](https://user-images.githubusercontent.com/26234626/55197650-6a1d4180-5170-11e9-8dd2-e0b2da377876.png)

**Comment by spcaswell-mindbody** [comment]
This is an insanely common use case.  Having to copy multiple directories into a subdirectory just to zip them up together is wasteful and overly complicated.  Please fix this.

**Comment by buckleyGI** [comment]
There is the option "Replace existing archive": If an existing archive exists, specify whether to overwrite it. Otherwise, files will be added to it as long as it is not a compressed tar.

**Comment by spcaswell-mindbody** [comment]
So we have to create a separate zip step for each file we want to add not under a directory we want to add in its entirety and for each directory we do want to add in entirety.  This is not better.  Instead of X copy steps plus one zip step we just have X zip steps.  Every compression tool takes a file list as a parameter for a reason.  A file list option should be standard input from ADO.

Now I'm nitpicking with this next bit but, the wording for the inline help on "Replace existing archive" could be improved:  "If enabled any existing archive file of the same filename will be deleted; otherwise the specified root folder or file to archive will be appended to the archive file."  The current help also does not indicate an exception for compressed tar files.

**Comment by mijacobs** [comment]
@PoppyPham, it looks like you've encountered an issue with the product itself, rather than an issue with the documentation. We apologize that it's taken so long to address this issue. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.

**Comment by janis-veinbergs** [comment]
> Instead of X copy steps plus one zip step we just have X zip steps.

@mijacobs actually you only need 1 Copy File Task.  Within contents specify what you want to copy, supports multiple lines:
```
- task: CopyFiles@2
  displayName: Copy SPA Assets to TEMP
  inputs:
    SourceFolder: '$(webApplicationProject)'
    Contents: |
      js\SPA\dist\**\*.*
      webpack-assets.json
    TargetFolder: '$(Agent.TempDirectory)\SPA'
```
