### ISSUE TITLE
IIS Deployment app_offline config (fcc23259-21ec-f9fa-4e25-f587e1e0f41b plugin)

### ISSUE THREAD

**Issue by Akhenathon** [MicrosoftDocs/vsts-docs#1215]
Hi, is there any way to configure the app_offline page that is injected while the app is deploying?

Thanks

**Comment by steved0x** [comment]
@Akhenathon The issues in this GitHub repo are for submitting documentation feedback. What article were you reading when you had this question? Let me know and I can assign this issue to the right author for review.

**Comment by steved0x** [comment]
I'm closing this issue since it is not associated with a topic. To continue the discussion, please open a new issue that is associated with a topic by browsing to the topic on docs.microsoft.com and choosing **Content feedback** at the bottom. Thank you for your feedback.

![image](https://user-images.githubusercontent.com/1580889/42953695-fd174150-8b48-11e8-94de-26924ca79c71.png)
