### ISSUE TITLE
duplicate of BuildHttpClient2_1?

### ISSUE THREAD

**Issue by danielstefanescu** [MicrosoftDocs/vsts-docs#1221]
What's the difference between BuildHttpClient2_1 and BuildHttpClient2_2 pages?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4625686-71f6-9937-6eaf-ee6108ff8c15
* Version Independent ID: 3c2d7292-5edf-fe30-1f4b-80c03493829b
* Content: [TFS/Build/RestClient BuildHttpClient2_2 API](https://docs.microsoft.com/en-us/vsts/extend/reference/client/api/tfs/build/restclient/buildhttpclient2_2?view=vsts)
* Content Source: [docs/extend/reference/client/api/TFS/Build/RestClient/BuildHttpClient2_2.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/reference/client/api/TFS/Build/RestClient/BuildHttpClient2_2.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @danielstefanescu , thanks for the question here.

Since we have a single API version for the service, it’s possible certain areas/APIs don’t change version to version, and so you’ll find some cases where the 2.1 docs are identical to the 2.2 docs (or even the 1.0 docs are identical to the 4.1 docs because some APIs haven’t changed in a long time).

Generally, the version only matters if an integration/extension plans on integrating with VSTS and one or more versions of on-prem TFS. Version 2.2 is only available in TFS 2015 Update 2 and later, so if a developer wanted to target TFS 2015 Update 1, they would want to use the 2.1 APIs. In this case it doesn’t matter since the 2.1 and 2.2 APIs are the same.

Closing this for now, but feel free to reach back out if you have another question!
