### ISSUE TITLE
Offline upstreams question

### ISSUE THREAD

**Issue by jfichtner** [MicrosoftDocs/vsts-docs#1227]
The following statement is confusing to me: "For outages lasting more than 12 hours, which are quite infrequent, you will experience issues listing and restoring packages, even if those packages have been installed into the feed."

This makes is sound like the automatic installation of the upstream package into the local feed is not actually happening, and that in the scenario where the upstream public source (i.e. nuget.org) goes down, there is actually no way to retrieve the package until it comes back up. What am I missing here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5f022df-36c3-34b1-cac1-ac33995a7d73
* Version Independent ID: 9634b0c8-7b14-4453-2c04-aedabbf331f1
* Content: [Upstream sources](https://docs.microsoft.com/en-us/vsts/package/concepts/upstream-sources?view=tfs-2018)
* Content Source: [docs/package/concepts/upstream-sources.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/package/concepts/upstream-sources.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
I'm adding @alexmullans to address this question, I believe he's on vacation for the next few days but he'll get to you soon!

**Comment by NsdWorkBook** [comment]
Any updates on an answer?

**Comment by alexmullans** [comment]
Sorry for the delay. Packages are retrieved and saved. However, the feed also keeps a cache of metadata so it can respond to range queries (which are common, esp. in NuGet) with the correct set of {versions in feed + versions in upstream sources}. Because the search of upstream sources are ordered, we have designed upstream sources to not automatically skip over sources that are down, because that could cause your query to have different results than expected. As mentioned in the docs, you can remove the offending upstream and continue to build and deploy using the saved packages.

**Comment by NsdWorkBook** [comment]
Thanks! That makes sense 👍

**Comment by elbatk** [comment]
Closing this now, thanks Alex!
