### ISSUE TITLE
Creating fields in scrum process.

### ISSUE THREAD

**Issue by yury-stepanov** [MicrosoftDocs/vsts-docs#1245]
Hello. I'am trying to create new field for the scrum process using this API (https://docs.microsoft.com/en-us/rest/api/vsts/processdefinitions/fields/create?view=vsts-rest-4.1). 

Model for the new field looks like this 
```
const fieldModel = {
        id: 'test',
        description: 'test',
        name: 'Name',
        type: 1, //String
        pickList: null,
        url: null,
  };
```
My application has `vso.project`_manage `vso.work_full` scopes.

In response I a receive; 
```
Error: VS402356: You do not have the permissions required to perform the attempted operation on this process.
```

I am not sure is it a missing scope (not found one) or I just can't create new fields for default process?
If so, is it possible in any way to create new field for workitem to hold data? (related to #1146 )

Thank you, cheers.

**Comment by elbatk** [comment]
Hi @yury-stepanov , I know I pointed you to the dev community on the other issue, but I wanted to link it again: [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html) because you'll find better answers quicker to product questions. Best of luck! Closing this as a docs issue here but if you find a docs change would help, please reach out!
