### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by samneirinck** [MicrosoftDocs/vsts-docs#1249]
Is there a way to do this when running the docker image of the VSTS agent? Preferably by setting an environment variable like VSTS_DEPLOYMENTTOOL and VSTS_DEPLOYMENTPOOLNAME?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09fa0c14-9937-41bc-cc34-179edb379083
* Version Independent ID: 10fe3600-21a5-12db-5e21-5ade3a8fa484
* Content: [How to provision agents for deployment groups](https://docs.microsoft.com/en-us/vsts/pipelines/release/deployment-groups/howto-provision-deployment-group-agents?view=vsts)
* Content Source: [docs/pipelines/release/deployment-groups/howto-provision-deployment-group-agents.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/deployment-groups/howto-provision-deployment-group-agents.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by thomps23** [comment]
Please accept our apology for the significant delay in addressing this issue.

It looks like you're working through an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
