### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by andreasblueher** [MicrosoftDocs/vsts-docs#1261]
Could you provide the example code on GitHub? I tried to setup everything as instructed, but req.body is null in first line of post method `var repoId = req.body.resource.repository.id;`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8f48d8a-33fb-9f6d-1db1-4cccb5b987d9
* Version Independent ID: 3e18fcbf-331d-9de2-62ae-c4e7c888cc48
* Content: [Create a pull request status server with Node.js](https://docs.microsoft.com/en-us/vsts/git/how-to/create-pr-status-server?view=vsts#feedback)
* Content Source: [docs/git/how-to/create-pr-status-server.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/git/how-to/create-pr-status-server.md)
* Product: **devops**
* GitHub Login: @mmitrik
* Microsoft Alias: **mmitrik**

**Comment by jgillette** [comment]
Found that if you move the following to the top under const app = express(), it works properly
var bodyParser = require('body-parser')
app.use(bodyParser.json());

**Comment by andreasblueher** [comment]
I indeed got the repoId part working after recreating everything from scratch. However setting the PR status still doesn't work for me. Anyone here who can assist me?

**Comment by leokr** [comment]
Sample is really not working.

That's because here
var vstsGit = connection.getGitApi().then( success => { console.log(success); }, error => { console.log(error); } );
They create a promise, a not a git client as we expect.
variable "success" is also named incorrectly, actually it is "result".

Fix is to replace mentioned line with 
var vstsGit = null;
connection.getGitApi().then(result => {vstsGit = result; console.log(result); }, error => { console.log(error); });

With this fix I was able to run example successfully.

**Comment by AlfredOdling** [comment]
You should put @leokr solution in the docs, as the current instructions do not work.
