### ISSUE TITLE
As of Visual Studio 15.7.1 we are able to associate test cases to MS Test V2, xUnit, and NUnit.  

### ISSUE THREAD

**Issue by mikedouglasdev** [MicrosoftDocs/vsts-docs#1262]
Here is my blog post describing it.  Is this officially supported? http://www.deliveron.com/blog/test-case-association-xunit-nunit-and-mstestv2-tests-available-visual-studio-2017-1571/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d8a7e40-73d6-795f-7b8c-77104ef606e8
* Version Independent ID: 8f15995b-bd94-8d9f-1e8b-82f1f364d221
* Content: [Associate an automated test with a test case](https://docs.microsoft.com/en-us/vsts/test/associate-automated-test-with-test-case?view=vsts)
* Content Source: [docs/test/associate-automated-test-with-test-case.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/associate-automated-test-with-test-case.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice. They are currently investigating some issues related to this. I'll update the topic as soon as I hear back from them.

**Comment by dt86uk** [comment]
Hi Alex, it's been a couple of months now, do we have any news on this? Many Thanks!

**Comment by PBoraMSFT** [comment]
@mikedouglasdev @dt86uk @alexhomer1 - this is not officially supported. The association experience for MSTest v2 and other test types was opened up in VS 15.7 accidentally because of an issue. You will find that as that issue got addressed, the association got blocked again in VS 15.8. 

We are working on supporting it officially and is expected to become available in the 15.9 timeframe.
