### ISSUE TITLE
Compare non-repo files

### ISSUE THREAD

**Issue by mrfnord** [MicrosoftDocs/vsts-docs#1326]
Plain old file compare is does not appear to be available in VS2017 when using Git. I have 2 directories on my computer I want to compare. The old TFS Compare tool could be pointed at arbitrary files, but the Git version can only compare branches or historic versions.

This is pretty basic functionality with lots of uses, checking that the freshly compiled version matches the running version, comparing files sitting on two different machines, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f065206-e7a8-a43a-bc6b-27c95d29af99
* Version Independent ID: 37f9de5e-aff1-89b5-de68-f5144d5df3f5
* Content: [Review your repo history](https://docs.microsoft.com/en-us/vsts/git/tutorial/history?view=vsts&tabs=visual-studio)
* Content Source: [docs/git/tutorial/history.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/git/tutorial/history.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@mrfnord You can compare two files together in Visual Studio by using the Tools.DiffFiles command from the command window as described [here](https://stackoverflow.com/questions/13752998/compare-two-files-in-visual-studio) and you can also run Visual Studio from the command line to get a diff as described at the top of the article [here](https://docs.microsoft.com/en-us/vsts/tfvc/compare-files?view=vsts). It sounds like you want to compare entire folders instead of just two files? Like the old WinDiff tool? Let me see what I can find on that.

**Comment by gbritton1** [comment]
I notice that almost a year has elapsed since "Let me see what I can find on that."  Just wondering if you've had any luck?
