### ISSUE TITLE
In a multiconfiguration phase, specify different demands for the different configuration

### ISSUE THREAD

**Issue by LokiMidgard** [MicrosoftDocs/vsts-docs#1332]
If I have a variable `OS` with the value `Win7,Win8,Win10` and I use the variable for the multiplier, can I use the values `Win7`, `Win8` and `Win10` for the demands of the running builds?

So in this case one build searchs for an agent that has the capabilitie `Win7`, another for an agent with `Win8` and a third agent that matchs `Win10`. Just using `$(OS)` did not work. I think it then will search for an agent that has the capability `Win7,Win8,Win10`. But I didn't get any information from the logs supporting this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f86c97-f534-50ad-bfb1-a2cf78c7af94
* Version Independent ID: acea40e3-512b-4d9a-9389-71b8b24327be
* Content: [Visual Studio Build build and release task](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/build/visual-studio-build?view=vsts#multiconfiguration)
* Content Source: [docs/pipelines/tasks/build/visual-studio-build.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/visual-studio-build.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by thomps23** [comment]
Please accept our apology for the significant delay in addressing this issue.

It looks like you're working through an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
