### ISSUE TITLE
Are .net standard packages supported?

### ISSUE THREAD

**Issue by fleed** [MicrosoftDocs/vsts-docs#1336]
I'm creating Nuget packages targeting .net standard, using the `dotnet pack --include-symbols`  and trying to publish them to a VSTS feed. I have two issues:
- when publishing the `.symbols.nupkg` package, it is in conflict with the corresponding `.nupkg` that I previously published
- if I publish the `.symbols.nupkg` file to a different feed in the same. VSTS account, I'm still not able to debug into the packages

Can I manually publish symbol packages side-by-side with normal packages? Is it possible to enable debugging from the feed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bbbdd72-60c5-52e9-23c4-e6a3dcf7c550
* Version Independent ID: 1bc292cd-e6bd-bb6e-69fb-6103e4770988
* Content: [Publish symbols for debugging](https://docs.microsoft.com/en-us/vsts/pipelines/symbols/?view=vsts)
* Content Source: [docs/pipelines/symbols/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/symbols/index.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **amullans**

**Comment by senj** [comment]
According to this (https://blogs.msdn.microsoft.com/devops/2017/11/15/vsts-is-now-a-symbol-server/) Comment by @alexmullans VSTS doesn't support symbol nuget packages right now.

I tried the `Publish symbols` VSTS Build Task but had no luck with it. I have the *.pdb files in my SymbolCache but Visual Studio can't find them

**Comment by senj** [comment]
After a lot of searching I found the source link documentation and it is working now, thank you

**Comment by alexmullans** [comment]
Thanks @mitchdenny for commenting. Are there any docs changes coming out of this? We can pass them on to @elbatk if it would help future users :)

**Comment by fleed** [comment]
@mitchdenny can you elaborate on _still publish the symbols to VSTS_?
Do you mean including the *.pdf files within a package or creating a separate `.symbols.nupkg` file?

**Comment by samrat-gavale** [comment]
It would be nice if the task would let us adjust the expiry time of the symbols. I do see a  --expirationInDays argument in command that is run by this task.

**Comment by alexmullans** [comment]
@steved0x can you do whatever magic is needed to allow me to assign this issue to @mitchdenny? I can't find him in the assignees box in the top right of the page. I poked around the GitHub management tool but didn't see how.

**Comment by steved0x** [comment]
@alexmullans Yes I am sending the instructions to @mitchdenny now

**Comment by mitchdenny** [comment]
OK so a few things have happened in the NuGet ecosystem since my last response. The most important change is that when publishing to NuGet.org you can now publish a *.snupkg file which is basically just a package which contains portable PDBs. When NuGet.org gets this package it extracts them and makes them available on a symbol server address that they host for the community.

Unfortunately in Azure DevOps today we don't yet support publishing *.snupkg packages (or *.symbols.nupkg packages). Instead you would generate your *.nupkg like normal, but then you would use the Index & Publish Symbols task to push the PDB files to Azure DevOps.

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/index-sources-publish-symbols?view=vsts

Because with .NET Standard you are producing a portable PDB and using SourceLink you can actually disable the Index Symbols option on the Index and Publish Symbols task because the symbols are already indexed appropriately - the task will just upload the PDBs into the service and when your debugger needs them it will download them.

Follow these instructions to setup VS to download symbols from Azure DevOps.

https://docs.microsoft.com/en-us/azure/devops/artifacts/symbols/debug-with-symbols-visual-studio?view=vsts
