### ISSUE TITLE
Database Developer

### ISSUE THREAD

**Issue by VickeyC** [MicrosoftDocs/vsts-docs#1348]
How do I create a label in TFS 2017 or VS 2017?   These instructions seem to apply to VSTS

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66afe74b-6887-286e-d354-9225575260b1
* Version Independent ID: 5e8e06f6-8494-408c-fcb4-d3f98580f92e
* Content: [Use labels to take a snapshot of your files](https://docs.microsoft.com/en-us/vsts/tfvc/use-labels-take-snapshot-your-files?view=tfs-2017)
* Content Source: [docs/tfvc/use-labels-take-snapshot-your-files.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/tfvc/use-labels-take-snapshot-your-files.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@VickeyC Labels are in TFVC in TFS 2017 and VS 2017 so if you have those versions you should be able to create and use labels. Labels are a Team Foundation Version Control feature (TFVC) only ,and not Git. If you are using TFVC and connected to a TFS server in your project, you should be able to apply labels to your files. What happens when you try to create your labels?

I don't have any screenshots, but here is a video (kind of older with a different version of Visual Studio made by a 3rd party (not Microsoft)) that shows how to create labels in Visual Studio. Does this match up with what you are seeing?

https://www.youtube.com/watch?v=zRVLQWrj2AM
