### ISSUE TITLE
Tags and TFS

### ISSUE THREAD

**Issue by VickeyC** [MicrosoftDocs/vsts-docs#1366]
Is there a specific TFS release which allows you to create and display tags?   My company is on version 15.112.26307.0 (2017 Update 1 RTM), but I don't see any tag options listed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8eb20e31-fc65-913d-f4a6-61318f079224
* Version Independent ID: 0c4960b1-d639-7452-a2e7-08c59934c3b3
* Content: [Working with Git tags](https://docs.microsoft.com/en-us/vsts/git/how-to/git-tags?view=vsts&tabs=vsts-tfs-web-portal)
* Content Source: [docs/git/how-to/git-tags.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/git/how-to/git-tags.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@VickeyC From looking at the VSTS features timeline it looks like the ability to view and create tags in the Web portal was added in this release:

https://docs.microsoft.com/en-us/vsts/release-notes/2017/mar-29-team-services#add-and-view-git-tags

Which was included as part of TFS 2017.2.

Let me confirm that with the product team, because if so, I need to update this article to include that information (I was given to understand that tags were supported in earlier versions)

Sorry for the trouble and I will reply back as soon as I have more information.

Thank you,

Steve
