### ISSUE TITLE
Signing commit

### ISSUE THREAD

**Issue by fakhrulhilal** [MicrosoftDocs/vsts-docs#1381]
Is there any way to sign the commit using GPG? Support for signing commit will be helpful. The VSTS should support signed commit as well. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9654b64d-80e5-a28e-30d8-240b02bbe175
* Version Independent ID: c4f3eb8e-e203-7452-ba96-b0990107339a
* Content: [Save your changes with Git commits](https://docs.microsoft.com/en-us/vsts/git/tutorial/commits?view=vsts&tabs=visual-studio)
* Content Source: [docs/git/tutorial/commits.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/git/tutorial/commits.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by fakhrulhilal** [comment]
I'm expecting VSTS to view signed commit like [GitLab](https://docs.gitlab.com/ee/user/project/repository/gpg_signed_commits/index.html) or [GitHub](https://blog.github.com/2016-04-05-gpg-signature-verification/) do. It would be better if visual studio can view signed commit as well. This [issue](https://github.com/jayphelps/git-blame-someone-else/commit/e5cfe4bb2190a2ae406d5f0b8f49c32ac0f01cd7) is still working in VSTS.

**Comment by steved0x** [comment]
@fakhrulhilal Right now we don't have that capability. VSTS does have the concept of `pushed by` which is kind of similar, but I know it is not the same thing.

I'm closing this issue since the issues in this repo are for documentation feedback, but you can continue the discussion and file a feature request for this functionality with the team here:

https://visualstudio.uservoice.com/forums/330519-visual-studio-team-services

Thank you for your feedback!

Steve

**Comment by louistio** [comment]
Here is a specific user voice idea requesting the feature:
> [Show whether commits are verified with GPG key on UI](https://developercommunity.visualstudio.com/idea/383281/show-whether-commits-are-verified-with-gpg-key-on.html)
