### ISSUE TITLE
Looking for a script to gather all information about installed agents and their hosts in TFS

### ISSUE THREAD

**Issue by IbrahimUmar** [MicrosoftDocs/vsts-docs#1391]
Hello
               Is it possible to write a script to get information of all agents installed with TFS and their machine names? If it is possible , please share how?

Regards

**Comment by steved0x** [comment]
@IbrahimUmar The issues in this repo are for documentation feedback. If you can let me know which article you think should cover this scenario I can assign it to the author for review. Thank you.

**Comment by steved0x** [comment]
I'm closing this issue since it is not associated with a topic. To continue the discussion, please open a new issue that is associated with a topic by browsing to the topic on docs.microsoft.com and choosing **Content feedback** at the bottom. Thank you for your feedback.

![image](https://user-images.githubusercontent.com/1580889/42953695-fd174150-8b48-11e8-94de-26924ca79c71.png)
