### ISSUE TITLE
Work on topic branches

### ISSUE THREAD

**Issue by MoiMoiDG** [MicrosoftDocs/vsts-docs#1420]
Hi,

It's a great documentation! Thanks for that!
A few more questions from my side about topic branches, especially features/*:
- How does the mapping between them and work items look like? Are there any policies?
- Work items usually have a hierarchical organization (e.g. feature item parent of PBI or user story): How does it reflect on the branching structure?
- Are updates on feature/* performed via pull request? Is it optional?

I can understand that the answers may vary from team to team, but what are your best practices?
Thanks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7f4784d-1539-adc9-68e1-036cfc004722
* Version Independent ID: d02a6a52-e736-b411-b2f8-5be08ad3f5a0
* Content: [How We Use Git at Microsoft - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/devops-at-microsoft/use-git-microsoft)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fdevops-at-microsoft%2fuse-git-microsoft.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fdevops-at-microsoft%2fuse-git-microsoft.md&version=GBlive&_a=contents)
* Product: **devops**
* Git Login: **samgu**
* Microsoft Alias: **mattc**

**Comment by MoiMoiDG** [comment]
Hi there,

The bot is right, this issue is stale. Is there any new documentation answering my questions above?

Thanks

**Comment by dazinator** [comment]
> virtually eliminating merge debt
Would you be able to clarify what you mean regarding "merge debt" as that's a term I've not stumbled across before.
P.S the cherry-picking from release branches into master and vice versa sounds like a prime opportunity for errors and instabilities - although I appreciate this is what works well for you. I think overall though, I still prefer `git flow` as it's less haphazzard.

**Comment by MoiMoiDG** [comment]
> > virtually eliminating merge debt
> > Would you be able to clarify what you mean regarding "merge debt" as that's a term I've not stumbled across before.
> > P.S the cherry-picking from release branches into master and vice versa sounds like a prime opportunity for errors and instabilities - although I appreciate this is what works well for you. I think overall though, I still prefer `git flow` as it's less haphazzard.

That's probably intended for another issue.

**Comment by steved0x** [comment]
@MoiMoiDG Sorry this one fell through the cracks, and you are right about that other reply, it sounds like it might be for another issue. We don't have any new content in this area since you posted your issue, but I can provide links to some existing content that may be helpful.

For the three things you mentioned:

* How does the mapping between them [topic branches] and work items look like? Are there any policies?

I don't know of any policies that enforce mapping between branch folder structures and work item hierarchies, but there is a branch policy that you can enable that requires you to [link at least one work item to a pull request](https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-policies?view=azure-devops#check-for-linked-work-items). You can link a branch to a work item, but that is a link directly between the branch and the work item, and isn't dependent on any work item hierarchies. That is my personal workflow, I like to create branches from within my work items, and then everything is linked and I get automatic linking of work items to my PRs from that source branch. 

* Work items usually have a hierarchical organization (e.g. feature item parent of PBI or user story): How does it reflect on the branching structure?

They are independent


* Are updates on feature/* performed via pull request? Is it optional?

That is controlled by branch policies. Once you have branch policies enabled on a branch, you can only make updates to that branch using a pull request, and can no longer push directly to it, unless you have the [Bypass policies when pushing](https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-permissions?view=azure-devops#permissions-in-azure-devops-services) permission. If you don't have any branch polices then using a PR is optional, but recommended.

Check out [Improve code quality with branch policies](https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-policies?view=azure-devops) for more information, and see the [Branch policies overview](https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-policies-overview?view=azure-devops) for links to the other content we have on branch policies.

If you have more questions, please open a new issue, which should get routed more quickly as we have vendors helping us now. Thank you for your feedback and sorry for the great delay in responding.
