### ISSUE TITLE
Extending Menus and commands link

### ISSUE THREAD

**Issue by alevans4** [MicrosoftDocs/vsts-docs#1466]
It doesn't appear to me that the "Extending menus and commands" link on this page:

https://docs.microsoft.com/en-us/vsts/integrate/ide/extensions/develop_extensions/extend_ui

goes to the right place. It links instead to Legacy Language Service Essentials, which doesn't seem related?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f31c8019-e619-b955-1dfd-d0f6de95e9f5
* Version Independent ID: 2e094ab3-7760-a488-35a8-2be571067e5f
* Content: [I want to extend the UI](https://docs.microsoft.com/en-us/vsts/integrate/ide/extensions/develop_extensions/extend_ui?view=vsts#feedback)
* Content Source: [docs/integrate/ide/extensions/develop_extensions/extend_ui.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/ide/extensions/develop_extensions/extend_ui.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
I'm not really sure where to forward VS IDE issues, @erickson-doug for help here.

**Comment by chcomley** [comment]
Hi @alevans4, I've just come across this issue from long ago... Since you filed your issue, our documentation has been updated considerably. The link you were looking for is here: https://docs.microsoft.com/en-us/vsts/integrate/ide/extensions/develop_extensions/extend_ui 
I'll be closing this issue, however please let us know if you have any more feedback or questions. Thank you!
