### ISSUE TITLE
Using PAT for GIT repo clone

### ISSUE THREAD

**Issue by Martinius79** [MicrosoftDocs/vsts-docs#1474]
Hi,

I was a bit confused after reading the article. After trying out some ways, I was finally able to use my PAT against TFS and VSTS GIT Repos.

The only way I was able to get a clone of my GIT repo using a PAT was setting the http.extraheader in the GIT commandline. The authorization tag must point to basic authentication, the protocoll must be HTTPS and the token must be BASE64 encoded, including a (fictional) user name.

Example:
git -c http.extraheader="AUTHORIZATION: Basic TXlHaXRTeW5jVXNlcjo2bHFqNXJkcHEzdXBxZWVmd2o3bDduZXN5NTR3d3gxNHFobDVlanl5NTVkb2g0M3d4YzRh" clone https://tfs.address/tfs/Collection/Project/_git/RepoName

Used basic token BASE64 encoded: TXlHaXRTeW5jVXNlcjo2bHFqNXJkcHEzdXBxZWVmd2o3bDduZXN5NTR3d3gxNHFobDVlanl5NTVkb2g0M3d4YzRh

Basic Token BASE64 decoded: MyGitSyncUser:6lqj5rdpq3upqeefwj7l7nesy54wwx14qhl5ejyy55doh43wxc4a

Token is constructed from &lt;fictional user name&gt;:&lt;PAT from a user with rights in the project&gt;
In this example:
Fictional user name: MyGitSyncUser
Used PAT: 6lqj5rdpq3upqeefwj7l7nesy54wwx14qhl5ejyy55doh43wxc4a

PAT scope: Code (Read)

The TFS/VSTS don't accepts "AUTHORIZATION: Bearer" headers in the moment :(

Maybe this will help someone using the PATs in TFS/VSTS.

Note: HTTPS is needed for BASIC Authentication!

Bye
Martinius

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bfea574-db69-a5fd-37fe-64ecfdac502a
* Version Independent ID: 4037d475-f194-2ac9-ffd6-70530fc3140a
* Content: [Authenticate access with personal access tokens](https://docs.microsoft.com/en-us/vsts/organizations/accounts/use-personal-access-tokens-to-authenticate?view=vsts)
* Content Source: [docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by steved0x** [comment]
@Martinius79 What Git client were you using, and on what platform (Windows, Mac, Linux?)

**Comment by Martinius79** [comment]
![image](https://user-images.githubusercontent.com/41959005/43719369-d0c76a64-998d-11e8-97d6-1fdd6d4d295b.png)

**Comment by steved0x** [comment]
@Martinius79 Thank you, on Windows it should "just work" - let me loop in some more folks and see if I can get some more information.

**Comment by Martinius79** [comment]
Yes, I am using this method in an automation way. We syncronize our code to a private VSTS project on irregular base. 

PS: I would like to see a nice tutorial here, how to generate short time PATs and use them programmatically :)

I wrote the comment above, because I expected problems using a PAT to access our on premise TFS (2018 Update 2) using the descriped methods (GCM and so on).
Maybe you never tried to use the a real indepented account to try to access the TFS.
Try the following: Open a cmd box under a user, who has NO access rights to the TFS at all (no CAL, no rights in any project).
Try to use the descriped methods with git. Storing then PAT in the GCM, using it directly with GIT in the URL or using "extraheader" option with Authorization bearer.  All this ways don't work.
Only the basic auth is working. 
(and before you ask, yes, the PAT is from a TFS user , who has the needed rights)

And yes, I know, the build system of the TFS is getting the sources in the way you descriped above, but I have no Idea what is the trick, that "bearer" is working there.

Bye
Martinius

**Comment by whoisj** [comment]
@Martinius79 just a point to make here, the GCM is not designed (thought it does attempt to support) for non-interactive authentication. VSTS worked with the Git for Windows and larger Git community to get the `http.extraheader` configuration added to Git because we knew that a tool like the GCM (designed for interactive usage) would problematic in automation.

In my opinion, the idea situation is where a lab has a central coordination account responsible for queuing builds, tests, etc. The account is granted permissions to generate access tokens in VSTS. When the account queues a task, it generates a token for the task. The token is securely stored (encryption most likely) and passed to the agent. The agent then uses the token to construct the `-c http.extraheader={base64(":" + token)}` prefix for each Git command. It could also use the token for accessing Nuget packages, container assets, etc.

@chrisrpatterson, @justmarks is there any documentation available on the creation of tightly scoped personal access tokens for automation?

**Comment by justmarks** [comment]
[ManagePATsviaREST.zip](https://github.com/MicrosoftDocs/vsts-docs/files/2274921/ManagePATsviaREST.zip)
Here's a sample for how to call our REST APIs to create/revoke/enumerate PATs

**Comment by JoseFMP** [comment]
@Martinius79  I was using the http.extraheader the way you mention and I still get no autorization.
@gistofj I use it the way you mention also. Still, not working for me.
As per this thread: https://stackoverflow.com/questions/53106546/cannot-clone-git-from-azure-devops-using-pat/53182981#53182981

**Comment by gistofj** [comment]
@JoseFMP the sample by @justmarks is your best bet. I mean, he's The Man (tm) when it comes to authenticating with Azure DevOps. Me, I am no longer associated with Microsoft so am over very little use to you. Best of luck however! 🙂

**Comment by JoseFMP** [comment]
I tried the way @justmarks  proposes in his code. Still cannot authenticate :(

**Comment by JoseFMP** [comment]
I have to confirm still in the machine where I had the problems.

**Comment by JoseFMP** [comment]
@justmarks Still not working. I tried the solution commented in  #2444  and it worked in one machine where I was sitting when I read the comment.

Sitting back in the machine where we need to make it work, still same error: Authentication failed.
We are considering to switch off our Azure DevOps and switch to other provider since we cannot just clone the repository :(

**Comment by ManuelGalindo** [comment]
@joseFMP can you open a AzDevOps Ticket and send the case number to me, email on the profile :)

**Comment by JoseFMP** [comment]
@ManuelGalindo  I opened the ticket already one week ago but no answer. 30 followers though, I am wondering if it's people having the same problem.
I'd love to send you the ticket but I cannot see your email in your profile.

**Comment by ManuelGalindo** [comment]
@JoseFMP I sent an email (to your @gmail.com account) with some steps to create a case

**Comment by padmick** [comment]
Bumping this thread as we are also having the same issues (headless ubuntu 18 LTS machines Azure). Is this something we need to open a support ticket for as we cant use credential manager in our environment or can we get a documentation update on how to get code onto a headless machine via PAT? #2444

**Comment by PiDiBi** [comment]
you can use
git clone https://%PAT%@msazure.visualstudio.com/DefaultCollection/One/_git/AAPT-Antares-Websites 
and use your pat at this place %PAT% or setup it as variable SET PAT=...

**Comment by PiDiBi** [comment]
and I've just tried that same works for Azure DevOps API calls

**Comment by nikhilepicor** [comment]
It is worth noting that there's another way to authenticate to git clone using the PAT and not the credential manager. See https://github.com/MicrosoftDocs/vsts-docs/issues/2455#issuecomment-439503194

**Comment by thomps23** [comment]
Please accept our apology for the significant delay in addressing this issue.

It looks like you're working through an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
