### ISSUE TITLE
Build status badge added to GitHub readme doesn't show up.

### ISSUE THREAD

**Issue by BradKwon** [MicrosoftDocs/vsts-docs#1499]
I added markdown build status badge on my GitHub readme file but the badge image doesn't show up although the link works like below. Is it related to the VSTS project access level or security permission?

I am using a public GitHub repo and a private git VSTS project.

[![Build status](https://bradkwon.visualstudio.com/test/_apis/build/status/test-Xamarin.Android-CI?branch=master)](https://bradkwon.visualstudio.com/test/_build/latest?definitionId=9&branch=master)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75a10513-2af9-8e16-61a4-25d4b09f6d32
* Version Independent ID: 788acaa2-d5a1-1d0d-18f4-e94a4e2fe2c9
* Content: [Build your GitHub repository](https://docs.microsoft.com/en-us/vsts/pipelines/build/ci-build-github?view=vsts&tabs=designer#feedback)
* Content Source: [docs/pipelines/build/ci-build-github.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/ci-build-github.md)
* Service: **vsts**
* Product: **devops**
* GitHub Login: @mlearned
* Microsoft Alias: **mlearned**

**Comment by mamoorkhan** [comment]
I am having the same problem.

**Comment by tomcurran** [comment]
I'm also having this issue

**Comment by mlearned** [comment]
@vijayma im having a look at this one, it looks like the MD snippet may be wrong here.

**Comment by mlearned** [comment]
this is due to public vs. private projects. if you make your project public the image URL will render.  There are other potential work arounds we are looking at for the doc.

**Comment by BradKwon** [comment]
@mlearned Thanks for the feedback. Your answer means that I have to make my VSTS project public? I couldn't find any options to change this on VSTS. My GitHub repo is already public. Could you please point out where could I do this?

At this moment, I see the build status option has disappeared on my VSTS build option. It seems there was any updates on VSTS.

**Comment by mlearned** [comment]
@BradKwon  yea its the VSTS that needs made public visibility  https://docs.microsoft.com/en-us/vsts/organizations/public/make-project-public?view=vsts&tabs=new-nav

**Comment by mamoorkhan** [comment]
The release badges are working though

**Comment by BradKwon** [comment]
@mlearned It worked after I made it public! Thanks! 🎉 🎉

**Comment by tomcurran** [comment]
I can confirm the same thing for release bagdes, they are working. I'm noticing that the release badges have `_apis/public` in the url...

**Comment by vijayma** [comment]
We understand that the release badges work. 

Last week, we introduced new URLs for build badge to cover additional requirements - (1) Ability to get a badge per branch (2) Ability to point the badge always to the latest build of the definition instead of the definition itself. (3) A more friendly URL for the badge and for the latest build. 

In the process of rolling out this change, we introduced two issues - (1) The section to show the URLs was removed from the definition options section and (2) The badge URL is not public anymore.

We have already rolled out a fix for the first issue. You should start seeing the URL in the definition options. We are working on a fix for the second issue so that the badge URL works even if your VSTS project is private. In the meantime, you can work around the second issue by making your VSTS project public.

**Comment by tashrifbillah** [comment]
For me, the issue was, there were spaces in the name of my project. In fact, I restored the project after deleting it. During restoration, spaces were put in the name. I was able to build successfully, however, `Status Badge` generation process probably was not happy with it. I renamed the projects without spaces. Now, I am able to see status badge in my GitHub description:

https://github.com/tashrifbillah/tbss_containers/blob/master/README.md

**Comment by mamoorkhan** [comment]
> We understand that the release badges work.
> 
> Last week, we introduced new URLs for build badge to cover additional requirements - (1) Ability to get a badge per branch (2) Ability to point the badge always to the latest build of the definition instead of the definition itself. (3) A more friendly URL for the badge and for the latest build.
> 
> In the process of rolling out this change, we introduced two issues - (1) The section to show the URLs was removed from the definition options section and (2) The badge URL is not public anymore.
> 
> We have already rolled out a fix for the first issue. You should start seeing the URL in the definition options. We are working on a fix for the second issue so that the badge URL works even if your VSTS project is private. In the meantime, you can work around the second issue by making your VSTS project public.

can we have a badge that shows us the latest build/branch info for a specific environment?

**Comment by fordprefect480** [comment]
>  We are working on a fix for the second issue so that the badge URL works even if your VSTS project is private. In the meantime, you can work around the second issue by making your VSTS project public.

Is this second issue being tracked somewhere? Making our Azure DevOps Server 2019 instance public is not an option for us.

**Comment by teamtam** [comment]
Is this a new feature? I don't remember having this issue previously, but on a new project "Disable anonymous access to badges" was on (i.e. disabled) by default.

![BadgeAnonymousAccess](https://user-images.githubusercontent.com/4782995/83825631-339c6880-a71d-11ea-9897-33009a05f6ff.png)
