### ISSUE TITLE
Adding .gitignore default generated code 

### ISSUE THREAD

**Issue by IryTech** [MicrosoftDocs/vsts-docs#1505]
When we add default .gitignore generated code file, it not only excludes nuget pkgs and local assemblies but also exludes all the necessary system references(system, system.web etc) to build the code. Which statement in .gitignore does that. Any help plz? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3f73e6a-75c9-6a8d-c2e1-08feeb9700c1
* Version Independent ID: 80570118-9b20-9999-6464-6e9e522c1ab7
* Content: [Ignore files in your Git repo](https://docs.microsoft.com/en-us/vsts/repos/git/ignore-files?view=vsts&tabs=visual-studio)
* Content Source: [docs/repos/git/ignore-files.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/ignore-files.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by thomps23** [comment]
Please accept our apology for the significant delay in addressing this issue.

It looks like you're working through an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
