### ISSUE TITLE
Incorrect description of the "Path" field for patching a work item

### ISSUE THREAD

**Issue by sobjornstad** [MicrosoftDocs/vsts-docs#1509]
For relations, this is described as follows:
    
    Path to the value you want to add, replace, remove, or test.
    For a specific relation, use "relations/Id".
    For all relations, use "/relations/-".

Not only is this not compliant with the [JSON Patch RFC](https://tools.ietf.org/html/rfc6902) which appears to be followed otherwise, but it also doesn't work when I try it:

* Paths must always start with a `/` or you get an error saying so.
* The ID of the relation doesn't work -- you get an index out of bounds error. You have to use the index of that item in the array.
* `-` does not mean "all relations". It is only valid for adds, and it means to append things to the end of the array. Trying to use it for "all" in for instance a remove operation yields the error "remove does not support insert".

Also, the indices of the items returned in the relations array don't appear to be consistent! When I get multiple items by ID, the order often comes out different than when I get a single item by ID. This makes it extraordinarily difficult to produce a correct patch for deleting items.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c841984d-1dbb-4757-e32f-14e2b98545b5
* Version Independent ID: 8531cb41-265a-15b1-de63-9b8522571cc5
* Content: [Work Items](https://docs.microsoft.com/en-us/vsts/integrate/previous-apis/wit/work-items?view=tfs-2018#update-work-items)
* Content Source: [docs/integrate/previous-apis/wit/work-items.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/previous-apis/wit/work-items.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @sobjornstad , I know it's been a while but you've brought up good points. @wnjenkin , these previous-apis docs are older docs that were migrated over and don't get much love/attention. They're like version 2, 2.1, instead of Version 4/5 which I think we're up to now in the auto-generated docs. However, these APIs are still important to people working with certain environments. I'm not sure if there's a decent plan here for updating/keeping these fresh-ish but manually editing them is kind of rough. Do you have any thoughts?

**Comment by chcomley** [comment]
Hi @sobjornstad, following up on this issue, I've contacted the WIT group, who can make these updates, and they've created a user story to address this, slated for this next sprint.
