### ISSUE TITLE
Microsoft Consultant

### ISSUE THREAD

**Issue by jontreynes** [MicrosoftDocs/vsts-docs#1517]
Hi Munil, does your team set up contract testing for L2 tests (ex. use pact.io). If so, how is that best implemented in Azure and VSTS?
 I realize that Contract testing has huge benefits for L2 tests. 
One can simply test a branch with the pact.io broker file, rather than having to stand up and kill after short tests of the provider and consumer service in one test environment. These 2 services can simply be stood up apart from each other and testing is constructed around the services' interactions with the pact http endpoint.
If this is what your team does for l2 tests, may you please illustrate it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1acb75f5-3f74-13a0-4053-406efc5389d7
* Version Independent ID: 216cbb0d-3e7b-b24e-b3c1-a9ae7776c14a
* Content: [Shift Left to Make Testing Fast and Reliable - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/devops-at-microsoft/shift-left-make-testing-fast-reliable)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fdevops-at-microsoft%2fshift-left-make-testing-fast-reliable.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fdevops-at-microsoft%2fshift-left-make-testing-fast-reliable.md&version=GBlive&_a=contents)
* Product: **devops**
* Git Login: **samgu**
* Microsoft Alias: **munils**

**Comment by steved0x** [comment]
@jontreynes I will forward this along to Minul

**Comment by jontreynes** [comment]
Thank you @steved0x

**Comment by steved0x** [comment]
@jontreynes Let me see if I can get some other feedback. @alexhomer1 Do you have a good contact in testing that might be able to help with @jontreynes feedback?

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have asked a member of the product team for advice.

**Comment by PBoraMSFT** [comment]
Azure DevOps (formerly VSTS) is a collection of microservices. Each service exposes REST endpoints that other services within our offering (and customers writing custom clients for their needs) use. Our test bed does include REST API tests, that are generally authored using REST clients (it's largely C# code for us, but you can use any language). 

Customers that want to run tests for contracts / REST endpoints for their services can choose any form of testing for their needs. This may include - code based tests (similar to what we have), declarative REST API tests using tools such as SOAPUI or Postman. They key for integrating these tests is to configure the tool to produce an XML result format (JUnit/XUnit/NUnit) that can be published to the server, so that you get the same integrated reporting experience in the CI/CD pipeline like any other test does.

The marketplace also has service virtualization tools such as Parasoft that customers may find useful.
