### ISSUE TITLE
SubFolder

### ISSUE THREAD

**Issue by chapterjason** [MicrosoftDocs/vsts-docs#1529]
Is there a way to create repositories under sub folders, like before without git?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: beb650b9-47d2-4f04-97c9-22b9b6ddeeb9
* Version Independent ID: 74ac33fd-0fee-1b22-b783-9ed9c83a23be
* Content: [Create a new Git repo](https://docs.microsoft.com/en-us/vsts/repos/git/creatingrepo?view=vsts&tabs=visual-studio)
* Content Source: [docs/repos/git/creatingrepo.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/creatingrepo.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@chapterjason Can you give me an example? Do you mean on your local computer? Or you would like to have a file structure in your team project but have the repo start somewhere other than the root of this folder structure?

**Comment by SebastianScherer88** [comment]
Bump. The ability to add a hierarchy to the current flat structure of  repositories - i.e instead of a project being a list of parallel repos, a parent directory with subdirectories eventually containing repos at the 'leaf' level - would be a massive help in cleaning up/organising larger VSTS projects from the code side of things. I've seen this is a popular request as per your voting/feedback pages - is there any plan to have this implemented soon? It sounds to me like a small change, but maybe there is more to it than that?

**Comment by chapterjason** [comment]
Sooo this means, no one cares? :disappointed:

**Comment by pmiossec** [comment]
@chapterjason If the different repositories in the sub folders are not linked, you'd better create multiple git repositories.

If there is a **real** link between the sub repositories, you should use `git submodules`.

But because it add a big burden and are not really easy to use, you must think about it twice about using it.
And perhaps stick to the `monorepo` strategy.

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
