### ISSUE TITLE
headless server with 2 factor auth?

### ISSUE THREAD

**Issue by TBusen** [MicrosoftDocs/vsts-docs#1548]
How do I clone a repo on a headless Linux server?  I have no browser so I can't respond to the browser pop up that normally shows up.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c2f260d-9321-d669-172d-01289c233263
* Version Independent ID: 14e9ae18-df9d-7555-902c-3e8b4c2b2f22
* Content: [Connect to your Git repos using credential managers](https://docs.microsoft.com/en-us/vsts/repos/git/set-up-credential-managers?view=vsts)
* Content Source: [docs/repos/git/set-up-credential-managers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/set-up-credential-managers.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by lorenpaulsen** [comment]
You can use a PAT token or SSH authentication

**Comment by thomps23** [comment]
Please accept our apology for the significant delay in addressing this issue.

It looks like you're working through an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
