### ISSUE TITLE
How to select all automated test cases in test suite and child test suite?

### ISSUE THREAD

**Issue by Evit15** [MicrosoftDocs/vsts-docs#1588]
Hi,

I have 1 test suite parent and 3 child test suite.
If I only select test suite parent, VS Test will report the warning "no automated test cases". 
How to select all automated test cases in test suite and child test suite?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16bd8dd1-7650-8c18-2553-38a8bc54e892
* Version Independent ID: f9fa517a-7adc-e327-d12e-256295a1ed52
* Content: [Visual Studio Test](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/test/vstest?view=vsts)
* Content Source: [docs/pipelines/tasks/test/vstest.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/test/vstest.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by thomps23** [comment]
Please accept our apology for the significant delay in addressing this issue.

It looks like you're working through an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
