### ISSUE TITLE
Different view for View recent builds and build pipelines

### ISSUE THREAD

**Issue by mehagar** [MicrosoftDocs/vsts-docs#1603]
The picture on this page is different than what I see on my VSTS. I am using the new navigation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00712ea7-e53d-8178-aa4a-b11e43313bcd
* Version Independent ID: a4569948-b8ef-75bf-117b-19aa7397d309
* Content: [View builds, releases, pipelines - VSTS Public Project](https://docs.microsoft.com/en-us/vsts/organizations/public/view-build-release-public?view=vsts&tabs=new-nav)
* Content Source: [docs/organizations/public/view-build-release-public.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/public/view-build-release-public.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@mehagar - Thank you for the feedback. From time to time, the images you see may differ from what is documented due to changes made to the User Interface or Preview Features that are being introduced. It may be that your Preview Features are set differently. I've added a backlog item for me to investigate and update the page as needed. Again thank you for your comments.
