### ISSUE TITLE
Is it installed temporarily just for the build where the task is defined?

### ISSUE THREAD

**Issue by akunaatrium** [MicrosoftDocs/vsts-docs#1622]
Or will all other builds in all other build pipelines in the project be suddenly capable of using the key?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ce9d017-fc43-c904-d94b-87cf91265ffc
* Version Independent ID: ecf3b0b7-6c2c-1cd9-33a9-2cf562932e2b
* Content: [Install SSH Key](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/utility/install-ssh-key?view=vsts)
* Content Source: [docs/pipelines/tasks/utility/install-ssh-key.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/install-ssh-key.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by DavidStaheli** [comment]
Keep-alive

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
