### ISSUE TITLE
Socket Exception when running URL load test 

### ISSUE THREAD

**Issue by vindupuri** [MicrosoftDocs/vsts-docs#1655]
Running URL load test (APIM URL, where in backend is Azure function), getting socket exception. The API is working perfectly fine with in the calling application as well as in postman using the same post request with headers to it. But in Load test it fails with Socket exception.

Can you please help me knowing what wrong im doing.

**Comment by steved0x** [comment]
Thank you for your feedback. The issues in this repo are for content feedback, can you let me know the URL of the article that goes with this feedback so I can pass it along to the correct author? If this is a product issue (something not working properly, or a feature request), please file an issue here: 

Thank you.

**Comment by steved0x** [comment]
I'm closing this issue since it is not associated with a topic. To continue the discussion, please open a new issue that is associated with a topic by browsing to the topic on docs.microsoft.com and choosing **Content feedback** at the bottom. Thank you for your feedback.

![image](https://user-images.githubusercontent.com/1580889/42953695-fd174150-8b48-11e8-94de-26924ca79c71.png)
