### ISSUE TITLE
Add How to Escape Markdown

### ISSUE THREAD

**Issue by spottedmahn** [MicrosoftDocs/vsts-docs#167]
I think it would be helpful to add: how one can escape markdown on [the guidance page](https://docs.microsoft.com/en-us/vsts/collaborate/markdown-guidance).

For example, I wanted to use #some-tag but I didn't want [header formatting](https://docs.microsoft.com/en-us/vsts/collaborate/markdown-guidance#headers).

I was able to do us the traditional backslash to get what I wanted, FYI.

![image](https://user-images.githubusercontent.com/14079228/36167987-b093340e-10c5-11e8-91bf-05c9126db6c3.png)

**Comment by steved0x** [comment]
@spottedmahn How to escape special characters, including the `#` character, is covered a little bit later in that article here:

[Special characters](https://docs.microsoft.com/en-us/vsts/collaborate/markdown-guidance#special-characters)

Do you think we should call it out more or maybe rename to "Escaping special characters"?

I'm going to close this issue since we have documentation for special characters, but please re-activate it if you think the section I linked doesn't cover what you were looking for.

Thank you,
Steve

**Comment by spottedmahn** [comment]
Ah, I see, cool.  I think '**escape**' is a critical keyword.  I think most programmers what use that word to search for how to do this.

## Example in [docs](https://docs.microsoft.com/en-us/vsts/collaborate/markdown-guidance#emoji):

![image](https://user-images.githubusercontent.com/14079228/36213169-09ccb85c-1174-11e8-835e-24dd70d48bf9.png)

**Comment by spottedmahn** [comment]
Hey @steved0x - did you have a chance to review my response?
