### ISSUE TITLE
Missing Android Emulator documentation

### ISSUE THREAD

**Issue by SinZ163** [MicrosoftDocs/vsts-docs#1677]
There is a section on this article dedicated to testing on the Android Emulator, but the section just says it only works on a MacOS image, without giving any YAML on how to actually go about doing it

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 955d694a-7285-45b6-56b9-3a86ddbb0820
* Version Independent ID: 0d226e23-1ddd-f6de-abf7-5b112533ec78
* Content: [Android](https://docs.microsoft.com/en-au/azure/devops/pipelines/languages/android?view=vsts)
* Content Source: [docs/pipelines/languages/android.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/android.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by DavidStaheli** [comment]
@PBoraMSFT, is this something your team wants to look at?  We can chat about it too.

**Comment by john-mccartin-id** [comment]
@DavidStaheli My organization needs help on this as well.  Could you point us in the right direction on this?

**Comment by janpio** [comment]
This works for `vmImage: 'macOS-10.13'` @AndreyMitsyk 👍 

Any way to get Android Emulator working on `ubuntu-16.04` and `vs2017-win2016`?

Windows currently fails because I don't have the correct "Start emulator in background" command, and for Linux I have problems with the permissions of the Android Tools/SDK: `/usr/local/lib/android/sdk/../tools/bin/sdkmanager: Permission denied`

**Comment by SinZ163** [comment]
Closed by #75855
