### ISSUE TITLE
How do I edit stack rank outside of using Excel?

### ISSUE THREAD

**Issue by dyslexicanaboko** [MicrosoftDocs/vsts-docs#1696]
How do I edit stack rank outside of using Excel? I understand you want me to refrain from doing so, but if I can do it in bulk via Excel, how do I do it via the TFS web portal? I understand that this field isn't present by default on the work item form - but what do I need to do in order to edit it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb3e66f4-9767-7856-8fd8-7cbd0b144c18
* Version Independent ID: 4859bb60-1f03-6969-c242-1b682d4ca911
* Content: [Stack rank or backlog priority - Azure Boards and TFS](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/stack-rank-backlog-position?view=vsts)
* Content Source: [docs/boards/backlogs/stack-rank-backlog-position.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/stack-rank-backlog-position.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@dyslexicanaboko - Thank you for your inquiry. The Stack Rank field supports changing the backlog priority of work items as described here - https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/create-your-backlog?view=vsts&tabs=new-nav#move-items-into-priority-order. If you want to edit it from the form, you can customize a work item type so that the Stack Rank field appears on the form.
