### ISSUE TITLE
How to review all changes for single work item within single review request?

### ISSUE THREAD

**Issue by streamstr** [MicrosoftDocs/vsts-docs#1709]
Imagine a situation: Dev is working on product backlog item. He works on story for about 2 hours and during this time checks in 4 small changesets, each containing changes in 3 files. Now entire user story is ready to pass code review. How he can request code review in such situation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8bb12a7-a20c-1dd5-bca0-4873f7ab9e36
* Version Independent ID: 360739fd-e98a-535f-9872-ed58ece28194
* Content: [Get your code reviewed with Visual Studio - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/tfvc/get-code-reviewed-vs?view=vsts)
* Content Source: [docs/repos/tfvc/get-code-reviewed-vs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/tfvc/get-code-reviewed-vs.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by mmitrik** [comment]
Unfortunately, we don't have a great story here.  You can review any single changeset or shelveset, but not a range of changesets.  

In this type of scenario, I might recommend using shelvesets to shelve the work multiple times instead of checking the 4 changesets.  Then, when the work is ready for review, review the shelveset before checking in the changes.

**Comment by jrh3k5** [comment]
You can pull a shelveset into your local workspace and then push updates into that same shelveset. By reviewing the shelveset, you're effectively reviewing the accumulation of all of your individual pushes to a shelveset because a shelveset has no individual history - it's basically a living, single revision that you continually update.
