### ISSUE TITLE
Does not explain PR triggers

### ISSUE THREAD

**Issue by escalonn** [MicrosoftDocs/vsts-docs#1710]
Nothing about pull request trigger behavior here, neither for YAML or designer. It's configurable under the Triggers tab in the designer, and as far as I can tell, it is not possible to configure this in YAML yet.

(There is an undocumented `pr:` syntax that does enable PR triggering, but it's not recognized by the build agent's parser so the build immediately fails.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build pipeline triggers - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
Thank you for the feedback. Addressing with a new section.

**Comment by iinatti** [comment]
Documentation for Pull request validation trigger should also contain the information found in issue #1251 
"Pull Request validation builds for source code in VSTS is setup via branch policies and **does not show up on the build definition** (Pipelines / Builds / Triggers tab)."

**Comment by jdshkolnik** [comment]
Hi,

This is still unclear regarding expected behavior. We have a build policy with a filter defined as "/Codebase/*;/BuildRelease/*". A change is pushed to the pull request for a file located in "/Migrations". Why does the pull request still trigger a build? Is it ignoring the entire triggers section in yaml along with the build policy and assuming the build applies to every file in the repo?

cc: @chrisrpatterson

**Comment by vtbassmatt** [comment]
Build policy controls when CI builds run. PR policies have their own set of triggers. For instance, maybe you don't want a `docs/` directory built on every PR push, but you do want to build them when the branch merges to master. You can do that with a single pipeline since you can define separate excluded branches.

If you want to totally exclude automated builds from happening for a given path, you'll need to explicitly define that in both places.

![image](https://user-images.githubusercontent.com/714283/46345547-011a9e00-c613-11e8-9d05-6fe179e7ee57.png)

**Comment by jdshkolnik** [comment]
That part I understand. What I don't get is why a change in the "/Migrations" folder is triggering a build for which the branch policy is explicitly filtered to "/Codebase/*;/BuildRelease/*".

**Comment by zeppelin4x** [comment]
In our case changes in “/Migrations’ folder, the build is trigger not cause the change in the  /Migrations folder, but the PR had a previous commit outside the /Migrations folder. The build will not trigger if no prior changes outside the /Migrations folder

To test the theory, I created a new branch and PR. The PR build would not trigger the build as long as the initial commits where in /Migrations folder (filters worked as intended). However, once a non /Migration folder change has been committed, the PR triggers the build on all successor commits to just the /Migration folder.

It seems the PR build is considering all changes in its commit when applying the filters. Is this the intended behavior?

**Comment by vtbassmatt** [comment]
Yes, it's intended. PR builds should help you understand the state of the changes in the PR, whether those came in 1, 10, or 100 commits. Everything else I can think of in our PR system considers the entire delta between tip-of-PR-branch and its merge-base (most recent common ancestor) with its target branch.
