### ISSUE TITLE
What about VSTS

### ISSUE THREAD

**Issue by arcotek-ltd** [MicrosoftDocs/vsts-docs#1721]
How do I consume a package in the CD (release) part of the pipe line in VSTS (Azure DevOps (stupid name))?
Do I need to authenticate? I would hope not as I am in VSTS.
Thanks

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 899a78d6-9d08-7744-108d-10add2ba7e2c
* Version Independent ID: 6ab31e96-fed8-4335-ed81-b97663d8300f
* Content: [Consume NuGet packages in Visual Studio](https://docs.microsoft.com/en-gb/azure/devops/artifacts/nuget/consume?view=vsts&tabs=new-nav)
* Content Source: [docs/artifacts/nuget/consume.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/nuget/consume.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by cverburgh** [comment]
I have the same question. Pushed a project into Azure DevOps that uses a custom private Nuget feed, but build fails because it can't restore our packages....

**Comment by johnkors** [comment]
+1

Raised a question here as well. 

https://github.com/Microsoft/azure-pipelines-tasks/issues/8641

**Comment by elbatk** [comment]
@arcotek-ltd and @cverburgh could you both check out the answer from the [issue](https://github.com/Microsoft/azure-pipelines-tasks/issues/8641) linked above and see if that helps? 

I'm closing this as questions like these (re: "How do I xxxx?") are typically better fielded on StackOverflow. If there's a docs consequence that comes out of that conversation I'd love for you to open another issue with what the docs are missing so that I can help add good info that will help future users.
