### ISSUE TITLE
What does the '|' character do after powershell or bash in the examples above.

### ISSUE THREAD

**Issue by cicorias** [MicrosoftDocs/vsts-docs#1817]
The script tag shows steps, then a child of PowerShell that has a value of a "pipe" character:
steps:
- powershell: |
    Write-Error 'Uh oh, an error occurred'
    Write-Host 'Trying again...'

**Update**: I see in Yaml it indicates that it is a "multi-line scalar value" that follows. That to me would be a nice bit of info in this doc. Not sure if you agree.  I don't see any good Link or help on explaining Yaml itself.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=vsts)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
I'll find a good YAML overview and link to it. Thanks for the suggestion.

**Comment by heaths** [comment]
@vtbassmatt, you might also consider mentioning as a note or something that any TextMate-based YAML synctax highlighting may appear broken at times because of bug https://github.com/textmate/yaml.tmbundle/issues/26. For example, the following will appear with errors but is correct. If authors try to put the lines that begin with "*" in quotes - which for literal strings is required - it will actually include those quotes as literals and the task(s) will likely fail:

```yaml
example: |
  **/*.zip
```

I have screenshots in a [bug I opened against VSCode](https://github.com/Microsoft/vscode/issues/54219), though when digging in deeper it was discovered it was a TextMate grammar issue.

**Comment by vtbassmatt** [comment]
Thanks @heaths -- that explains the string behavior I see with our [Azure Pipelines extension](https://github.com/Microsoft/azure-pipelines-vscode) as well.

**Comment by vtbassmatt** [comment]
Still need a good "intro to YAML" someplace in our docs.

**Comment by vtbassmatt** [comment]
There's a YAML primer linked from the [schema](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#yaml-basics) now.
