### ISSUE TITLE
can we edit a page in TFS web?

### ISSUE THREAD

**Issue by malluri19** [MicrosoftDocs/vsts-docs#1839]
Under test plans, test suites we can run test cases. Under run, we have an option to run with options, which displays a page. Can we edit that page? I would like to add a text field and some validation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8b703fe-8982-4284-6db0-ef33abac08a4
* Version Independent ID: 0fc84d11-1c32-0a49-04ec-641b68f44886
* Content: [Extension Manifest Reference](https://docs.microsoft.com/en-us/azure/devops/extend/develop/manifest?view=vsts#scopes)
* Content Source: [docs/extend/develop/manifest.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/manifest.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @malluri19 , sorry for the really long delay, I'm finally getting around to this backlog. Adding @matthewisabel to get his thoughts here and make sure it's on his radar.

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
