### ISSUE TITLE
PR Labels?

### ISSUE THREAD

**Issue by spottedmahn** [MicrosoftDocs/vsts-docs#186]
What are PR Labels?

![image](https://user-images.githubusercontent.com/14079228/36551002-955ec788-17c4-11e8-8ae6-c72a741cf91f.png)

I don't seem them documented [here: Review code with pull requests](https://docs.microsoft.com/en-us/vsts/git/pull-requests).  Shouldn't it be?  Thanks!

**Comment by spottedmahn** [comment]
Just found this:

![image](https://user-images.githubusercontent.com/14079228/36553743-220feb8e-17cb-11e8-80fb-1e6ba87bc2f4.png)

[VSTS Release Notes: 2018-q1](https://docs.microsoft.com/en-us/vsts/release-notes/#2018-q1)

**Comment by spottedmahn** [comment]
[Help reviewers using pull request labels](https://docs.microsoft.com/en-us/vsts/release-notes/2018/jan-24-vsts#help-reviewers-using-pull-request-labels)

**Comment by steved0x** [comment]
@spottedmahn Pull Request labels are a new feature and there was a slight delay in getting them fully rolled out. It looks like that issue was just resolved (https://developercommunity.visualstudio.com/content/problem/197950/pull-request-labels-not-implemented.html) and we'll be updating our documentation shortly. In the short term I'll go ahead and link out to the release notes. Thank you.

**Comment by spottedmahn** [comment]
thanks @steved0x 🔥

**Comment by steved0x** [comment]
@spottedmahn You are welcome, I am merging it in now, should be live later today :)
