### ISSUE TITLE
How to connect to Microsoft Graph using Service Connections

### ISSUE THREAD

**Issue by agrabhi** [MicrosoftDocs/vsts-docs#1932]
Is I want to call a Microsodft Graph API (or any OAUTH2 based service endpoint) using VSTS service connections, which connection I should use. I tried to use Generic one and it didnt work. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72b90dd0-49f9-4ed4-3010-9a64dde6ae5a
* Version Independent ID: 6e679d50-4e94-eee3-8793-af884cc909ca
* Content: [Service connections in Azure Pipelines and Team Foundation Server](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=vsts#common-service-connection-types)
* Content Source: [docs/pipelines/library/service-endpoints.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/service-endpoints.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by azooinmyluggage** [comment]
@agrabhi You are using any task? What is the scenario?

**Comment by agrabhi** [comment]
The scenario is to be able to call MSGraph apis in CI/CD scenarios. To get a token for MSGraph using known credentials and call the apis.

**Comment by omeshp** [comment]
You can check https://github.com/Microsoft/azure-pipelines-extensions/blob/master/docs/authoring/endpoints/authenticationSchemes.md for supporting oauth2 based endpoints.

**Comment by thomps23** [comment]
Please accept our apology for the significant delay in addressing this issue.

It looks like you're working through an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
