### ISSUE TITLE
Present the previously created PAT 

### ISSUE THREAD

**Issue by westerdaled** [MicrosoftDocs/vsts-docs#1944]
Why can't we present or reference the Personal Access Token, previously created in VS Online (DevOps). This could be cached locally rather than create a new one on the fly. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c2f260d-9321-d669-172d-01289c233263
* Version Independent ID: 14e9ae18-df9d-7555-902c-3e8b4c2b2f22
* Content: [Connect to your Git repos using credential managers - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/set-up-credential-managers?view=vsts#windows)
* Content Source: [docs/repos/git/set-up-credential-managers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/set-up-credential-managers.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@westerdaled Let me see if I can find out for you - that seems like it would be a good option. If it is possible I'll add the steps to the documentation.

**Comment by westerdaled** [comment]
Hi @steved0x  ,I think the PAT gets both  seamlessy created remotely, and stored locally in the Windows Credential Manager) . The sync changes seems to be able to present this again behind the scenes.  I found this out purely by accident ;-)

**Comment by westerdaled** [comment]
@steved0x  ,  I think the PAT is created remotely and then stored locally ( by Windows Credential Manager) .  Thereafter the VSTS addin or Git Credential manger handles the retrieval of the PAT duruing the sync changes process.

**Comment by dwumpus** [comment]
For some reason, everytime I open a new command prompt and interact with Azure Git repo, it opens my browser and challenges me login. Everything works, but each time it creates a new PAT.  I just went in to manage them all and as you can expect, there are like 50 PATs created.   So, yes, I would like it if this question were answered please.

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
