### ISSUE TITLE
Nested tables are not supported

### ISSUE THREAD

**Issue by JeisonSalazar** [MicrosoftDocs/vsts-docs#1948]
I am using nested tables on a document (an entry in a table contains a table) but this is not properly shown on the page, with the nested table showing up as a separate table, and breaking any content of the initial table in the process.

I also tried using an HTML table for any nested tables but this also failed, with the page becoming completely messed up in the process. (It looked like when a table is within a table, the wiki assumes all tables are contained within each other which isn't right).

**Comment by steved0x** [comment]
@JeisonSalazar Thank you for your feedback. The issues in this repo are for content feedback, can you let me know the URL of the article that goes with this feedback so I can pass it along to the correct author? If this is a product issue (something not working properly, or a feature request), please file an issue here: https://developercommunity.visualstudio.com/spaces/21/index.html

Thank you.

**Comment by steved0x** [comment]
@JeisonSalazar I'm closing this issue since it is not associated with a topic. To continue the discussion, please open a new issue that is associated with a topic by browsing to the topic on docs.microsoft.com and choosing **Content feedback** at the bottom. Thank you for your feedback.

![image](https://user-images.githubusercontent.com/1580889/42953695-fd174150-8b48-11e8-94de-26924ca79c71.png)
