### ISSUE TITLE
Please update notes

### ISSUE THREAD

**Issue by plang85** [MicrosoftDocs/vsts-docs#1950]
There's still references to August and September rollouts, what's the current status?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3339a2e0-be29-1363-f588-b231d4472c02
* Version Independent ID: 72dd11a3-704d-d0fd-6dfa-cf49f3352de3
* Content: [Container Jobs in Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/process/container-phases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/container-phases.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **macoope**

**Comment by radu-matei** [comment]
The doc states that NodeJS is required inside the container - I successfully ran a container job in a container without NodeJS - the doc is misleading, and requiring Node in a CI container should make no sense.

**Comment by vtbassmatt** [comment]
@radu-matei ah, I think you're right. The requirement is that *either* you bring your own Node or you support our agent's distribution of Node. That's why Alpine-based containers don't work (among other things, they're musl-based whereas our Node dependency is glibc-based).

Node is a dependency for now. We're working on something a little better / less surprising. But today the container gets created like this:

`/usr/bin/docker create --name my_container_ubuntu1604 [...] "/__a/externals/node/bin/node" -e "setInterval(function(){}, 24 * 60 * 60 * 1000);"`

**Comment by vtbassmatt** [comment]
The notes have been updated (a while ago -- I forgot to close this bug).

Also, we're working on a feature where [musl-based containers can bring their own Node.js implementation](https://github.com/Microsoft/azure-pipelines-agent/blob/master/docs/design/non-glibc-containers.md). That's a separate item, though, so closing this issue.
