### ISSUE TITLE
How to include another yaml file?

### ISSUE THREAD

**Issue by markmadlangbayan** [MicrosoftDocs/vsts-docs#1952]
Is it possible to include a yaml file inside another one?

**Comment by steved0x** [comment]
@markmadlangbayan Thank you for your feedback. The issues in this repo are for content feedback, can you let me know the URL of the article that goes with this feedback so I can pass it along to the correct author? If this is a product issue (something not working properly, or a feature request), please file an issue here: https://developercommunity.visualstudio.com/spaces/21/index.html

Thank you.

**Comment by steved0x** [comment]
@markmadlangbayan I'm closing this issue since it is not associated with a topic. To continue the discussion, please open a new issue that is associated with a topic by browsing to the topic on docs.microsoft.com and choosing **Content feedback** at the bottom. Thank you for your feedback.

![image](https://user-images.githubusercontent.com/1580889/42953695-fd174150-8b48-11e8-94de-26924ca79c71.png)
