### ISSUE TITLE
Maven task: Avoid showing effective pom?

### ISSUE THREAD

**Issue by ahaeber** [MicrosoftDocs/vsts-docs#1960]
For a large multi-module project it takes a long time to execute the help:effective-pom goal. Is it possible to avoid that step?

**Comment by steved0x** [comment]
@ahaeber Thank you for your feedback. The issues in this repo are for content feedback, can you let me know the URL of the article that goes with this feedback so I can pass it along to the correct author? If this is a product issue (something not working properly, or a feature request), please file an issue here: https://developercommunity.visualstudio.com/spaces/21/index.html

Thank you.

**Comment by ahaeber** [comment]
Hi,

I don't know whether this is possible or not. That is why I'm asking. The
URL most related is
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/maven?view=vsts

Looking at the source code for the Maven task it seems like it uses the
output of that command to figure out repositories for the project. So I'm
afraid it can't be disabled.

BR Andreas

**Comment by steved0x** [comment]
@ahaeber Thank you for providing the additional information, I am assigning this issue to the right person for review.

**Comment by DavidStaheli** [comment]
Hi @ahaeber .  Apologies for the delay in getting back to you.  Since you reported this, we changed the Maven task to **avoid building the effective pom by default**.

Here is the checkbox that when enabled, causes the effective pom to be generated.  It's only necessary to enable this if you want your build to automatically authenticate to Maven artifact feeds from Azure Artifacts.

- ![image](https://user-images.githubusercontent.com/1767415/49943937-25b6b000-feb7-11e8-8e01-681037a93915.png)

If you're using YAML instead of the visual designer shown above, you can avoid building the effective pom by [setting this Maven task input to false](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/maven?view=vsts) (which is the default):

```yaml
mavenAuthenticateFeed: false
```
