### ISSUE TITLE
'configuration' documentation is not correct / complete

### ISSUE THREAD

**Issue by heaths** [MicrosoftDocs/vsts-docs#1976]
The documentation above reads,

&gt;     #configuration: '$(BuildConfiguration)' # Optional

However, based on its source at https://github.com/Microsoft/vsts-tasks/blob/9463077acb97b0414f854232861e3c785036dd37/Tasks/DotNetCoreCLIV2/task.json#L319 `configuration` is only an alias for `configurationToPackage`, and https://github.com/Microsoft/vsts-tasks/blob/9463077acb97b0414f854232861e3c785036dd37/Tasks/DotNetCoreCLIV2/task.json#L124 implies that `/p:Configuration=Release` is necessary to pass to `arguments`, which is incongruent with other tasks that take a `configuration` property.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d227a6f2-a94b-1c05-57e4-b63d42e2b9e5
* Version Independent ID: d063e189-d0fd-4ca3-c108-a0bd2ae49d22
* Content: [.NET Core CLI](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=vsts)
* Content Source: [docs/pipelines/tasks/build/dotnet-core-cli.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/dotnet-core-cli.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by StefH** [comment]
@heaths 
This looks a lot like the issue created today:

**When building configuration "Release" using the task 'DotNetCoreCLI@2', a "Debug" version is build ?**
https://github.com/MicrosoftDocs/vsts-docs/issues/2053

**Comment by heaths** [comment]
Yes, this is the same issue. That's what happened to me. Given other tasks support a `configuration` option that sets the `Configuration` property automatically - though the .NET Core CLI does not - it's very confusing to document this configuration option as it is. Conversely, .NET could just add a "real" `configuration` option like other tasks, instead of requiring people pass it via `additionalProperties`.

**Comment by karataliu** [comment]
This is still incorrect, can someone take a look?

**Comment by chasewilson** [comment]
Hi @karataliu I'll be taking a look at this issue. Feel free to reach out with anymore feedback or questions.

**Comment by chasewilson** [comment]
Hi @heaths Thanks for the feedback. I've gone and done some major updates and would appreciate, if you had a few minutes to take a look  and see if things are any clearer or if you had a suggestion you might think work better?

**Comment by heaths** [comment]
@chasewilson, do you have a link to a PR or commit?

**Comment by chasewilson** [comment]
@heaths, sorry for the delay. You can see the commit here. https://dev.azure.com/mseng/TechnicalContent/_git/vsts-docs-pr/commit/e888e43ecb68e837b0539bafcb00cc0605adcbb8?refName=refs%2Fheads%2Flive

**Comment by chasewilson** [comment]
Going through this, that does make sense to me. At this point @elbatk, it would be good to get your perspective on this. Is there current functionality to work with this and I can update the documentation?

**Comment by elbatk** [comment]
Hey @heaths , Azure Artifacts PM here. We're actually making a move away from these heavy build tasks in favor of light-weight, auth-first tasks where we handle authentication for you, and then just get out of your way and let you call your tooling (in this case dotnet) like you would from any command line. This transition will fix many annoyances, like this one, where the behavior of the task is not what you expect and it becomes a headache. 

With that said, we are putting bandwidth into the transition and don't have extra resources to update these current tasks. They are open source, however, and if you wanted to spin up a PR that updated the configuration parameter to be applicable for all commands, tag me and we would be down to take a look. This won't be very high priority for us though as it's more of a convenience feature since there isn't anything blocking you today, it's just not very intuitive. 

@chasewilson I'd say there's nothing really to do here from a docs perspective, possibly adding another line to the end of the "configurationToPack" YAML snippet line that says "Use 'arguments' to pass configs for other commands", or something so that it's more clear.
