### ISSUE TITLE
No documentation on how to deploy a Javascript function app from VSTS pipeline

### ISSUE THREAD

**Issue by GuyHarwood** [MicrosoftDocs/vsts-docs#1979]
There is no official documentation on how to deploy a javascript function app from VSTS.

I created [my own](https://guyharwood.co.uk/2018/07/26/deploy-node-js-azure-functions-from-vsts/) from snippets of different blog posts, but this no longer works since azure functions went GA on V2.

Can someone at the very least provide an official process on how to make this work

**Comment by GuyHarwood** [comment]
@ggailey777 @andyjlewis 5 months and no response?

**Comment by andyjlewis** [comment]
@GuyHarwood I'm sorry about the delayed response. I was out of the office earlier this year. When you posted your original request we did have this on the backlog. Since then we've published https://docs.microsoft.com/azure/devops/pipelines/languages/java-function. I'll add the idea to our backlog to cover the JavaScript dimension as well.
