### ISSUE TITLE
Adopt the Tab Approach for Different Versions Instead of Inline Approach

### ISSUE THREAD

**Issue by spottedmahn** [MicrosoftDocs/vsts-docs#2]
The Asp.Net Core team is using tabs to show different documentation for different versions.  I think this makes the pages more readable and definitely shorter!

[Example 1: Using Cookie Authentication without ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie?tabs=aspnetcore2x)

![image](https://user-images.githubusercontent.com/14079228/32016037-daa35936-b990-11e7-98ef-4d66c4e7447e.png)

**vs VSTS Docs**

[Kanban -> Add Columns](https://docs.microsoft.com/en-us/vsts/work/kanban/add-columns)

VSTS, TFS 2017 section
....
TFS 2015.1 section
....
TFS 2015, TFS 2013 section

All that makes the page really long and hard to skim

**Comment by EisenbergEffect** [comment]
@spottedmahn We've got an official versioning feature of the platform that is coming online soon. We're in the process of on-boarding the initial content sets now. VSTS is one of the first adopters :)

**Comment by spottedmahn** [comment]
@EisenbergEffect great!  So it is different then what the asp.net team is doing?

Anyways, I'm excited to the see the `versioning feature` 🎉

**Comment by EisenbergEffect** [comment]
@spottedmahn Yes, it's a bit different in that it has a lot more power to control what you see in the table of contents, the in this article section, the content in the article, etc. When this launches  you will see a version selector above the ToC. When you click that, you'll see every product and version that is covered by the documentation. You'll be able to select your preference and it will shift all content, ToC, nav, etc so that it displays exactly what is relevant for that version.

**Comment by scottaddie** [comment]
@spottedmahn To add to what Rob stated above, the ASP.NET docs will eventually adopt this same versioning feature.

**Comment by spottedmahn** [comment]
@EisenbergEffect nice!  sounds sweet!  and feature rich.  Hope it gets released soon!

Any blog posts or preview for this new feature?

**Comment by EisenbergEffect** [comment]
Not yet because we haven't fully onboarded the first content set. We'll definitely blog about it when we do. It's been a ton of engineering effort. It's hard to convey just how complex a feature like this is when you look at our entire platform and try to build a system that works for the whole company. So, when this launched, even though it manifested in a very simple way on the site, we'll be doing big cheers here in Redmond and in Shanghai where our teams are located :)

**Comment by spottedmahn** [comment]
Hi @EisenbergEffect - any updates on this feature?

**Comment by scottaddie** [comment]
@spottedmahn Let's ask someone else on the team. Rob has since left the company.

@erickson-doug @KathrynEE Please see the question above. Are there any updates to provide?

**Comment by spottedmahn** [comment]
>Rob has since left the company.

😭

**Comment by spottedmahn** [comment]
Hello - any updates on this?  Thanks 🙏

**Comment by paiw** [comment]
His


รับ Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by spottedmahn** [comment]
Looks like this is live now!!

![image](https://user-images.githubusercontent.com/14079228/41789332-ef5df4be-761c-11e8-887d-039efd798e79.png)
