### ISSUE TITLE
Available regions not showing up when products available by region is clicked

### ISSUE THREAD

**Issue by maniSbindra** [MicrosoftDocs/vsts-docs#2009]
When products available by region is clicked, and Azure Devops is selected, the only region it shows available is "Non Regional"
https://azure.microsoft.com/en-us/global-infrastructure/services/?products=azure-devops 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be194f45-05b2-8421-186f-f12700eea9aa
* Version Independent ID: efffdc56-fd4c-aeba-6cd3-d07aaf776d51
* Content: [Find or change your Azure DevOps organization location (region)](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/change-organization-location?view=vsts&tabs=new-nav)
* Content Source: [docs/organizations/accounts/change-organization-location.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/change-organization-location.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @maniSbindra thank you for your comment. The entry for Azure DevOps in Azure’s “Products available by region” page is not correct, and we are working to get it updated. Azure DevOps is available in the following Azure geographies: Asia Pacific, Australia, Brazil, Canada, Europe, India and the United States. Azure DevOps is delivered as a geographical service rather than a regional one, and the “Products available by region” page does not yet have the ability to indicate this, which led to the current issue. For more information on Azure geographies and regions, see https://azure.microsoft.com/en-us/global-infrastructure/geographies/.
