### ISSUE TITLE
Update for Azure Devops and the new navigation experience?

### ISSUE THREAD

**Issue by j-windsor** [MicrosoftDocs/vsts-docs#2020]
For example, It seems that it is possible to create a new icon on the vertical navigation bar, as that what Azure DevOps Packages does, but this is not in the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56437af3-75da-d219-5364-9b7927298ece
* Version Independent ID: ca01655a-9195-cf92-14b4-77ef66053dcf
* Content: [Extension Points](https://docs.microsoft.com/en-us/azure/devops/extend/reference/targets/overview?view=vsts)
* Content Source: [docs/extend/reference/targets/overview.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/reference/targets/overview.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by mehmetkut** [comment]
+1 Please update this for new navigation experience

**Comment by elbatk** [comment]
Hi everyone, this is definitely a pain point/area that we need to update. Adding @matthewisabel to add it to his radar. Sorry for the delay here, we know that this doc is out of date and hopefully can get a work item in place.

**Comment by corrededos** [comment]
+1 Please update this for new navigation experience

**Comment by zlogo** [comment]
+1 Please update the with the new information

**Comment by MichaelPlourde** [comment]
+1 Please udpate for new vertical navigation!

**Comment by mehmetkut** [comment]
Any updates?

**Comment by piense** [comment]
Please do this, it's a PITA cross-referencing what these mean vs the area I'm actually trying to extend.

**Comment by matthewisabel** [comment]
Looping through this now, will keep updating in the following PR or another one as I get through the rest of the screenshots: https://github.com/MicrosoftDocs/vsts-docs/pull/4350

**Comment by jeffpriz** [comment]
Badly need this documentation updated..

**Comment by chcomley** [comment]
@warren2k and shayki5, here's the duplicate issue. 

Work is in progress, my friends. Thank you.

**Comment by chcomley** [comment]
Hello all! We've got the ball rolling on these updates! I'll be publishing the first phase of updates to this article today, which includes versioning (with new nav) for Azure DevOps. The first phase includes new content for the "Hubs and hub groups" section. This includes a new section on [adding an icon](https:// docs.microsoft.com/en-us/azure/devops/extend/reference/targets/overview?view=azure-devops#add-an-icon), @j-windsor. This issue is linked to this initial PR, so when I publish, it will automatically close this issue. I've created 4 additional user stories for updated images (for each sub-section that remains within the "Menus and toolbars section": Azure Pipelines, Azure Repos, Azure Test Plans, and Azure Boards) slated for completion by end of January. If you have any questions or concerns, please @mention me. Thank you!
