### ISSUE TITLE
delete branch permission granularity

### ISSUE THREAD

**Issue by f00-beerd** [MicrosoftDocs/vsts-docs#2025]
We need a way to grant contributors permission to delete feature branches without allowing everything granted with the "Force Push (Rewrite History and Delete Branches)" permission.
Is this already possible? Is this on the feature roadmap?

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bf345ce-1831-bc64-bc2a-617fb69b3352
* Version Independent ID: 3f1e08ea-3db8-92e8-1873-953d1f026f25
* Content: [Set Git branch security and permissions - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-permissions?view=vsts)
* Content Source: [docs/repos/git/branch-permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/branch-permissions.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by LockTar** [comment]
A reaction from the team would be nice about this... Not be able to delete branches of team members is a functionality that would be nice.

**Comment by ecl1ps** [comment]
We found out that this permission also applies to "Delete [branch name] after merging" option when completing pull request. This was quite unexpected for us as it didn't event warned the user that branch won't be deleted. This can be fixed by allowing permission for force push but we would like it to be sepatare permission for this use case.

**Comment by tcs1896** [comment]
Our teams are experiencing the same issue described above.  This limitation does not exist in BitBucket.  Which leads me to conclude that it is not a git limitation.

**Comment by pwen090** [comment]
One thing that might work for you is you can follow the documentation here to restrict branch creation to folders such as feature, users, etc... https://docs.microsoft.com/en-us/azure/devops/repos/git/require-branch-folders?view=azure-devops&tabs=browser

Once you have done that then you can add an allow rule for a user or group to be able to ForcePush (delete branch) on anything in just a specific branch such as anything under users:
tf git permission /allow:ForcePush /user:user@server.com /collection:https://dev.azure.com/company/ /teamproject:YourProject /repository:YourRepo /branch:users

This will make it so that users have to use the feature or users folder paths and you can then specify for those paths whom is allowed to delete branches... e.g. your reviewers can delete automatically upon pull request approval/merge.

**Comment by mtaylorfsmb** [comment]
I'm more concerned about the fact that granting Force Push is required for any dev using a traditional Github/Git flow branching policy but at the same time they can also delete tags. Given that tags are how versioning is implemented in these types of flows a developer could delete all our tags (and hence version information) by accident.

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
