### ISSUE TITLE
How to import task group to Release pipeline - stage - agent job?

### ISSUE THREAD

**Issue by johnqxu1** [MicrosoftDocs/vsts-docs#2041]
On release pipe line - stage under agent job, one can add tasks, but there is no option can add task group? Is there a way to do that so when import Task group to Task Groups page, add the task group to release agent will be more quick and easy to change.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8098f527-ebdf-60d5-3989-5228b7a207c1
* Version Independent ID: ce27c817-9599-00ef-5af2-3ac1dbad8dc6
* Content: [Build and Release Tasks in Azure Pipelines and TFS - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/tasks?view=vsts)
* Content Source: [docs/pipelines/process/tasks.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/tasks.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by etaletovic** [comment]
I'd like to know as well how to do this.

**Comment by RoopeshNair** [comment]
@ashokirla  - can you please take a look?

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
