### ISSUE TITLE
Not enough information here

### ISSUE THREAD

**Issue by bigtfromaz** [MicrosoftDocs/vsts-docs#2055]
I have done all this and have a jar artifact in a feed.  So far so good.  When I try to build a project in azure dev ops the artifact cannot be found when preparing for compile.  It would appear it is only looking at Maven Central.  This page would be a good place to put some information regarding using a feed in an Azure Dev Ops build pipeline.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a845b604-ed87-fb81-fcea-3ef43062f445
* Version Independent ID: 45762c44-81aa-9c59-6011-b57e5f8f4796
* Content: [Get Started with Maven Azure Artifacts in Azure DevOps Services and TFS](https://docs.microsoft.com/en-us/azure/devops/artifacts/get-started-maven?view=vsts&tabs=new-nav#setup-your-POM-and-settings-.xml)
* Content Source: [docs/artifacts/get-started-maven.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/get-started-maven.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @bigtfromaz , you've definitely hit a weak spot in our docs and also a scenario that we need to address in the product as well. As you can tell by how short the Maven in Pipelines article that is linked to from this page. I know this is already on @alexmullans 's radar but I'm adding him for awareness.

**Comment by b-og** [comment]
You've probably fixed your problem by now. To fix this you'd need to look at the "Connect to feed" screen and take the <repository> element from there and use it inside your pom.xml <repositories>. That would tell the pom.xml where to get the artifact from. Then on your Build pipeline on the Maven task you should use mavenAuthenticateFeed: true in order to be able to use the repository connection.
