### ISSUE TITLE
AoHell

### ISSUE THREAD

**Issue by Infraton11** [MicrosoftDocs/vsts-docs#2061]
How malicious is too current application's such as relocatable.ext

**Comment by steved0x** [comment]
@Infraton11 I'm closing this issue since it is not associated with a topic. To continue the discussion, please open a new issue that is associated with a topic by browsing to the topic on docs.microsoft.com and choosing **Content feedback** at the bottom. Thank you for your feedback.

![image](https://user-images.githubusercontent.com/1580889/42953695-fd174150-8b48-11e8-94de-26924ca79c71.png)
