### ISSUE TITLE
The "Push NuGet packages" example uses wrong path separator in the 'Path to NuGet package(s) to publish' property

### ISSUE THREAD

**Issue by StefH** [MicrosoftDocs/vsts-docs#2065]
The property `packagesToPush` (Path to NuGet package(s) to publish) uses an example like `Example: **\*.nupkg;-:**\*.Tests.nupkg`, but this should be `Example: **/*.nupkg;-:**/*.Tests.nupkg` ?

 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96561b11-820d-b386-4208-e88e9552f5fc
* Version Independent ID: 42918fea-f9ad-260c-ec38-70254a47de5d
* Content: [.NET Core build and release task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core?view=vsts#push-nuget-packages)
* Content Source: [docs/pipelines/tasks/build/dotnet-core.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/dotnet-core.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **amullans**

**Comment by alexmullans** [comment]
This is an artifact of the task being multi-platform. The task docs are correct for Windows agents. @steved0x how are we handling this in general across the docs? `\` is right for Windows, `/` is right for Mac/Linux.

That said, there's also another issue here. The new version of the task moved to `!` instead of `-`. We should have a note explaining that, similar to the [note here](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget?view=vsts#push-nuget-packages).

**Comment by chasewilson** [comment]
The syntax has been updated and if there are any more issues, please reach out!
