### ISSUE TITLE
Not able to create a WPF EXE.

### ISSUE THREAD

**Issue by Antovibin** [MicrosoftDocs/vsts-docs#2066]
I am able to build the source code using DevOps, but not able to create a EXE file. 
Need a straightforward solution to create a Desktop application EXE, from Azure DevOps. 
Video link for latest devOps could help us a lot. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02b747eb-53c2-dd5f-cd2b-f337c15e0864
* Version Independent ID: 04538505-00cd-33ac-8008-4b85cca089e3
* Content: [Use the visual designer to create a CI/CD pipeline - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started-designer?view=vsts&tabs=new-nav)
* Content Source: [docs/pipelines/get-started-designer.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/get-started-designer.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by thomps23** [comment]
Please accept our apology for the significant delay in addressing this issue.

It looks like you're working through an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
