### ISSUE TITLE
Empty Artifact Name

### ISSUE THREAD

**Issue by bredar** [MicrosoftDocs/vsts-docs#2067]
I would like to set an empty artifact name. Or and option to not use the artifact name as subfolder. This, because in need to drop the artifacts in a certain way to an unc path without an additional Folder.

**Comment by steved0x** [comment]
@bredar Thank you for your feedback. The issues in this repo are for content feedback, can you let me know the URL of the article that goes with this feedback so I can pass it along to the correct author? If this is a product issue (something not working properly, or a feature request), please file an issue here: https://developercommunity.visualstudio.com/spaces/21/index.html

Thank you.

**Comment by steved0x** [comment]
I'm closing this issue since it is not associated with a topic. To continue the discussion, please open a new issue that is associated with a topic by browsing to the topic on docs.microsoft.com and choosing **Content feedback** at the bottom. Thank you for your feedback.

![image](https://user-images.githubusercontent.com/1580889/42953695-fd174150-8b48-11e8-94de-26924ca79c71.png)
