### ISSUE TITLE
existing build pipeline -> selected phase -> view YAML -> variable missing

### ISSUE THREAD

**Issue by HeikoWitthoeft** [MicrosoftDocs/vsts-docs#2082]
Hi, we faced the problem that we wanted to reuse a existing build definition on another repository. So we copied our build pipeline with that "view YAML" window on the needed Phase. In that Phase we have some steps of type task: CmdLine@1. In the third of those we use a variable which is copied just fine, in the fith step we use another variable which is just missing. If we select the command line step itself the variable is contained. So only if we select the overall summary that one is missing. I could not find any difference for those variables so I assume this is a bug. 

TBH: i dont know if i am in the right spot for this, let me know if i should submit that somewhere else please.
Best Regards :)

**Comment by steved0x** [comment]
I'm closing this issue since it is not associated with a topic. To continue the discussion, please open a new issue that is associated with a topic by browsing to the topic on docs.microsoft.com and choosing **Content feedback** at the bottom. Thank you for your feedback.

![image](https://user-images.githubusercontent.com/1580889/42953695-fd174150-8b48-11e8-94de-26924ca79c71.png)
