### ISSUE TITLE
Private Agent missing .taskkey file in working direktory

### ISSUE THREAD

**Issue by out-dev** [MicrosoftDocs/vsts-docs#2111]
After a restart of the private build agent the .taskkey is missing in the working directory. When executing a build it tries to access the .taskkey file. This fails and so the build fails as well.

How can I recreate the .taskkey file? After a restart this file will not be created again.

The files _update.cmd, IMC.hiv are also missing.

I am happy about every idea

Simon Schmitt

**Comment by steved0x** [comment]
@out-dev Thank you for your feedback. The issues in this repo are for content feedback, can you let me know the URL of the article that goes with this feedback so I can pass it along to the correct author? If this is a product issue (something not working properly, or a feature request), please file an issue here: https://developercommunity.visualstudio.com/spaces/21/index.html

Thank you.

**Comment by steved0x** [comment]
I'm closing this issue since it is not associated with a topic. To continue the discussion, please open a new issue that is associated with a topic by browsing to the topic on docs.microsoft.com and choosing **Content feedback** at the bottom. Thank you for your feedback.

![image](https://user-images.githubusercontent.com/1580889/42953695-fd174150-8b48-11e8-94de-26924ca79c71.png)
