### ISSUE TITLE
DateTimeOffset sub Duration should return DateTimeOffset

### ISSUE THREAD

**Issue by hegold** [MicrosoftDocs/vsts-docs#215]
Instead, it throws.

In my example, trying to use `now() sub duration'P1D'`  in a $filter results in:

```
{
  "error": {
    "code": "0",
    "message": "Arithmetic expressions over arguments without a common numeric type is not supported.",
    "innererror": {
      "message": "Arithmetic expressions over arguments without a common numeric type is not supported.",
      "type": "Microsoft.VisualStudio.Services.Analytics.ODataUnsupportedFeatureException",
      "stacktrace": ""
    }
  }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54c923a7-9e1f-d0fe-badc-c68facc63ab5
* Version Independent ID: 381a3f9c-c068-2eba-9f61-58f98e0bd868
* [Content](https://docs.microsoft.com/en-us/vsts/report/extend-analytics/odata-supported-features#not-supported-features)
* [Content Source](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/report/extend-analytics/odata-supported-features.md)
* Service: unspecified

**Comment by zsd4yr** [comment]
@KathrynEE  @steved0x @JoshCZimmerman  can we get this reopened?
This is a rather cumbersome feature gap for our team

**Comment by WilliamAntonRohm** [comment]
@zsd4yr -- Zachary, thank you for your followup.  This is more a product issue than a documentation issue.  Please add it here:
- [Developer Community](https://developercommunity.visualstudio.com/AzureDevOps)

**Comment by zsd4yr** [comment]
@WilliamAntonRohm can you help me find if there is an existing issue on the developer community?

**Comment by WilliamAntonRohm** [comment]
@zsd4yr -- Zachary, thank you for your followup.  I'm not sure of the context for your intended task, which will determine the keywords to search for.

**Comment by ligei2** [comment]
Replying in place of Zach, since he replied on my behalf and I am them one hitting the issue.

The goal is to get a relative-date filter into an OData query of Azure DevOps, without creating a dynamic query.

I first attempted to filter by a date in an OData query, passed via a variable (created in Power Query M) giving me a date 10 days in the past.  This created a dynamic query, which wouldn't refresh automatically on the Power BI service.
"$apply=filter(SamplingTime gt " & RelativeDateAsString & ")"

My second attempt was to use Web.Content() to work around having a dynamic query, but I suspect it didn't succeed due to OData syntax needs.  Perhaps there is a solution, but I didn't find one. (Workaround provided by [Chris Webb's BI Blog: Using The RelativePath And Query Options With Web.Contents() In Power Query And Power BI M Code (crossjoin.co.uk)](https://blog.crossjoin.co.uk/2016/08/16/using-the-relativepath-and-query-options-with-web-contents-in-power-query-and-power-bi-m-code/))
    Filter = "1&$apply=filter(SamplingTime ge " & RelativeDateAsString & ")",
    Source = Json.Document(Web.Contents("https://analytics.dev.azure.com", [RelativePath="orgName/projectName/_odata/v4.0-preview/TaskAgentRequestSnapshots", Query=[1=Filter]])),
**Outcome** _not filtered_

Lastly, I proceeded to attempt to use OData to perform the calculation in the query.
"@TenDaysAgo=Now() sub duration'P10D'&$apply=filter=(SamplingTime ge @TenDaysAgo)"
**Outcome** _VS403534: Arithmetic expressions over arguments without a common numeric type is not supported._

The error lead me to this issue page regarding the documentation, which is the wrong location to be commenting.  However, I have also seen another page, which may be the developer community?
[Support subtraction for Date/DateTimeOffset types · Issue #1743 · OData/WebApi · GitHub](https://github.com/OData/WebApi/issues/1743)

**Comment by WilliamAntonRohm** [comment]
@ligei2 -- Lilly, thank you for your detailed follow-up.  This query seems close to this issue:
- https://developercommunity.visualstudio.com/AzureDevOps?q=relative+date+filter+OData

cc @steved0x for awareness

**Comment by ligei2** [comment]
I found the work around I need:  powerbi.com stores the specific URL used for querying OData, but the VSTS.Contents() connector (I'm using OAuth2 to authenticate) doesn't.  Hence all the querying I need to do for OData completed with a single authentication.  Thus, a dynamic query is supported with scheduled refreshing.

No follow-up necessary.  I appreciate the hand with the issue, even though my flow is off topic.
