### ISSUE TITLE
Code Coverage Report disabled by iframe sandbox settings

### ISSUE THREAD

**Issue by jordanbrock** [MicrosoftDocs/vsts-docs#2168]
Within the Azure Devops Pipelines "Code Coverage" tab, the SimpleCov Code Coverage report is embedded within an iframe with the sandbox enabled, which prevents the JavaScript within the SimpleCov Report from working. Is there a way around this limitation? 

Here is an example of the code:
&lt;iframe sandbox src="https://dev.azure.com/&lt;fullpath deleted&gt;/Code Coverage Report_95/index.html" class="code-coverage-summary-frame"&gt;&lt;/iframe&gt;

Is this a bug/request that should be submitted to a different team? If so, where should I send it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45d010e9-7e5a-3f62-8c10-29c0c1b64846
* Version Independent ID: d274c8a4-aca9-6e8e-5b28-5a62d1e7c85d
* Content: [Building Ruby projects with Azure Pipelines - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/ruby?view=vsts#example)
* Content Source: [docs/pipelines/languages/ruby.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/ruby.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by JimmyCouch** [comment]
This appears to still be an issue. Are there any updates?

**Comment by jordanbrock** [comment]
@PBoraMSFT Just wondering if there's any comment on this at all? the stale bot has marked the issue as stale, and I'm still waiting on some form of response.

**Comment by PBoraMSFT** [comment]
@jordanbrock - this was a known limitation of the coverage report rendering. Since the HTML could contain anything, it could lead to security issues if rendered as is. Hence, the HTML was sanitized before rendering. 
We recently fixed this by generating our own HTML report - you no longer need to supply an HTML file and since we control the HTML content, it can be rendered with full fidelity. Please give it a shot and let us know if this is still an issue for you.

See the release notes for details.
https://docs.microsoft.com/en-us/azure/devops/release-notes/2019/sprint-150-update#cobertura-code-coverage-report-updates

**Comment by jordanbrock** [comment]
Thanks for the update @PBoraMSFT I'll check it out.

**Comment by jordanbrock** [comment]
@PBoraMSFT That's awesome. Works wonderfully. Thanks to you and the team for all your work.

I'll close the issue.

**Comment by steved0x** [comment]
@jordanbrock And we have disabled the stale bot as well and that will go live once we do our first documentation publishing after the BUILD conference.
