### ISSUE TITLE
Testing Bug-Fixes under Scrum

### ISSUE THREAD

**Issue by todor-dk** [MicrosoftDocs/vsts-docs#2203]
Under the Scrum template, it is little unclear to me, what is the workflow of a bug after it has been fixed by a developer.

Under the Agile template, the developer team will set the item into Review/QA state. When QA has reviewed the item does it become "Done".

Under Scrum, it is unclear to me when an item (especially bug) is "Done". And also, how do the development team mark the item as "Done by Development" and "Ready for Testing". I am aware that the bug may be reopened if not fixed correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58aacca7-05a2-e8dd-6a6f-3025d734ef20
* Version Independent ID: 3eea19c1-8bda-6b60-e77d-8c0e82c3f096
* Content: [Create & manage bugs using Agile tools - Azure Boards and TFS](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/manage-bugs?view=vsts&tabs=new-web-form)
* Content Source: [docs/boards/backlogs/manage-bugs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/manage-bugs.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by danhellem** [comment]
[This will give you a high level](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/guidance/scrum-process-workflow?view=vsts) of how the scrum process works.

The short answer is, keep the bug in the doing column until all tasks are completed. Your tasks can be activities you need to finish the bug so that it is considered 100% done. Things like "complete testing", "validate", etc. Once all the tasks are completed you can mark the bug as done.

Alternatively you can always customize the process and another state to help you track "Ready for Testing".

Tags may also help you if you want to that route.
