### ISSUE TITLE
Web trigger

### ISSUE THREAD

**Issue by htmlauthor** [MicrosoftDocs/vsts-docs#2238]
We have a very unusual use case where code we are working with cannot be tracked in GIT or other usual repository. We still want and need to use build pipeline to run QA jobs. The only way I can think of now is trigger by calling some URL available on Azure DevOps, something like https://company.visualstudio.com/project/build/trigger. Calling this URL from our internal tooling would trigger build pipeline to run.

Is there, by any chance, plan to implement something like this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build pipeline triggers - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=vsts&tabs=designer)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by mijacobs** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
