### ISSUE TITLE
Unable to Connect to GitHub for Deployment

### ISSUE THREAD

**Issue by RehanSaeed** [MicrosoftDocs/vsts-docs#2255]
I'm able to select the GitHub organisation but the drop down for the repo is empty. I have to enter the repo name `Azure` and branch name `master` manually myself. However, the `Default Version` dropdown also has nothing in it and I can't select anything to create the connection.

![untitled](https://user-images.githubusercontent.com/2270364/47617823-5c7d6600-dac3-11e8-8c48-bc86c8930bb4.png)

**Comment by RehanSaeed** [comment]
Here is another screenshot showing an error:

![image](https://user-images.githubusercontent.com/2270364/47800039-6a312680-dd23-11e8-8bf1-4afefe5c2bf6.png)

**Comment by RehanSaeed** [comment]
Any news?

**Comment by RoopeshNair** [comment]
@RehanSaeed - can you create a new GitHub service connection and try? Let us know if it isn't working

**Comment by RehanSaeed** [comment]
How can I create one for an organisation?

**Comment by RehanSaeed** [comment]
I had to create a new connection using tokens instead of OAuth. When I use OAuth, I can't see repositories for any of the GitHub organisations I am a member of.

**Comment by lkillgore** [comment]
Hi @RehanSaeed,
- How was your original endpoint set up?  (OAuth or GitHub Pipelines App)  I ask because the error message is connected with using the GitHub App.  Does the repository you're using have the Azure Pipelines app installed in the GitHub repository?
- From your screenshot, it seems that the repository information wasn't filled out correctly.  (For instance, you have 'master' (a branch name) in the repository section.)  What is the repository you were trying to set up here?  It should be in the format of 'org/reponame', so 'Azure/myrepo' or 'MyOrg/Azure' or something.

Notably, the org you're trying to access matters.  If you go to Github->Settings->Applications->Authorized OAuth Applications.  You should see the Azure Pipelines OAuth app in your list.  It should look something like this:
![image](https://user-images.githubusercontent.com/26548919/49949473-af6c7a80-fec3-11e8-800e-a69e4ab1898f.png)

Does the org you're looking to access have a 'green check mark'?  Or does it have a 'red X'?  There may be a button that allows you to request access or grant it to the side:
![image](https://user-images.githubusercontent.com/26548919/49949551-e478cd00-fec3-11e8-87cb-13047cff40c9.png)

It won't show up in your list of OAuth repositories until it's been granted there.

Thanks!

**Comment by RehanSaeed** [comment]
Thanks, fixed.
