### ISSUE TITLE
exclude builds when new branches are created

### ISSUE THREAD

**Issue by jeffpriz** [MicrosoftDocs/vsts-docs#2268]
I would like to be able to have one build to build "features/*" as shown, however this ends up triggering a build each time a new branch is created.. this ends up creating a number of un-necessary builds (if I create a new branch off of develop, this really isn't necessary to build, as the commits to develop would have already built)..  I'd like a method of building for "all the branches" but don't need builds for things that haven't changed.

**Comment by steved0x** [comment]
@jeffpriz Thank you for your feedback. Can you let me know the URL of the article that goes with this feedback so I can pass it along to the correct author?

Are you looking at this one: https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-policies?view=vsts#build-validation

Or is it this one: https://docs.microsoft.com/en-us/azure/devops/pipelines/build/ci-build-git?view=vsts&tabs=yaml

Or another one?

Thank you.

**Comment by jeffpriz** [comment]
It was the 2nd one the build-multiple branches one.

thanks

**Comment by steved0x** [comment]
@jeffpriz Thank you, we'll see if we can find a way for you to do that.

**Comment by steved0x** [comment]
@jeffpriz Sorry for the great delay, I am following up on this and hope to have an answer soon. The only way I know of off the top of my head is if you are creating the branch locally, and then don't push it up to the server until it has some changes on it. My personal workflow however is to create my new branches on the server (directly from my user stories) which does also trigger a build as you desribe. Let me see if I can get some info for you.

**Comment by steved0x** [comment]
@jeffpriz Currently this is a limitation in the product, and you can see more information here:

* https://developercommunity.visualstudio.com/content/problem/53496/build-definition-triggers-when-i-create-a-new-bran.html
* https://developercommunity.visualstudio.com/idea/394272/prevent-create-a-new-branch-from-triggering-a-buil.html

There is a possible workaround documented in the first link above, similar to the following:

1. Create a new branch locally but don't push it up
2. Make a commit to the branch and include `***NO_CI***` or one of the other "no commit" messages as decribed [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#skipping-ci-for-individual-commits)
3. Push the branch to the remote repo, creating the branch there
4. There should be no "initial" CI build on this new branch, due to the commit message

You can review the two feature requests linked above and vote on one (or both) of them to help the get increased visibility with the product teams.

Thank you for your feedback.
