### ISSUE TITLE
Mention that scope changes in your extension will change the extension certificate

### ISSUE THREAD

**Issue by pkuma-msft** [MicrosoftDocs/vsts-docs#227]
It'll be good to mention that scope changes in extension would cause the certificate to change. We've had a couple of instances where this happened.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: add23736-f0a9-2cc7-8bd2-4b8720898552
* Version Independent ID: 3f763c47-317d-a32a-37dd-6507d3f630b5
* [Content](https://docs.microsoft.com/en-us/vsts/extend/develop/auth)
* [Content Source](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/extend/develop/auth.md)
* Service: unspecified

**Comment by elbatk** [comment]
Thanks @pkuma-msft , that's solid input and I'm adding a warning that explains cert changes after scope alterations!

**Comment by andreinfra** [comment]
I am looking for a problem to link to this link https://docs.microsoft.com/en-us/vsts/extend/develop/auth?view=vsts where System.IdentityModel.Tokens.Jwt is maintained. version 4.0.2.206221351 can not be installed on dotnet core 2.0 because it does not recognize the TokenValidationParameters so the page is outdated. Can someone help me to authenticate as the page quoted correctly?

**Comment by elbatk** [comment]
Hi @andreinfra , sorry to be getting to this so late, could you open another issue and I'll try to get some answers for you? Closing the original one here.
