### ISSUE TITLE
PR template message in "Complete pull request" dialog

### ISSUE THREAD

**Issue by noogn** [MicrosoftDocs/vsts-docs#2294]
When you complete a pull request, a dialog appears with fields prepopulated with PR description and details. The details field is filled with the contents of the PR template. Is there a way to prevent the PR template from being populated in that field?

Example screen to demonstrate what I mean:

![image of "Complete pull request" dialog with pull request description field prepopulated with pull request template](https://user-images.githubusercontent.com/2731056/47753249-fb37db80-dcea-11e8-9682-65ad70f17aef.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a297d54f-48b3-1b68-e828-15d1559d9b2d
* Version Independent ID: fd9dcb35-72f9-f5a9-e0c0-75c3e59ba8d9
* Content: [Improve your pull request descriptions using pull request templates - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/pull-request-templates?view=vsts)
* Content Source: [docs/repos/git/pull-request-templates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/pull-request-templates.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@noogn I am checking but I don't think so - the contents of the pull request template are saved into the description of the PR when you create it, and then when you complete the PR, the PR description (that now contains the contents of the PR template) is used to pre-populate that box.

You have a couple of options:

1. Edit the PR description as you are creating the PR and move the PR template down, or edit/delete all or part of it. 
2. After you create the PR, move the PR template contents from the PR description and move them into a comment.
3. Before completing the PR, edit the description to remove the parts you don't want
4. As you are completing the PR, edit the contents of the description box and remove the parts you don't want before completing the PR.

Would any of those work for you? Since the PR template contents become part of the PR description, I don't know if there is an automatic way to have it not appear in the description box when you complete the PR,

**Comment by noogn** [comment]
Shame there isn't automated way to clean up that description box. I'll be going with one of the workarounds you suggested.

Thanks for the detailed response.
