### ISSUE TITLE
How does IIS Deploy set the value of the Package Or Folder?

### ISSUE THREAD

**Issue by staneee** [MicrosoftDocs/vsts-docs#2297]
The path to the package.zip is dynamic, how do I get it through the environment variable?

![image](https://user-images.githubusercontent.com/26987099/47763203-b451e200-dcfa-11e8-9976-6b6fe1d9ae27.png)

![image](https://user-images.githubusercontent.com/26987099/47763269-fd099b00-dcfa-11e8-92cd-3a2dd42e22ef.png)

![image](https://user-images.githubusercontent.com/26987099/47763260-f3803300-dcfa-11e8-8e79-69d1d0e8e2db.png)

**Comment by steved0x** [comment]
@staneee Thank you for the feedback. Can you let me know which article this feedback is for, so I can assign it to the author? You can reply here with the URL of the topic, or you can create a new issue by browsing to the topic on docs.microsoft.com and choosing **Content feedback** at the bottom. 

![image](https://user-images.githubusercontent.com/1580889/42953695-fd174150-8b48-11e8-94de-26924ca79c71.png)

**Comment by steved0x** [comment]
I'm closing this issue since it is not associated with a topic. To continue the discussion, please open a new issue that is associated with a topic by browsing to the topic on docs.microsoft.com and choosing **Content feedback** at the bottom. Thank you for your feedback.

![image](https://user-images.githubusercontent.com/1580889/42953695-fd174150-8b48-11e8-94de-26924ca79c71.png)
