### ISSUE TITLE
PR permissions and roles

### ISSUE THREAD

**Issue by MisinformedDNA** [MicrosoftDocs/vsts-docs#2336]
I, a project admin, rejected a PR and then another project admin came along and reset my vote. He probably shouldn't be a project admin anyway, but I'm not sure what specific rights give him the power to override me. Can you clarify?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 028e7b61-62e4-a10e-e420-3535f7843f0e
* Version Independent ID: 1a6fdbe7-5ba4-a7f8-1b2e-271289a7b9fd
* Content: [Review and merge code with pull requests - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/pull-requests?view=vsts&tabs=new-nav#review-a-pull-request)
* Content Source: [docs/repos/git/pull-requests.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/pull-requests.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by thomps23** [comment]
Please accept our apology for the significant delay in addressing this issue.

It looks like you're working through an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
