### ISSUE TITLE
Error on 'Build an Image'

### ISSUE THREAD

**Issue by stevennwood** [MicrosoftDocs/vsts-docs#234]
Am getting an error with this on VSTS on visualstudio.com:

failed to register layer: re-exec error: exit status 1: output: ProcessUtilityVMImage C:\ProgramData\docker\windowsfilter\375e60ffec4c4894997ce3a8b2c09a7688a9da16ac3cda591404a282ebaf065e\UtilityVM: The system cannot find the path specified.

See log below

Am I missing something?

******************************************************************************
Starting: Build an image
******************************************************************************
==============================================================================
Task         : Docker
Description  : Build, tag, push, or run Docker images, or run a Docker command. Task can be used with Docker or Azure Container registry.
Version      : 0.3.6
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?linkid=848006)
==============================================================================
"C:\Program Files\Docker\docker.exe" build -f D:\a\1\s\MyWebApi\Dockerfile -t mywebapicontainerregistry.azurecr.io/pip17p:17 D:\a\1\s\MyWebApi
Sending build context to Docker daemon  1.075MB
Step 1/18 : FROM microsoft/aspnetcore:2.0-nanoserver-1709 AS base
2.0-nanoserver-1709: Pulling from microsoft/aspnetcore
407ada6e90de: Pulling fs layer
3cb15ab58a2c: Pulling fs layer
1050149864b0: Pulling fs layer
32214cb47dab: Pulling fs layer
03328e43f821: Pulling fs layer
a919756ad928: Pulling fs layer
2b59d8ec4fd9: Pulling fs layer
e7ebf6a1687b: Pulling fs layer
4e7d1817baa3: Pulling fs layer
a919756ad928: Waiting
2b59d8ec4fd9: Waiting
e7ebf6a1687b: Waiting
4e7d1817baa3: Waiting
32214cb47dab: Waiting
03328e43f821: Waiting
1050149864b0: Verifying Checksum
1050149864b0: Download complete
32214cb47dab: Verifying Checksum
32214cb47dab: Download complete
03328e43f821: Verifying Checksum
03328e43f821: Download complete
a919756ad928: Verifying Checksum
a919756ad928: Download complete
2b59d8ec4fd9: Verifying Checksum
2b59d8ec4fd9: Download complete
3cb15ab58a2c: Verifying Checksum
3cb15ab58a2c: Download complete
e7ebf6a1687b: Verifying Checksum
e7ebf6a1687b: Download complete
407ada6e90de: Verifying Checksum
407ada6e90de: Download complete
4e7d1817baa3: Verifying Checksum
4e7d1817baa3: Download complete
failed to register layer: re-exec error: exit status 1: output: ProcessUtilityVMImage C:\ProgramData\docker\windowsfilter\375e60ffec4c4894997ce3a8b2c09a7688a9da16ac3cda591404a282ebaf065e\UtilityVM: The system cannot find the path specified.
C:\Program Files\Docker\docker.exe failed with return code: 1
******************************************************************************
Finishing: Build an image
******************************************************************************

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc9593a-77be-75c1-8d20-86a995d925f6
* Version Independent ID: 63c81326-3b7a-8452-bc04-95ff06e517a7
* [Content](https://docs.microsoft.com/en-us/vsts/build-release/apps/containers/build?tabs=web)
* [Content Source](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/apps/containers/build.md)
* Service: unspecified

**Comment by andyjlewis** [comment]
Hi stevennwood, thanks for the question. I'm following up with the product team.

**Comment by vijayma** [comment]
You are using 1709 version of container image, and that is not compatible with the OS of the hosted image that we run.
https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility
https://github.com/docker/for-win/issues/1800
We are working on supporting these newer container images. Until then, your best best is to run a private agent.

**Comment by satya0025** [comment]
Can someone look at this error and help me out?

##[section]Starting: dotnet build Release
==============================================================================
Task         : Command Line
Description  : Run a command line script using cmd.exe on Windows and bash on macOS and Linux.
Version      : 2.148.0
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613735)
==============================================================================
Generating script.
Script contents:
dotnet build --configuration Release
========================== Starting Command Output ===========================
[command]/bin/bash --noprofile --norc /home/vsts/work/_temp/99f7da28-e596-4f31-937b-3dd11a892174.sh
Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1011: Specify which project or solution file to use because this folder contains more than one project or solution file.
##[error]Bash exited with code '1'.
##[section]Finishing: dotnet build Release
