### ISSUE TITLE
Custom RBAC

### ISSUE THREAD

**Issue by StefanIvemo** [MicrosoftDocs/vsts-docs#2412]
The steps in this article provides very high privileges at the subscription level, which is not suitable for most organizations. You should updated this article with info regarding which Azure Resource Manager resource provider operations is needed to create a custom RBAC role for the purpose.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9433f55f-62e8-c143-539d-f1e03dea0bb3
* Version Independent ID: 14911897-df06-41a9-1d47-c5f8f61ae7e9
* Content: [Add a user who can purchase](https://docs.microsoft.com/en-us/azure/devops/organizations/billing/add-backup-billing-managers?view=vsts)
* Content Source: [docs/organizations/billing/add-backup-billing-managers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/billing/add-backup-billing-managers.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks @StefanIvemo, I've created a work item for my backlog.

**Comment by wadesh** [comment]
@chcomley any update on this? I just had another global enterprise customer ask the same question...

**Comment by andyjballgit** [comment]
Hi there, 

Any update on this ? 

regards, 
Andy.

**Comment by alex-3sr** [comment]
Hi everyone,

work item has an update about this "must have" feature ? it's not imaginable to add contributor righ at subscription level for just add some VS licences. Please, can you give us an update.

Thanks
Alexandre

**Comment by drewbren** [comment]
We haven’t created a custom RBAC role, but what we’ve done is to leverage the admin role we already have in Azure DevOps. In the past, you needed to have at least contributor rights to make any purchases (ie. to increase/decrease the count of paid users, pipelines, etc…). Now you only need to have contributor access _initially_ to set up billing (a one time operation). After that, anyone you add as an Project Collection Admin in Azure DevOps can add paid users, increase/decrease pipelines, etc… We’ve actually changed the title of this topic from “Add a user who can purchase” to “Add a user who can set up billing” to reflect this change. This means you can either A) add an subscription admin to your DevOps org one time to set up billing or B) grant one of your DevOps admins temporary access to the Azure subscription in order to set up billing and then remove it. Let us know if this addresses your feedback.

Thanks,
-Andrew

**Comment by alex-3sr** [comment]
Hi Andrew, Thanks for your quick reply. So if I understand correctly, I just to give contributor 1 time for its first bill, then i can remove rbac access to azure subscription and let only PCA role in DevOps. If this process works, so yes for me it's enough ;)
Thanks
Alexandre
