### ISSUE TITLE
Work item tracking

### ISSUE THREAD

**Issue by tanzencoder** [MicrosoftDocs/vsts-docs#2427]
I love the information on using Git and it has provided us with a lot of information. One question that keeps coming up that I haven't found a solution for yet is work item tracking. When we did our releases off of the master branch all work items that were tagged since the last release were associated with the new build and release in the pipeline. We have switch to doing release branches (we do like that better) the work item linking now includes all work items not the ones since the last release. How can we fix that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7f4784d-1539-adc9-68e1-036cfc004722
* Version Independent ID: d02a6a52-e736-b411-b2f8-5be08ad3f5a0
* Content: [How We Use Git at Microsoft - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/devops-at-microsoft/use-git-microsoft)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fdevops-at-microsoft%2fuse-git-microsoft.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fdevops-at-microsoft%2fuse-git-microsoft.md&version=GBlive&_a=contents)
* Product: **devops**
* Git Login: **samgu**
* Microsoft Alias: **samgu**

**Comment by steved0x** [comment]
@KathrynEE Do you have any ideas?

**Comment by olesjo** [comment]
Did you find a solution to this?

**Comment by thomps23** [comment]
Please accept our apology for the significant delay in addressing this issue.

It looks like you're working through an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
