### ISSUE TITLE
Idioms support

### ISSUE THREAD

**Issue by rafsanulhasan** [MicrosoftDocs/vsts-docs#2460]
Is Xamarin Android Watch/TV, Xamarin MAC/tvOS/watchOS supported in the pipeline?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c45a95ce-73c8-861e-f92d-a26f1667aa60
* Version Independent ID: ecb82128-cdf4-3834-62c1-2cf61989ab5e
* Content: [Building Xamarin apps with Azure Pipelines - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/xamarin?view=vsts)
* Content Source: [docs/pipelines/languages/xamarin.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/xamarin.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by DavidStaheli** [comment]
Hi @rafsanulhasan.  Those app types should be supported just fine in Azure Pipelines.  Can you describe the additional options you're looking for?  Since some of those app types require multiple Apple provisioning profiles, you might need to use the [Install Apple Provisioning Profile](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/install-apple-provisioning-profile?view=vsts) task multiple times, or install all of them on the agent machine if it is hosted by you.  I'm closing this issue for now, but please reopen it if you're encountering any problem that we can help with or document better.
