### ISSUE TITLE
downloadType argument enum not clear

### ISSUE THREAD

**Issue by atg-abhishek** [MicrosoftDocs/vsts-docs#2515]
For the downloadType argument, it is not clear what the difference between 'single' and 'specific' is from the description provided

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0a16bcf-af6c-e278-f0a6-8ec95012ce4a
* Version Independent ID: ae442106-33b3-786f-2158-34eed3fed6e0
* Content: [Download Build Artifacts task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-build-artifacts?view=vsts)
* Content Source: [docs/pipelines/tasks/utility/download-build-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/download-build-artifacts.md)
* Product: **devops**
* GitHub Login: @erickson-doug
* Microsoft Alias: **dastahel**

**Comment by DavidStaheli** [comment]
@Lovakumar does your team own this task and its docs?  If so, could you please assign this issue appropriately?

**Comment by DavidStaheli** [comment]
@Lovakumar does your team own this task and its docs? If so, could you please assign this issue appropriately?

**Comment by davidstaheli** [comment]
This has been clarified in the docs which should be live within a few days.

Options: single vs. specific:
Choose whether to download a **single** artifact or all artifacts of a **specific** build.

**Comment by seesharprun** [comment]
That's still not very clear. Is the enum value ``specific`` and that means use the **specific build**?

**Comment by JoeBrockhaus** [comment]
>> Choose whether to download a single artifact or all artifacts of a specific build.
> That's still not very clear.

Not only is is not very clear, it actually seems wrong _(or other bits are still wrong)_.
The use of the value `specific` to denote `all` files seems to be the confusion. 
Both of these settings values should be applied to the `specified build`, right?

Given the Description: 
> Choose whether to download a single artifact or all artifacts of a specific build.

How should that be interpreted?

1. 
   - "... download a single artifact .. of a specific build."
   - "... download all artifacts .. of a specific build."
     _(but really: "... download *specific* artifacts .. of a specific build.")_

2. 
   - "... download a single artifact."
   - "... download all artifacts of a specific build."
 
Interpretation `#2` doesn't make a lot of sense as a binary option; it forces a dual meaning of 'specific' between the description + option. If downloading a 'single' artifact, how would I specify a build? 

If the intent and functionality should follow Interpretation #1, then the config value of '`specific` is referring to the specific artifacts+files you want to download, right? If that follows, then this would be a better Description: 

> _Choose whether to download a *single* artifact or *specific* artifacts of the configured build or pipeline._ 

This would at least remove the overload of the term 'specific', which in the configuration **_value_** is undoubtedly referring to **_specific artifacts_**, and not **_a specific build_**, as the Description seems to allude. 

This still doesn't help the confusion between the `artifactName (required)` and `itemPattern (optional)` when combined with this setting. Based on the current docs, if `downloadType` == `specific`, `artifactName` is basically ignored because `the default pattern will download all files across all artifacts`. While we're at it, *what is the default pattern*?
