### ISSUE TITLE
Signed builds

### ISSUE THREAD

**Issue by marwaeldafrawy** [MicrosoftDocs/vsts-docs#2520]
How can we specify these arguments? 
/target 
/p:SignAssembly
/p:AssemblyOriginatorKeyFile
/p:DelaySign=true 
/p:BuildProjectReferences

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 483dcb1c-1a89-2b20-4cf2-abd3ae88d9ed
* Version Independent ID: dc4722ed-5a4b-26ec-e7d5-a149bf6e79a7
* Content: [Building .NET Core projects with Azure Pipelines and Team Foundation Server (TFS) - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/dotnet-core?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/languages/dotnet-core.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/dotnet-core.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by thomps23** [comment]
Please accept our apology for the significant delay in addressing this issue.

It looks like you're working through an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
