### ISSUE TITLE
When do team members try out the code?

### ISSUE THREAD

**Issue by MisinformedDNA** [MicrosoftDocs/vsts-docs#2530]
In reference to

> We require a successful build (including passing tests), signoff by the owners of any code that was touched, and a handful of external checks verifying corporate policies before a PR can be completed.

What does "signoff" involve for the team? Is the PR code spun up in a separate environment? Or are PR signoffs based mostly on an "eyeball approach"?

If an environment is spun up for each PR, is that manual or automatic? And is there an auto-delete of the resources once the PR is accepted?

Right now, our PRs are by "eyeball" and then the code is auto-deployed to a team dev environment, where everyone can always see the latest changes and developers can see that their code works in an environment that is not their own. We definitely have room for improvement.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7f4784d-1539-adc9-68e1-036cfc004722
* Version Independent ID: d02a6a52-e736-b411-b2f8-5be08ad3f5a0
* Content: [How We Use Git at Microsoft - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/devops-at-microsoft/use-git-microsoft)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fdevops-at-microsoft%2fuse-git-microsoft.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fdevops-at-microsoft%2fuse-git-microsoft.md&version=GBlive&_a=contents)
* Product: **devops**
* Git Login: **samgu**
* Microsoft Alias: **samgu**

**Comment by steved0x** [comment]
@MisinformedDNA Signoff means approval by required reviewers that are added based on the path of files modified in the PR, as described [here](https://docs.microsoft.com/en-us/azure/devops/git/branch-policies#automatically-include-code-reviewers)

For example, consider this docs repo, where there are different folders for the different product areas for Azure DevOps Services, such as Pipelines or Repos. We have required reviewers setup based on these paths, and any PR that touches files in those paths must be approved before the PR can be merged.

Does that help answer your question?

**Comment by MisinformedDNA** [comment]
@steved0x Thanks for your reply. The crux of my question is really about when developers first get to test-drive new code. Does this happen as part of the PR? Or only after the push to production starts?

**Comment by vtbassmatt** [comment]
Hi @MisinformedDNA - author of that doc here :grin:

The short answer is, there's no one answer. It varies depending on the scope of the change, area of the product, comfort level of the developer doing the review, and more.

In many (most?) cases, developers will pull the branch, build it, and deploy it locally to a test environment. That can be a heavy process, especially for a change that's dependent on a particular data set or data shape. So for some cases, it's easier for a reviewing developer to walk over to the other dev's desk (or do a screen share, if folks are remote). These kind of "over the shoulder" code reviews are also fairly common.

There's a huuuuge range at the extremes, though. Let me illustrate two ends of the spectrum, while again emphasizing that most changes are somewhere in between these two extremes.

On the low end: as a PM, my code changes are largely restricted to strings in resource files. The engineers don't love it when I try to write actual product code. Even strings have the potential to break the experience, though: one extraneous `{}` placeholder and you're in for a bad time. But string formatting is well-understood and largely not confusing. If a working string is replaced by different words, most reviewers won't spin up an environment to test it. Instead, they'll visually inspect that I got the placeholders in the right places per the callsites, that the text makes sense for known inputs, etc. (I recently got called out on a change I made -- the most common input was a project name, and that's what my new string assumed, but the dev knew about one edge case where it could be a project GUID instead...)

On the high end: we've been working closely with a partner team on a very large change for the past 3-4 months. So big that we've got an entire production-like environment set up for them to test in essentially realtime. That environment gets deployed from the topic branch, not from `master`, and it's configured so that only people with @microsoft.com identities can see it. But in other respects, it might as well be production: it's on our Azure subscriptions with production storage and compute, it deploys through a release pipeline, etc. Reviews for that code tend to happen in this production-like environment.

One final thought: these things are not mutually exclusive. A *really* common pattern is to do a visual inspection on things like "does this match the patterns/practices of the team?", "are the files in the right places and named properly?", etc. Then one of the pull/build/deploy or in-person processes kicks in.

Hope this helps!
