### ISSUE TITLE
Squash/No-FF merge results in merge conflicts in master when using gitflow strategy

### ISSUE THREAD

**Issue by wkosten1982** [MicrosoftDocs/vsts-docs#2531]
We often have merge conflicts in a pull-request to master from a release branch. We would like to squash but because this creates a new commit in master it also results very often in a merge conflict in the next pull request to master. We think this is because development continues from develop branch and not master as described here above. 

Not sure if this is a Azure DevOps issue or just an issue of git

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56dec464-f25a-5c46-52e7-2cbf17a2db1d
* Version Independent ID: bbe4d6d1-71a7-0c47-7bfb-1577760e003b
* Content: [Squash merge your pull requests - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/merging-with-squash?view=vsts)
* Content Source: [docs/repos/git/merging-with-squash.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/merging-with-squash.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by dubcdr** [comment]
My project is having a similar issue. I thought I was going crazy. Someone I put it together and came here to see if anyone else had input

**Comment by krilbe** [comment]
Doesn't GitFlow specify that the merge from release to both master and back to develop? I assumed that this would avoid the merge conflicts that you encounter, but I haven't tried it yet. We're moving towards GitFlow, so I'd appreciate comments about this.

**Comment by thomps23** [comment]
Please accept our apology for the significant delay in addressing this issue.

It looks like you're working through an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
