### ISSUE TITLE
Group Rules - Adding User

### ISSUE THREAD

**Issue by ksix** [MicrosoftDocs/vsts-docs#2557]
It seems group rule group members are added to "all users" only after a group member tries to login the first time. Before that the users from the group don't appear in the users list. Once the user is there the group rules are successfully managing the user's licenses / project access.

Is _**not**_ creating the users before their first Azure DevOps login expected behaviour?

Either way can the documentation be updated to describe this in more detail?

Another user having the same problem here:
https://developercommunity.visualstudio.com/content/problem/343044/group-rules-not-working-in-azure-devops.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba38644a-fe6c-e644-2f35-2cf6fa092650
* Version Independent ID: 7d18b423-923f-d9c4-e451-ab7f8ff27bb1
* Content: [Assign access levels and extensions to users by group membership in Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/assign-access-levels-and-extensions-by-group-membership?view=vsts&tabs=new-nav)
* Content Source: [docs/organizations/accounts/assign-access-levels-and-extensions-by-group-membership.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/assign-access-levels-and-extensions-by-group-membership.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
@ksix, That is the intended behavior. Group rules are used purely for *licensing* and not for permissions. It is the same way that Office 365 group licensing works. I've created a work item on my backlog to clarity within the documentation. Thank you!

**Comment by ksix** [comment]
Hi @chcomley, not entirely sure you are correct that it is licensing only and not permissions also. There is an option with group rules to assign Project Membership at a particular permission level. There is a whole panel for it?

As for the users not being created until they login, sure? Although probably not the best or expected behaviour?

**Comment by alictai** [comment]
Hi @ksix, 

Azure DevOps includes group-based licensing for Azure Active Directory (Azure AD) groups and Azure DevOps group so you can assign an access level or extensions to a group. Resources in Azure DevOps are assigned to all members of the group. This enables organization administrators to easily automate their licensing policies.

The licenses are assigned upon users' first sign-in to the organization, as available, so that large groups are not arbitrarily assigned an insufficient license count. Users who have taken up a license will be reflected in the Users list. If you would prefer to explicitly manage all licenses without group rules, and have all users immediately materialize in your Users list, then you must add them individually.

The Permissions tab on the group details are provided as a convenience for viewing what the group, and consequently any users (once they sign into the organization) in the group have access to.

-Ali Tai
