### ISSUE TITLE
Incorrect twine command in the documentation

### ISSUE THREAD

**Issue by SimonKrischer** [MicrosoftDocs/vsts-docs#2589]
Doc says to use --config-file $(PYPIRC_PATH) as part of the twine command, but that syntax is incorrect.  It should be --config-file $PYPIRC_PATH.  The original gives me an error that the PYPRRC_PATH command is not found.

**Comment by gaborbernat** [comment]
Either should work, 👍 the $() applies the replace at the template level, while the $ just at environment level. Can you provide an example?

**Comment by SimonKrischer** [comment]
Here is a snippet from the Azure log when I used

twine upload -r KeplerTool --config-file $(PYPIRC_PATH) dist/*


2018-11-27T16:46:25.0655214Z ++ PYPIRC_PATH
2018-11-27T16:46:25.0656197Z ./scripts/deploy.sh: line 12: PYPIRC_PATH:
command not found
2018-11-27T16:46:25.0659888Z + python3 -m twine upload -r KeplerTool
--config-file dist/kepler_protobuf-2.1.304-py3-none-any.whl
dist/kepler-protobuf-2.1.304.tar.gz

Notice that PYPIRC_PATH is being treated as a command, and "the result"
expands to ''.

When I try it without the parens

twine upload -r KeplerTool --config-file $PYPIRC_PATH dist/*


2018-11-27T19:28:16.7880664Z + python3 -m twine upload -r KeplerTool
--config-file /vsts-agent/_work/4/twineAuthenticate/dPK7w5/.pypirc
dist/kepler_protobuf-2.1.309-py3-none-any.whl
dist/kepler-protobuf-2.1.309.tar.gz
2018-11-27T19:28:17.0576523Z Uploading distributions to
https://jet-tfs.pkgs.visualstudio.com/_packaging/KeplerTool/pypi/upload
2018-11-27T19:28:17.0576896Z Uploading
kepler_protobuf-2.1.309-py3-none-any.whl


PYPIRC_PATH is treated as an actual bash variable, and get expanded
correctly.


Our Azure agent is running Ubuntu Linux if that helps.

**Comment by steved0x** [comment]
@SimonKrischer Can you let me know the URL of the doc and I can forward this to that author for their feedback.

**Comment by steved0x** [comment]
@SimonKrischer I'll see if I can find it by doing a search.

Here are a couple of possibilities:
https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pypi?view=vsts&tabs=yaml#use-a-custom-twine-task-to-publish

https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/python?view=vsts&tabs=ubuntu-16-04#publish-with-twine

Any feedback for either of these articles would go to the same place, so I am assigning this issue to that author to see if they have any feedback for you.

@alexmullans David Staheli is OOF until January, but since this also had to do with artifacts I thought you might have some feedback?

Thanks!

**Comment by elbatk** [comment]
Hey everyone, going to loop @alexmullans back in, but it looks like it should either be no parentheses at all: $PYPIRC_PATH, or brackets: ${PYPIRC_PATH}. This could be a OS-based issue though. Alex, I think just no brackets or parens would be fine, but let me know what you think
