### ISSUE TITLE
Need help responding to engineers who are frustrated with the constant changes in Azure DevOps

### ISSUE THREAD

**Issue by SilverHawk777** [MicrosoftDocs/vsts-docs#2610]
They say that the constant changes to the interface, processes have caused them productivity issues. There is no warning a change is coming or a way to defer the change. They say is it hard to plan a project that has deadlines and that the rate and level of changes have been too much. I want to convey how working in Azure DevOps has positives over on-premise TFS and the why and wherefor of having Microsoft manage the environment. I need to craft a palatable encouraging reply so they do not get so discouraged, they think of going somewhere else. Any suggestions or document on line that could help me do this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cf98c4b-9185-00d5-a980-e2adb3e291fd
* Version Independent ID: f6005931-c9b5-48d9-e6c3-f835bb9b01b1
* Content: [What is DevOps? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/what-is-devops?view=vsts)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fwhat-is-devops.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fwhat-is-devops.md&version=GBlive&_a=contents)
* Product: **devops**
* Git Login: **samgu**
* Microsoft Alias: **samgu**

**Comment by MattDavisRM** [comment]
From the feedback that you've gotten your engineers, what do they feel like is the biggest recent change they were surprised by?  The new navigation?  My experience as a consumer of the service has been that the Azure DevOps team has been very transparent and very organized about what they are planning feature-wise and the timing on roll-out.  I haven't seen any real breaking changes enforced before they've been available to try through preview feature flags for at least a few months.

You can refer them to the [features timeline](https://docs.microsoft.com/en-us/azure/devops/release-notes/) for upcoming roadmap items.

You can refer them to the DevOps blog which usually has a lot of neat info about upcoming or planned item.  Specifically, if you want to understand what the roll-out schedule is for the new navigation, it's been available since [September](https://blogs.msdn.microsoft.com/devops/2018/09/24/navigation-update-for-azure-devops/).

I personally would probably push back on their assertions that things are being rolled-out without change or communication.  Most of the new features start opt-in, so I'd start encouraging them to understand what's available and start trying out the features ahead of time so they don't feel like changes are sprung on them.

**Comment by SilverHawk777** [comment]
Thank you for getting back to me. Everything you are saying makes perfect sense to me as the Azure admin and I just
need to help the engineers get comfortable with the rapidly changing( better) way of working in Azure DevOps.

I think this is what upset them the most.
Our engineers that have MSDN subscriptions have had them for more than 2 years.
We have an Enterprise agreement and we renew every 3 years for 3 more years.
Up until recently, our engineers had to create a Microsoft ID with their email as a username.
That username and Microsoft ID password was how they accessed projects in VSTS (Now Azure DevOps)

Our company now has Azure AD that sync’s with our on premise Active Directory. Our engineers are now ‘tenants’ in Azure AD.

I saw a communication a while back that Microsoft was changing some things and no longer going to allow access via the ‘personal’ Microsoft ID to projects in the cloud
after a certain time if the person had a matching email address in a company Azure AD.

That timeline passed and we did not see it ‘enforced’ ,,,then suddenly about a month ago, it was enforced.
All of the sudden, engineers started getting “401 Not Authorized” errors when they tried to access the Azure DevOps projects.

The workaround I had to do was delete their current MSDN.
Then assign a new MSDN from the drop down box where it selected their company email from Azure AD.
The original MS ID as an example was carol.flavin@welchallyn<mailto:carol.flavin@welchallyn>, now the new MSDN is flavinc1@welchallyn.com<mailto:flavinc1@welchallyn.com>

After assigning a new MSDN, I had to remove their old username from the top level Azure repository (i.e. https://welchallyn.visualstudio.com)
This also removed them from all the projects under that repository.
Then I added the new username back at the top level and to every subsequent project where they previously had access.

Fallout:
They were able to access the projects again, however, if they had work items, you have to go into EACH work item and change
the assigned to name to the new username. They are confused now more than ever as they have an account for TFS onpremise
which is tied to their domain credentials, Azure DevOps which is their company email account, and various other accounts and passwords
for other applications in our organization. Bottom Line: Too many accounts and having to keep track of what account goes with what applications, etc.

So far, we have had to do this for a LOT of engineers. I am fixing them as they let me know.

**Comment by steved0x** [comment]
@SilverHawk777 Thank you for this feedback and discussion. The issues in this repo are primarily for documentation feedback (and I can see how this thread would fit into that). For product feedback (which this thread could also fit into), you can continue the conversation by creating an issue here:

https://developercommunity.visualstudio.com/spaces/21/index.html

Thank you again for the feedback and sorry that you ran into trouble.
