### ISSUE TITLE
How to determine if given Azure DevOps PAT token is valid for all accessible organizations?

### ISSUE THREAD

**Issue by konrad-jamrozik** [MicrosoftDocs/vsts-docs#2647]
Please see my question I asked on public Stack Overflow: [How to determine if given Azure DevOps PAT token is valid for all accessible organizations?](https://stackoverflow.com/questions/53623171/how-to-determine-if-given-azure-devops-pat-token-is-valid-for-all-accessible-org)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bfea574-db69-a5fd-37fe-64ecfdac502a
* Version Independent ID: 4037d475-f194-2ac9-ffd6-70530fc3140a
* Content: [Authenticate access with personal access tokens in Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=vsts)
* Content Source: [docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/use-personal-access-tokens-to-authenticate.md)
* Product: **devops**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @konrad-jamrozik, 
I've copied and pasted the answer from StackOverflow at the bottom of this comment, for your reference. Yes, you can test whether a PAT has access to an organization by checking the projects API, but that doesn't say what kind of access it has. Please let me know if you have further questions. Thank you.

There's no API that I know of that validates a PAT or otherwise tells you information about it.

The easiest way to check if a PAT has access somewhere is to use it to access a REST API. If you get a 200, you're all good. If you get a 401, you don't have access. Listing projects is a pretty safe operation that basically any PAT that has access to an organization is going to be able to do:
GET https://dev.azure.com/{organization}/_apis/projects/?api-version=4.1
