### ISSUE TITLE
O365 domain account can't sign in

### ISSUE THREAD

**Issue by blade-feng-wang** [MicrosoftDocs/vsts-docs#2664]
I can't login using the Office365 domain account here, the error shows the microsoft account doesn't exist. But I can use my personal Microsoft account *@outlook.com.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c2f260d-9321-d669-172d-01289c233263
* Version Independent ID: 14e9ae18-df9d-7555-902c-3e8b4c2b2f22
* Content: [Connect to your Git repos using credential managers - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/set-up-credential-managers?view=vsts)
* Content Source: [docs/repos/git/set-up-credential-managers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/set-up-credential-managers.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@blade-feng-wang Sorry that you ran into trouble. Thank you for your feedback. The issues in this repo are for content feedback, and this sounds like a product feedback or a bug. For product feedback, including feature requests or bugs, please file an issue here: https://developercommunity.visualstudio.com/spaces/21/index.html

If this turns out to be a documentation issue, I will get this article updated.

Thank you.
