### ISSUE TITLE
Default pull request templates only appear when checked into master branch

### ISSUE THREAD

**Issue by eddylu94** [MicrosoftDocs/vsts-docs#2681]
From personal experimentation, it seems that VSTS pull request description fields are pre-populated by the default pull request template after the template has been checked into the master branch of the repository; whereas if the template is only checked into branches other than the master branch, then the pull request description fields remain empty. Is this the expected behaviour?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a297d54f-48b3-1b68-e828-15d1559d9b2d
* Version Independent ID: fd9dcb35-72f9-f5a9-e0c0-75c3e59ba8d9
* Content: [Improve your pull request descriptions using pull request templates - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/pull-request-templates?view=vsts)
* Content Source: [docs/repos/git/pull-request-templates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/pull-request-templates.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@eddylu94 Hi Eddy, yes, this is the expected behavior. I will make an update to the article to see if I can clarify that. If you think it would be a good idea to use other branches (such as you describe above where your source branch has a pull request template) you can file it with the product team here:

https://developercommunity.visualstudio.com/spaces/21/index.html

I'll get that article updated shortly.

Thank you for the feedback.

**Comment by KUGA2** [comment]
I created a feature request here:
https://developercommunity.visualstudio.com/idea/975580/pull-request-templates-should-be-branch-specific.html
Upvote if you agree.
