### ISSUE TITLE
create variables inside Variable groups using VSTS Cli

### ISSUE THREAD

**Issue by abhiramani-iptiq** [MicrosoftDocs/vsts-docs#2748]
Any way to create/update/list variables inside Variable groups using VSTS Cli?
Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by steved0x** [comment]
@abhiramani-iptiq Thank you for your feedback. I am forwarding this to the author of some of the variables articles to see if they can help.

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by thomps23** [comment]
Please accept our apologies for the delay in getting to this issue. It looks like you were working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking your question in the future:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
