### ISSUE TITLE
Unclear Documentation About Casting

### ISSUE THREAD

**Issue by rvlacil** [MicrosoftDocs/vsts-docs#2773]
Seems to me that the documentation is bit unclear about how types are casted from one to another. Types paragraph uses this example:

Types
Although expressions evaluate to strings, they're coerced to other data types as needed. For instance, if an inner function evaluates to "true" and then is used as an input to and(), it will be coerced to Boolean True.

It seems that it implies that "true" is coerced to True because it has value "true". But String paragraph clearly says:

String
To Boolean: '' (the empty string) → False, any other string → True

So it seems the Types paragraph should be rephrased a bit not to give the false assumption of the "true" -&gt; True casting as it is also "false" -&gt; True

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=vsts)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by HermanCordes** [comment]
Why is this issue closed? The examples on the page still don't provide any guidance on how to cast values. 

For instance, how to use a variable to perform a greater than comparison. As far as I understand, such a variable reference first needs to be cast to a numeric value. How can this be accomplished? What function to use for this?

**Comment by vtbassmatt** [comment]
There aren't explicit cast functions. The operators automatically cast as needed. I can make that more clear in the docs.

**Comment by cpdohert** [comment]
The specific case of myCustomVariable = 'false' (or '0') *evaluating to True instead of False* needs to be called out explicitly.  This is extremely counter-intuitive and it cost us several days of debugging.  We make heavy use of conditional execution based on custom variables and myCustomVariable = 'False' is much more readable by our release operators than myCustomVariable = ''

**Comment by vtbassmatt** [comment]
@cpdohert sorry you spent so much time debugging that 😞 I agree and would recommend you switch to string comparison instead of relying on casting: `$[ if eq(variables.myCustomVariable, 'False') ]`

It's documented [on that page](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#string-1). If you have suggestions on how to make it more obvious, I'd be happy to hear them.
