### ISSUE TITLE
Regarding Azure Scanner

### ISSUE THREAD

**Issue by udayansarma** [MicrosoftDocs/vsts-docs#2801]
Hello Mike,
Can you provide more details on the "Azure Scanner" component? I was interested in learning how did you create it, any logic used etc. so I can recreate it assuming it is not available as service.

Thanks
Udy  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31e62447-f971-a085-7ded-442a363f31e7
* Version Independent ID: 5c650019-951f-b103-3010-bfee05b99acc
* Content: [Add Continuous Security Validation to your CICD Pipeline](https://docs.microsoft.com/en-us/azure/devops/articles/security-validation-cicd-pipeline?view=vsts)
* Content Source: [docs/articles/security-validation-cicd-pipeline.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/articles/security-validation-cicd-pipeline.md)
* Product: **devops**
* GitHub Login: @mikedouglasdev
* Microsoft Alias: **douge**

**Comment by steved0x** [comment]
@udayansarma I'll reach out to Mike and see if we can get some more details.

**Comment by steved0x** [comment]
@mikedouglasdev Do you have any more information to share from this customer feedback?

**Comment by mikedouglasdev** [comment]
sorry for the late delay.  I'll upload it to my repo and let you know when it is there.

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
