### ISSUE TITLE
Broken Functionality

### ISSUE THREAD

**Issue by dmakaroff** [MicrosoftDocs/vsts-docs#2839]
The workaround to authorise a resource does not work anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee4ec9d0-e0d5-4fb4-7c3e-b84abfa290c2
* Version Independent ID: 3e2b80d9-30e5-0c48-49f0-4fcdfedf5eee
* Content: [Resources - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=vsts)
* Content Source: [docs/pipelines/process/resources.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/resources.md)
* Product: **devops**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **alewis**

**Comment by tsuga** [comment]
I agree. I cannot authorize a resource anymore.

**Comment by vtbassmatt** [comment]
@vijayma did we change something in 144 which would invalidate the workaround?

**Comment by scottdallamura** [comment]
what type(s) of resources are you attempting to authorize?

**Comment by scottdallamura** [comment]
ok, cool.  glad it worked on a second try.  i'll take a look and make sure there's no flakiness here, just in case.

**Comment by mmikola** [comment]
I have the same issue with ACR, unable to authorise it.

**Comment by Iristyle** [comment]
Running into same issue with now failing authorizations. We have 5 repos configured in total. 2 of them, after making a change in the editor yesterday (rather than the YAML in corresponding repo), have lost authorization to a custom private agent pool.

This had been working properly for months, so something has recently changed on the Azure side it looks like.

**Comment by vtbassmatt** [comment]
@mmikola @Iristyle we took a look and don't see any obvious culprits. Since this is the repo for documentation feedback, let's move this over to a more formal product support channel. [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html) has more engineers and support folks who can dig in and figure out what's up.

**Comment by sc250024** [comment]
I recently added a new Kubernetes service endpoint; now all of the builds we have are broken. None of them are YAML based; they're from before the YAML pipelines were even available. I'd prefer NOT to have to redo all of them.

**Comment by vtbassmatt** [comment]
The docs repo isn't the right place to get product support.
