### ISSUE TITLE
How to add to public upstream extra remote nuget feeds?

### ISSUE THREAD

**Issue by vutkin** [MicrosoftDocs/vsts-docs#2845]
Hello team,

How can I add public nuget package feed on a premises hosted on Azure DevOps 2018 environment?

We need add to upstream url from https://nuget.devexpress.com.

https://docs.microsoft.com/en-us/azure/devops/artifacts/concepts/upstream-sources?view=vsts#

Content: Upstream sources
Product: Azure DevOps Service

**Comment by elbatk** [comment]
Hi @vutkin , which update of TFS 2018 are you running? NuGet upstream sources are only available in Update 2 or later.

**Comment by vutkin** [comment]
Hi @elbatk , we are using Azure DevOps (VSTS). So I guess latest.

**Comment by elbatk** [comment]
Oh okay, yes if you have Azure DevOps Services (previously VSTS), it updates automatically. 

So I know that you can add custom upstream sources by following the [instructions here](https://docs.microsoft.com/en-us/azure/devops/artifacts/nuget/upstream-sources?view=azdevops&tabs=new-nav), except modifying it slightly to choose "custom" instead of the nuget.org stream. However, it looks like we may only currently support **npm** packages from custom sources. This issue in the developer community discusses this in a little more detail: https://developercommunity.visualstudio.com/content/problem/375634/cant-add-nuget-upstream-source-in-azure-artifacts.html. Adding @alexmullans to see if he has any insight on plans and workarounds, but it's looking like we just don't support it at the moment.

**Comment by elbatk** [comment]
I'll throw that on the backlog and add it today, thanks Alex. Sorry @vutkin , hopefully that dev community post can help you work around this for now. Going to add the snippet about custom upstream sources and close this as a docs issue now.
