### ISSUE TITLE
Can't use variables for sshEndpoint in SSH Deployment Task

### ISSUE THREAD

**Issue by daanishmillwallacg** [MicrosoftDocs/vsts-docs#2849]
jobs:

- job: deployjob

  pool:
    vmImage: 'Ubuntu 16.04'
    
  strategy:
    matrix:
        box_1:
            endpoint: Box1
        box_2:
            endpoint: Box2
  

  steps:
  
  - script: echo $(endpoint) #works and prints Box 1 and Box 2 on two jobs
    
  - task: SSH@0
    inputs:
        sshEndpoint: $(endpoint) # doesn't work and literally uses $(endpoint)
        runOptions: commands
        commands: '/home/deploy-scripts/script.sh'

The SSH Deployment task doesn't resolve variables for its sshEndpoint parameter.

**Comment by steved0x** [comment]
@alexhomer1 Can you assist with this one, it sounds like it is about variables?

**Comment by alexhomer1** [comment]
Thank you for your feedback. Bugs, issues, suggestions, and feature requests related to the product rather than the documentation are best posted on the Developer Community website at https://developercommunity.visualstudio.com/spaces/21/index.html, where they are tracked by the product teams, who will be able to offer advice. Please post your feedback there. 

I will also consult the development team about this issue to see if this is expected behavior, and update the documentation as required.

Thank you.
