### ISSUE TITLE
Allowing a variable to be set at queue time doesn't tell you how

### ISSUE THREAD

**Issue by CoolDadTx** [MicrosoftDocs/vsts-docs#2895]
The documentation for allowing a variable to be set at queue time says to not define the variable inside the variables section. But if you don't define it there then where would you define it such that it could have a default value and still be overridable? An example of how to do this would be great.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Pipeline variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=vsts&tabs=yaml%2Cbatch)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
Today, you have to *not* include the variable in the YAML file in order to set it at queue time. You can set a value in the pipeline editor which will be used as the default, and at queue time, someone can replace it. I'll add a note to the doc.

I have a feature on my backlog to have formal, queue-time parameters which will fix this with a true "config as code" approach.
