### ISSUE TITLE
Jenkins query failed with exception'No connection could be made because the target machine actively refused it 127.0.0.1:8080 '

### ISSUE THREAD

**Issue by kotnav01** [MicrosoftDocs/vsts-docs#2905]
Thank you for document , I'm following this document https://docs.microsoft.com/en-us/azure/devops/service-hooks/services/jenkins?view=vsts to setup Jenkins serive hooks subscription within the Azure Devops Projects , but getting error :: Jenkins query failed with exception'No connection could be made because the target machine actively refused it 127.0.0.1:8080 '

Is their anything we need to make changes on our jenkins side , Attached error picture 
![servicehook](https://user-images.githubusercontent.com/45443358/50648128-00f6ab00-0f40-11e9-92cb-f406e3b56b78.PNG)

**Comment by wangpengxpy** [comment]
Has this problem been resolved? I also encountered the same problem

**Comment by kotnav01** [comment]
Yeah, to work with service hooks in Azure Devops the target URL need to be public accessible.  I't would be great if Microsoft come up with best solution like Express routes to make it more secure,

**Comment by elbatk** [comment]
Hey everyone! Thank you for your feedback. Bugs, issues, suggestions, and feature requests related to the product rather than the documentation are best posted on the Developer Community website at https://developercommunity.visualstudio.com/spaces/21/index.html, where they are tracked by the product teams. It looks like you may have a solid suggestion! Thank you.
