### ISSUE TITLE
'Deploy a web app' YAML step fails for me with an ASP.NET core 2.1 project.

### ISSUE THREAD

**Issue by keithbabinec** [MicrosoftDocs/vsts-docs#2930]
When I attempted to build my ASP.NET core 2.1 project in an Azure DevOps pipeline, I hit an error: "No web project was found in the repository". You can see some discussion from other people who experience it here: https://stackoverflow.com/questions/46694349/ci-cd-of-a-asp-net-core-web-api-using-vsts. 

The problem here seems to be that dotnet core 2 creates an appsettings.json file instead of a web.config- so the build step thinks there is no web project to publish (even though there is a web project present). I had to set the publishWebProjects property to false and then manually specify the csproj file to publish. 

It would be appreciated if the example was updated to reflect ASP.NET core 2+.

Thanks!
Keith

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 483dcb1c-1a89-2b20-4cf2-abd3ae88d9ed
* Version Independent ID: dc4722ed-5a4b-26ec-e7d5-a149bf6e79a7
* Content: [Build, test, and deploy .NET Core apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/dotnet-core?view=vsts&tabs=yaml)
* Content Source: [docs/pipelines/languages/dotnet-core.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/dotnet-core.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by vijayma** [comment]
1. Updated the sample repo and this topic to work with dotnet sdk 2.2.
2. Updated the sample repo so that the "Create your first pipeline" topic creates the azure-pipelines.yml file instead of a pre-created one. This will ensure that any future updates we make in the YAML template apply to the topic automatically.
3. If you are using the designer, then you would have to uncheck "Publish web projects".
