### ISSUE TITLE
VikAnt1010Admin2019AP○○●PC●○•APP

### ISSUE THREAD

**Issue by VikAnt1010** [MicrosoftDocs/vsts-docs#2934]
Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by steved0x** [comment]
@VikAnt1010 Thank you for the feedback, but it looks like the feedback portion is missing. I'm closing this issue since it is not associated with a topic. To continue the discussion, please open a new issue that is associated with a topic by browsing to the topic on docs.microsoft.com and choosing **Content feedback** at the bottom. Thank you for your feedback.

![image](https://user-images.githubusercontent.com/1580889/42953695-fd174150-8b48-11e8-94de-26924ca79c71.png)
