### ISSUE TITLE
Need to copy files using Deployment groups

### ISSUE THREAD

**Issue by PillaiOEC** [MicrosoftDocs/vsts-docs#2973]
LINK: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/windows-machine-file-copy?view=vsts#q--a

Do you have anything that i can use to copy files to remote machines using a deployment group?

**Comment by steved0x** [comment]
@PillaiOEC I have assigned this issue to the folks responsible for deployments tasks, but since the issues in this repo are for documentation feedback, you may get a faster reply by posting here, which is for product feedback and questions:

https://developercommunity.visualstudio.com/spaces/21/index.html

**Comment by RoopeshNair** [comment]
Assuming remote machines are not part of deployment group, 

- You can use PowerShell on Target step from a deployment group target and copy the files to remote machine. 
- Or you can use Windows File Copy task to copy to remote target. 
- If the remote machine is an Azure VM, then you can use Azure File Copy task.  
- If the target is a Linux VM, then use SSH task.

**Comment by msisterna** [comment]
Hi @PillaiOEC, did you find any solution to do that?.
I want to copy files to the remote machines that match the tag from the deployment group.
