### ISSUE TITLE
Associating an NUnit test case to a TFS test case 

### ISSUE THREAD

**Issue by jonTuck23031991** [MicrosoftDocs/vsts-docs#2978]
Hi

I have associated an NUnit test case in Visual Studio to a test case in a TFS suite, I am using VS Enterprise 15.9.4.

When i enter that test case in the design view on TFS and enter Associated Automation I can see the correct Automated Test Case and Automated Test Storage associations.

After I have ran a build of that automation project on TFS I as hoping to see the TFS test cases status update to represent a pass after the automated test run but the test cases status is still active.

Am i missing a piece of setup that it is needed or have I missed the point in how this association is supposed to work?

**Comment by steved0x** [comment]
@jonTuck23031991 Sorry that you ran into trouble with this. The GitHub issues in this repo are for documentation feedback. For product issues, please file an issue here:

https://developercommunity.visualstudio.com/spaces/21/index.html

If it turns out that we have missed a step in our documentation, we'll get it fixed.

Thank you.
