### ISSUE TITLE
Cannot unlock files locked by other user using above documentation in Visual Studio Enterprise 2017 as well as through Command line

### ISSUE THREAD

**Issue by yashwanthmb** [MicrosoftDocs/vsts-docs#2988]
I am one of the Project Collection Administrators with all permissions to projects. I do have permission to Unlock Other Users Changes and Undo Other Users Changes. Yet I am unable to unlock files locked by others.

When using Visual Studio Enterprise 2017 client . Unlock option is disabled for files locked by others when I right click on the file and navigate to Advanced-&gt; unlock.

When I useCommand line to execute 
tf lock /lock:none "File location" it threw error TF14090: Cannot Unlock "File location". It is not currently locked in your work space

Please update the document with working instructions and commands.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd0761c2-64dd-3923-5533-9de10e956514
* Version Independent ID: 94173d96-5a14-98b2-45ce-2a66f70d9656
* Content: [Use the Lock Command to lock or unlock a TFVC file or folder - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/tfvc/lock-command?view=vsts)
* Content Source: [docs/repos/tfvc/lock-command.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/tfvc/lock-command.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by Nightwalker76** [comment]
Try something like this:
tf lock /lock:none /workspace:"joesmithsworkspace;Joe J. Smith" /login:mydomain\myusername $/Root/Dev/Dev/src/MyProject/somecode.cs

The /workspace:"joesmithsworkspace;Joe J. Smith" is the name of the workspace on the other person's machine where the file is currently locked.

You may get the message: The item xyz.exe must remain locked because its file type prevents multiple check-outs.  If so, just execute an undo:
tf undo /workspace:"joesmithsworkspace;Joe J. Smith" /login:mydomain\myusername $/Root/Dev/Dev/src/MyProject/xyz.exe

**Comment by WilliamAntonRohm** [comment]
@yashwanthmb -- you may find answers here:
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

@Nightwalker76 -- thank you for your answer.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

My apologies for the delay in responding.

**Comment by juangps96** [comment]
Is there any way to call the Lock Command from REST API?
