### ISSUE TITLE
How to attach and debug a custom task in build process?

### ISSUE THREAD

**Issue by ahmadyo** [MicrosoftDocs/vsts-docs#3005]
How to attach and debug a custom task in build process?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44581f4a-93df-7507-3844-eadedf9a6cc4
* Version Independent ID: 33c7bcf0-1512-975f-5ef8-9f2a192a84ad
* Content: [Add a Build or Release Task](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=vsts#optional-install-and-test-your-extension)
* Content Source: [docs/extend/develop/add-build-task.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/add-build-task.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Thank you for your feedback. Bugs, issues, suggestions, and feature requests related to the product rather than the documentation are best posted on the Developer Community website at https://developercommunity.visualstudio.com/spaces/21/index.html, where they are tracked by the product teams. Please post your feedback there. Thank you.
