### ISSUE TITLE
Responsible user workitems integratrion

### ISSUE THREAD

**Issue by AlexandreSanLim** [MicrosoftDocs/vsts-docs#3007]
It would be nice to give a trigger option when setting a user responsible for the workitem

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 7fd5671b-b7b8-9acb-c195-7897fec3538b
* Version Independent ID: ff894c1b-f2f7-581d-94b4-dbc77d80ad6d
* Content: [Slack with Azure DevOps Services](https://docs.microsoft.com/pt-br/azure/devops/service-hooks/services/slack?view=vsts)
* Content Source: [docs/service-hooks/services/slack.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/service-hooks/services/slack.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hello! Thank you for your feedback. Bugs, issues, suggestions, and feature requests related to the product rather than the documentation are best posted on the Developer Community website at https://developercommunity.visualstudio.com/spaces/21/index.html, where they are tracked by the product teams. Please post your feedback there. Thank you.
