### ISSUE TITLE
2 suggestions

### ISSUE THREAD

**Issue by revolunet** [MicrosoftDocs/vsts-docs#3009]
Hi, i'm not sure but : 

 - looks like you use the name `pswd` in the docker login code samples while the variable to create is named `dockerPassword` in the introduction 
 - i had to manually define the `imageName` in the build variables too

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e825c07d-2168-c0aa-782a-ef6f9c7ba95e
* Version Independent ID: 5cb6926b-215a-bf89-8e63-b2e1129e41df
* Content: [Build, test, and push Docker container apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/docker?view=vsts&tabs=yaml#use-docker-compose)
* Content Source: [docs/pipelines/languages/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/docker.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by PilotBob** [comment]
You would create dockerPassword as a variable in the build pipeline. It will be provided to the agent as an ENV variable and then set pswd with that value for use in the pipeline.

I know they aren't very explicit about needing to do that here.

**Comment by shashankbarsin** [comment]
The entire set of docs associated with the container ecosystem has been updated. This issue is addressed as the doc on [pushing images to container registries](https://docs.microsoft.com/azure/devops/pipelines/ecosystems/containers/push-image?view=azure-devops) uses samples based on Docker@2 task and Docker registry service connection instead.
