### ISSUE TITLE
Unclear if this applies to TFS (Azure DevOps Server). If not, where can we find the documentation for TFS?

### ISSUE THREAD

**Issue by PerthCharern** [MicrosoftDocs/vsts-docs#3031]
We need our extension to be able to authenticate to a backend service, while being run in TFS. We followed this documentation but it looks like this might not be working as expected. Is it expected to work, or are there different steps to follow for TFS?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: add23736-f0a9-2cc7-8bd2-4b8720898552
* Version Independent ID: 3f763c47-317d-a32a-37dd-6507d3f630b5
* Content: [Auth and Security](https://docs.microsoft.com/en-us/azure/devops/extend/develop/auth?view=vsts)
* Content Source: [docs/extend/develop/auth.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/auth.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @PerthCharern , I believe this is the correct doc to follow. If you're having trouble with authenticating/the product, bugs, issues, suggestions, and feature requests related to the product rather than the documentation are best posted on the Developer Community website at https://developercommunity.visualstudio.com/spaces/21/index.html, where they are tracked by the product teams. Please post your feedback there for a better response. Thank you.
