### ISSUE TITLE
Clarify Use of variable groups from YAML

### ISSUE THREAD

**Issue by cdeil** [MicrosoftDocs/vsts-docs#3048]
I find the current description of using variable groups from YAML unclear.

At https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=vsts&tabs=yaml#use-a-variable-group it says:

> To use a variable group, open your build or release pipeline, select the Variables tab ...

When using YAML and I go e.g. to https://dev.azure.com/cdeil/azure-pipelines-test/_build?definitionId=1 there is no Variables tab, so I was stuck.

I found a workaround: click "Edit", then on the edit page click "Edit in the visual designer" and then finally one can reach the "Variables" tab.

Suggest to improve the UI for projects using YAML, or to improve the docs page.

---

There is also the note in that section:

> Note: You must link your variable groups in the UI before they'll be available to your pipeline. This is a security feature: if you only had to name the variable group in YAML, then anyone who can push code to your repository could extract the contents of secrets in the variable group.

This doesn't seem to be accurate. I created a variable group and then put this in my YAML:
```
variables:
- group: pipeline-variables
```
and was able to access a variable (see https://dev.azure.com/cdeil/azure-pipelines-test/_build/results?buildId=5), even though I didn't create a link in the UI as mentioned in that note.

Maybe this note only applies to secret variable?

---

What I'm trying to achieve really is to store some secret that allows me to push to Github to have an automated github pages build. I asked about that here:
https://developercommunity.visualstudio.com/content/idea/427830/document-how-to-push-github-pages-from-azure-pipel.html
So really what I'm looking for is a description like https://github.com/Syntaf/travis-sphinx, but for Azure pipelines. Presumably the way to do it is to generate a Github PAT in a variable group? I'll try that now ...

**Comment by vijayma** [comment]
Thanks for the feedback. We will improve the doc for variables to explain this better. While we do that, here is how the security of variable groups works. Yes, you are right that one can include a reference to a variable group in the YAML file and push that change to the repo. However, that build fails since we do not know whether that user has permission to use that variable group. You will notice a resource authorization error in the build. A user with permission to use the resource (variable group in this case) would have to do one of the following to authorize the use of that variable group in the pipeline:

a. Go the Pipelines hub -> Variable groups -> Select the variable group in question. Then, switch on the toggle that says "Authorize all pipelines to use this resource". This will allow all pipelines to use the resource, which makes sense if you do not have secrets in that variable group.
b. Open the pipeline by selecting "Edit". Then, queue a build manually. You will see the same resource authorization error. But, you will also see a "Fix it" action on the error. Clicking on this will explicitly add the pipeline as an authorized user of the variable group.

If your pipeline just worked without any of these failures (after you added the variable group), you might have to turn off the toggle described in (a) above.

Thanks
Vijay
