### ISSUE TITLE
Modify the workflow states and transition reason (inherited process)

### ISSUE THREAD

**Issue by tumm0283** [MicrosoftDocs/vsts-docs#3067]
Hi Team,

is it possible to edit/modify the workflow states and reasons for inherited process template?

Thanks

**Comment by steved0x** [comment]
@tumm0283 Thank you for the feedback. Can you let me know which article this feedback is for, so I can assign it to the author? You can reply here with the URL of the topic, or you can create a new issue by browsing to the topic on docs.microsoft.com and choosing **Content feedback** at the bottom. 

![image](https://user-images.githubusercontent.com/1580889/42953695-fd174150-8b48-11e8-94de-26924ca79c71.png)

**Comment by steved0x** [comment]
I'm closing this issue since it is not associated with a topic. To continue the discussion, please open a new issue that is associated with a topic by browsing to the topic on docs.microsoft.com and choosing **Content feedback** at the bottom. Thank you for your feedback.

![image](https://user-images.githubusercontent.com/1580889/51848491-af95cd80-22eb-11e9-81a2-1680fc40caf9.png)
