### ISSUE TITLE
nuspec properties not updated by values in build properties for pack

### ISSUE THREAD

**Issue by giwleb** [MicrosoftDocs/vsts-docs#3109]
nuspec properties appear to be ignored when using property="value" in "Additional build properties" as described in the "Pack" section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fa37a3f-6551-16ad-e164-a4ac522cdaab
* Version Independent ID: a3fd6935-2b99-92ef-4eb3-3249fca01f8a
* Content: [NuGet restore, pack, and publish task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget?view=vsts)
* Content Source: [docs/pipelines/tasks/package/nuget.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/package/nuget.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hmm it may be a product issue. Tagging @alexmullans and @mitchdenny for awareness, but I suggest you also post to the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html). I'm going to close this as a docs issue because it sounds like you may just have a product issue. Please reach back out if the docs need updating!

**Comment by edgariscoding** [comment]
@giwleb Did you ever resolve this issue or create a post on the Azure DevOps Developer Community? I'm having the same issue.
