### ISSUE TITLE
Question: Is there a way to enable live update for sprint taskboard?

### ISSUE THREAD

**Issue by AlexandrPavlovski** [MicrosoftDocs/vsts-docs#3154]
It would be really nice to enable live update for sprint taskboard.

![image](https://user-images.githubusercontent.com/36845873/51839716-12528d80-231b-11e9-856f-ab81958be479.png)

As you can see there is no such setting there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d394881-c492-cd58-7fbf-1ee6a268af93
* Version Independent ID: e0b2e071-7bd8-04e5-c1e0-c1e499dc73f1
* Content: [Enable live updates for a Kanban board - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/boards/live-updates?view=azdevops&tabs=new-nav)
* Content Source: [docs/boards/boards/live-updates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/boards/live-updates.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by steved0x** [comment]
@AlexandrPavlovski Thank you for the feedback. I am assigning this to the author of this article, in case there are any changes we need to make to the documentation with regard to this feedback, but it looks like it might be a product feedback instead of a content feedback.

To submit product feedback, such as bug reports or feature requests, please choose **Product feedback** at the bottom of the article:

![image](https://user-images.githubusercontent.com/1580889/51848904-90e40680-22ec-11e9-893f-ded2716f3ea2.png)

or you can file an issue directly at https://developercommunity.visualstudio.com/spaces/21/index.html

Thank you for your feedback.

**Comment by KathrynEE** [comment]
@AlexandrPavlovski - No. The  Live Updates feature is only valid for Kanban boards.

**Comment by navneet-g** [comment]
@AlexandrPavlovski Live updates are now available for Taskboard, it should just work for you on Azure Devops Service, and will be available for Azure DevOps Sever 2020.

**Comment by dsiders-rs** [comment]
@navneet-g Can live updates be made optional on Taskboard, via a toggle like on Kanban?  Or make improvements to the live update so that it doesn't annoyingly scroll your view anytime someone else makes a change when you're looking at the board?

**Comment by navneet-g** [comment]
Thanks @dsiders-rs for the feedback, we will try to repro it at our end and see if this regressed recently. If you can share a video/gif of the experience it will be helpful to understand.
