### ISSUE TITLE
JMeter Versions

### ISSUE THREAD

**Issue by brownbl1** [MicrosoftDocs/vsts-docs#3177]
Is there a plan in place to support newer versions of JMeter? What are the constraints that are preventing this? We have built some JMeter 5.0 tests and would like to understand if it is worth the effort to downgrade them to 3.2.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52406841-b4d5-031b-dc90-ecc1ad70443f
* Version Independent ID: 90db9458-de65-e8f9-1644-9ef58e4de40a
* Content: [FAQs for load testing - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/load-test/reference-qa?view=azdevops#apache-jmeter-tests)
* Content Source: [docs/test/load-test/reference-qa.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/load-test/reference-qa.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. Issues, suggestions, and feature requests related to the product rather than the documentation are best posted on the Developer Community website at https://developercommunity.visualstudio.com/spaces/21/index.html, where they are tracked by the product teams. Please post your feedback there. Thank you.
