### ISSUE TITLE
Import standalone report to DevOps

### ISSUE THREAD

**Issue by rolfik** [MicrosoftDocs/vsts-docs#3179]
It would be nice to have the ability to import exported standalone session into DevOps to automatically fill in bugs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00155b3c-d5b2-0384-822d-bdba37609da5
* Version Independent ID: df1d0ac3-874a-0e6a-1e45-99a915f398b6
* Content: [Exploratory test in standalone mode - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/standalone-mode-exploratory-testing?view=azdevops)
* Content Source: [docs/test/standalone-mode-exploratory-testing.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/standalone-mode-exploratory-testing.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. Suggestions and feature requests related to the product rather than the documentation are best posted on the Developer Community website at https://developercommunity.visualstudio.com/spaces/21/index.html, where they are tracked by the product teams. Please post your feedback there. Thank you.
