### ISSUE TITLE
select the ASP.NET Core template ?

### ISSUE THREAD

**Issue by dazinator** [MicrosoftDocs/vsts-docs#3193]
Why does it say select the "ASP.NET Core" template when this is to build non asp.net core websites?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a494f5a-6143-e567-6c0f-e2c817b1f1a9
* Version Independent ID: 15819679-5914-25f6-34f8-91f1da16b0bf
* Content: [Build ASP.NET apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/aspnet/build-aspnet-4?view=azdevops)
* Content Source: [docs/pipelines/apps/aspnet/build-aspnet-4.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/apps/aspnet/build-aspnet-4.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by dankellett** [comment]
ASP.NET core projects can still use .NET Framework for now.

**Comment by joaopgrassi** [comment]
I think this shouldn't have been closed. The doc page links to a repo 
```
https://github.com/Microsoft/devops-project-samples/tree/master/dotnet/aspnet/webapp/Application
```
that's a **non core** MVC App. I think it is wrong to state: `Select the ASP.NET Core template`, since the whole page talks about non ASP.NET Core projects.

I got on this page specifically because I was looking at how to build "traditional" ASP.NET App on Azure DevOps.
