### ISSUE TITLE
Need other agent variables

### ISSUE THREAD

**Issue by heaths** [MicrosoftDocs/vsts-docs#3195]
What about other agent variables available to builds, like Agent.OS, Agent.OSVersion, etc.? These would be incredibly useful and I would think could be readily available as any other agent variables.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 611642f0-881f-10b9-ae94-3c562001d1f0
* Version Independent ID: 41efb94b-4c7a-64a3-b23b-70c8634ae727
* Content: [Release variables  and debugging - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=azdevops&tabs=batch#default-variables)
* Content Source: [docs/pipelines/release/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/variables.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. The list does not cover every variable because these depend on a range of factors such as the agent version and location. As the topic says: "Some of the most significant variables are described in the following tables. To view the full list, see View the current values of all variables". Using this approach, you can see there is an Agent.OS variable:
![image](https://user-images.githubusercontent.com/19287943/52271305-2ad62f80-293b-11e9-95a7-c7a6b2786b61.png)
For other variables that you would like to see added to the product, I suggest you file a request on the Developer Community website at https://developercommunity.visualstudio.com/spaces/21/index.html, where they can be upvoted and are tracked by the product teams.

**Comment by heaths** [comment]
https://developercommunity.visualstudio.com/content/problem/445506/need-exposed-variable-for-agent-osversion.html
