### ISSUE TITLE
URL pattern changed ?

### ISSUE THREAD

**Issue by vmaruhpe** [MicrosoftDocs/vsts-docs#3203]
Until very recently automation using the format https://dev.azure.com/{your organization}/{your project} to clone a repo from Azure DevOps worked well. This seems to be broken now as the format changed to  https://project@dev.azure.com/_git/organization essentially breaking the pattern of using https://username:password@dev.azure.com/{your organization}/{your project} . While using this pattern is not ideal, the change is braking existing automation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b8a5b68-909f-126d-5f83-4659e0f55b85
* Version Independent ID: f71ca2b9-c00d-0b2b-34bc-63d11b3576db
* Content: [Clone an existing Git repo - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/clone?view=azure-devops&tabs=visual-studio)
* Content Source: [docs/repos/git/clone.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/clone.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by mehmetilker** [comment]
Same problem here. I am getting authantication error:
fatal: Authentication failed for '...

**Comment by WilAtMSFT** [comment]
To my knowledge the clone format https://username:password@dev.azure.com/{your organization}/{your project} still works. What error are you seeing?

We introduced the https://{org}@dev.azure.com/{org}/AzureDevOps/_git/{project} a good while a go to help Git Credential Manager authenticate. So if you are passing your auth directly via username:password@ then the {org}@ should not be needed.

I will caution you from using the username:password@ for cloning since it get stored in the .git/config file.

**Comment by mijacobs** [comment]
It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. If you're still encountering this issue, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
