### ISSUE TITLE
Build Triggers fail with path filters if no changes are detected

### ISSUE THREAD

**Issue by StephenHodgson** [MicrosoftDocs/vsts-docs#3210]
When integrating pull request triggers in GitHub with path filters, the build is never started, which prevents the required status check from passing.

If the branch policy includes a required pipeline status check, then it'll be impossible for the pull request to be completed because the build is never triggered and status is never updated.

![image](https://user-images.githubusercontent.com/13334553/52145087-f69a0080-2614-11e9-9b12-5d78b891e0c0.png)

![image](https://user-images.githubusercontent.com/13334553/52145130-103b4800-2615-11e9-9a2d-df3bd64806d7.png)

![image](https://user-images.githubusercontent.com/13334553/52145169-26e19f00-2615-11e9-9be8-be4e3581d1f2.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfba9a21-e0f9-4fc6-43fc-bfdc51af31d3
* Version Independent ID: d93c7852-ce63-a6d0-417a-45f8cf2fc522
* Content: [Build GitHub repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops)
* Content Source: [docs/pipelines/repos/github.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/repos/github.md)
* Product: **devops**
* GitHub Login: @DavidStaheli
* Microsoft Alias: **dastahel**

**Comment by DavidStaheli** [comment]
Hi @StephenHodgson.  Thank you for reporting this and apologies for the trouble of it.  We just began a new sprint in which we plan to address this by reporting a status of `Neutral` when the pipeline is skipped because of branch/path filters.  However, GitHub [only supports](https://developer.github.com/v3/checks/runs/) the `Neutral` status when your pipeline uses the [Azure Pipelines GitHub App](https://github.com/apps/azure-pipelines/).  If your pipeline is based on your identity's OAuth or a personal access token, the `Neutral` status isn't supported.  Please let me know if we can help ensure you're set up to use the GitHub App.  This improvement should be available once it reaches all rings of production in mid-March.

**Comment by StephenHodgson** [comment]
@DavidStaheli any update on this?

**Comment by davidstaheli** [comment]
This work has been completed.  Please reopen if there are any additional concerns.

**Comment by ardianfrance** [comment]
How can you make an Azure DevOps pipeline publish a neutral status when it's not triggered because of path filter ?

**Comment by Koshak118** [comment]
Hi @davidstaheli 

I am having the same issue, even worse - the builds configured as "Required" are not started at all and remain with "Expected — Waiting for status to be reported" status if there a PR path filter in the build YAML file.

Can you please advise?

**Comment by EvanMulawski** [comment]
@davidstaheli 

The `Neutral` status does not appear to be working for me. The project has a service connection using the Pipelines app. I have the following path filters on a PR validation trigger:

- exclude `.github/`
- exclude `README.md`

The pipeline is correctly not triggered, but the status remains `Expected — Waiting for status to be reported` in GitHub, blocking the merge.

**Comment by rynop** [comment]
@davidstaheli I have a bunch of existing "classic" pipelines. I have just installed the DevOps app for GitHub.  How do I hook up my existing pipelines to use the app so I can get the `neutral` status integration?  Thanks in advance

**Comment by pjivers-bom** [comment]
This still doesn't work. Status remains as `Expected — Waiting for status to be reported` when PR pipeline is configured not to run on specified paths.

**Comment by bodnarkevin** [comment]
Same problem here, using Azure Pipelines App and yml pipeline files. Whould be a useful feature though.

**Comment by jorupp** [comment]
@davidstaheli can you clarify what how I should need to configure things to make it send "neutral"?  I'm using the app, but my PRs are showing "Expected - waiting for status to be reported" for the builds that don't run due to the PR not containing any changes to the paths the build is triggered on.

**Comment by aramase** [comment]
@davidstaheli We're facing similar issues with our repos hosted in Azure. Are there docs on how to enable this?

**Comment by amar-aslam** [comment]
Issue still exists as status remains Expected — Waiting for status to be reported

**Comment by michaelstaszewski** [comment]
For what it's worth I opened a support ticket with Microsoft for this and they enabled a feature flag in my Azure DevOps org or project reserved for the "Product Group." I re-tested and it does work with that flag enabled, only. The Github display could be cleaner because pipelines that do not trigger still say "Expected --- Waiting..." but it does enable the Merge button when the pipelines that do trigger complete. PRs are no longer blocked.

Open a case with Microsoft if you need this and request that the feature flag be enabled. I opened a support case through Azure Portal because that gets you to actual support vs. using the Azure DevOps Help menu which routes you to the developer community. Feel free to include my ticket tracking ID, 2105070040005533, and maybe you can save a week or more of slow communication with the first level (contractor) support staff. ;-)
