### ISSUE TITLE
Instructions in document are so out of date they don't work any more

### ISSUE THREAD

**Issue by lewcianci** [MicrosoftDocs/vsts-docs#3217]
This document doesn't show how to use Service Hooks in the new Azure DevOps UI.  There's no obvious way to configure the service hook.

**Comment by steved0x** [comment]
Thank you for the feedback. Can you let me know which article this feedback is for, so I can assign it to the author? You can reply here with the URL of the topic, or you can create a new issue by browsing to the topic on docs.microsoft.com and choosing **Content feedback** at the bottom. 

![image](https://user-images.githubusercontent.com/1580889/51848491-af95cd80-22eb-11e9-81a2-1680fc40caf9.png)

**Comment by steved0x** [comment]
I'm closing this issue since it is not associated with a topic. To continue the discussion, please open a new issue that is associated with a topic by browsing to the topic on docs.microsoft.com and choosing **Content feedback** at the bottom. Thank you for your feedback.

![image](https://user-images.githubusercontent.com/1580889/51848491-af95cd80-22eb-11e9-81a2-1680fc40caf9.png)
