### ISSUE TITLE
Unable to deploy to the target 'TargetMachineName' as the Deployment Group deployment configuration settings are not met.

### ISSUE THREAD

**Issue by naveenkumargc** [MicrosoftDocs/vsts-docs#322]
Created a release definition, defined all the parameters to it. Also joined the TagetMachine to the deployment group and the page shows that the machine is online & healthy. But when triggered the deployment, it will show the following error :

Unable to deploy to the target '<TargetMachineName>' as the Deployment Group deployment configuration settings are not met.

**Comment by naveenkumargc** [comment]
Did some rnd, came to know that the all machines in the deployment group should be online in order to release. Please close this issue.

**Comment by RyanThomas73** [comment]
Encountered this error message in an on-prem instance of ADO Server 2020.

Sharing resolution in case anyone comes across this issue while doing a general search for the above error message:

If there is only a single target in the deployment group and the deployment group job is set to the default for the 'Targets to deploy in parallel' you will receive the described error message. Explicitly changing it to 'One target at a time' for a deployment group with a single target was necessary to resolve.

![image](https://user-images.githubusercontent.com/9260799/166519706-12a3365e-bce4-4f1f-887f-43e964b0ed03.png)

**Comment by itsme112358** [comment]
Hi!
Sorry to dig this up, I'm unsure if I'm in the right place.
I'm getting the same message on a deployment group. One agent was down due to a hardware issue.
We have more than 20 servers in this group and there are multiple releases daily, so it's not rare that one machine might be unavailable at release time. That's not really an issue for us, all changes would be rolled up with one of the following releases.
Since the machines use a shared resource which would bottleneck or in worst case even lead to a blocking issue, I've set it up as follows:
**Deployment queue settings** (in Pre-deployment conditions)
![image](https://user-images.githubusercontent.com/16080908/181633573-afcaf2f8-c964-4c29-895e-2298e9788909.png)
**Stage setting**
![image](https://user-images.githubusercontent.com/16080908/181634852-e46f9d22-e78a-43ec-a832-3ed22a50608f.png)

Now I basically have to issues:
1. As soon as one agent is down, all subsequent releases fail/go to state `Not deployed` and the stage logs show failed for all agents: ![image](https://user-images.githubusercontent.com/16080908/181634583-3575ea4a-cb15-4a26-a324-164ff068b840.png)
2. Even when the agent came back online nothing happened.
My expectation was that the latest release would get deployed.

Essentially: We need most servers to receive releases. If one or two fail it's not an issue, as they will cach back up once they get the latest release. How do I need to configure the stage to achieve this?

**Comment by WilliamAntonRohm** [comment]
@itsme112358 -- thank you for your follow-up and questions.  Are you following a particular docs.microsoft.com article?  Meanwhile, please consider these resources:
- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
