### ISSUE TITLE
JSON substitution doesn't replace variables starting with the word 'system'

### ISSUE THREAD

**Issue by osilvaa** [MicrosoftDocs/vsts-docs#3223]
We've decided to add some configuration settings as part of the appsettings.json file and replace them as part of our release pipeline.

I noticed that whenever the word 'system' is at the beginning of any variable (object or not), the substitution does not happen. None of our variables were using only the word 'system', like the system.debug variable, to access nested values. They were something like 'SystemUsersApiUri' or some variation of that. 

If this is not classified as a bug, could you please add the JSON substitutions' restrictions to the docs? I have collected logs and I'm happy to share them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 315ff823-9992-9f9b-62a1-42ce622ed41c
* Version Independent ID: 72ec3ffc-1dc9-b2dc-e3d4-4f14deae3720
* Content: [File transforms and variable substitution - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/transforms-variable-substitution?view=azure-devops)
* Content Source: [docs/pipelines/tasks/transforms-variable-substitution.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/transforms-variable-substitution.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. There is no published limitation as you describe, and so this issue should be filed as a product bug. Bugs, issues, suggestions, and feature requests related to the product rather than the documentation are best posted on the Developer Community website at https://developercommunity.visualstudio.com/spaces/21/index.html, where they are tracked by the product teams. Please post your feedback there. Thank you.
