### ISSUE TITLE
Is release pipeline appropiate for you

### ISSUE THREAD

**Issue by stofte** [MicrosoftDocs/vsts-docs#3232]
As opposed to what alternatives? I'm assuming that even if I just make a "manual" deployment using batch/ps1, it's going to be a pipeline? Or what?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63234ade-28cc-02fc-a319-42e3491da601
* Version Independent ID: 7ccbfe96-d61e-8bf2-de22-61150d648abd
* Content: [Understand release pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/what-is-release-management?view=azure-devops#isitforyou)
* Content Source: [docs/pipelines/release/what-is-release-management.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/what-is-release-management.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. If you wish to use the automation tasks (https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/?view=azure-devops#deploy) and jobs (https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=designer) in Azure DevOps or TFS to deploy artifacts, you will need to use a pipeline. Currently, there are different pipelines for build and release processes, though you can use release/deployment automation tasks in a build pipeline to deploy if you don't need the additional features of a release pipeline such as rich support for triggers, redeploying a release, and controlling deployment with approvals and gates (all of these features are linked in the table of contents from this topic). You can create a release pipeline using YAML instead of using the designer UI in Azure DevOps.
