### ISSUE TITLE
VS Tests Deprecated

### ISSUE THREAD

**Issue by ashishmundrajll** [MicrosoftDocs/vsts-docs#3267]
Hi All, 

This article (https://docs.microsoft.com/en-us/visualstudio/test/quickstart-create-a-load-test-project?view=vs-2017) from Microsoft mentions that Load Test with Visual Studio will be deprecated (also Coded UI test will be deprecated). 

Will Azure DevOps continue to support creating Load Tests or is it also following the same path?

We see that screenshot shows importing JMeter tests, so should that be the preferred way of writing Performance Tests going forward?

Thanks,
Ashish

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74322585-effa-ba29-a9f3-982843169913
* Version Independent ID: 15e8e929-eda0-88af-b173-4773407e95f2
* Content: [Run URL-based cloud load tests - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/load-test/get-started-simple-cloud-load-test?view=azure-devops)
* Content Source: [docs/test/load-test/get-started-simple-cloud-load-test.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/load-test/get-started-simple-cloud-load-test.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by sasivimala** [comment]
After reading this web site I am very satisfied simply because this site is providing comprehensive knowledge for you to audience. 
Thank you to the perform as well as discuss anything incredibly important in my opinion. We loose time waiting for your next article writing in addition to I beg one to get back to pay a visit to our website in


<a href="https://www.besanttechnologies.com/training-courses/software-testing-training/selenium-training-institute-in-chennai">Selenium training in Chennai </a>  
<a href="https://www.besanttechnologies.com/training-courses/software-testing-training/selenium-training-institute-in-bangalore">Selenium training in Bangalore</a>

**Comment by nschonni** [comment]
https://devblogs.microsoft.com/devops/cloud-based-load-testing-service-eol/

**Comment by sebainones** [comment]
After reading the last comment from @nschonni I don't if this is still the right place or time to ask this question :(
Anyway, I'm trying to do some load testing to a back-end service I'm currently developing.

So, the same GET request that successfully runs in Postman if I do it with URL-based load test on Azure Dev Ops  gives 100% of Failed Requests.
In some post someone suggested that instead of using https I could try with just http. Now, I get 50% of Failed Requests when using http.
So, I believe I'm missing something as I know that the service works.
Any help will be appreciated.

**Comment by thomps23** [comment]
@sebainones Please accept our apologies for the delay in getting to this issue. It looks like you were working through an issue with your scenario or implementation, rather than a specific issue with the documentation. Here are a few options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
