### ISSUE TITLE
Add precision on status policy name

### ISSUE THREAD

**Issue by olileger** [MicrosoftDocs/vsts-docs#3288]
I think you could add the status policy name pattern when you create a release pipeline with PR within that documentation.
Because it's very strange the need to run at least one PR release without status policy to get the name of the release status policy, no?
So the pattern name is : VSTS-RM/&lt;release definition name&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cbb2877-5e10-4065-e3c6-7883e9df4b3c
* Version Independent ID: 58122a19-2258-3cf3-8335-74bb0dad892f
* Content: [Deploy pull request builds - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/deploy-pull-request-builds?view=azure-devops)
* Content Source: [docs/pipelines/release/deploy-pull-request-builds.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/deploy-pull-request-builds.md)
* Product: **devops**
* GitHub Login: @raiyanalam
* Microsoft Alias: **moala**

**Comment by raiyanalam** [comment]
Hi Olileger,
    Apologies for the delay and thanks for raising this.
 The need to run at least one PR release for status policy is a standard practice also followed by other repositories like GitHub. Since this looks a bit off, we have explicitly mentioned this requirement in the documentation. As for the pattern, we didn't find the need to write the pattern in words as it is highlighted in the images. 
Closing this issue.

**Comment by raiyanalam** [comment]
#please-close
