### ISSUE TITLE
New question about Project and Azure Boards

### ISSUE THREAD

**Issue by TonieStark** [MicrosoftDocs/vsts-docs#3300]
Hi,

I and others have asked about the integration of Project and Azure Boards, and from what I understand you will be able to use the current version of the TFS Office add-on (2017 version) until you say that it is no longer supported, but no plans to deprecate it now at least.

Well, what about the "TFSFieldMapping" command? You say here at the top that it is no longer supported with Azure Devops Services (I don't care about onprem). I have been using the command the last few weeks and also I tried today and it still works. (with the 2017 version of TFS Office add-on) Or you perhaps mean that the command won't work with the new version (TFS Office add-on 2019)?

Also, you still have this text towards the end of this page:
"To add more work tracking fields or change the way fields are mapped, see Customize the Microsoft Project field mapping file. This feature is available for both Azure Boards and TFS. "

Will I be able to use the "TFSFieldMapping" command with TFS Office 2017 add-on with Azure Devops Services (Boards) or not, it certainly works right now?!

/Concerned user

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f6edd47-46d7-ab0d-db47-d73bc45d6b43
* Version Independent ID: 6ac2ae49-0bd0-2c28-fc87-7f034dd96443
* Content: [Create your backlog and tasks using Project - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/office/create-your-backlog-tasks-using-project?toc=%2Fazure%2Fdevops%2Fboards%2Fbacklogs%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fboards%2Fbacklogs%2Fbreadcrumb%2Ftoc.json&view=tfs-2018&viewFallbackFrom=azure-devops&tabs=office-365)
* Content Source: [docs/boards/backlogs/office/create-your-backlog-tasks-using-project.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/office/create-your-backlog-tasks-using-project.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by danhellem** [comment]
We removed the Project integration in VS 2019. However, the TFSFieldMapping command will currently still work for Azure DevOps Service. It is on a path to deprecation. But we have not announced anything or have solid plans in place yet on when that will be. That is a long way of saying, you should be able to use it for now.

**Comment by abhall724** [comment]
It is unfortunate that this didn't work properly from the start and is now being killed off due to limited use. If it didn't work correctly how are we suppose to use this. The big problem is Microsoft doesn't have a good solution for project management that is integrated with it's other products. There is not a way to track properly effort and estimates in Azure DevOps, the reports are STILL missing in Azure DevOps, Project no longer integrates with Sharepoint seamlessly. Now with this feature being deprecated we (Project Managers) have to basically track in both Project for traditional reports for our Managers and Azure DevOps for our Dev teams.
