### ISSUE TITLE
Explain why copy is recommended in Build artifacts

### ISSUE THREAD

**Issue by letmaik** [MicrosoftDocs/vsts-docs#3317]
You say:
&gt; In build artifacts, it's common to first copy files to $(Build.ArtifactStagingDirectory) and then use the Publish Build Artifacts task to publish that directory. With pipeline artifacts, we recommend pointing the Publish Pipeline Artifacts tasks directly to the paths to be published. This saves your build the time of creating a copy of the files that you want to publish.

It doesn't seem to be required though and works just fine without copying. Why is this mentioned as an advantage of Pipeline artifacts if Build artifacts can do the same?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 861ce7a5-4fa4-55f1-2c97-46a9cc6a2f66
* Version Independent ID: bdf954b9-9bbe-8b34-b674-71ad8153519d
* Content: [Publish and consume Pipeline artifacts in builds - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/artifacts/pipeline-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/pipeline-artifacts.md)
* Product: **devops**
* GitHub Login: @alexmullans
* Microsoft Alias: **amullans**

**Comment by elbatk** [comment]
Hi @letmaik , essentially we recommend that because it ensures all of your artifacts are in one place, and it's a directory that gets cleaned with every build, but yes, you can publish build artifacts from any directory. I'm adding @mitchdenny to comment on your last bit about why pipeline artifacts are advantageous since technically you could publish build artifacts from any directory as well. I'm not sure about the overhead of the "copy files" task and how it compares to the implicit "copy files" that the "publish pipeline artifacts" task does.

**Comment by letmaik** [comment]
Cleaning is only important for self-hosted agents. In Microsoft hosted agents, everything is cleaned anyway after a build (the VM gets removed I assume). That's probably useful to consider as well when thinking about the distinction between both task types.

**Comment by Jaykul** [comment]
Isn't the problem just that Build artifacts must publish a _folder_, rather than a file?

They include the directory structure -- *that* is why it's common to copy the files first: to avoid having your artifact be named "Product" but produce a zip with \Product\bin\*.exe instead of just \Product\*.exe ...

With pipeline artifacts you can point at a file, and not include any folder structure.

**Comment by chasewilson** [comment]
Hi all, @Jaykul is correct. I'll be closing this issue. Feel free to reach out or open a new issue!
