### ISSUE TITLE
Removing an Artifact from a View

### ISSUE THREAD

**Issue by JamesMBristow2** [MicrosoftDocs/vsts-docs#3335]
Is it possible to remove an artifact from a release view once it has been promoted? If this is conceptually not desirable, please explain.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b254809-bcfe-5859-42e1-05df82aa730b
* Version Independent ID: cd8e1d01-c11b-4173-8f36-95d4237bc6a5
* Content: [Communicate package quality with release views](https://docs.microsoft.com/en-us/azure/devops/artifacts/feeds/views?view=azure-devops&tabs=new-nav)
* Content Source: [docs/artifacts/feeds/views.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/feeds/views.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by stoopered** [comment]
I think this would be bad. For example, if you have a @Prerelease view, and you have a project referencing 1.0.4 (@Prerelease) and remove that for some reason (like it gets promoted to @Release), then the package would then reference the older package in the view i.e 1.0.3 (@Prerelease)

**Comment by thomps23** [comment]
Please accept our apology for the significant delay in addressing this issue.

It looks like you're working through an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
