### ISSUE TITLE
I cannot add a team to the build or release permissions

### ISSUE THREAD

**Issue by eal61** [MicrosoftDocs/vsts-docs#3344]
I would like to be able to add a specific team to the build and release permissions list on an object instead of an entire project level group. The use case for this is that different teams own different build/release pipelines and should not or do not need to have access to certain pipelines. 

Currently it seems I can add a team to the permissions list and save it, but if I leave and return the team is gone. This makes me think I should be able to do what I described above, but there is defect preventing me from doing so. Can you take a look into this?

relevant info:
I am in the role of Project Administrator and Project Collection Administrator 

relevant documentation page:
https://docs.microsoft.com/en-us/azure/devops/pipelines/policies/set-permissions?view=azure-devops#feedback

**Comment by steved0x** [comment]
@eal61 That's good feedback, thanks for letting us know. I am forwarding this to the product team and closing this issue, since the issues in this repo are for content feedback. Although I am forwarding this to the product team, it will carry more weight if you also file a feature request here:

https://developercommunity.visualstudio.com/spaces/21/index.html

You cn also submit product feedback, such as bug reports or feature requests, by choosing **Product feedback** at the bottom of any article:

![image](https://user-images.githubusercontent.com/1580889/51848904-90e40680-22ec-11e9-893f-ded2716f3ea2.png)

Thank you.

**Comment by eal61** [comment]
@steved0x Thank you! I will follow up with a feature request
