### ISSUE TITLE
Full commit message not included in slack web hooks

### ISSUE THREAD

**Issue by chrisjpatty** [MicrosoftDocs/vsts-docs#3353]
Hi, would it be possible to have the option to include the full commit message in messages posted to Slack? Right now it doesn't include the full message, just the title of the commit.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fd5671b-b7b8-9acb-c195-7897fec3538b
* Version Independent ID: ff894c1b-f2f7-581d-94b4-dbc77d80ad6d
* Content: [Create a service hook for Azure DevOps Services and TFS with Slack](https://docs.microsoft.com/en-us/azure/devops/service-hooks/services/slack?view=azure-devops)
* Content Source: [docs/service-hooks/services/slack.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/service-hooks/services/slack.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by steved0x** [comment]
@chrisjpatty That's good feedback, thanks for letting us know. I am forwarding this to the product team and closing this issue, since the issues in this repo are for content feedback. Although I am forwarding this to the product team, it will carry more weight if you also file a feature request here:

https://developercommunity.visualstudio.com/spaces/21/index.html

You can also submit product feedback, such as bug reports or feature requests, by choosing **Product feedback** at the bottom of any article:

![image](https://user-images.githubusercontent.com/1580889/51848904-90e40680-22ec-11e9-893f-ded2716f3ea2.png)

Thank you.

PS If I have mischaracterized this issue and it should remain as a doc feedback item, please reactivate the issue and we'll take another look. Thank you for your feedback.
