### ISSUE TITLE
Git failed with a fatal error. Authentication failed for 'https://xxxxx.git/'

### ISSUE THREAD

**Issue by IOL0ol1** [MicrosoftDocs/vsts-docs#3369]
When I first pushed, the verification window popped up, I lost the wrong password, and then the title appeared.
So I now have an external git installed, but git inside the VS is no longer able to push.
What do I do to pop up the verification box?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 6d5ca6b5-523a-21d0-26f3-567846f7c298
* Version Independent ID: c712c338-46d6-a70a-0ba1-0d1ec3cd6ac7
* Content: [Sync your changes to a remote Git repo - Azure Repos](https://docs.microsoft.com/zh-cn/azure/devops/repos/git/pushing?view=azure-devops&tabs=visual-studio)
* Content Source: [docs/repos/git/pushing.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/pushing.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by thomps23** [comment]
@IOL0ol1 Please accept our apologies for the delay in getting to your issue. It looks like you were working through an issue with your scenario or implementation, rather than an issue with the documentation. In the future, here are a few options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
