### ISSUE TITLE
SSH service connection private keys

### ISSUE THREAD

**Issue by jdkemme** [MicrosoftDocs/vsts-docs#3387]
SSH service connection section provides no guidance on what types of keys are supported: RSA, DSA, ECDSA, ED25519, PEM format, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72b90dd0-49f9-4ed4-3010-9a64dde6ae5a
* Version Independent ID: 6e679d50-4e94-eee3-8793-af884cc909ca
* Content: [Service connections in Azure Pipelines and Team Foundation Server - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops#sep-ssh)
* Content Source: [docs/pipelines/library/service-endpoints.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/service-endpoints.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
The task uses the SSH llibraries, and so supports the key types it uses. The SSH docs at https://www.ssh.com/ssh/public-key-authentication discuss key types. See also the library at https://github.com/mscdex/ssh2.
This information was taken from a similar question at the end of the topic at https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/copy-files-over-ssh: It did not add support for the newer OpenSSH key format until version v0.7.0. (See this issue for more info: mscdex/ssh2#746). The task version 0.148 update will have v0.8 of the ssh2 library and support for the new OpenSSH key format. Prior to that task version, the -m PEM flag must be passed to ssh-keygen so that the key works with the task. The newer version of the task should be rolling out in the next few weeks.
