### ISSUE TITLE
angular library

### ISSUE THREAD

**Issue by hoksource** [MicrosoftDocs/vsts-docs#3395]
I created an angular library in projects/my-lib then build the project with "ng build" the output is on "dist/my-lib".

1. for the first .npmrc, when publishing the dist/my-lib, I think it should be located at "dist/my-lib/.npmrc", am I right?
2. for the 2nd .npmrc, I am not sure where is this $env.HOME located my understanding with npm or node is not comprehensive.
3. when installing the package on another project. should I be adding the .npmrc on the root of the angular project ClientApp/.npmrc?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb7c2ab6-4ba1-51d5-96bb-38a9ab6b50c3
* Version Independent ID: 415de875-ba1b-476b-f08b-1a61dc7a2747
* Content: [Set up your client's npmrc](https://docs.microsoft.com/en-us/azure/devops/artifacts/npm/npmrc?view=azure-devops&tabs=new-nav%2Cwindows)
* Content Source: [docs/artifacts/npm/npmrc.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/npm/npmrc.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by thomps23** [comment]
@hoksource Please accept our apologies for the delay in getting to this issue. It looks like you were working through your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking your question going forward:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
