### ISSUE TITLE
Convert Visual pipeline to YAML ?

### ISSUE THREAD

**Issue by iAmoric** [MicrosoftDocs/vsts-docs#3400]
Is there a way to convert a visual build pipeline to yaml file ?  

The preview feature `New YAML pipeline creation experience` is enabled but the button `View YAML` is disabled for my project.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/fr-fr/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **macoope**

**Comment by thomps23** [comment]
@iAmoric Please accept our apologies for the delay in getting to this issue. 

It looks like you were working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking your question in the future:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
