### ISSUE TITLE
Visual Studio App Missing In Teams

### ISSUE THREAD

**Issue by ljr55555** [MicrosoftDocs/vsts-docs#3409]
Per the "Configuring Azure DevOps Services Tabs in Microsoft Teams" section: We do not have a "Visual Studio" or "VSTS" app in Teams. My Azure DevOps org uses the same tenant as my Teams account. There *is* an "Azure DevOps" app that seems to provide the same functionality -- I've added a Kanban board & dashboard tab using this app. Has the "Visual Studio" app been rebranded?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cddc0ae-93af-297c-2e71-334143ebee1e
* Version Independent ID: cb76e516-8471-c3e1-45f4-0a20a223f32a
* Content: [Create a service hook for Azure DevOps Services and TFS with Microsoft Teams](https://docs.microsoft.com/en-us/azure/devops/service-hooks/services/teams?view=azure-devops&viewFallbackFrom=vsts)
* Content Source: [docs/service-hooks/services/teams.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/service-hooks/services/teams.md)
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by ppilev** [comment]
same issue. any plans to get this fixed soon?

**Comment by csongs** [comment]
why remove "Visual Studio" or "VSTS" app  T.T

**Comment by misolutions9** [comment]
VSTS/DevOps is not available in Microsoft Team, I tried to add connect but it is not available

**Comment by soroshsabz** [comment]
Why this app does not available in Microsoft Team?

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
