### ISSUE TITLE
Multiple Steps in a Job?

### ISSUE THREAD

**Issue by Eldorian** [MicrosoftDocs/vsts-docs#3410]
Can I have multiple steps in a job? Anytime I try to do this it throws an error "While parsing a block mapping, did not find expected key." What is strange is I had these steps set up to begin with and they worked fine, then when I added jobs to the equation they started failing.

jobs:
- job: ui
  steps:
  - task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
      command: restore
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
  displayName: Build
  inputs:
      command: build
      projects: '**/*.csproj'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=example)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **macoope**

**Comment by thomps23** [comment]
@Eldorian Please accept our apologies for the delay in getting to this issue.

It looks like you were working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking your question in the future:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
