### ISSUE TITLE
Test Runner -- how to move this window or resize it

### ISSUE THREAD

**Issue by jun-mac** [MicrosoftDocs/vsts-docs#3425]
It seems to have locked itself to the leftmost part of my screen(s) and can't be moved.  Is there a way to move this around my desktop? Please advise.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 985ecee3-e347-43bb-5ed2-08ce3aee7621
* Version Independent ID: fdf465fc-a9e1-0198-2e8c-e859c74252b3
* Content: [FAQs and problem solutions - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/reference-qa?view=azure-devops)
* Content Source: [docs/test/reference-qa.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/reference-qa.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by klvnraju** [comment]
This is happening because of the docking experience we have built for the Test Runner. It takes 25% of screen width (max 400px) and currently not resizable/moveable.
It is designed to dock because we want to make sure the test runner always stays on screen taking 25% of space and the remaining 75% of space is available for application under test. (Similar to Manual Test Runner (MTM) that we used to ship)

I want to understand what you are trying to do, is the Test Runner taking additional screen size and hence want to reduce it?
Or is it taking less space and hence want to increase it?
Or do you want to move it? Say, to the right side? If so, would giving an option to dock to the right edge fix it?

The reason I am asking the above questions is because I want to understand what the pain point is to take the right approach for fixing it.

**Comment by jun-mac** [comment]
I think as in any windowed apps, giving an option to dock to the any and ability to re-size that window will be just the right fix for it.

also, the capture window doesn't give you the option to focus on a particular application running the test environment !   this makes it different from the previous Microsoft Test !  Can't we have that back please?

**Comment by jun-mac** [comment]
I work on a multi screen desktop (2 minimum) and the focus seems not correct when running a test scenario !

**Comment by jun-mac** [comment]
Can this be re-opened?

Jun Macalalad
Frisk-Search Pty Ltd

Scheduled leave: none

**Comment by klvnraju** [comment]
There are 3 issues discussed here:
- Capture screenshot for individual applications is a known issue we are tracking. And this is happening due to 3rd party dependency (Electron issue)
- We have put options to dock left/dock right/undock and resize as part of our backlog.
- Did not understand the 2 desktop and focus problem. Can you please give us more details regarding this?

**Comment by jun-mac** [comment]
My test environment runs off a laptop with multiple displays.  I would re-map one as the master in order for the test runner to run and be at that particular location of the screen -- more of a work preference.
Hope i make sense.  Thanks

**Comment by jun-mac** [comment]
Also, is there a way to make Test Runner remember the options you've selected (at least when running a test plan) -- like:
<ol>
<li> allowing the switch between "Microsoft Edge" to open "TestRunnder_AzureTestPlans"
<li> taking a snapshot (which screen to share), and 
<li>once selected to auto tick the checkbox?
</ol>

**Comment by mijacobs** [comment]
@jun-mac, we mostly use issues to track documentation issues. It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. Could you [submit a bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) instead so that it will be easier to track?

Regards,
Mike

**Comment by AJelarcic** [comment]
Why not add a zoom feature to the docked window? That would allow users the ability to shrink the screen so the text in each test case can be seen without having to scroll horizontally on each test step. This would be a huge time save for testers.

**Comment by AJelarcic** [comment]
> This is happening because of the docking experience we have built for the Test Runner. It takes 25% of screen width (max 400px) and currently not resizable/moveable.
> It is designed to dock because we want to make sure the test runner always stays on screen taking 25% of space and the remaining 75% of space is available for application under test. (Similar to Manual Test Runner (MTM) that we used to ship)
> 
> I want to understand what you are trying to do, is the Test Runner taking additional screen size and hence want to reduce it?
> Or is it taking less space and hence want to increase it?
> Or do you want to move it? Say, to the right side? If so, would giving an option to dock to the right edge fix it?
> 
> The reason I am asking the above questions is because I want to understand what the pain point is to take the right approach for fixing it.

----------------------------------------------------------

@klvnraju Why not add a zoom feature to the docked window? That would allow users the ability to shrink the screen so the text in each test case can be seen without having to scroll horizontally on each test step. This would be a huge time save for testers.
