### ISSUE TITLE
Unclear how to access JSON object with names containing dots

### ISSUE THREAD

**Issue by Fulgan** [MicrosoftDocs/vsts-docs#3438]
Assuming I have a JSON object that looks like this in a config file
{
  "HostNames":
    {"app.org.test":"SomeSetting"}
}

The documentation is unclear about how to set the value "SomeSetting" using JSON variable substitution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 315ff823-9992-9f9b-62a1-42ce622ed41c
* Version Independent ID: 72ec3ffc-1dc9-b2dc-e3d4-4f14deae3720
* Content: [File transforms and variable substitution - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/transforms-variable-substitution?view=azure-devops#jsonvarsubs)
* Content Source: [docs/pipelines/tasks/transforms-variable-substitution.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/transforms-variable-substitution.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by SumiranAgg** [comment]
@Fulgan To set the value "SomeThing" you need to add a variable to your release HostNames.app.org.test with required value.

**Comment by alexhomer1** [comment]
The product team response is:

We do support variable substitution with dots. 
If a variable is like “first.second.third” we try to find this hierarchy in json file i.e.
“first” : {
                “second”: {
                                “third” : “val”
                }
}
And an exact match like:
“first.second.third” : “val”

All such instances will be substituted with given value.

I will add this to the topic.

**Comment by SumiranAgg** [comment]
@Fulgan I misunderstood your question. You are correct we only do variable substitution not addition of a new value. We will add it to our documentation for clarity. @alexhomer1 Can you take care of this?

Thank you for reporting this. As for adding this support, we might not be able to take it up immediately due to other priority items in our queue. This will require more customer asks before we take it up. We will update the documentation once the support is added.

**Comment by SquallHalle** [comment]
Sorry to respons to an old ticket but i run in the same issue as @Fulgan 
For this appsettings.json

```
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Information",
      "Microsoft.Hosting.Lifetime": "Information",
      "Microsoft.EntityFrameworkCore": "Warning"
    }
}
```

i would need a variable with Logging.Microsoft.Hosting.Lifetime = Information
but the problem is that "Microsoft.Hosting.Lifetime" is containing "." in the NAME but the task will try to match is as a PATH and so it wont work. 

so how so set the variable Microsoft.Hosting.Lifetime inside Logging ?!
