### ISSUE TITLE
Apply Teams channel defaults to Azure DevOps

### ISSUE THREAD

**Issue by yoyomeng2** [MicrosoftDocs/vsts-docs#3440]
I'm setting up Kanban boards for multiple channels. Each channels represents a product in development. The product backlogs are all under the same large project under respective Epics and tagged by product name. Would like to apply a default filter per channel on the tag so that users don't have to all manually apply the filter themselves or perhaps not realize they should and get confused from seeing stories unrelated to the channel.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9dd1eb12-58c8-4128-d5de-bda134e9c5f6
* Version Independent ID: dac4ba9d-20ef-50e6-dacf-88db9c4f3d92
* Content: [Manage teams, configure team tools - Azure DevOps & TFS](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/manage-teams?view=azure-devops&tabs=new-nav)
* Content Source: [docs/organizations/settings/manage-teams.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/manage-teams.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by chcomley** [comment]
Hi @yoyomeng2, I've asked for some clarity from my PMs, so I'll be back in touch with you soon. Thanks for reaching out!

**Comment by yoyomeng2** [comment]
Also noticed the tag filter applies to all channels with an Azure Devops tab so it won't be possible to filter stories by tag per channel this way.

**Comment by chcomley** [comment]
Hi @yoyomeng2, thanks for your patience. Filters on Boards/Backlogs are sticky per user - it is not possible for someone else to pre-apply filters for others. However, once the user sets this filter, it will always be applied when they visit the page unless they remove it. We have received a feedback request asking that we apply filter parameters to the URLs so that users could bookmark a pre-applied filter. If you'd like, feel free to [upvote that request](https://developercommunity.visualstudio.com/spaces/21/visual-studio-team-services.html?type=idea). If you don't see it, I'd just create a new request.

Alternatively, you can create a team for each of the channels (which creates an area path for that channel on the work item). Then each team will have a separate backlog dedicated to their respective areas. This [doc page](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fdevops%2Forganizations%2Fsettings%2Fset-area-paths%3Fview%3Dazure-devops&data=02%7C01%7CChrystal.Comley%40microsoft.com%7Ca7383d3ded2f4e7fb5e708d698d9dcf8%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636864458812748721&sdata=dgoz5djb0VuLLjOqcJS1XnPJUOUQijjAyds6MAqdbCk%3D&reserved=0) goes into more detail about how to configure and achieve that.

I'll be closing this issue, however you can still comment on it if you do have any further questions please. Thanks for reaching out!
