### ISSUE TITLE
How do you version

### ISSUE THREAD

**Issue by stoopered** [MicrosoftDocs/vsts-docs#3445]
How do you automate versioning? I was trying to use GitVersion with this workflow, but unfortunately it does not seem to support it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1235ec4-e7e9-b0c2-8f1f-ee9682175a05
* Version Independent ID: a473750a-fbb6-4eed-e0e6-34e8a5009507
* Content: [Release Flow - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/devops-at-microsoft/release-flow)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fdevops-at-microsoft%2frelease-flow.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fdevops-at-microsoft%2frelease-flow.md&version=GBlive&_a=contents)
* Product: **devops**
* Git Login: **samgu**
* Microsoft Alias: **ethomson**

**Comment by true-zanuda** [comment]
I'm still interested in a response.

**Comment by thomps23** [comment]
@stoopered Please accept out apologies for the delay in getting to this issue. 

It looks like you were working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few other options where you might consider asking your questions in the future:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
