### ISSUE TITLE
Undocumented auto-generation of Test Plans and Cases under one specific scenario.

### ISSUE THREAD

**Issue by The-DevOps-Guy** [MicrosoftDocs/vsts-docs#3470]
Ref: https://docs.microsoft.com/en-us/azure/devops/test/create-a-test-plan?view=azure-devops&viewFallbackFrom=vsts

When creating a new "Test" from ; https://dev.azure.com/{your devops tenant}/{your project name here}/_boards/board/t/{your project name here}%20Team/Stories

By clicking on the ellipsis of a board item (user story) and selecting create Test, it not only creates a test work item, but also automatically creates a Test Plan named as per the iteration, and also a test suite, named as per the user story title. 

![image](https://user-images.githubusercontent.com/25591010/53340828-dacb0700-3901-11e9-9036-0b4e4db7e627.png)

This behavior is only possible if you create tests by this method. Which has caused confusion within the team. Since those who are NOT Enterprise MSDN subscribers are otherwise unable to see the  plus button next to Test Plans or indeed, on the icon tool bar when within a test plan to create test suite folders. 

However this strange side affect (hidden behavior which is not documented) is the only way the rest of the team can create Test Plans and Test Suite Folders - albeit automated by DevOps and conforms to the naming of the hidden routine that seems to do this / cannot be changed.

Incidentally this area of the DevOps UI is very buggy and this sometimes does not result in an automated Test Suite generation for the User Story. At such times the only way to invoke that, is to create another temporary test to invoke this routine, then delete the test. Usually works on a second attempt, that is as long as the Ajax calls dont get out of sync. Seems the DevOps UI sometimes gets out of sync with it's own data - feels like some form of eventual consistency is going on rather than transactions ? i digress.

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by harishkragarwal** [comment]
@The-DevOps-Guy, you are right that when a Test is added through a Board then its create a RBS (Requirement Based Suite) inside a Test Plan and links the test case to that suite. This is by design and we should document that this happens. There's no intent to keep it hidden/secret.

To manage Test Plans or Suites explicitly one need to be a Visual Studio Enterprise, Visual Studio Test Professional, or MSDN Platforms subscribers. Or needs to have a Test Manager license [(see](https://marketplace.visualstudio.com/items?itemName=ms.vss-testmanager-web#pricing)).  

Do share the buggy behaviour you have encountered and we will get it fixed.

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will update the topic to include this.
