### ISSUE TITLE
broken URL in navigation

### ISSUE THREAD

**Issue by fiksen99** [MicrosoftDocs/vsts-docs#3479]
'Resources &gt; Git REST APIs' from left hand side navigation leads to a 404 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 183b0984-8a99-c671-5e5a-c1a5d0d85f87
* Version Independent ID: 6e14f792-35d3-97e3-85db-78731cf9b3a5
* Content: [Create and delete a branch in your Git repo - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/branches?view=azure-devops&tabs=visual-studio)
* Content Source: [docs/repos/git/branches.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/branches.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@fiksen99 I think this has been fixed, I couldn't find the exact entry you mention but I was able to make a slight update to another one:

![image](https://user-images.githubusercontent.com/1580889/58910167-d5404280-86e2-11e9-8cf1-1ca8b7140b61.png)

If this issue is still broken, please reactivate this issue. Thank you.
