### ISSUE TITLE
Unable to delete/remove attachment from work item by using VSTS api

### ISSUE THREAD

**Issue by erangaapp** [MicrosoftDocs/vsts-docs#3481]
Currently, we are developing a tool by using VSTS api (https://docs.microsoft.com/en-us/rest/api/azure/devops/wit/attachments/get?view=azure-devops-rest-5.0) + WorkItemTrackingHttpClient to manage attachments and work items for our customers. But there is no option to delete/remove an attachment from the work item. Is this feature already available, please give me an update or can you enable that feature?

Regards,
Eranga

**Comment by steved0x** [comment]
@erangaapp That's good feedback, thanks for letting us know. I am forwarding this request to have the ability to delete/remove an attachment to work items to the product team and closing this issue, since the issues in this repo are for content feedback. Although I am forwarding this to the product team, it will carry more weight if you also file a feature request here:

https://developercommunity.visualstudio.com/spaces/21/index.html

You can also submit product feedback, such as bug reports or feature requests, by choosing **Product feedback** at the bottom of any article:

![image](https://user-images.githubusercontent.com/1580889/51848904-90e40680-22ec-11e9-893f-ded2716f3ea2.png)

Thank you.

**Comment by somasunil** [comment]
Is there any update/solution for this? I'm in the same boat now.
