### ISSUE TITLE
XML variable substitution in applicationsettings when using type: ArrayOfString

### ISSUE THREAD

**Issue by diegoortizmatajira** [MicrosoftDocs/vsts-docs#3485]
Hello,

How should I provide values to set the values in a variable of type ArrayOfString in applicationsettings?:

```
 <applicationSettings>
    <myApp.Properties.Settings>
      <setting name="EmailList" serializeAs="Xml">
        <value>
          <ArrayOfString xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <string>email1@xxxx.com</string>
            <string>email2@xxxx.com</string>
          </ArrayOfString>
        </value>
      </setting>
    </CHAT.Properties.Settings>
  </applicationSettings>
```
Thanks in advance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 315ff823-9992-9f9b-62a1-42ce622ed41c
* Version Independent ID: 72ec3ffc-1dc9-b2dc-e3d4-4f14deae3720
* Content: [File transforms and variable substitution - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/transforms-variable-substitution?view=azure-devops#xmlvarsubs)
* Content Source: [docs/pipelines/tasks/transforms-variable-substitution.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/transforms-variable-substitution.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by thomps23** [comment]
@diegoortizmatajira Please accept our apologies for the delay in getting to this issue. It looks like you were working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking similar questions in the future:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
