### ISSUE TITLE
How to figure out who has enabled/disabled agent from the agent pool?

### ISSUE THREAD

**Issue by 163satish** [MicrosoftDocs/vsts-docs#3487]
Is there any way I can check on who has enabled or disabled the build agent from my agent pools?
With the current view I do not see any way of finding that out.

**Comment by thomps23** [comment]
@163satish Please accept our sincere apology for the delay in getting to your issue. It looks like you were working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking similar questions in the future:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
