### ISSUE TITLE
Send binary data in POST request

### ISSUE THREAD

**Issue by rahulrai-in** [MicrosoftDocs/vsts-docs#3495]
Can this task be used to send a zipped file to a POST endpoint?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89bc6da4-5a1e-5989-f4f0-27465953b5fd
* Version Independent ID: fd12f976-5d3b-3b1b-3d0a-a0bf2a60c961
* Content: [Invoke HTTP REST API task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/http-rest-api?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/http-rest-api.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/http-rest-api.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by thomps23** [comment]
@rahulrai-in Please accept our apologies for the delay in getting to this issue. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

**Comment by HughDevlin** [comment]
More generally, on a PUT, can an input file be specified in the parameters for this task, as it can in the corresponding underlying PowerShell Utility method? 
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-restmethod?view=powershell-6
