### ISSUE TITLE
What it actually means to include / exclude branch from scheduled builds?

### ISSUE THREAD

**Issue by iricigor** [MicrosoftDocs/vsts-docs#3510]
I have scheduled build that runs every day regardless if anything was changed or not. But, I am confused about setting called "Branch filter" with option include/exclude. What does it mean exactly? 

The explanation above says only "you can also specify branches to include and exclude". Just to note, I have configured what is default branch for scheduled builds at the "Tasks" tab, so I do not know what is this for.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=designer)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by iricigor** [comment]
And here is a screenshot of my settings

![image](https://user-images.githubusercontent.com/15923171/53556470-3be21d00-3b44-11e9-89e8-75f4f2bd5cb8.png)

**Comment by kevbry** [comment]
I would also like to know this. It would be very useful to be able to run a daily build, but only if there were changes since the last build for a given branch.

**Comment by steved0x** [comment]
@iricigor @kevbry Apologies for the delay in responding to this.

Branch filter include/exclude specifies which branches are to be built on the specified schedule. It is kind of redundant with the branch being set as the default branch for manual and scheduled builds set on the tasks tab. Here is (a little) more information on that:

https://developercommunity.visualstudio.com/content/problem/348835/scheduled-builds-are-not-using-branch-set-in-the-g.html

@kevbry To only run your scheduled build when the source has changed since the last build, check the "Only schedule builds if the source or pipeline has changed" which was added in TFS 2018.2:

https://docs.microsoft.com/en-us/azure/devops/release-notes/2017/dec-11-vsts#skip-scheduled-builds-if-nothing-has-changed-in-the-repo

Did I answer your questions? Igor, if not, please send me an email to my MS alias and I'll put you in touch with the pipelines team. @Kevbry, if I didn't answer your question, please reactivate this issue.

Also note that YAML scheduled builds using cron syntax are now available on Azure DevOps Services.
