### ISSUE TITLE
Confusion about the MSA Creation

### ISSUE THREAD

**Issue by MatthewMcD** [MicrosoftDocs/vsts-docs#352]
From this statement:

> If the emails are the same, then follow these steps, otherwise continue on to Connect your VSTS account to your organization directory.

It would appear that the creation of the MSA is only needed is the third bullet is true. Skipping 2-8. But it does not work. Even with a completely different account (and no MSA) I still only see "Nothing to display" in the Azure Portal.

**Comment by steved0x** [comment]
@MatthewMcD Which article is this feedback for so I can assign it to the right author? Thank you for letting us know of this issue.

**Comment by chcomley** [comment]
@MatthewMcD We appreciate your comment! In order to do the migration, the user doing the migration must be a guest/member of the target Azure AD tenant and the owner of the VSTS account.  If that’s not the case, you would see “Nothing to display”.  Otherwise, create a new identity per the 2-8 instructions.
