### ISSUE TITLE
How to evaluate the length of an array?

### ISSUE THREAD

**Issue by jordanchang** [MicrosoftDocs/vsts-docs#3521]
Is it possible to check the length of an array?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by thomps23** [comment]
@jordanchang Please accept our apologies for the delay in getting to this issue.

It looks like you were working through a specific scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking your question in the future:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

**Comment by vtbassmatt** [comment]
It's not, sorry.
