### ISSUE TITLE
Release Work Items Variable

### ISSUE THREAD

**Issue by cosminstirbu** [MicrosoftDocs/vsts-docs#3529]
Hello,

Is there a way to retrieve the release work items via a variable?
We'd like to automate our release notes via such a variable.

Looking at https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=azure-devops&tabs=batch we weren't able to find it.

As an alternative, maybe you could change the default value of `Release.ReleaseDescription` to be the list of linked worked items.

Thank you,
Cosmin

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice. In addition, suggestions and feature requests related to the product rather than the documentation can be posted on the Developer Community website at https://developercommunity.visualstudio.com/spaces/21/index.html, where they are tracked by the product teams.

**Comment by RoopeshNair** [comment]
No, work items associated with the release are not available as release variables.
