### ISSUE TITLE
Secure Files

### ISSUE THREAD

**Issue by scriptmonkey69** [MicrosoftDocs/vsts-docs#3530]
I would like to parameterize the Secure File name in the Download Secure File task, as I have 3 certificates needed on each environment, I have 4 environments.

Is there away of doing this?

**Comment by thomps23** [comment]
@scriptmonkey69 Please accept our apologies for the delay in getting to this issue. 

It looks like you were working through an issue with a scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking your question in the future:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
