### ISSUE TITLE
Negation does not work as expected.

### ISSUE THREAD

**Issue by websitewill** [MicrosoftDocs/vsts-docs#3568]
$(System.DefaultWorkingDirectory)/Nuget-Packages/Nuget-Packages/*.nupkg;
!$(System.DefaultWorkingDirectory)/Nuget-Packages/Nuget-Packages/*Alpha.nupkg;
I would expect this to match all packages that do not end with Alpha.nupkg, but that is not the case.

I have also tried the old syntax of -: for negation.

When I run the above, I get an error that the package named *Alpha already exists - indicating the negation filter is not working.
I have tried various ways to limit files and haven't gotten one to work.

This did not work either
$(System.DefaultWorkingDirectory)/Nuget-Packages/Nuget-Packages/*!(Alpha|Beta).nupkg;

**Comment by thomps23** [comment]
@websitewill Please accept our apologies for the delay in getting to this issue.  

It looks like you were working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking your question in the future:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
