### ISSUE TITLE
Is it Possible to Customise vsts email templates

### ISSUE THREAD

**Issue by akash3456** [MicrosoftDocs/vsts-docs#3574]
All, 

Is it at all possible, to customize my VSTS Email templates regardless of whether builds fail or complete.?

**Comment by steved0x** [comment]
@akash3456 I don't believe so, can you check the following Developer communities feature request to see if it matches what you are looking for? If so, you can add your vote to have that feature added, and also add your comments in case you have any additional things to add to the feature request.

* [Customise VSTS email templates](https://developercommunity.visualstudio.com/content/idea/365760/customise-vsts-email-templates.html)

If your issue is not related to this existing feature request, please reopen this issue.

Thank you.
