### ISSUE TITLE
How do you delete a service connection?

### ISSUE THREAD

**Issue by Paul-Dempsey** [MicrosoftDocs/vsts-docs#3594]
Really this very basic: anywhere you describe how to create something, describe how to delete it. In the Service connections page in Azure Devops, I don't see any means for deleting a Service connection. How do you do that? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26477658-d1ad-a4c9-0d9e-59aeead8a71e
* Version Independent ID: 45dfbd24-b9f4-fdf2-48a2-5648220204fe
* Content: [Connect to Microsoft Azure - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/connect-to-azure?view=azure-devops#feedback)
* Content Source: [docs/pipelines/library/connect-to-azure.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/connect-to-azure.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by Paul-Dempsey** [comment]
Of course, right after I post it, I see "Disconnect". I was expecting the normal "Delete" that usually corresponds to "New". If the removal verb is "Disconnect", then the creation verb should be "Connect", not "New".

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will add more relevant information to the topic. Meanwhile, suggestions such as this related to the product rather than the documentation are best posted on the Developer Community website at https://developercommunity.visualstudio.com/spaces/21/index.html, where they are tracked by the product teams. Please post your feedback there. Thank you.
