### ISSUE TITLE
The command line tool exits after running .exe file. Is there a way not to close the command window or process?

### ISSUE THREAD

**Issue by BugShredder** [MicrosoftDocs/vsts-docs#3620]
The command line tool exits after running .exe file. Is there a way not to close the command window or process?

**Comment by thomps23** [comment]
@BugShredder Please accept our apologies for the delay in getting to this issue. 

It looks like you were working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking your question in the future:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
