### ISSUE TITLE
How delete work item from ms project only?

### ISSUE THREAD

**Issue by bazis** [MicrosoftDocs/vsts-docs#3637]
I press "Get work items" button, then add existing work items from TFS.  Now I want to delete this work items from my project, but not delete them from TFS. How in 2019 adding something in table can't be undone?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f6edd47-46d7-ab0d-db47-d73bc45d6b43
* Version Independent ID: 6ac2ae49-0bd0-2c28-fc87-7f034dd96443
* Content: [Create your backlog and tasks using Microsoft Project - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/office/create-your-backlog-tasks-using-project?view=tfs-2018&viewFallbackFrom=vsts&tabs=office-365#feedback)
* Content Source: [docs/boards/backlogs/office/create-your-backlog-tasks-using-project.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/office/create-your-backlog-tasks-using-project.md)
* Product: **devops**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by thomps23** [comment]
@bazis Please accept our apologies for the delay in getting to this issue. 

It looks like you were working through an issue with the product, rather than an issue with the documentation. Here are a few options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
