### ISSUE TITLE
This documentation would be more useful if it had some examples. 

### ISSUE THREAD

**Issue by samsmithnz** [MicrosoftDocs/vsts-docs#3649]
For example, if you have a query with open bugs in it, and a lower and upper threshold is set to the defaults (of 0), when the gate will process correctly, and when it won't. I have a query with a bug in it, and I'm using the default values in the query deployment gate, but it's not failing as I would expect.

Currently this documentation is very short, just doesn't explain concepts well enough. What is the difference between the lower and upper threshold? In some parts of the document we refer to it as lower and upper, in others minimum and maximum. In what situations would changing the lower/minimum and upper/maximum values make sense?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ccc264d-264f-b1e7-e5bf-eabe76ac36bc
* Version Independent ID: 6e7213ee-23d6-2077-2df3-f5dec3c24d15
* Content: [Query Work Items task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/work-item-query?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/work-item-query.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/work-item-query.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. The topic https://docs.microsoft.com/azure/devops/pipelines/release/deploy-using-approvals#configure-a-gate shows how to use the task, and explains a little more about the settings. Perhaps this will be useful. For questions related to the product rather than the documentation, you may also find the Developer Community website at https://developercommunity.visualstudio.com/spaces/21/index.html useful, where questions are tracked and answered by the product teams.
