### ISSUE TITLE
Log of a particular task as attachment in mail notification

### ISSUE THREAD

**Issue by sunpau** [MicrosoftDocs/vsts-docs#3684]
In my build, I have multiple task. When the build completes, I want to send the log of a particular task as an attachment in mail. How do I solve it?

**Comment by thomps23** [comment]
@sunpau Please accept our apologies for the delay in getting to your issue. It looks like you were working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking similar questions in the future:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
