### ISSUE TITLE
Can I associate a Test plan to a Build Pipeline, to update test result status every time a Test ran within that pipeline?

### ISSUE THREAD

**Issue by robinmanuelthiel** [MicrosoftDocs/vsts-docs#3694]
I find it very confusing and over-engineered to create a dedicated Release pipeline for running automated test cases. 

We usually run unit tests as part of our Build pipelines and have associated some test cases with unit tests in our code. What we would like to achieve is that every new Build is updating the status of a test case. 

What we want to achieve is the following flow:

1. Create a Test plan in Azure DevOps
1. Create some Test Cases
1. Associate Unit Tests with those test cases using Visual Studio 2017
1. Associate the test plan with a release pipeline
1. Add the 'Visual Studio Test' step to that release pipeline
1. Run the release pipeline
1. See the test results not only on the release pipeline but also in the Test plan (as a new Test run) 

Is this possible or the totally wrong approach?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b6c92a2-2f5c-e34e-f285-3e1a2a02604b
* Version Independent ID: 6f31f4c2-94ac-20eb-da01-e1d47f041945
* Content: [Run automated tests from test plans - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/run-automated-tests-from-test-hub?view=azure-devops#run-the-automated-tests)
* Content Source: [docs/test/run-automated-tests-from-test-hub.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/run-automated-tests-from-test-hub.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by robinmanuelthiel** [comment]
Hey @alexhomer1, any update on this?

**Comment by louisecollins** [comment]
Hi, I too have been wrecking my brain with this one! BUT I think i have managed to figure out the solution to this. 

Since the product team haven't been able to answer this one, I'll give it a go!
Go to your build definition and edit your VS Test Task, for "Select Tests Using" instead of test assemblies, use "Test Plan" 
Then it's just a matter of choosing the associated test plan, suite, and configuration (you'll need to have these set up in advance in the Test Plan section) to determine where you want your results to write to. 
There is no need for a release pipeline this way!
It works for me :) Good Luck!!!

**Comment by PBoraMSFT** [comment]
@robinmanuelthiel - setting up a release pipeline is necessary if you want to run tests by selecting one or more automated test cases *from the test hub*. This is because that workflow uses the release pipeline as an orchestrator. Such a test run is triggered on-demand, based on user action. 

If you are simply looking to run *all* automated tests of a test plan/test suite in build/release pipeline, the Visual Studio Test task has that capability already. Instead of 'Test assemblies' use the 'Test Plan' option in the 'Select tests using' field. Such a run will take place any time the pipeline is triggered (CI/scheduled/manual trigger).

**Comment by robinmanuelthiel** [comment]
Thanks for your replies! 👍
