### ISSUE TITLE
Where is the iisnode.yml file?

### ISSUE THREAD

**Issue by timmyreilly** [MicrosoftDocs/vsts-docs#3708]
As I'm troubleshooting working through Azure DevOps for Node, I noticed that the iisnode.yml is missing when I follow the DevOps build and release cycle and my app would not start. Then when I manually added it via the kudu console it worked. How do I ensure that this file and configuration is correct in Azure DevOps? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a40a853-83d6-844a-4752-8b00909c9ffb
* Version Independent ID: e3121964-de38-2a57-2414-c1e29a880477
* Content: [Deploy an Azure Web App - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/webapp?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/targets/webapp.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/targets/webapp.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by thomps23** [comment]
@timmyreilly Please accept our apologies for the delay in getting to this issue. It looks like you were or still are working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
