### ISSUE TITLE
Non Functioning Link

### ISSUE THREAD

**Issue by nigelainscoe** [MicrosoftDocs/vsts-docs#374]
The Tenant Id [...] More Information hyperlink under Manual subscription definition does not leave the page or provide more information

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72b90dd0-49f9-4ed4-3010-9a64dde6ae5a
* Version Independent ID: 6e679d50-4e94-eee3-8793-af884cc909ca
* Content: [Service endpoints in VSTS and Team Foundation Server](https://docs.microsoft.com/en-gb/vsts/build-release/concepts/library/service-endpoints?view=vsts#sep-azure-rm-existingsp)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/vsts-docs-pr?path=%2fdocs%2fbuild-release%2fconcepts%2flibrary%2fservice-endpoints.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/vsts-docs-pr?path=%2fdocs%2fbuild-release%2fconcepts%2flibrary%2fservice-endpoints.md&version=GBlive&_a=contents)
* Service: **unspecified**
* GitHub Login: @douge
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will update the topic to correct the links. They should point to the section "To use an existing service principal instead of creating a new one". There is also a blog post referenced in the topic that provides additional information: https://blogs.msdn.microsoft.com/devops/2015/10/04/automating-azure-resource-group-deployment-using-a-service-principal-in-visual-studio-online-buildrelease-management/
