### ISSUE TITLE
Key Vault protected by firewall

### ISSUE THREAD

**Issue by petenorth** [MicrosoftDocs/vsts-docs#3803]
Currently the Azure DevOps Agents can only access a firewall protected key vault if an explicit network rule is configured for the key vault dynamically via the Azure CLI.

It would be nice if either by default Azure DevOps agents are included in the 'Azure Services' which can access the key vault or if the task has a configuration option which when enabled automatically opens the firewall for the agent and closes it afterwards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69ff8e50-4187-3622-1beb-155f006af5f5
* Version Independent ID: bc56fa96-bded-95f8-39a4-a9e5242db1bf
* Content: [Azure Key Vault task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-key-vault?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-key-vault.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-key-vault.md)
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. Suggestions and feature requests related to the product rather than the documentation are best posted on the Developer Community website at https://developercommunity.visualstudio.com/spaces/21/index.html, where they are tracked by the product teams. Please post your feedback there. Thank you.
