### ISSUE TITLE
docker-compose  build  -m xGB option 

### ISSUE THREAD

**Issue by komby** [MicrosoftDocs/vsts-docs#3806]
Example of how to pass the memory flag option to docker-compose build task. 

When running on the command line I am able to 

   docker-compose  --verbose -p .. -f ../docker-compose.yml  build -m 6GB

Is there an option to set the memory flag on the docker-compose action: Build Service task?

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

My apologies for the delay in responding.
