### ISSUE TITLE
VST only discover 200 tests from a suite

### ISSUE THREAD

**Issue by shenhong1000** [MicrosoftDocs/vsts-docs#3841]
I have a AzureOps pipeline using VST, however the VST task can only discover 200 tests from the suites. The query-based suites actually has couple thousands tests. I checked configuration from test plan view. It returns a thousand tests with same configuration. I tried couple different suites, it still discover 200 tests. Wondering which field can limit test discover number in VST?

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

My apologies for the delay in responding.
