### ISSUE TITLE
Fail if there are test failures not failing the build

### ISSUE THREAD

**Issue by Ixionnyu** [MicrosoftDocs/vsts-docs#3856]
I have a CI build with a testing phase consisting of a "SoapUI Pro for Azure Devops" task and a "Publish Test Results" step.

When my test has failed steps (and the report does indicate there are failed test steps) the build does not show as failed.

I was expecting the build to fail when there are failed test steps.

**Comment by WilliamAntonRohm** [comment]
Thanks for your feedback. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

My apologies for the delay in responding.
