### ISSUE TITLE
Nuget Task Not respecting Bypass Proxy settings on on-prem Agent and TFS

### ISSUE THREAD

**Issue by jeffpriz** [MicrosoftDocs/vsts-docs#3881]
I am trying to utilize the Nuget task to publish Nuget packages to a Local TFS Nuget Feed.. However, the NuGet Task gets a ECONNRESET error .. Investigating this, it is due to the call to TFS being routed through our Proxy server.  However the settings on that Agent Server are set to bypass the proxy for the TFS Server address, so I am not sure why the call is still being routed through the proxy. Also I've added a NO_PROXY environment variable to also attempt to bypass the proxy, but no luck, calls still route through the proxy and cause this to fail..

How can I make this task Bypass our proxy when attempting to publish a package to our TFS Server?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fa37a3f-6551-16ad-e164-a4ac522cdaab
* Version Independent ID: a3fd6935-2b99-92ef-4eb3-3249fca01f8a
* Content: [NuGet restore, pack, and publish task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/package/nuget.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/package/nuget.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by thomps23** [comment]
@jeffpriz Please accept our apologies for the delay in getting to this issue. It looks like you were working through a problem with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider similar questions in the future:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
