### ISSUE TITLE
Tests under the Visual Studio Team Explorer?

### ISSUE THREAD

**Issue by MisinformedDNA** [MicrosoftDocs/vsts-docs#3883]
&gt; Those tests must also run under the Visual Studio Team Explorer.

What does that mean? Is there a test option in the VS Team Explorer that I've totally missed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1acb75f5-3f74-13a0-4053-406efc5389d7
* Version Independent ID: 216cbb0d-3e7b-b24e-b3c1-a9ae7776c14a
* Content: [Shift Left to Make Testing Fast and Reliable - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/devops-at-microsoft/shift-left-make-testing-fast-reliable#feedback)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fdevops-at-microsoft%2fshift-left-make-testing-fast-reliable.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fdevops-at-microsoft%2fshift-left-make-testing-fast-reliable.md&version=GBlive&_a=contents)
* Product: **devops**
* Technology: **devops-learn**
* Git Login: **samgu**
* Microsoft Alias: **samgu**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question, and apologies for the delay in responding. 

It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
