### ISSUE TITLE
What is the connection between pr: triggers in my yml and build validation for a branch policy?

### ISSUE THREAD

**Issue by seangwright** [MicrosoftDocs/vsts-docs#3891]
I have a azure-pipelines.yml in my repository.

It has a `pr:` trigger

```yml
pr:
  autoCancel: true
  branches: 
    include:
    - master
  paths:
    exclude: 
    - README.md
    - .gitignore
    - .editorconfig
```

What connection does this have to Build Validation in Branch Policies?
https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-policies?view=azure-devops&viewFallbackFrom=vsts#build-validation

Is this the same thing?

When I remove all my build validations, creating a PR does not have any build requirements.

Is the `pr:` trigger a completely independent trigger from the Build Validation requirement on a Branch Policy?

If I have both a `pr:` trigger and a Build Validation for a Branch Policy will the build described in my .yml run twice?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#pull-request-validation)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by scorpionlion** [comment]
it seems that "branch policies" build validation is only for Azure DevOps/Server Git branches. For third party code repositories the "build trigger" build validation is used. Which makes sense but it would be good to have the same experience for both.

**Comment by seangwright** [comment]
It would be really nice to define the triggers/steps for a branch policy build validation in my repository - that's where I'm already defining the triggers/steps for my build pipelines and my CI build validation is very similar stuff.

**Comment by steved0x** [comment]
@seangwright Right now, PR triggers for Azure Repos Git are implemented using branch policies, as described [here](https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-policies?view=azure-devops#build-validation). When configuring a build validation using this branch policy, you select a Pipeline, but only the build portion of that pipeline is used, and if the selected pipeline has any other triggers specified (CI or scheduled, or even PR) they won't be used in the scope of the build validation branch policy. In that case, the branch policy controls the trigger, and the pipeline controls the build.

`Is the pr: trigger a completely independent trigger from the Build Validation requirement on a Branch Policy?`

Yes, completely independent, and the `pr` trigger is not used, and won't fire, on Azure Repos Git repos.

`If I have both a pr: trigger and a Build Validation for a Branch Policy will the build described in my .yml run twice?`

No,  just once, because the `pr` trigger in the YAML won't be used.

`It would be really nice to define the triggers/steps for a branch policy build validation in my repository - that's where I'm already defining the triggers/steps for my build pipelines and my CI build validation is very similar stuff.`

That is a valid concern/request, I recommend that you file a feature request [here](https://developercommunity.visualstudio.com/spaces/21/index.html) and let the product team directly know. I would be happy to do it for you, but if it comes from a customer it carries more weight. You are not the only one with this suggestion (example:https://github.com/MicrosoftDocs/vsts-docs/issues/4416), and the more submissions/votes it gets, the better.

Thank you.

**Comment by seangwright** [comment]
@steved0x Thanks for the feedback.

It looks like there is an existing request for this functionality, which I voted for, if anyone else comes across this.

https://developercommunity.visualstudio.com/idea/385329/pr-triggers-in-yaml-should-be-supported-on-azure-d.html

**Comment by laurynasr** [comment]
> When configuring a build validation using this branch policy, you select a Pipeline, but only the build portion of that pipeline is used

How do I mark the "build portion" of a YAML pipeline?

**Comment by elninoisback** [comment]
@laurynasr AFAIK anything under the "steps:" is the build portion of the pipeline.

**Comment by elninoisback** [comment]
> How do I mark the "build portion" of a YAML pipeline?

@laurynasr AFAIK anything under the "steps:" is the build portion of the pipeline.
