### ISSUE TITLE
Tie hosted agents into an Azure subscription?

### ISSUE THREAD

**Issue by soccerjoshj07** [MicrosoftDocs/vsts-docs#3910]
With the hosted agents and writing custom build/release tasks, is it possible to have access to Azure resources in our company's subscription other than providing the ClientId, ClientSecret, and ClientSecretURI? 

I am trying to write a task for our company's use that pulls back a password from the keyvault and was having difficulties with not having to hardcore the above values in the task code itself.

**Comment by thomps23** [comment]
Please accept our apologies for the delay in getting to this issue. It looks like you were working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking similar questions in the future:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
