### ISSUE TITLE
Test Results are not Categorized by JUnit Test Suite

### ISSUE THREAD

**Issue by planetmarshall** [MicrosoftDocs/vsts-docs#3917]
When publishing a JUnit format XML file, The Tests all appear under a single Test Suite : 'Unspecified' instead of the Test Suite specified in the XML file.

**Comment by thomps23** [comment]
@planetmarshall Please accept our apologies for the delay in getting to this issue, It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.

**Comment by WilliamAntonRohm** [comment]
@planetmarshall -- Andrew, I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
