### ISSUE TITLE
PR Triggers not working for Azure DevOps Git Repos

### ISSUE THREAD

**Issue by olandese** [MicrosoftDocs/vsts-docs#3922]
I am trying to fire builds with PR Triggers, and it's not working.
Following this thread https://developercommunity.visualstudio.com/content/problem/402133/yaml-definition-does-not-work-with-pull-requests.html  seems that the PR triggers works only for GitHub Repos and not for ADO Git Repos. 
If true, please update the docs, it's misleading. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@olandese Sorry that you ran into trouble, and I will get the documentation updated to make this clearer. We do have a note in the [YAML Schema](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#pr-trigger) that makes this distinction, but it needs to be made more clear in other places, and I will do that.

However, since your repo is an Azure Git Repo, you can set a branch policy that does the same thing:

https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-policies?view=azure-devops#build-validation

Let me get more clarification and I will get the docs updated.

**Comment by steved0x** [comment]
@olandese I just updated the docs and they should be live later today. Branch policies is the way to get the same functionality as a PR trigger when your code is in Azure Repos Git.

**Comment by alloro** [comment]
@steved0x is it planned to have PR trigger on azure repositories in the future? Branch policies are more or less ok but will be executed atm on every change or needed to be triggered manually. PR trigger would be more fine granular and better suitable for certain use-cases where you only want to execute certain actions when a PR is opened for example.

**Comment by hecflores** [comment]
@steved0x not sure if the question from @alloro was answered but I had the same query. When can we expect pr triggers defined in yaml to be enforced for azure devops git repos? Please tell me it's in the road map to support one of the best features in the in house repo inside if azure devops.... just confused why its not...

**Comment by Lusey77** [comment]
@hecflores From the looks of this [ticket](https://developercommunity.visualstudio.com/idea/385329/pr-triggers-in-yaml-should-be-supported-on-azure-d.html), it does not appear to be on the roadmap and is still only a suggestion unfortunately.
