### ISSUE TITLE
Failure analysis using Test Failure field

### ISSUE THREAD

**Issue by louisecollins** [MicrosoftDocs/vsts-docs#3929]
I have set up a build&release pipeline to run on demand automated tests. Using the run results I have triage failures and updated the Failure Type and Resolution fields. When I then view my test suite, and try to create a chart using Failure Type, it does not work, all tests show failure type as none, what am I doing wrong? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23cfb51b-0b54-7d26-f9b2-4167915fba7a
* Version Independent ID: 5716194c-87f4-b1dc-7f31-592529a1fd3a
* Content: [Track test status - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/track-test-status?view=azure-devops)
* Content Source: [docs/test/track-test-status.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/track-test-status.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by thomps23** [comment]
@louisecollins Please accept our apologies for the delay in getting to this issue. It looks like you were working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking similar questions in the future:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
