### ISSUE TITLE
Latest tag not being properly applied to the image

### ISSUE THREAD

**Issue by lsantos10** [MicrosoftDocs/vsts-docs#3931]
On the Docker Build task I have selected the option to tag the image is latest, but it on recent build the latest tag is not being applied after docker push.

**Comment by thomps23** [comment]
Please accept our apologies for the delay in getting to this issue. It looks like you were working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking your question in the future:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
