### ISSUE TITLE
Artifact Download - Multiple artifacts all defaulting to primary artifact Build Id

### ISSUE THREAD

**Issue by eal61** [MicrosoftDocs/vsts-docs#3968]
Defect uncovered while attempting to configure multiple artifacts in release pipeline.

Using the artifact download section of the agent job/deployment job fails when attempting to download an artifact outside of the primary artifact. It uses to the build id of the primary to search for the artifact and fails because it is incorrect.

Example:

A1 (primary) - latest build id 1890 
A2 - latest build id 1892

In any stage that attempts to download A2, it will fail with the following message:
"A2 was not found for build 1890."

The workaround right now if to use the Download Pipeline Artifact task, but I think we should be able to make use of the Artifact Download functionality of the Agent Job as it seems that this scenario is intended to work.

https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml

**Comment by eal61** [comment]
Any updates?

**Comment by eal61** [comment]
Hello?

**Comment by eal61** [comment]
@andyjlewis Looking for any input on this

**Comment by andyjlewis** [comment]
@eal61 I'm sorry for the delayed response. Assigning to @elbatk to review this issue.

**Comment by elbatk** [comment]
Hi @eal61 , sorry you ran into this issue. I think from a docs point of view, the solution would just be to update that DownloadBuildArtifact task with the DownloadPipelineArtifact task: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-pipeline-artifact?view=azure-devops, however if this is about the product issue itself, you would gain better traction posting it to the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html). However, because there is already a workaround with DownloadPipelineArtifacts, I doubt we would prioritize a fix here. In fact, Pipeline Artifacts are the "new" Build Artifacts so we'd prefer you use the pipeline task.

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
