### ISSUE TITLE
Docker build getting failed when using self hosted agent which was created using Linux docker file showed in the url - https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops 

### ISSUE THREAD

**Issue by Srikanthshetty** [MicrosoftDocs/vsts-docs#3971]
Created self hosted Linux agent as specified in this document, but using this agent docker build is failing with following error;

Unhandled : Failed which : Not found docker: null

edit the docker file with following change but getting new error.

**DockerFile**

RUN apt-get update \
&& apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
        jq \
       **docker.io** \
        git \
        iputils-ping \
        libcurl3 \
        libicu55

**Error**

##[error]Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31d4f6c-d16d-2ba1-1294-6aa94e328046
* Version Independent ID: 88aec599-4410-697d-1002-1c41b1c17bb6
* Content: [Running the agent in Docker - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops#linux)
* Content Source: [docs/pipelines/agents/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/docker.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliobbv
* Microsoft Alias: **alewis**

**Comment by vtbassmatt** [comment]
@juliobbv any thoughts on this one? I don't mind to fix docs but it's not clear to me what's wrong. Thanks!

**Comment by juliobbv** [comment]
I believe that in order to run the Docker task inside the docker container, the customer has to also map the Docker socket (`docker.sock`) into the container.

https://forums.docker.com/t/how-can-i-run-docker-command-inside-a-docker-container/337

Please note that once the step above is done, and the container is running as root, anybody can run arbitrary commands via `docker exec`, so the customer has to be explicitly aware of the implications of allowing running Docker commands.

https://docs.docker.com/engine/reference/commandline/exec/
