### ISSUE TITLE
How to login both AzureRM and Azure module in Azure PowerShell Task 

### ISSUE THREAD

**Issue by melode11** [MicrosoftDocs/vsts-docs#3973]
I had a script that need to dealing Azure Resources mixed with ARM and ASM, I require both AzureRm and Azure in my script.
Although Azure PowerShell task version 3.x have Both Azure And AzureRM modules installed, it only login the AzureRm cmdlets. 
Is there a way to let the task login for both?
Otherwise, Is it possible to get credential from AzureRmContext and do login by myself in Azure?

**Comment by melode11** [comment]
I have also tried Azure Powershell 4.*, looks like it only login Azure CLI for you, and looks like the Azure CLI version doesn't support ASM resources at all.

**Comment by thomps23** [comment]
@melode11 Please accept our apologies for the delay in getting to this issue. It looks like you were working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking these types of questions in the future:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
