### ISSUE TITLE
Can't add Query Widget to Dashbaord

### ISSUE THREAD

**Issue by Nubestic** [MicrosoftDocs/vsts-docs#3974]
While trying to add a new query widget in dashboard the drop down for queries is not populated properly and can't choose the query.
Also from the custom query side, there is no ... button to add to dashboard !

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e56e5bfa-e2ea-c309-8487-3ba3236ee6ee
* Version Independent ID: 981fdeed-0f98-135c-effb-2446cff74ea9
* Content: [Add a team administrator - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/add-team-administrator?view=azure-devops#feedback)
* Content Source: [docs/organizations/settings/add-team-administrator.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/add-team-administrator.md)
* Product: **devops**
* Technology: **devops-settings**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by thomps23** [comment]
@Nubestic Please accept our apologies for the delay in getting to this issue. It looks like you were working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking these types of questions in the future:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
