### ISSUE TITLE
Can't add to Dasboard

### ISSUE THREAD

**Issue by Nubestic** [MicrosoftDocs/vsts-docs#3975]
The ... add to dashboard doesn't exists on query charts, I'm project admin with full access to Project

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 309b3b5f-7355-57ac-3775-b441f6e037f1
* Version Independent ID: 0d30ed27-9dc4-e8de-ef7e-c71842c9b4c3
* Content: [Create managed queries with the Query Editor - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/using-queries?view=azure-devops)
* Content Source: [docs/boards/queries/using-queries.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/queries/using-queries.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by thomps23** [comment]
@Nubestic Please accept our apologies for the delay in getting to this issue. It looks like you were working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking these types of questions in the future:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
