### ISSUE TITLE
Using VSTS_AGENT_INPUT_ for non-key/value parameters

### ISSUE THREAD

**Issue by tomaszkosturekswissre** [MicrosoftDocs/vsts-docs#3978]
Is it supported to set parameters like --once and --replace by passing them as environment variables (VSTS_AGENT_INPUT_ construct)? I've tried setting them via CLI, when deploying the agents to ACI, but they do not seem to take effect.

e.g. --environment-variables VSTS_AGENT_INPUT_ONCE= VSTS_AGENT_INPUT_REPLACE= 

I'd like to avoid forking the start.sh script and building my own docker image.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23328b13-f079-ad21-5d7a-6c640f25391c
* Version Independent ID: 4a39889d-fa00-ae2b-aa43-f358631b7b1a
* Content: [Deploy a build and release agent on Linux - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-linux?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/v2-linux.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/v2-linux.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by thomps23** [comment]
@tomaszkosturekswissre Please accept our apologies for the delay in getting to this issue. It looks like you were working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking these types of questions in the future:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
