### ISSUE TITLE
What's the grammar for `dotnet build` project path?How do I add more than one project for `dotnet build` project path?

### ISSUE THREAD

**Issue by WeihanLi** [MicrosoftDocs/vsts-docs#3981]
As the title, we use `**/*.csproj` commonly for  `dotnet build` project path, it works greatly.
But we recently add a dotnet framework project, while we run our build on *nix build agent, we wanna exclude the dotnet framework projects or include the dotnet core projects only, but when I try to update the project path like `dotnet pack`, I meet the error below:

```
Project file(s) matching the specified pattern were not found.
```

but the project path I defined works for `dotnet pack` project path, I'm so confused. Hope anyone would help.

project path I use:

```
Business/*.csproj;Models/*.csproj;
**/*.csproj;-FxModels/*.csproj;
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 483dcb1c-1a89-2b20-4cf2-abd3ae88d9ed
* Version Independent ID: dc4722ed-5a4b-26ec-e7d5-a149bf6e79a7
* Content: [Build, test, and deploy .NET Core apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/dotnet-core?view=azure-devops#build-your-project)
* Content Source: [docs/pipelines/languages/dotnet-core.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/dotnet-core.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by thomps23** [comment]
@WeihanLi Please accept our apologies for the delay in getting to this issue. It looks like you were working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking these types of questions in the future:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

**Comment by WeihanLi** [comment]
Found no answer, created a question on stackoverflow [here](https://stackoverflow.com/questions/56592319/whats-the-grammar-for-azuredevops-dotnet-build-project-pathhow-do-i-add-more), hope anyone would help
