### ISSUE TITLE
Azure AD API testing

### ISSUE THREAD

**Issue by vijaychowthri** [MicrosoftDocs/vsts-docs#3984]
We are trying to Build API functional testing using Apache J-meter, We got struck authentication part. how you login with user credentials and get Azure AD cookies to post/get/put further transactions ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7f40446-f1cc-5b5a-35f2-8115f4204f6e
* Version Independent ID: a321bcf7-0924-3d3b-385b-33e5aa6b5125
* Content: [Run Apache JMeter load tests - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/load-test/get-started-jmeter-test?view=azure-devops#feedback)
* Content Source: [docs/test/load-test/get-started-jmeter-test.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/load-test/get-started-jmeter-test.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by vijaychowthri** [comment]
We are using adal , to access token.
we already set-up native client_Id for this automation.
How you set this parameter such as  username , password , client_id and resource and get the Authorization token.

**Comment by drakor007** [comment]
Hi, I tried JMeter on Azure DevOps and there is version 3.2 which is very obsolete.  Is there any chance to update it to e.g. 5.1 version? Because some more sophisticated tests don't run on this over 2-year-old version.

**Comment by WilliamAntonRohm** [comment]
@vijaychowthri, @drakor007 -- Thanks for your questions. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your questions: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 

 
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by vijaychowthri** [comment]
@WilliamAntonRohm 

thanks !!
