### ISSUE TITLE
How to run unit tests in a container that depends on mongodb and redis container.

### ISSUE THREAD

**Issue by AceHack** [MicrosoftDocs/vsts-docs#3987]
I have unit tests that need redis and mongodb containers running so the tests can pass.  How do I orchestrate this using Container jobs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3339a2e0-be29-1363-f588-b231d4472c02
* Version Independent ID: 72dd11a3-704d-d0fd-6dfa-cf49f3352de3
* Content: [Container Jobs in Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/container-phases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/container-phases.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thomps23
* Microsoft Alias: **macoope**

**Comment by thomps23** [comment]
@AceHack Please accept our apologies for the delay in getting to this issue. It looks like you were working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking your question in the future:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
