### ISSUE TITLE
task list button

### ISSUE THREAD

**Issue by EldarAliev** [MicrosoftDocs/vsts-docs#3994]
![2019-04-17 150758](https://user-images.githubusercontent.com/49719359/56286529-9e0dd600-6122-11e9-83c1-6b9ddee1ca59.jpg)
How to use the task list button?
When added, the checkbox without a check mark appears.
And how to add a checkbox with a check mark?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7892ee5-8b56-bd95-29bb-41ebb8a8bd7e
* Version Independent ID: eccf0785-0968-d6a2-d29e-0c4796aa165c
* Content: [Add, edit, reorder and manage wiki pages in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/add-edit-wiki?view=azure-devops#feedback)
* Content Source: [docs/project/wiki/add-edit-wiki.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/add-edit-wiki.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @EldarAliev, You can add an "x" inside of the "[]" to get a checked checkbox.

Here's a [link ](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fdevops%2Fproject%2Fwiki%2Fmarkdown-guidance%3Fview%3Dazure-devops%23checklist-or-task-list&data=01%7C01%7CChrystal.Comley%40microsoft.com%7Ceb1ac5db2b1549f7567708d6cec7e586%7C72f988bf86f141af91ab2d7cd011db47%7C1&sdata=rsD8P8xlRhdaHzZGW%2FO3kDfMoYBkU%2FAdILFTK4Ah%2B1I%3D&reserved=0) to the documentation about checklists. Thanks for reaching out and please let us know if you have any further questions, otherwise I'll be closing this issue. Thanks again!

**Comment by EldarAliev** [comment]
Hi @chcomley thank you! now I see. for some reason, the search failed to find this documentation page.
