### ISSUE TITLE
Store and reuse expression result?

### ISSUE THREAD

**Issue by sylveon** [MicrosoftDocs/vsts-docs#4002]
Is it possible to somehow store and reuse the result of an expression, instead of having to rewrite the same expression multiple times?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c58a78-a567-e99a-9eb7-62dddd1b90b6
* Version Independent ID: 680a79bc-11de-39fc-43e3-e07dc762db18
* Content: [Expressions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops)
* Content Source: [docs/pipelines/process/expressions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/expressions.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by dkmiller** [comment]
This would be super useful if possible! I find myself repeating the same expression for "on master branch, not a PR build" multiple times in most build definitions.

**Comment by thomps23** [comment]
@sylveon Please accept our apologies for the delay in getting to this issue. It looks like you had a product question, rather than an issue with the documentation. Here are a few options where you might consider asking your question in the future:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
