### ISSUE TITLE
How to restrict the REST call response for service connection endpoint with just one value in the build task picklist

### ISSUE THREAD

**Issue by tanmayghosh2507** [MicrosoftDocs/vsts-docs#4010]
So, for a custom service connection type, multiple service connection endpoints can be created. Now in the build task picklist, all those endpoint names will be populated in the dropdown. 
Is there any way I can just show only one fixed endpoint or set that as default and make the field readonly? Or can I add a restriction the service connection, that no one else can create an endpoint?

**Comment by tanmayghosh2507** [comment]
Any update on the same? Thanks!

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
