### ISSUE TITLE
Integrate Azure DevOps with Azure TemplateUri for resource deployment

### ISSUE THREAD

**Issue by bcjmk** [MicrosoftDocs/vsts-docs#4017]
We are building reusable and linked templates for our internal use. Due to confidentiality concerns, we cannot keep them on public GitHub where we could use "https://raw.githubusercontent.com/" as the source. 

How do we establish a similar baseUri for our content to link these Azure deployment templates? Would be a great example to improve uptake.

Thanks

**Comment by thomps23** [comment]
@bcjmk It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
