### ISSUE TITLE
Out of date grahpics

### ISSUE THREAD

**Issue by bbob55** [MicrosoftDocs/vsts-docs#4022]
Step 3 under Create a service connection is an outdated graphic.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72b90dd0-49f9-4ed4-3010-9a64dde6ae5a
* Version Independent ID: 6e679d50-4e94-eee3-8793-af884cc909ca
* Content: [Service connections in Azure Pipelines and Team Foundation Server - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops#feedback)
* Content Source: [docs/pipelines/library/service-endpoints.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/service-endpoints.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by steved0x** [comment]
@bbob55 I was reviewing this issue, and I just verified that this dialog is the most current version displayed on Azure DevOps Services. If you are on an earlier TFS version, yours may be different, and there are also differences based on your authentication, and there is also a full version of the service connection dialog, so that may explain the differences as well. I will add a note to clear this up.

Thank you for your feedback.
