### ISSUE TITLE
Using mac and Azure CLI

### ISSUE THREAD

**Issue by sideez** [MicrosoftDocs/vsts-docs#4028]
Could I use the same on mac using Azure CLI? How would I be able to accomplish the same structure using mac?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 330532da-d568-b010-a154-62afb1844e4a
* Version Independent ID: 4efad37d-4ec2-033e-51b1-b9f588e675c6
* Content: [Require branches to be created in folders - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/require-branch-folders?view=azure-devops&tabs=browser)
* Content Source: [docs/repos/git/require-branch-folders.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/require-branch-folders.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by thomps23** [comment]
@sideez Please accept our apologies for the delay in getting to this issue. It looks like you were working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking your questions in the future:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
