### ISSUE TITLE
Clean Target Folder fails with sub folders

### ISSUE THREAD

**Issue by larrybud2004** [MicrosoftDocs/vsts-docs#4033]
If the target has sub folders with files in them, the task fails:

2019-04-22T18:42:59.5556492Z ##[error]Unhandled: Failed rmRF: rm: could not remove directory (code ENOTEMPTY):

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81f02378-b85b-d3a4-d3c8-f07d935367da
* Version Independent ID: fab57f76-35d2-4024-6f7f-1740d7b24743
* Content: [Copy Files task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/copy-files?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/tasks/utility/copy-files.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/copy-files.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
