### ISSUE TITLE
Docker Task - Tag/Run commands now missing

### ISSUE THREAD

**Issue by SQLGeordie** [MicrosoftDocs/vsts-docs#4039]
I have a previously built pipeline using Docker tasks and they allowed the use of tag/run commands but these are no longer available and a new buildAndPush command is now an option.

I can still access these in the previously built pipeline. Are these just missing or removed going forward? The docs seem to indicate that they should be there so if they are removed them the [docs need updating](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=azure-devops).

Screen shots of the Docker task command options (previous and current) are attached:

![Previous Docker Task Commands](https://user-images.githubusercontent.com/15836050/56574208-90d96700-65ba-11e9-8196-006f611351ed.png)
![New Docker Task Commands](https://user-images.githubusercontent.com/15836050/56574240-a0f14680-65ba-11e9-851f-8498ca4a3a2b.png)

**Comment by shashankbarsin** [comment]
In Docker@1, even though run and tag were supported as options in the dropdown, the task itself was not doing anything more than running the equivalent command directly using docker binary on script. In order to keep the task interface clean with fewer number of inputs, Docker@2 doesn't have tag and run as options in the task. However, as mentioned earlier, the recommendation is to run these commands directly via docker binary on script
