### ISSUE TITLE
How to deploy to DMZ servers with Deployment group Agent.

### ISSUE THREAD

**Issue by saidevops729** [MicrosoftDocs/vsts-docs#4071]
Hi Everyone,

My company uses TFS 2018 and use deployment groups as deploying to servers. We can able to deploy to dev and qa environments with Deployment Groups. But We have other DMZ servers which are not in our domain. There is no connection between our corporate TFS server and DMZ servers. What is the best scenario here to deploy and have a CI/CD?

**Comment by KathrynEE** [comment]
@thomps23 - this is a CI/CD question. Please assign accordingly.

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
