### ISSUE TITLE
Shelveset listing in VS is restricted to the first 100 results. 

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/vsts-docs#4077]
This is never enough, and it assumes you know the name of the shelveset instead of another property like an approximate date.

Are the other properties of a shelveset searchable? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfd36c9f-c60e-6191-f344-0cd8c0829bb6
* Version Independent ID: 25868222-c846-1e31-9373-a741df436cb6
* Content: [Suspend your work and manage your shelvesets - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/tfvc/suspend-your-work-manage-your-shelvesets?view=azure-devops)
* Content Source: [docs/repos/tfvc/suspend-your-work-manage-your-shelvesets.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/tfvc/suspend-your-work-manage-your-shelvesets.md)
* Product: **devops**
* Technology: **devops-code-tfvc**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).

**Comment by StingyJack** [comment]
@mijacobs - same deal as the one I just commented on. I have a question about usage after consulting the manual and not finding the info I was looking for.

How is this a product issue when I'm looking for the instructions?

**Comment by StingyJack** [comment]
@mijacobs - do you like it when you ask someone a question and they only respond with a form letter exemplifying a lack of attention and professional courtesy/respect while stating that your questions are not their problem? 

And then do you prefer it when you try to make it simpler for them to understand how the question is in their area of responsibility and then they wholly ignore that?

I don't like either if those things being done to me, so I try _really_ hard to not do them to anyone else. Making someone a victim of policy is another "don't" on my list. 

You closed three of the issues I has opened in about 10 minutes on the same day, all with the same canned response. I can only assume you want the same treatment in return. Would that be correct?
