### ISSUE TITLE
Tag-triggered builds [Designer]

### ISSUE THREAD

**Issue by vaddieg** [MicrosoftDocs/vsts-docs#4090]
Is it possible to configure a pipeline in Visual designer to be triggered by pushing a new tag?
Tried 'refs/tags/*' as 'Branch Specification', but it does not work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=designer#feedback)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@vaddieg I am finding out for you and will report back shortly.

**Comment by perryloh** [comment]
@steved0x I would be keen to know as well. I tried this from the {Designer} like below, and didn't seem to work.
Add -> Branch filter -> Include -> /refs/tags/v1.*

**Comment by benedict1986** [comment]
Me too. I am working with BitBucket and includes the following two branches
- /refs/tags/*
- build

If I push to build branch, pipeline is triggered. But it is not triggered when I push a new tag or origin.

**Comment by steved0x** [comment]
Closing the loop on this - it should work, and if not, it sounds like there might be some product issue happening. Here are a few related threads:

* https://developercommunity.visualstudio.com/content/problem/580939/build-trigger-on-refstagsx-with-external-git.html
* https://developercommunity.visualstudio.com/idea/365545/trigger-build-when-pushing-tag-to-git.html
* https://developercommunity.visualstudio.com/content/problem/544008/build-process-triggered-by-git-tag-creation-starte.html
* https://developercommunity.visualstudio.com/idea/370285/pipeline-builds-not-being-triggered.html

If this issue is still happening (your builds aren't triggered by pushing a tag that matches your filters), please file an issue here: https://developercommunity.visualstudio.com/spaces/8/index.html
