### ISSUE TITLE
No caching mechanism available for Universal Packages

### ISSUE THREAD

**Issue by Eragra3** [MicrosoftDocs/vsts-docs#4098]
Hello,

Universal Packages do not offer any caching mechanism AFAIK, so if you call the same command twice, it will download and then re-download the package (unlike NuGet for instance).

Is there anything on the roadmap to make this available? Because the packages are not zipped, and can contain multiple file in "root", a built-in caching mechanism is probably quite hard to get right. 

But maybe something simpler like that could work (might be also useful later):
Create new lightweight API (preferably also in VSTS CLI) that returns checksum for the package, based on it's name, version and feed.

Example
```ps1
vsts package universal checksum`
    --instance "https://dev.azure.com/SomeOrg/" `
    --feed "SomeFeed" `
    --name "some-name" `
    --version "1.0.0"
```
Returns just: `BE906A753CD532E5DDE5BC0BFFC144DA4E3C6AB30A0A7DE283C488F620511611`, so it can be piped in scripts.
Package users can then save this checksum into a file, and next time check the hash first before downloading, essentially having very simple caching.

We could add a switch to alternate between MD5 and SHA256 as well.

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
