### ISSUE TITLE
Error in storing the certificate in a PFX file using a password that also comes from the key-vault.

### ISSUE THREAD

**Issue by arefinsami** [MicrosoftDocs/vsts-docs#4114]
Powershell throws error if you store the certificate in a PFX file using a password that also comes from the key-vault.
For example, the following code doesn't work. Is there a workaround?

$password = $(PFX_PASSWORD)
$protectedCertificateBytes = $certCollection.Export([System.Security.Cryptography.X509Certificates.X509ContentType]::Pkcs12, $password)
$pfxPath = $(Agent.TempDirectory)\MyCert.PFX
[System.IO.File]::WriteAllBytes($pfxPath, $protectedCertificateBytes)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69ff8e50-4187-3622-1beb-155f006af5f5
* Version Independent ID: bc56fa96-bded-95f8-39a4-a9e5242db1bf
* Content: [Azure Key Vault task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-key-vault?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-key-vault.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-key-vault.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by thomps23** [comment]
Please accept our apology for the significant delay in addressing this issue.

It looks like you're working through an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
