### ISSUE TITLE
Is there a way to send a download link of published artifacts into Slack?

### ISSUE THREAD

**Issue by gazeing** [MicrosoftDocs/vsts-docs#4115]
Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by thomps23** [comment]
@gazeing Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
