### ISSUE TITLE
Branch cleanup?

### ISSUE THREAD

**Issue by spivonious** [MicrosoftDocs/vsts-docs#4124]
How long do you keep release branches in the repo? I could see it getting pretty messy after a year or two.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1235ec4-e7e9-b0c2-8f1f-ee9682175a05
* Version Independent ID: a473750a-fbb6-4eed-e0e6-34e8a5009507
* Content: [Release Flow - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/devops-at-microsoft/release-flow#feedback)
* Content Source: [https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fdevops-at-microsoft%2frelease-flow.md&version=GBlive&_a=contents](https://mseng.visualstudio.com/DefaultCollection/TechnicalContent/_git/devops-learn-pr?path=%2fdocs%2fdevops-at-microsoft%2frelease-flow.md&version=GBlive&_a=contents)
* Product: **devops**
* Technology: **devops-learn**
* Git Login: **samgu**
* Microsoft Alias: **ethomson**

**Comment by alainvezina** [comment]
Yes  im also super interested in that

**Comment by tgdane** [comment]
Also interested! An idea I had for our programme is to only keep a certain number (e.g. 2) of release branches alive to allow bug fixing. However, we would keep all artifacts of old release branches in the Azure Artifact storage, which would mean we are able to redploy an old version for whatever reason if necessary even though the branch has been killed. There is also the option to git tag the last commit in the release branches. If I remember correctly, you can delete the git branch, but the tag is still in the list of git tags, allowing you to checkout that commit even though the branch no longer exists.

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
