### ISSUE TITLE
Provide YAML as template in devops?

### ISSUE THREAD

**Issue by Spagoot420** [MicrosoftDocs/vsts-docs#4148]
If there is a standard procedure for buildpipelines regarding flask apps on azure, why isn't there a template available in dev ops?

There is one for ASP.NET and Java web apps on azure...

Also it is very infuriating that when choosing any other git, the build process is automated, but when i choose devops i have to define it myself? :/

For github and bitbucket it is literally 5 clicks but for devops it is *this*

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eefdcb17-b1e5-141c-aef8-36795c9983af
* Version Independent ID: 007ebfcf-12bf-755c-858b-540d0fc59f96
* Content: [Build and deploy Python web apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/python-webapp?view=azure-devops)
* Content Source: [docs/pipelines/languages/python-webapp.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/python-webapp.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
