### ISSUE TITLE
Current iteration during build

### ISSUE THREAD

**Issue by phatcher** [MicrosoftDocs/vsts-docs#4163]
Is there a way of knowing the name of current iteration during the build? The @CurrentIteration macro doesn't work, at the moment I have to update the value manually the build definition for each sprint.

Could be something like System.TeamProjectIteration/CurrentIteration

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by miham-aib** [comment]
Hi, I've created a feature request on DeveloperCommunity about it, please vote for it and hopefully it'll get implemented. 
Link: https://developercommunity.visualstudio.com/idea/560221/making-the-team-project-iteration-number-available.html

**Comment by phatcher** [comment]
Thanks

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
