### ISSUE TITLE
Variable groups, Library. Miss history tracking

### ISSUE THREAD

**Issue by kristelaune** [MicrosoftDocs/vsts-docs#4168]
Hi
I am working with TFS build and release. Trying to use Libray, variable groups for all Releases and Builds.
But I would like to see the history for the Library. Important for the configuration management. Will this soon be avalable?

**Comment by WilliamAntonRohm** [comment]
@kristelaune -- Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
