### ISSUE TITLE
Custom labels for release badges

### ISSUE THREAD

**Issue by ibruynin** [MicrosoftDocs/vsts-docs#4191]
Is it possible to customize badges for releases?
In build badges, adding ?Label=MyLabel replaces "Azure Pipelines" with "MyLabel" in the badge
In releases this does not seem to work and it only shows "deployment", where "staging" and "production" would be more effective.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63234ade-28cc-02fc-a319-42e3491da601
* Version Independent ID: 7ccbfe96-d61e-8bf2-de22-61150d648abd
* Content: [Release pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/?view=azure-devops)
* Content Source: [docs/pipelines/release/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/index.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by mattyweb** [comment]
it would also be helpful to have the option of showing a release name or build name somehow

**Comment by raiyanalam** [comment]
@ibruynin: Agreed. I will add 'allowing labels in badges' to our backlog.
@mattyweb: We've looked into showing additional data with badges like release name, deployment branch, environment deployed to etc, however this just doesn't scale with badges. I would recommend you to add this suggestion in our [dev community forum](https://developercommunity.visualstudio.com/spaces/21/index.html) so that others can vote on it and we can prioritize the exact information that needs to be bubbled up and explore ways in which it can be done.

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
