### ISSUE TITLE
Cannot edit the "Code is checked in" notification

### ISSUE THREAD

**Issue by Simone000** [MicrosoftDocs/vsts-docs#4196]
After settings the global rule "Code is checked in" =&gt; send email to "Project Collection Valid Users", that option is grayed out and cannot be disabled

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2fdc7bf-dd88-5f39-cfaf-77dca428990e
* Version Independent ID: c939066c-c671-7f50-3ba3-9916b0f4cd4c
* Content: [Manage personal notification settings - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/notifications/howto-manage-personal-notifications?view=azure-devops#feedback)
* Content Source: [docs/notifications/howto-manage-personal-notifications.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/notifications/howto-manage-personal-notifications.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @Simone000, thanks for reaching out. I'm looking into this and we'll be in touch. Have a great day!

**Comment by chcomley** [comment]
Hi @Simone000, Following up on this, I'm hoping you found a solution at this point. If you are still having issues, I believe you may need technical help, rather than a doc update. Go [here](https://visualstudio.microsoft.com/vs/support/#talktous), and then select **Technical Support**. Best of luck to you!
