### ISSUE TITLE
IP Address Changing

### ISSUE THREAD

**Issue by fhack2** [MicrosoftDocs/vsts-docs#4197]
This is the second time I've gone to do a dry-run test and there is a new IP to add. 
13.86.39.123 and 52.158.209.56
It would be nice if there was a tool that can run to let you know which IPs are not working or working by region.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fa0ebd3-8437-8508-5a8d-462186fcce80
* Version Independent ID: efe892fe-387e-0a61-fe7d-33d2ac99dfa9
* Content: [Migration import from Azure DevOps Server to Azure DevOps Services - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/migrate/migration-import?utm_source=ms&utm_medium=guide&utm_campaign=vstsdataimportguide&view=azure-devops&viewFallbackFrom=vsts#feedback)
* Content Source: [docs/migrate/migration-import.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/migrate/migration-import.md)
* Product: **devops**
* Technology: **devops-learn**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
