### ISSUE TITLE
Code Coverage Badge

### ISSUE THREAD

**Issue by borgmanJeremy** [MicrosoftDocs/vsts-docs#4201]
Is there a way to link to a code coverage badge like there is a way to link to the build status badge? I have used this in Travis CI before but can't figure out how to set it up here.

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
