### ISSUE TITLE
Code Coverage report in a new tab

### ISSUE THREAD

**Issue by TestUser20191** [MicrosoftDocs/vsts-docs#4210]
Hi, 
When I use the *Visual test code* task in the pipeline with *code coverage enabled*, it is currently generating a *.coverage* file. Would it be possible to provide *.xml* file so that we could avoid the step of converting the .coverage to .xml(As xml is the default format provided by so many other providers). This can then be used in report generator to view the code coverage report in the code coverage tab?

If we could avoid ReportGenerator as well, it would be a really good feature. 

**Things to consider**: There could be multiple test solutions in a project and code coverage should consider all the tests which are existing as a different project.

**Comment by thomps23** [comment]
This looks like a potential gap in the documentation- is there a specific topic you're referencing?

If you'd like to get your feature idea in the right place, you can submit it [here](https://developercommunity.visualstudio.com/content/idea/post.html?space=21)

**Comment by TestUser20191** [comment]
@thomps23 when we use the visual studio task with code coverage enabled, for the .net projects to be specific - for unit tests written using mstest2, it will only generate the code coverage report artifact ( which contains the file in  .coverage format). This coverage file cannot be used to publish the code coverage results and the report was not appearing in the code coverage tab.  Also report can only be generated using report generator task which require files to be in Cobertura or jococo format. 

To overcome this, I have now used opencover which generated the XML file in Cobertura format. This file is then used in the report generator to generate the report. The output file from report generator is used to published to generate the code coverage results in the code coverage tab.


It would be nice if we could get code coverage report generated automatically or alternatively if you could provide Cobertura format files which we can  use in report generator. 
There is a document : https://docs.microsoft.com/en-us/azure/devops/pipelines/test/review-code-coverage-results?view=azure-devops

We could view the code coverage report from visual studio 2017 Enterprise  but the feature which we are looking for is to view the code coverage report from the code coverage tab. This will also remove the dependency on opencover and it is also tricky to get coverage report when there are units tests in different projects.

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
