### ISSUE TITLE
Linux and Azure Artifacts (Symbols Publishing)

### ISSUE THREAD

**Issue by RussellLMiller** [MicrosoftDocs/vsts-docs#4212]
Is there any update on getting the Publish Symbols working on Linux hosted agents publishing to Azure Artifacts? Looking around it doesn't seem like this is possible even with SourceLink

Currently when I run the Publish symbols on the Unbuntu hosted agent I get the following error "The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell."

**Comment by thomps23** [comment]
@RussellLMiller Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

**Comment by basickarl** [comment]
@thomps23 Would you care to link where the documentation is? All of the documentation assumes you are running Windows.
