### ISSUE TITLE
Agent pool offline

### ISSUE THREAD

**Issue by pattarika** [MicrosoftDocs/vsts-docs#4215]
Agent service status show running.   But when I queue the job on Azure pipeline, azure says an agent is offline.  The agent pool is enabled.
I'm on redhat 7.
Everytime, I still have to trigger ./run.sh manually.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23328b13-f079-ad21-5d7a-6c640f25391c
* Version Independent ID: 4a39889d-fa00-ae2b-aa43-f358631b7b1a
* Content: [Deploy a Azure Pipelines agent on Linux - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-linux?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/v2-linux.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/v2-linux.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by thomps23** [comment]
@pattarika Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

**Comment by andyjlewis** [comment]
@vtbassmatt is this issue a candidate to be moved to one of your open source repos?

**Comment by vtbassmatt** [comment]
I'd start with one of the support links @thomps23 mentioned above.

**Comment by Genysys** [comment]
Currently affected by this issue. Please advise.
