### ISSUE TITLE
Defaults very confusing if exclude specified

### ISSUE THREAD

**Issue by letmaik** [MicrosoftDocs/vsts-docs#4216]
```yaml
trigger:
  branches:
    exclude:
    - foo
```
Intuitively this should run on all branches except `foo`. In practice, it *never* runs, since probably now `include` is empty, since I defined `trigger` which removes all defaults. There should be nested defaults as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?tabs=yaml&view=azure-devops#ci-triggers)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@letmaik I just went back to the article and read it again and I agree it is confusing, since there is no include or exclude in the first example. Let me confirm the behavior and I will get this updated.

**Comment by steved0x** [comment]
@letmaik I have confirmed the behavior - when the defaults are overridden, only what is explicitly configured in the trigger is used. So your supposition was correct, since you only specified an exclude, no branches were included by default and so no CI builds. I am updating the documentation to make that more clear, and the Pipelines team has taken a work item to revisit the story for the defaults. I'm tagging this issue in my doc update and this issue should close when the docs fix is synced over to the public repo.

**Comment by letmaik** [comment]
Thanks, sounds good.
