### ISSUE TITLE
Save All Variable group as a json file

### ISSUE THREAD

**Issue by Planche95** [MicrosoftDocs/vsts-docs#4237]
Hi,

I'm playing with Azure Pipelines, and i would like to save all variables from specific, linked variable group to json file. Is this is possible?

**Comment by thomps23** [comment]
@Planche95 Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
