### ISSUE TITLE
How can I search the reference of a property

### ISSUE THREAD

**Issue by w371987114** [MicrosoftDocs/vsts-docs#4238]
if I have this c# code ,how to find `studentA.Name="shiney";`
```c#
Public Class Student
{
    Public int Age{get;set;}
    Public string Name {get;set;}
}
Public Class Teacher
{
    Public int Age{get;set;}
    Public string Name {get;set;}
}
Class Program
{
     static void Main(string[] args)
    {
        var studentA=new Student();
        studentA.Name="shiney";//how can I search this line source code
        var teacherB=new Teacher();
        teacherB.Name="MS";//not contains this line 
    }
}
```
it means that I neet the features of  Find ALL Reference(F12) in visual studio

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 12512a47-a85e-736e-9045-3004b4459d95
* Version Independent ID: c7a4b27e-5b68-1e07-527c-cb357eb53b3b
* Content: [Use advanced code search options](https://docs.microsoft.com/zh-cn/azure/devops/project/search/advanced-code-search-syntax?view=azure-devops#feedback)
* Content Source: [docs/project/search/advanced-code-search-syntax.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/search/advanced-code-search-syntax.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by thomps23** [comment]
@w371987114 Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
