### ISSUE TITLE
why multi branch trigger PR,but the deployment can't know which source branch trigger it?

### ISSUE THREAD

**Issue by lc273734858** [MicrosoftDocs/vsts-docs#425]
why multi branch trigger PR,but the deployment can't know which source branch trigger it?
I need diffrent branch deploy to diffrent env!! 

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 0fa5a83c-70fd-6925-a8c8-256b21c21a2e
* Version Independent ID: 75f4a136-7245-7878-2953-6b68272fe4ec
* Content: [Build definition options](https://docs.microsoft.com/zh-cn/vsts/build-release/concepts/definitions/build/options?view=vsts#feedback)
* Content Source: [docs/build-release/concepts/definitions/build/options.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/concepts/definitions/build/options.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **alewis**

**Comment by alexhomer1** [comment]
Thank you for your feedback. The topic https://docs.microsoft.com/en-us/vsts/build-release/concepts/definitions/release/triggers?view=vsts#release-triggers shows how you can filter the CD release trigger on specific branches. You could create a separate release definition for each set of branches applicable to specific environments, so that only those for the updated branch will be triggered.
