### ISSUE TITLE
Can't see global retention policies for Azure pipelines

### ISSUE THREAD

**Issue by gpj1** [MicrosoftDocs/vsts-docs#4250]
Though I am not an administrator of my Azure DevOps organisation I expected to view global retention policies of my org at https://dev.azure.com/{your_organization}/_admin/_buildQueue as mentioned in this documentation. But this URL shows current build queue and no where on the screen I can see retention details. And also, I could not find any option related to this in left navigation bar of org settings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43a285f9-738d-9f76-4de0-a4c4ecf6f5f5
* Version Independent ID: 9581a043-4873-bf0a-138f-85f6a61ae950
* Content: [Build and release retention policies - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/policies/retention?view=azure-devops#feedback)
* Content Source: [docs/pipelines/policies/retention.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/policies/retention.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by hintbw** [comment]
Agreed - this is unclear and I'm being asked about this. I know I can get to it at a project level at this url https://dev.azure.com/{your_organization}/teamproject>/_settings/settings but not at the organizational level.

**Comment by ltrzesniewski** [comment]
Also, the *minimum number of builds* option is missing from the `_settings/settings` page, and I see no way to specify a minimum number of builds to retain.

I noticed this issue because the status badge of some of my less active projects started to show *"never built"*: ![status](https://pbs.twimg.com/media/D_BI-eFXUAA7Z6c.png)

The screen in the following screenshot:

![screen](https://docs.microsoft.com/en-us/azure/devops/pipelines/policies/_img/define-git-retention-policies.png?view=azure-devops)

is nowhere to be found in the UI.

**Comment by jbeesonnuva** [comment]
Really would like the minimum number of builds setting back

**Comment by chasewilson** [comment]
@gpj1, Thank you for the feedback. I've update the documentation and you should see it live within the next 24 hours. As of right now you can no longer change global retention policies. Only at the project level. Functionality is in development to retain a minimum number of builds. if you have any more feedback, feel free to create a new issue :)
