### ISSUE TITLE
Semantics of Build.SourceBranchName extremely weird

### ISSUE THREAD

**Issue by letmaik** [MicrosoftDocs/vsts-docs#4259]
The example says:
&gt; In refs/heads/feature/tools this value is `tools`.

Who on earth would want that? To me this makes the SourceBranchName variable useless. It should be set to "feature/tools" in this case, and not the last component. That would make it consistent with other CI providers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#build-variables)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by MSFT-Chris-Barrett** [comment]
@letmaik, I'm also not sure how `$(Build.SourceBranchName)` might be used.  It seems to just be the filename/leaf node of the ref, instead of the branch name.

I don't know what your use-case is for wanting the branch name.  Personally, I'm finding myself in a detached HEAD state on the latest commit in the branch being checked out.  So to re-attach, I'm doing this: `git symbolic-ref HEAD "$(Build.SourceBranch)"`.  Since symbolic-ref takes the refs/heads/<branch-name> format, this will sort of "checkout" the branch being used in the build.

**Comment by juliakm** [comment]
It looks like the documentation here is accurate but that you have a feature request for a variable that would output `feature/tools`.  You can reach out to the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html), which is monitored by the product team, to share your idea for how to improve the product!

**Comment by letmaik** [comment]
@juliakm Are you saying we just wasted half a year without any action on this and now I have to start the reporting process again somewhere else? Oh well... I think I'll switch to GitHub Actions anyway going forward. Their community is much more organised and responsive :/

**Comment by MSFT-Chris-Barrett** [comment]
@juliakm, sorry about the negative response above.  I agree the documentation's example is definitely accurate.  The variable name just feels a bit misleading, since the "branch name" in git would be "feature/tools".

Looks like this issue is known, after finding this at the developer community page you linked to: https://developercommunity.visualstudio.com/content/problem/307522/sourcebranchname-variable-does-not-include-full-br.html
It sounds like the plan is to introduce a new variable that has the git branch name, but there's no ETA.  At least as of 2019-05-14.

**Comment by wtgodbe** [comment]
@juliakm is there any plan to implement the feature request from https://developercommunity.visualstudio.com/content/problem/307522/sourcebranchname-variable-does-not-include-full-br.html? This is a problem for me as well & requires an ugly workaround: https://github.com/dotnet/aspnetcore/pull/42131
