### ISSUE TITLE
Error AZP_URL

### ISSUE THREAD

**Issue by jhonalexander0809** [MicrosoftDocs/vsts-docs#4272]
I have an error, do not lift the container
and when I start the start.sh file, I get an error in the variable AZP_URL.
this is my url

https://dev.azure.com/nombreColeccion/

**Comment by thomps23** [comment]
@jhonalexander0809 Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
