### ISSUE TITLE
Secret variable name unknown at design time

### ISSUE THREAD

**Issue by arkiaconsulting** [MicrosoftDocs/vsts-docs#4284]
I have a use case where one of my secret variable name can only be known at runtime (depends on the result of a terraform command). I need to use the content of that variable in a subsequent task, but as secret variables are not available in inline scripts, I'm facing a bottleneck.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 450ac349-5c33-6cdf-1ecd-6eb989a00334
* Version Independent ID: a7119c1a-59b2-3081-a241-e93aa0d6b4b9
* Content: [Bash task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/bash?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/bash.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/bash.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by thomps23** [comment]
@arkiaconsulting Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
