### ISSUE TITLE
Commenting to github

### ISSUE THREAD

**Issue by holiber** [MicrosoftDocs/vsts-docs#4294]
Hi. I need to manage GitHub checks status and write comments to PR from my pipeline. Can I fetch my Github token into the pipeline to make API requests to github? Or maybe there is another way to do this? Thanks

**Comment by thomps23** [comment]
@holiber Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
