### ISSUE TITLE
The documentation is out of date. There is no longer any option to prevent the Source Label from being deleted when the build is deleted.

### ISSUE THREAD

**Issue by dammejed** [MicrosoftDocs/vsts-docs#4300]
This section: https://docs.microsoft.com/en-us/azure/devops/pipelines/policies/retention?view=azure-devops#what-parts-of-the-build-get-deleted
Mentions that it's possible to configure what parts of the build will be deleted (and is even shown in a screenshot). That configuration is no longer possible.

I'd like the tags to remain in my repository even when builds are deleted. Is my only option for that to modify the build to create the tag as one of the tasks?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43a285f9-738d-9f76-4de0-a4c4ecf6f5f5
* Version Independent ID: 9581a043-4873-bf0a-138f-85f6a61ae950
* Content: [Build and release retention policies - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/policies/retention?view=azure-devops#what-parts-of-the-build-get-deleted)
* Content Source: [docs/pipelines/policies/retention.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/policies/retention.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by chasewilson** [comment]
@dammejed, Thanks for the feedback and I'm sorry for the slow response. The functionality you mention is no longer available in Azure DevOps. The documentation has been out of date but I have updated accordingly and you should see the new information within 24 hours

**Comment by StingyJack** [comment]
@chasewilson - the loss of this feature is not really acceptable as its how many of us tie our deployable artifact versions back to the source code that created them. Without those labels we cant properly hotfix production system. 

@dammejed - I had this problem when they "streamlined" the retention policy last year and deleted years of build history. It took about 5 months for me to get through to them via support. That was plenty of time for the off site backup to have expired as well. After the second month of waiting for support to get through to the product team I had to make this https://github.com/StingyJack/AzureDevOps-BuildRetainer . Its kind of a nuclear option because now there are thousands of builds retained we dont need to keep, but its the only thing that will stop them from wrecking my worklife by applying another bugged retention feature
