### ISSUE TITLE
yaml build error

### ISSUE THREAD

**Issue by juanren** [MicrosoftDocs/vsts-docs#4307]
hi, 
after I  update my yaml file , and run ,there is error message as following; please help, thanks!

Could not queue the build because there were validation errors or warnings. /azure-pipelines.yml: (Line: 36, Col: 1, Idx: 976) - (Line: 36, Col: 2, Idx: 977): While parsing a block mapping, did not find expected key.

this line has error: - task: CopyFiles@2
all my yaml file content is:
# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
# at the top of your YAML file 
# set some variables that you'll need when you deploy
variables:
  # the name of the service connection that you created above
  serviceConnectionToAzure: java-test-wal
  # the name of your web app here is the same one you used above
  # when you created the web app using the Azure CLI
  appName: rjfirsttest20190508

# ...
# ...
# add these as the last steps
# to deploy to your app service
- task: CopyFiles@2
  displayName: Copy Files
  inputs:
    SourceFolder: $(system.defaultworkingdirectory)/target/azure-functions/
    Contents: '**'
    TargetFolder: $(build.artifactstagingdirectory)   

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact
  inputs:
    PathtoPublish: $(build.artifactstagingdirectory)    

- task: AzureFunctionApp@1
  displayName: Azure Function App deploy
  inputs:
    azureSubscription: $(serviceConnectionToAzure)
    appType: functionApp
    appName: $(appName)
    package: $(build.artifactstagingdirectory)/javafunctions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43e576b8-a378-a985-33cb-8adb9d7d7957
* Version Independent ID: d1b99713-8e01-23d9-47b7-1a9b5c98d5ca
* Content: [Build and deploy to a Java web app on Linux - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/java-function?view=azure-devops)
* Content Source: [docs/pipelines/languages/java-function.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/java-function.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by thomps23** [comment]
@juanren Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

**Comment by andyjlewis** [comment]
@juanren can you verify that you followed all of the topic instructions? Also, double-check the indents in your YAML file; whitespace is part of the syntax.

**Comment by juanren** [comment]
after try again, I can build well. thanks!

**Comment by TiggySravan** [comment]
Trying to create the azure pipeline through the command line, the error I am facing is the pipeline is creating but it **Could not queue the build because there were validation errors or warnings**
configured my source code repository with the service connection and passing as an argument through CLI.
Help me with this. Attaching the error screenshot for further reference.
![Capture1](https://user-images.githubusercontent.com/44838166/82451442-4ae91e00-9aae-11ea-9e58-aef990165541.PNG)
