### ISSUE TITLE
Clone from Several Repository in the same Build

### ISSUE THREAD

**Issue by issamhouidi** [MicrosoftDocs/vsts-docs#4327]
Hello, 
We are trying to migrate from TFVC to the new Azure DevOps Git. We found a problem within mapping the workspace the same way we are doing before in our builds. Could you please give me a full documentation of how I can clone a multiple repo in the same  build ? 

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 800c5477-b39f-48e6-6f9c-aa7994b2ec2a
* Version Independent ID: db9e2e97-d44d-734e-6a6f-b01f60f01c95
* Content: [Options for Git repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/pipeline-options-for-git?view=azure-devops)
* Content Source: [docs/pipelines/repos/pipeline-options-for-git.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/repos/pipeline-options-for-git.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by thomps23** [comment]
@issamhouidi Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

**Comment by steved0x** [comment]
@issamhouidi I am about to publish an update to this topic:

https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops

That will include instructions for how to clone multiple Azure Repos Git repos into your pipeline, it will be live within the next few days. It should help you out.
