### ISSUE TITLE
Set a variable from Azure Function response for Release Gate

### ISSUE THREAD

**Issue by theandrewdodson** [MicrosoftDocs/vsts-docs#4331]
Is there a way to set a variable from the response from an Azure Function? I can define the success criteria but I need to access part of the output in a future step of the pipeline.

**Comment by thomps23** [comment]
@theandrewdodson Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
