### ISSUE TITLE
How to support themes in host dialog?

### ISSUE THREAD

**Issue by Bhsha** [MicrosoftDocs/vsts-docs#4338]
I tried adding SCSS file with following import @import "node_modules/azure-devops-ui/Core/_platformCommon.scss";
That does not work. Host container is using Azure-DevOps-UI components though.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f7f0126-0e00-ccfe-d1df-74201dc46a93
* Version Independent ID: 6abadf7d-8a1f-21f4-d6e6-efa5d9481182
* Content: [Modal Dialog](https://docs.microsoft.com/en-us/azure/devops/extend/develop/using-host-dialog?view=azure-devops)
* Content Source: [docs/extend/develop/using-host-dialog.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/using-host-dialog.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by thomps23** [comment]
@Bhsha Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
