### ISSUE TITLE
Add a Predefined Variables for Git Tags

### ISSUE THREAD

**Issue by RehanSaeed** [MicrosoftDocs/vsts-docs#4343]
If the build was started via a git tag, there should be a simple variable that tells you if the build was started via a git tag and another that retrieves the git tag name.

According to https://github.com/MicrosoftDocs/vsts-docs/issues/4258, you might be able to use `Build.SourceBranchName` but how can I tell if it's a branch name or a tag? Tags need their own dedicated variable.

AppVeyor provides `APPVEYOR_REPO_TAG` which is a boolean telling you if the build was started using a tag and `APPVEYOR_REPO_TAG_NAME` which gives you the tag name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by jmlane** [comment]
Until a predefined variable is available, you can use `Build.SourceBranch` and check for values beginning with `refs/tags/`, e.g. `refs/tags/v1.0.0`.

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
