### ISSUE TITLE
Can't  confiig agent

### ISSUE THREAD

**Issue by newhillchan** [MicrosoftDocs/vsts-docs#4351]
for time saving,I just copied the whole thing from another agent and start to config. but ./config.sh told me:
GPUNode4:/home/vsts-agent-linux$ ./config.sh
Cannot configure the agent because it is already configured. To reconfigure the agent, run 'config.cmd remove' or './config.sh remove' first.
GPUNode4:/home/vsts-agent-linux$ ./config.sh remove
Removing service
Failed: Removing service
Unconfigure service first according to https://www.visualstudio.com/en-us/docs/build/admin/agents/v2-linux

I went into a dead end. there is no svc.sh generated and how can I Unconfigure service?
Even I removed all the files and started from beginning again, the error still exists. Is there any way to config the agent by force ? I will check the agent list and make sure it is correct.

**Comment by thomps23** [comment]
@newhillchan Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
