### ISSUE TITLE
Document whether pipeline artifacts should work between hosted and private agents

### ISSUE THREAD

**Issue by timfish** [MicrosoftDocs/vsts-docs#4356]
Ref: https://developercommunity.visualstudio.com/content/problem/555009/should-pipeline-artifacts-work-between-hosted-and.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 861ce7a5-4fa4-55f1-2c97-46a9cc6a2f66
* Version Independent ID: bdf954b9-9bbe-8b34-b674-71ad8153519d
* Content: [Publish and consume Pipeline artifacts in builds - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/artifacts/pipeline-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/pipeline-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @alexmullans
* Microsoft Alias: **amullans**

**Comment by willsmythe** [comment]
This should work. Glad to see a devcom problem report was opened --- this is the right way to report problems.

For the docs ... I don't know that we need an explicit statement about this (since it should work), but we should probably say something about the required version of the [self-hosted] agent..

For context ... the logic for the pipeline artifact tasks ships in the agent itself (which is different from every other task), so communicating the minimum required agent version in the docs is important. I think the docs needs some statement about the minimum required agent version --- maybe in an FAQ section. Ideally it's not something that needs to be updated every time the version changes (won't be that often).

Btw, currently for Download Pipeline Artifact (V2) and Publish Pipeline Artifact (V1) the minimum agent version is `2.153.1` (see [task.json](https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/DownloadPipelineArtifactV2/task.json#L18)).
