### ISSUE TITLE
Can we restrict notifications for the workitem we followed

### ISSUE THREAD

**Issue by imdkanikamahajan** [MicrosoftDocs/vsts-docs#4397]
When we follow a TFS workitem, we get notifications whenever there is any change made in workitem. Can we have a way by which we can get notifications for followed workitems only when there is a change in workitem state.

**Comment by thomps23** [comment]
@imdkanikamahajan Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
