### ISSUE TITLE
Failed to install service when agent has a space in its name

### ISSUE THREAD

**Issue by dgonzalezp** [MicrosoftDocs/vsts-docs#4398]
Hello, I've installed a linux agent and I can see it in our DevOps Agent Pool, I named it "Celerik Agent", but when I try to start the agent as a service, the script creates a "file" 'vsts.agent.celerik.Celerik Agent.service' and its not recognized as a folder.

The service fails to start.
~/agent$ sudo ./svc.sh install
Creating launch agent in /etc/systemd/system/vsts.agent.celerik.Celerik Agent.service
Run as user: celerik
Run as uid: 1000
gid: 1000
chmod: cannot access '/etc/systemd/system/vsts.agent.celerik.Celerik': No such file or directory
chmod: cannot access 'Agent.service': No such file or directory
Failed: failed to set permissions on /etc/systemd/system/vsts.agent.celerik.Celerik Agent.service

(Mind the space between "Celerik Agent"). The "folder" is not created as a folder.

Workaround: Create agent with no spaces on its name.

Ubuntu 18.04

Thanks

**Comment by thomps23** [comment]
@dgonzalezp Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
