### ISSUE TITLE
Search by version

### ISSUE THREAD

**Issue by kanchm** [MicrosoftDocs/vsts-docs#4414]
Is it possible to search which feed has a particular version of the package? Something along the lines of:
`Microsoft.OData.Edm And version:7.6.0-beta`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4488541f-e00f-aa81-4731-9649800e2640
* Version Independent ID: 59b5b0cf-0d9f-c710-d9f5-e56a578f74f4
* Content: [advanced package search syntax](https://docs.microsoft.com/en-us/azure/devops/project/search/advanced-package-syntax?view=azure-devops)
* Content Source: [docs/project/search/advanced-package-syntax.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/search/advanced-package-syntax.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @KathrynEE
* Microsoft Alias: **sumallel**

**Comment by thomps23** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking your question:

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

**Comment by sandeepchads** [comment]
Currently you cannot search for packages using version. we are not indexing the version information. The intent is for users to find the package name and then traverse the version by getting into the package details. If you believe this is a feature that you would like to have in future releases then please consider creating a new feature request here:

https://developercommunity.visualstudio.com/search.html?f=&type=question+OR+problem+OR+idea&type=question+OR+problem+OR+idea&c=&redirect=search%2Fsearch&sort=relevance&q=package+search
