### ISSUE TITLE
Will YAML PR triggers also come to Azure Repos Git?

### ISSUE THREAD

**Issue by binaryunary** [MicrosoftDocs/vsts-docs#4416]
As the title says, will support for YAML PR triggers ever come to Azure Repos Git based repositories?

In https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#pr-triggers it says that this feature is currently available only for Github and Bitbucket repos. 

In my case I have a repository with multiple components/projects in it; and multiple respective build YAMLs. In those YAMLs I have already specified all the build path triggers, if necessary I can easily  update them or even set up an automated process to update them based on project dependency graph. However, having to keep essentially the same set of triggers in two places: one in build YAML and in branch policies is very error prone and painful to manage. 

Also, if I decide to make changes in the repo structure, I can't easily validate the changes in a PR because branch policies are static. However, if PR validation would happen based on updated (in the PR) build YAML it would easy to verify such structure changes before they are merged into the main branch.

**Comment by thomps23** [comment]
@andyjlewis Andy, has this level of support changed at all?

**Comment by steved0x** [comment]
Right now, PR triggers for Azure Repos Git are implemented using branch policies, as described [here](https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-policies?view=azure-devops#build-validation). When configuring a build validation using this branch policy, you select a Pipeline, but only the build portion of that pipeline is used, and if the selected pipeline has any other triggers specified (CI or scheduled) they won't be used in the scope of the build validation branch policy. In that case, the branch policy controls the trigger, and the pipeline controls the build.

`Also, if I decide to make changes in the repo structure, I can't easily validate the changes in a PR because branch policies are static. However, if PR validation would happen based on updated (in the PR) build YAML it would easy to verify such structure changes before they are merged into the main branch.`

These are valid concerns, I recommend that you file a feature request [here](https://developercommunity.visualstudio.com/spaces/21/index.html) and let the product team directly know. I would be happy to do it for you, but if it comes from a customer it carries more weight. You are not the only one with this suggestion (example: https://github.com/MicrosoftDocs/vsts-docs/issues/3891), and the more submissions/votes it gets, the better.

Thank you.
