### ISSUE TITLE
Not able to add new fields to user story

### ISSUE THREAD

**Issue by vinitgadre** [MicrosoftDocs/vsts-docs#4417]
Scenario: I had created a custom field with name"userstorystartdate' and then removed the field from user story. Now I want to re-create the field with a different field type but system is giving error Field already exists.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1d7885e-7aa6-1e0e-8f90-a7177a53b0d7
* Version Independent ID: 0494e296-574f-b226-5bfd-0193667ad40d
* Content: [Add a custom field to an inherited process - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/add-custom-field?view=azure-devops#feedback)
* Content Source: [docs/organizations/settings/work/add-custom-field.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/work/add-custom-field.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by thomps23** [comment]
Thanks for your question. It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.

You may also find short term help in the [Stack Overflow Azure DevOps community](https://stackoverflow.com/questions/tagged/azure-devops).
