### ISSUE TITLE
how to get conditional strings

### ISSUE THREAD

**Issue by StefanSchoof** [MicrosoftDocs/vsts-docs#4426]
I try to figure out how I can get an conditional string. I want to call a script in the test stage with `--dry-run` and in the production environment without this.
So I want something like
```
cmd ${{ if eq(parameters.environment, 'test') '--dry-run' else '' }}
```
But I was not able to find nothing in the documentation to help in such use case. Is this possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6724abea-bbdc-bf66-ed5e-3214fa6c3e66
* Version Independent ID: 4f8dab21-3f0e-da32-cc0e-1d85c13c0065
* Content: [Job and step templates - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#template-expressions)
* Content Source: [docs/pipelines/process/templates.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/templates.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by thomps23** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

**Comment by vtbassmatt** [comment]
Everything but the "else" section is supported and should work.
