### ISSUE TITLE
Consume from Vs Code

### ISSUE THREAD

**Issue by dcb99** [MicrosoftDocs/vsts-docs#4431]
How can an artifact be downloaded and used in VS Code? Why do the examples only show Visual Studio?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 899a78d6-9d08-7744-108d-10add2ba7e2c
* Version Independent ID: 6ab31e96-fed8-4335-ed81-b97663d8300f
* Content: [Consume NuGet packages in Visual Studio](https://docs.microsoft.com/en-us/azure/devops/artifacts/nuget/consume?view=azure-devops#feedback)
* Content Source: [docs/artifacts/nuget/consume.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/nuget/consume.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by thomps23** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
