### ISSUE TITLE
Using sub folder as artifact name

### ISSUE THREAD

**Issue by RezaRahmati** [MicrosoftDocs/vsts-docs#4439]
I have two publish artifact tasks, first one copy 1 file into `drop` (as artifact name), second one copy a folder into `drop/myfolder` (as artifact name). At the end of the build it shows two artifact but when you click it opens as one.
Also in release, it downloads the content of build twice (since it thinks there are two artifacts). 
My question is, Is this by design? if not how can I publish files into different folders under `drop`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b3f565b-88e4-88d6-a534-48ec21e6e3d8
* Version Independent ID: 9fca89ae-4a6e-a43a-2834-1a91ad44c256
* Content: [Publish Build Artifacts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-build-artifacts?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/publish-build-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/publish-build-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @DavidStaheli
* Microsoft Alias: **dastahel**

**Comment by thomps23** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

**Comment by Devqon** [comment]
@RezaRahmati how have you resolved this? I am having the exact same issue
