### ISSUE TITLE
How to list available package versions with the cli?

### ISSUE THREAD

**Issue by fgervais** [MicrosoftDocs/vsts-docs#4448]
How can azure cli be used to list available package version like we can get on the web interface?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77bcd39f-91ab-bb93-40fc-dd4fc5f2374f
* Version Independent ID: c228aece-669a-57d6-b3ed-d427586f8a61
* Content: [Publish and then download a Universal Package](https://docs.microsoft.com/en-us/azure/devops/artifacts/quickstarts/universal-packages?view=azure-devops&tabs=azuredevops)
* Content Source: [docs/artifacts/quickstarts/universal-packages.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/quickstarts/universal-packages.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by thomps23** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
