### ISSUE TITLE
Multiple pipelines in single yaml

### ISSUE THREAD

**Issue by piotr-napadlek** [MicrosoftDocs/vsts-docs#4472]
Hello,

either there is no such option and I would like to have it or I haven't seen it anywhere in the docs: is there an option to configure multiple pipelines in a single `azure-pipelines.yml` file? Use case: define several pipelines for branches, PRs, specific paths etc. and have VSTS automatically pick it up instead of manually clicking and importing them. I assume that a pipeline name and location option would be necessary for that.

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
