### ISSUE TITLE
How to uninstall SDK from $(Agent.ToolsDirectory) 

### ISSUE THREAD

**Issue by heng-liu** [MicrosoftDocs/vsts-docs#4483]
I run this task to install .NETCore SDK 3.0 for several times, with specifying $(Agent.ToolsDirectory) for the  installationPath.
Then I realize that $(Agent.ToolsDirectory) is shared by other pipelines and I don't want to pollute the agent environment, so I would like to uninstall it. But I 'm not sure if I  have access to remote into machine of agent pool, if not, how can I uninstall it? Thanks!

**Comment by thomps23** [comment]
@heng-liu Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
