### ISSUE TITLE
Set no tester on creation

### ISSUE THREAD

**Issue by SarahDurden** [MicrosoftDocs/vsts-docs#4487]
On creating a new test case, the Tester field is automatically set to the name of whoever created the card. How can this be changed to show that no testers have yet been assigned and the test case is waiting to be picked up by one of the team? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cf72265-156c-de8c-d729-ba7b3b90193d
* Version Independent ID: 1a0c7272-6d36-6036-06cf-5801b55e2f70
* Content: [Create manual tests - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/create-test-cases?view=azure-devops#feedback)
* Content Source: [docs/test/create-test-cases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/create-test-cases.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by thomps23** [comment]
@SarahDurden Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
