### ISSUE TITLE
Using Helm task with AKS RBAC enabled cluster

### ISSUE THREAD

**Issue by jjindrich** [MicrosoftDocs/vsts-docs#4488]
Hi, I'm trying to deploy kubernetes deployment with HELM to AKS cluster with RBAC. I'm getting from authorization error:  [command]/opt/hostedtoolcache/helm/2.14.1/x64/linux-amd64/helm upgrade --install --wait Release-6 /home/vsts/work/r1/a/_source/drop/jjwebapicore
2019-06-12T14:03:41.4227491Z To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code DGVD3U3MH to authenticate.
2019-06-12T14:03:41.4318876Z ##[error]To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code DGVD3U3MH to authenticate.
E0612 14:03:41.417976    3331 azure.go:127] Failed to acquire a token: acquiring a new fresh token: waiting for device code authentication to complete: autorest/adal/devicetoken: Error while retrieving OAuth token: Code Expired
Error: Get https://jjaks-jjmicroservices--82fb79-31999f04.hcp.westeurope.azmk8s.io:443/api/v1/namespaces/kube-system/pods?labelSelector=app%3Dhelm%2Cname%3Dtiller: acquiring a token for authorization header: acquiring a new fresh token: waiting for device code authentication to complete: autorest/adal/devicetoken: Error while retrieving OAuth token: Code Expired\

There is the question how to authorize to cluster.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc7eeb7f-4e6b-8fee-1d7f-582cfb018b02
* Version Independent ID: 00fb3082-1069-9060-012c-0b6d75ef120b
* Content: [Package and Deploy Helm Charts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/helm-deploy?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/helm-deploy.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/helm-deploy.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thomps23
* Microsoft Alias: **shasb**

**Comment by jjindrich** [comment]
Hi @thomps23, any progress or idea how to make it working?

**Comment by thomps23** [comment]
@andyjlewis Are you aware of any documentation, in our docset or another, that might help here?

**Comment by mprigge** [comment]
I ran into the same problem. I've at least temporarily worked around this by utilizing a Kubernetes Service Connection with a kube config that was generated by `az aks get-credentials` with the `--admin` flag set (instead of an Azure RM connection). The `--admin` flag will force it to use administrator credentials rather than user credentials which, if I understand this correctly, circumvents the interactive device auth workflow used for user credentials when azure ad user auth is configured. I'm not sure how that workflow could ever work in a headless / non-interactive fashion necessary for use in a build/release pipeline, but maybe there's a way. 

I'm by no means an expert here, so ymmv, but hopefully this will help in the short term.

**Comment by RaymsDev** [comment]
any solution ?

**Comment by shashankbarsin** [comment]
A task input has been introduced to use cluster admin credentials instead of the cluster user credentials. More details can be found in the [release notes](https://docs.microsoft.com/en-us/azure/devops/release-notes/2019/sprint-155-update#support-for-cluster-admin-credentials-in-helmdeploy-task) and this change should roll out soon to all accounts with Sprint 155 update
