### ISSUE TITLE
Azure pipeline - how to avoid checkout ?

### ISSUE THREAD

**Issue by krogold** [MicrosoftDocs/vsts-docs#4505]
Hello, 
I'm using a build in a pipeline and I specified clean : false and shallow fetch (1 level) as I want to gain performance, however each time I build after a source change, it seems that the whole repository is checked out, which is really long and not acceptable for my purpose. 
- did I miss an option ? 
- is it possible to disable checkout as I just want to launch tests without modifying them ?

thank you

Alexandre

**Comment by thomps23** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
