### ISSUE TITLE
How do you do a Git based code review without a pull request?

### ISSUE THREAD

**Issue by timcromarty** [MicrosoftDocs/vsts-docs#4511]
Description says: Are you using Git to share your code? If so, then use a pull request.

If you haven't made any changes but still want a review, or multiple pull request have been completed how can you do a code review?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8bb12a7-a20c-1dd5-bca0-4873f7ab9e36
* Version Independent ID: 360739fd-e98a-535f-9872-ed58ece28194
* Content: [Get your code reviewed with Visual Studio - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/tfvc/get-code-reviewed-vs?view=azure-devops#feedback)
* Content Source: [docs/repos/tfvc/get-code-reviewed-vs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/tfvc/get-code-reviewed-vs.md)
* Product: **devops**
* Technology: **devops-code-tfvc**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by thomps23** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
