### ISSUE TITLE
Publishing artifacts on a hosted linux agent

### ISSUE THREAD

**Issue by basickarl** [MicrosoftDocs/vsts-docs#4529]
Hi. The documentation assumes you're using a Windows agent. Where is the documentation and examples for us that use Linux agents?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b3f565b-88e4-88d6-a534-48ec21e6e3d8
* Version Independent ID: 9fca89ae-4a6e-a43a-2834-1a91ad44c256
* Content: [Publish Build Artifacts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-build-artifacts?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/publish-build-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/publish-build-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @DavidStaheli
* Microsoft Alias: **dastahel**

**Comment by WilliamAntonRohm** [comment]
@basickarl -- thank you for your question.  Please try [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) to see if there is additional information for you there.

@davidstaheli -- is this in your current plans?

**Comment by davidstaheli** [comment]
@basickarl thanks for pointing this out.  I updated the documentation for this and it should be live in a couple of days. However, it is now recommended to use the [Publish Pipeline Artifact](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-pipeline-artifact?view=azure-devops) task instead of "Public Build Artifacts".
