### ISSUE TITLE
Geared to teams not single programmers

### ISSUE THREAD

**Issue by edaymami** [MicrosoftDocs/vsts-docs#4551]
The article mentions "Even if you're just a single developer, version control helps you stay organized as you fix bugs and develop new features. " However for the single programmers, like me, that want to work from a local repository there seems to be no other mention than this sentence. A tutorial specifically geared to a local developer/programmer showing how to do without all of the "Push" / "Pull" complication of making the changes available to developers that don't exist, would be extremely helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbfd7c2a-8a23-3a15-2888-4170352eb260
* Version Independent ID: e1c83f61-657d-4ec3-aaff-54d736a7c1c2
* Content: [Azure Repos Git tutorial - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/gitworkflow?view=azure-devops#version-control-workflow)
* Content Source: [docs/repos/git/gitworkflow.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/gitworkflow.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@edaymami I know what you mean, I have been on projects where I was the only developer and going through distributed version control like this seems to add extra overhead without too much benefit.

You can do everything, just without the pushing and pulling, and keep everything local, but even if a developer is just on a team of one, pushing/pulling to/from a remote repo, Pull requests into that remote repo, and the rest can help out by:

* Keeping a backup copy of your source code apart from your local computer
* If you need to move to another computer for testing, you can easily clone the remote repo to that computer
* Pull requests are a good way to group up changes to support a new feature, and allow you to go back and review what was done to support a certain feature or release
* Branch policies and build validation can help make sure that changes don't break something else in the build (not as typical on smaller projects)

I don't have a lot of recent personal experience on single-team development combined with version control (last time I did was on Visual Source Safe, MFC, and Visual Studio 4 or 5?), but here are a couple of (external non-Microsoft) articles that I found that have some additional tips and workflow for the solo developer and Git

* https://softwareengineering.stackexchange.com/questions/114258/as-a-sole-developer-for-now-how-should-i-be-using-git
* https://medium.com/learn-git-today/single-branch-development-with-git-f72a052446cf

We don't have any content specifically geared toward a solo developer, but, except for the parts that specifically show how to share things with another person, the content should apply to developers on teams of 1 and up.

If you are doing local development with a local Git repo only, without pushing to a remote repo (whether it be GitHub, Azure Repos, etc...) then we do have some "Git server agnostic" content at [Learn Git](https://docs.microsoft.com/en-us/azure/devops/learn/git/what-is-version-control) but I don't think that is what you're asking.

We do tend to be more focused on teams since that is our internal workflow, but I've added a note to include info that is relevant to single-developer teams as well as larger teams.

Thanks,

Steve
