### ISSUE TITLE
Universal package push to local feed from behind firewall

### ISSUE THREAD

**Issue by roystonmc** [MicrosoftDocs/vsts-docs#4560]
We are currently experiencing an issue in our Build Pipeline where we attempt (and fail) to push a universal package to a local feed from a build agent with a proxy.  When the push is attempted, we get either a '403' or '407' error and the push fails.  Now could this issue be due to the incorrect or missing settings for the username/password on the proxy, or is there a specific set of IP addresses that need to be added to our white-list to permit the universal package to pushed properly to the local feed.  More information can be provided, and any assistance would be appreciated.

**Comment by WilliamAntonRohm** [comment]
@roystonmc -- Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
