### ISSUE TITLE
How to remove a pipeline from a channel

### ISSUE THREAD

**Issue by miles1302** [MicrosoftDocs/vsts-docs#4579]
Hi I can remove subscriptions easily, but there doesn't seem to be a way to remove a pipeline from a channel...

**Comment by msebolt** [comment]
@miles1302 Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. 

Here are a few options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 

Also, please refer to documentation on [Channels](https://docs.microsoft.com/en-us/azure/devops/pipelines/integrations/microsoft-teams?view=azure-devops).
