### ISSUE TITLE
How to consume secrets

### ISSUE THREAD

**Issue by dougbw** [MicrosoftDocs/vsts-docs#4582]
What is the recommended approach for consuming secrets? There doesn't appear to be a parameter for mapping secrets through to environment variables like you can with the bash/powershell tasks. I don't wan't to pass them through as arguments to the script.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1eeb2956-beca-447d-c9a6-a859f3cfc4bf
* Version Independent ID: 89f2a014-99bb-420d-265c-42515d30c80b
* Content: [Python Script task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/python-script?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/utility/python-script.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/python-script.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @brcrista
* Microsoft Alias: **brcrista**

**Comment by msebolt** [comment]
@dougbw Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. 

Here are a few options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

**Comment by brcrista** [comment]
@dougbw If you think this is a feature gap in the task, could you please open an issue at https://github.com/Microsoft/azure-pipelines-tasks/issues?
