### ISSUE TITLE
Unable to pass Json as Script Arguments to PowerShell Script

### ISSUE THREAD

**Issue by niragtibdewal** [MicrosoftDocs/vsts-docs#4598]
I have a requirement to pass JSON Param to the PowerShell script. My Environment variable is a JSON and passing it as Script Arguments (ex. -TenantConfiguration "$(TenantConfiguration)") but in Powershell instead of entire JSON it is passed only as "{" 

Looking for help to resolve this 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb215324-b1a0-93b5-5022-4bcc7da93bb7
* Version Independent ID: 9eb2977b-ac34-9d53-670e-04fa027bc8e4
* Content: [Azure PowerShell task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-powershell?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/deploy/azure-powershell.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-powershell.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment]
@niragtibdewal Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. 

Here are a few options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
