### ISSUE TITLE
Adding app to Teams puts it in General channel even if you specify another channel

### ISSUE THREAD

**Issue by mariusstrom** [MicrosoftDocs/vsts-docs#4599]
I've tried adding this app a few times now to my team's Teams engineering/chatops channel, but no matter what I do the app shows up in the General channel which is not useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9adc845-adee-a494-79b4-3466f51d3ec9
* Version Independent ID: 12445205-8acc-98e6-fe65-9508e0dccb5c
* Content: [Azure Pipelines with Microsoft Teams - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/integrations/microsoft-teams?view=azure-devops#feedback)
* Content Source: [docs/pipelines/integrations/microsoft-teams.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/integrations/microsoft-teams.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @atinb
* Microsoft Alias: **atinb**

**Comment by msebolt** [comment]
@mariusstrom It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. 

To make sure it gets in front of the right people, please [submit your Azure DevOps bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.

Additionally you may want to report this issue to [Microsoft Teams support](https://support.office.com/en-us/home/contact?contactUsExperienceEntryPointAssetId=S.HP.teams).

**Comment by atinb** [comment]
@mariusstrom I could be wrong, but my understanding is that apps are always added to Teams at a team level instead of channel level. Once added to a team, you can always use it within any channel within the team - just that the welcome message is shown in the General channel. Thanks!
