### ISSUE TITLE
search folder value when creating task group for release pipeline

### ISSUE THREAD

**Issue by tinuverma** [MicrosoftDocs/vsts-docs#4600]
I have created a task group for build pipeline. One of the steps in it is "Publish Build Artifacts" with path to publish as $(Build.ArtifactStagingDirectory) and "Artifact publish location" as "Azure Pipelines/TFS" (the other option being "A file share".
Once my build is successful, I want to "release". I created a new set of task group to first install NUnit Console runner, than Install NUnit3 Test adapter (both powershell scripts).
My next step is to run "Visual Studio Test Platform Installer" after which I want to run all my tests to make sure they are passing. In this step one of the required parameters is "Search Folder".
If I give it the value "$(System.DefaultWorkingDirectory)", it works fine. But it feels like I should be using a variable that's specific to the build and not system level.
Can someone please clarify what I should be using? Am I thinking right that the system level variable would be too low and I should be using something closer to the build artifacts? when I use Build.ArtifactStagingDirectory, it fails saying it could not find my test dlls.
Thanks

**Comment by msebolt** [comment]
@tinuverma Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. 

Here are a few options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
