### ISSUE TITLE
Combining coverage results from multiple jobs in Python (with pytest)

### ISSUE THREAD

**Issue by shoyer** [MicrosoftDocs/vsts-docs#4617]
I've setup my open source project to run CI with Azure Pipelines (see https://github.com/pydata/xarray/pull/3039), and am collecting code coverage following the example from the Azure pipelines docs on how to test Python apps.

This seems to work pretty well, but the code coverage statistics seem to only pick up a test results from a single job (at random). To get complete coverage for my project (e.g., for platform dependent code), I really need to aggregate coverage across all of the test jobs.

What's the right way to configure Azure to show this information?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ca42420-9324-1988-16bd-501be69e278d
* Version Independent ID: 400c0122-a0cc-bb52-b6cc-8aa93ff2c47a
* Content: [Build and test Python apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/python?view=azure-devops)
* Content Source: [docs/pipelines/languages/python.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/python.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thomps23
* Microsoft Alias: **dastahel**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
