### ISSUE TITLE
Can I use a variable in repositories:ref ?

### ISSUE THREAD

**Issue by MarkCBS** [MicrosoftDocs/vsts-docs#4620]
Using Azure DevOps Git repo
Two branches: master and feature/myfeature

In feature branch I am using:

resources:
  repositories:
    - repository: templates
      type: git
      name: MyProject/MySolution
      ref: refs/heads/feature/myfeature

In master branch:

resources:
  repositories:
    - repository: templates
      type: git
      name: MyProject/MySolution
      ref: refs/heads/master

I would like to use a variable for 'ref' so whichever branch is being used it always references itself.

The default is to reference 'refs/heads/master' so can't just omit this parameter.

I've tried using: 

ref: $(Build.SourceBranch)

But it doesn't work error: 

62638: "/azure-pipelines.yml: Could not get the latest source version for repository MySolution hosted on Azure Repos using ref refs/heads/$(Build.SourceBranch)."

Can we have some additional documentation for 'ref:' param to explain how variables can be used?

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
