### ISSUE TITLE
Different behaviour of app if selecting all repositories versus individually selecting repositories

### ISSUE THREAD

**Issue by mcollis2** [MicrosoftDocs/vsts-docs#4624]
Hi,

We have found that if we select repositories individually, we can add them to multiple Azure Devops Projects.  In our use case, lets say we have 50 repositories.  We want to connect 10 repositories with one project, 10 with another, and so on.  This appears to work for individually selecting repositories.  We can run through the connection wizard multiple times, selecting a different project each time.  However, we would ideally like to make all repositories available to all projects.  We thought this would be possible by selecting to allow access to all repositories, and then running through the wizard multiple times to authenticate with each azure devops project in turn.  However, this does not work - once all repositories are selected, it will only let us run through the wizard once to connect them to a single ADO project.  We have to uninstall and reinstall the app, and then select repositories individually to be able to connect it to multiple projects.  

Is this the intended behavior?

Thanks,

Matthew

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfba9a21-e0f9-4fc6-43fc-bfdc51af31d3
* Version Independent ID: d93c7852-ce63-a6d0-417a-45f8cf2fc522
* Content: [Build GitHub repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#github-app-authentication)
* Content Source: [docs/pipelines/repos/github.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/repos/github.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @DavidStaheli
* Microsoft Alias: **dastahel**

**Comment by WilliamAntonRohm** [comment]
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.

**Comment by harringj** [comment]
Hi, @WilliamAntonRohm -- I would argue that there is still an issue with the docs here, since they clearly state that "[o]nce the GitHub App is installed, pipelines can be created for the organization's repositories in different Azure DevOps organizations and projects" AND that "[a]s an alternative to installing the app for all repositories, repository admins can install it one at a time for individual repositories. This requires more work for admins, but has no advantage nor disadvantage": https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#create-pipelines-in-multiple-azure-devops-organizations-and-projects.

If people are finding that creating pipelines in multiple ADO projects isn't possible when installing the app for all repos -- I've noticed this as well -- and are wondering whether this is a bug, can you please provide a definitive statement that ADO should indeed work this way? If it should, but isn't, then I'll submit a bug. If it shouldn't be expected to work this way, would you please amend the docs to reflect this? Contrary to what the docs say, it seems like setting the app up manually for each repo carries a very big advantage if that approach allows you to create pipelines for your repos in multiple ADO projects. Thanks!
