### ISSUE TITLE
Feature question regarding iterations

### ISSUE THREAD

**Issue by erinhelf** [MicrosoftDocs/vsts-docs#4628]
It appears creating a work item that is a child of another automatically inherits the iteration of the parent. Is there anyway to avoid that and have it default blank, forcing the user to select the correct one?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa7a0948-ee09-8734-ed6e-bc45bd78ce01
* Version Independent ID: da9ac11c-958d-f5dd-efad-0c20c2d7cf2f
* Content: [Describes work item fields, attributes and how to list them - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/work-item-fields?view=azure-devops#feedback)
* Content Source: [docs/boards/work-items/work-item-fields.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/work-items/work-item-fields.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
