### ISSUE TITLE
Is there any way to create a private task (run it without publishing it so other people can see it)?

### ISSUE THREAD

**Issue by ekolis** [MicrosoftDocs/vsts-docs#4630]
I want to create a private task to do things that are specific to my business, so I don't want to have to publish it for other people to see. Is there any way to do this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44581f4a-93df-7507-3844-eadedf9a6cc4
* Version Independent ID: 33c7bcf0-1512-975f-5ef8-9f2a192a84ad
* Content: [Add a Build or Release Task](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops#feedback)
* Content Source: [docs/extend/develop/add-build-task.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/add-build-task.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
