### ISSUE TITLE
Custom the color of states in the built-in cumulative flow chart

### ISSUE THREAD

**Issue by BrightRan** [MicrosoftDocs/vsts-docs#4640]
It seems that we can't custom the color of states in the built-in cumulative flow chart.
Is this feature supported currently? Or do you have any other workaround?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5ed2e6c-e558-9297-9c38-7971e97a48f2
* Version Independent ID: ee4a588a-a4b0-4f13-15ff-bb0b30081ee3
* Content: [Cumulative flow charts - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/cumulative-flow?toc=%2fazure%2fdevops%2fboards%2fboards%2ftoc.json&%3bbc=%2fazure%2fdevops%2fboards%2fboards%2fbreadcrumb%2ftoc.json&view=azure-devops)
* Content Source: [docs/report/dashboards/cumulative-flow.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/dashboards/cumulative-flow.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@BrightRan Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation.

Here are a few options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 

Also you can [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.
