### ISSUE TITLE
How to manually trigger a stage?

### ISSUE THREAD

**Issue by poveilleux** [MicrosoftDocs/vsts-docs#4645]
Right now with release pipelines it is possible to re-deploy a stage if it fails. I have not seen any way to do that with YAML pipelines. How can I achieve that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4266f72c-c774-0046-4593-d01eb775d3c3
* Version Independent ID: f20827aa-a6c5-96a8-5969-e576ffbc2e38
* Content: [Stages in Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/stages?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/process/stages.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/stages.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by msebolt** [comment]
@poveilleux Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. 

Here are a few options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

**Comment by CasperJ** [comment]
Any news MS on how to do this in YAML?

**Comment by vijayma** [comment]
The ability to retry a failed stage in YAML pipelines is implemented, and it will be available in all orgs over the next 2-3 weeks.
