### ISSUE TITLE
Allow scripts to access OAuth token on multi-stage yaml pipelines

### ISSUE THREAD

**Issue by randyram-at-ms** [MicrosoftDocs/vsts-docs#4654]
I am trying out YAML multi-stage pipelines preview. I cannot find the setting for "Allow scripts to access OAuth token" anywhere in the UI. How do I enable this?

I'm happy to use the REST API to set this per this example: https://powershell.org/2019/04/azure-devops-enable-allow-scripts-to-access-the-oauth-token-using-powershell/

But that example is for a release definition and the waters are muddy around whether my multi-stage pipeline is a build or release definition.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by msebolt** [comment]
@randyram-at-ms Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. 

Here are a few options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
