### ISSUE TITLE
Possiblity of SQL Injection

### ISSUE THREAD

**Issue by kallam9** [MicrosoftDocs/vsts-docs#4658]
I am using Wiql Query in my C# application, to get projects under an organization. But i see a possiblity of SQL Injection Attacks due to using the SQL queries directly,Is there any other way to query the WIQL without using the SQL queries and  is the Wiql protected aganist SQL injection attacks.

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
