### ISSUE TITLE
Is there a way to add a new tab in the build summary to display an HTML file ?

### ISSUE THREAD

**Issue by kevinDespoulains** [MicrosoftDocs/vsts-docs#4659]
I need to display HTML content in a new tab in the build summary of an Azure DevOps pipeline. The HTML file is generated from a task of the pipeline. How to do that?

I have followed this guide (https://github.com/microsoft/vsts-extension-samples/tree/master/build-results-enhancer) which explains briefly how to build an extension that shows an HTML file content in a new tab but this HTML file is included in the extension and can't come from a build task.

Has anyone already done it?

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
