### ISSUE TITLE
Pushing NuGet packages to multiple Azure Artifact instances

### ISSUE THREAD

**Issue by kieronlanning** [MicrosoftDocs/vsts-docs#4660]
Is it possible to push resulting NuGet packages from a build into private NuGet (Azure Artifact) repositories outside of the building subscription?

Example is:

1. Build NuGet packages
2. Publish to internal (current sub) Azure Artifact instance.
3. Publish to client (external sub/ subs) Azure Artifact instance(s).

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a few options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
