### ISSUE TITLE
How to pass parameter during agent configuration?

### ISSUE THREAD

**Issue by vmilevski** [MicrosoftDocs/vsts-docs#4681]
I can't found where in azure portal I need to write this command
./config.cmd --proxyurl http://127.0.0.1:8888 --proxyusername "myuser" --proxypassword "mypass"

to pass  parameter during agent configuration. Is there yaml file (example will be nice) or some options page in azure portal or somewhere other. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e47a1942-09cb-f294-f1d3-09999645afb7
* Version Independent ID: 7b885f66-7165-ae4f-d35f-3cffe84cce28
* Content: [Run the agent behind a web proxy - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/proxy?view=azure-devops&tabs=windows#feedback)
* Content Source: [docs/pipelines/agents/proxy.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/proxy.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
