### ISSUE TITLE
Using Dockerfile as basis for container jobs

### ISSUE THREAD

**Issue by casparjespersen** [MicrosoftDocs/vsts-docs#4693]
Is it possible to specify a Dockerfile as basis for a container job, instead of a reference to an already created container? This is possible with Jenkins, and a much appreciated feature.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3339a2e0-be29-1363-f588-b231d4472c02
* Version Independent ID: 72dd11a3-704d-d0fd-6dfa-cf49f3352de3
* Content: [Container Jobs in Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/process/container-phases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/container-phases.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thomps23
* Microsoft Alias: **macoope**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

**Comment by j-channings** [comment]
I also have this question and can't find a way to do it in the documentation.

If it's possible, an example would be useful as I guess it's a fairly common use case. For instance, you might want to use the same Dockerfile for your local dev (e.g. with the VS Code Remote extensions).

**Comment by ledettwy** [comment]
Not directly, but you could probably add host-targeted `docker build` steps beforehand. For complete control, you can issue your own `docker run` / `docker exec` commands as well.

**Comment by hommeabeil** [comment]
@LisannaAtHome This is really painful to do since you need to account for the UID and GID and bind mount a bunch of file. This would be really useful feature since if you need more package to build a project you need to do 2 PRs and 2 pipelines. The first one update the Dockerfile and publish the new image. Then you need to wait for it complete and update your yaml with the new image reference.
