### ISSUE TITLE
Providing custom vmImage for hosted agents?

### ISSUE THREAD

**Issue by casparjespersen** [MicrosoftDocs/vsts-docs#4694]
I have a job in which I want the host machine to have BLAS and LAPACK installed. I see three solutions:
1. Install BLAS/LAPACK at each build (this is time-consuming)
2. Install BLAS/LAPACK to a Docker container, and use this as base for job (this gives other compatability issues, however)
3. Install BLAS/LAPACK to the vmImage that is basis for the job

Therefore: **Is it possible to extend/modify/specify the vmImage for hosted agents?**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99af681d-41ad-da15-0b72-08b5cd5a11ac
* Version Independent ID: 2fa0df36-a437-8cbb-b019-b49b31b1e116
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/hosted.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @joebourneMS
* Microsoft Alias: **jobourne**

**Comment by RandomNoun7** [comment]
I would also be interested it knowing if it's possible to upload custom VM Images to be used as build workers. It would help me avoid running build workers on internal infrastructure.

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
