### ISSUE TITLE
What do you do with own workitem type

### ISSUE THREAD

**Issue by DalpheSDC** [MicrosoftDocs/vsts-docs#4696]
We have an issue where we have our own workitem type in Azure devops Server where it give an exception "Unable to get property 'workItemTypeNames' of undefined or null reference"
 This happens for both lead and cycle time.

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: ea9310f2-b131-3903-0c15-5bbebbd95959
* Version Independent ID: 22486f35-4e75-8dd4-7c97-cd3c6e8245fc
* Content: [Cumulative flow guidance - Azure DevOps](https://docs.microsoft.com/da-dk/azure/devops/report/dashboards/cumulative-flow-cycle-lead-time-guidance?view=azure-devops)
* Content Source: [docs/report/dashboards/cumulative-flow-cycle-lead-time-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/dashboards/cumulative-flow-cycle-lead-time-guidance.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
