### ISSUE TITLE
TFS 2017 - Reset code reviewer votes when there are new changes.

### ISSUE THREAD

**Issue by pfedotovsky** [MicrosoftDocs/vsts-docs#470]
Is this feature available on TFS 2017 "Reset code reviewer votes when there are new changes". I don't see this option in TFS Version 15.117.27024.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cd986e0-608c-1d8c-6faf-ecdb12e10bc6
* Version Independent ID: d60c996e-187e-dd6b-7f3a-dd056a1603f4
* Content: [Protect your Git branches with policies](https://docs.microsoft.com/en-us/vsts/git/branch-policies?view=vsts#feedback)
* Content Source: [docs/git/branch-policies.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/git/branch-policies.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@pfedotovsky That feature was introduced in TFS 2018, [here](https://docs.microsoft.com/en-us/visualstudio/releasenotes/tfs2018-relnotes#reset-votes-on-pushnew-iteration). You can see all of the VSTS release notes [here](https://docs.microsoft.com/en-us/vsts/release-notes/index) and see which versions of TFS contain those features. I'm working on updating this article so that when you select a version of TFS from the version selector, only supported features for that version are displayed. That should be live within the week. Thank you.
