### ISSUE TITLE
How do I get the value of a capability in a YAML build?

### ISSUE THREAD

**Issue by lengau** [MicrosoftDocs/vsts-docs#4706]
A lot of capabilities have the name of an application in the key box and its location in the value box. How can you get that value in a YAML build?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7541ee6-d2bb-84c0-fead-1aa8ee7d2372
* Version Independent ID: 5cf7c51e-37e1-6c67-e6c6-80262c4eb662
* Content: [Demands - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/demands?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/process/demands.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/demands.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
