### ISSUE TITLE
Azure Repos git commit data into Power BI ?

### ISSUE THREAD

**Issue by bbarman4u** [MicrosoftDocs/vsts-docs#4708]
Will it support importing and visualizing the git commit data also other than just work items ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ea920e3-9644-ae0c-120d-db9e899ee192
* Version Independent ID: 452bf06e-28f4-7815-72b3-16a4c2086e47
* Content: [Connect to Power BI Data Connector - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/powerbi/data-connector-connect?view=azure-devops#feedback)
* Content Source: [docs/report/powerbi/data-connector-connect.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/powerbi/data-connector-connect.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
