### ISSUE TITLE
Svn to Git Migration

### ISSUE THREAD

**Issue by sree12345789** [MicrosoftDocs/vsts-docs#4722]
in windows i am using tortoise svn then i am creating git bash in windows and also i am open github account also but i have small error in this file tortoise svn users how we are checking on that
and windows can you please provide a command

**Comment by msebolt** [comment]
@sree12345789 Thank you for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation.

Please post the specific error to one of the following:

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
