### ISSUE TITLE
Copy/paste rows in a test case

### ISSUE THREAD

**Issue by SarahDurden** [MicrosoftDocs/vsts-docs#4727]
In Excel, you can highlight a single row or multiple rows of cells to be copied and pasted elsewhere. Can this be done in a devops test case?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 985ecee3-e347-43bb-5ed2-08ce3aee7621
* Version Independent ID: fdf465fc-a9e1-0198-2e8c-e859c74252b3
* Content: [FAQs and problem solutions - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/reference-qa?view=azure-devops#feedback)
* Content Source: [docs/test/reference-qa.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/reference-qa.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by msebolt** [comment]
@SarahDurden This sounds like a product question as opposed to a documentation issue.

Since the product teams aren’t always watching this repository, to make sure it gets in front of them for triage, please [submit your question]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.

**Comment by hollowdrutt** [comment]
@SarahDurden You can do that when using the test case grid view https://docs.microsoft.com/en-us/azure/devops/test/reference-qa?view=azure-devops
