### ISSUE TITLE
Can you please provide an example on how to pass arguments to the Powershell script?

### ISSUE THREAD

**Issue by olaeld** [MicrosoftDocs/vsts-docs#4740]
How are the arguments specified? How does the ps1 file make use of the arguments?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e444c2-69c6-4d71-6fd0-94d0f4097d3a
* Version Independent ID: 3a727833-1cc3-c2fb-c5b3-22605eee2721
* Content: [PowerShell task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/utility/powershell.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/powershell.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by msebolt** [comment]
@olaeld Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. 

Here are a few options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

**Comment by tyler-hogsett-microsoft** [comment]
I agree with olaeld, here. There is no documentation on passing arguments to a ps1 file. The parameter is briefly explained, but it is not clear from documentation how to actually use it, and any working implementation would really just be based on guessing and assuming/hoping that observed behavior is intended functionality, which is far form ideal for production deployments.

Please provide an example snippet on usage of the "arguments" parameter.

**Comment by timendez** [comment]
I agree, an example in the documentation would be nice.
