### ISSUE TITLE
Pull Request approval permission 

### ISSUE THREAD

**Issue by ankitthakkar23** [MicrosoftDocs/vsts-docs#4741]
I want to add developer and project lead where developer can create pull request only but do not allow to approve it, where project lead can only approve that Pull request. How can I do this in Azure DevOps ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68686c2b-c69a-d9e4-3e21-a46d231b649c
* Version Independent ID: 049659da-1772-3166-f909-4feeb8a97730
* Content: [What are all the default permissions and groups? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/permissions?view=azure-devops#project-level-permissions)
* Content Source: [docs/organizations/security/permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/permissions.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@ankitthakkar23 Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. 

Here are a few options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
