### ISSUE TITLE
Querying multiple tags?

### ISSUE THREAD

**Issue by sorikorik** [MicrosoftDocs/vsts-docs#4750]
Hello,

When querying tags, I am left with two options: Contain, Does not Contain.

Question 1 - My team currently have different variation of "blocks" for tags, IE, "Blocked," "Blocked by Dependencies," "Blocked by [Team]," "Blocked by Dependency," "Blocked by Design," etc.

I'd like to have it where I'd like to pull all tags that contains the word "Blocked" instead of having to create multiple clauses, such as Tags Contains "Blocked" OR Tags Contains "Blocked by Dependencies" etc. 

Question 2 - I'd like to include multiple tags within one clause, such as Tags Contains "Tag1" , "Tag2" , "Tag3" instead of creating 3 different clauses.

Are these possible? Thanks.

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

**Comment by peklein** [comment]
@WilliamAntonRohm, I don't think that's ana answer to @sorikorik's question. Is there documentation on how to handle his scenario? I have the same question, but the best answer I can find is to use multiple rows in the query and Or operators to join the Tags criteria. That seems broken since I can use an In cluase for State or any number of other fields and that allows me to select multiple States in a single query parameter, grouped with commas which indicates an Or clause. Is there documentation on how to do that with Tags?

**Comment by WilliamAntonRohm** [comment]
@peklein -- thank you for your follow-up.  Please consider the resources in my initial comment.

@steved0x -- does such a feature exist, and if so where is it documented?  If not, @peklein, add this feature suggestion here:
- [Developer Community](https://developercommunity.visualstudio.com/search?space=21)
