### ISSUE TITLE
Add examples of printing predefined variables

### ISSUE THREAD

**Issue by MakotoE** [MicrosoftDocs/vsts-docs#4751]
I wasn't aware at all that Build.SourceBranch is stored in `$env:BUILD_SOURCEBRANCH` for Powershell. I think it would greatly improve this page if there was a YAML snippet at the top of the page showing examples of printing a predefined variable for each script language, like this:

```
jobs:
  steps:
  - powershell: |
      echo $env:BUILD_SOURCEBRANCH
  - bash: |
      ...
```

Currently, one will have to read every sentence in 
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops in order to figure out this confusing naming scheme.

Related to #4231.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by juliakm** [comment]
Thanks for flagging this. This is a tricky one because we have a lot of detailed instructions on how to work with variables, including how to specify variables for different scripting languages on the [variables concept page](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#set-variables-in-pipeline). We're going to keep this page as is for now but will keep an eye on the issue queue to see if there are other people in the future who bring this up as a problem.
