### ISSUE TITLE
No YAML build on Generic Git Repo

### ISSUE THREAD

**Issue by yasseralhayali** [MicrosoftDocs/vsts-docs#4791]
It's not possible to have a YAML build pipeline with generic git repos.

**Comment by WilliamAntonRohm** [comment]
@yasseralhayali Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.  

Also, it looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider looking for information: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

**Comment by msebolt** [comment]
Please comment below if you'd like to have the issue re-opened.

#please-close
