### ISSUE TITLE
This document is not appearing properly.

### ISSUE THREAD

**Issue by bluebaroncanada** [MicrosoftDocs/vsts-docs#4794]
Some people cannot see this full document.  Some people can, though.  It's really weird.  The part that's missing is the part in `Authentication` after `PAT`.  All that stuff's gone for me.  The document source has it and one person on IRC can see it, but the rest can't.

https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/agents.md

https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops#authentication

**Comment by steved0x** [comment]
@bluebaroncanada On that page (which has had some updates so things may have changed since your report) there are several subsections of the Authenticate section that apply only to on-premises versions, and so if you have Azure DevOps Services selected in the upper left hand side, you won't see those sections, is it possible that might be what is happening? Please reactivate this issue (and provide a screenshot comparison showing the missing parts if possible) if that is not the correct explanation and I will report this to our build team to see if they can figure out the differences. Thank you!
![image](https://user-images.githubusercontent.com/1580889/63360745-ef320e80-c33c-11e9-8dd5-5cbc85382c13.png)
![image](https://user-images.githubusercontent.com/1580889/63360786-04a73880-c33d-11e9-8b46-768cef4e61ca.png)
