### ISSUE TITLE
Azure Repos currently does not support using SSH in repos with Git LFS tracked files.

### ISSUE THREAD

**Issue by LordGordonQ** [MicrosoftDocs/vsts-docs#4795]
As stated in limitations section: "Azure Repos currently does not support using SSH in repos with Git LFS tracked files".

There is a timeline to support Git LFS over SSH?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3d0afd1-bce9-b05e-ff1d-2914f63e2884
* Version Independent ID: 4b69aa48-977c-cf18-bd30-17185814c8e5
* Content: [Work with large files in your Git repo - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/manage-large-files?view=azure-devops#feedback)
* Content Source: [docs/repos/git/manage-large-files.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/manage-large-files.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
