### ISSUE TITLE
How do I use MSVC tools?

### ISSUE THREAD

**Issue by hacksoi** [MicrosoftDocs/vsts-docs#4798]
For example, on my machine I usually run the vcvars batch file so that I can use MSVC tools like CL and LINK. How do I use those tools on a Microsoft-hosted agent?

**Comment by msebolt** [comment]
@hacksoi Thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. 

Here are a few options where you might consider asking your question:​  

[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
[https://www.stackoverflow.com](https://www.stackoverflow.com) 
[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

Else if there's a document in particular this relates to, please reference it below.

**Comment by msebolt** [comment]
Please add documentation reference below and I can re-open this issue.
