### ISSUE TITLE
How to set acceptable exit codes?

### ISSUE THREAD

**Issue by neonrights** [MicrosoftDocs/vsts-docs#4804]
I was wondering how to set acceptable exit codes for scripts.  For example, if pytest runs 0 tests then it will exit with a code of 5 which I would like to be interpreted as a success.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8098f527-ebdf-60d5-3989-5228b7a207c1
* Version Independent ID: ce27c817-9599-00ef-5af2-3ac1dbad8dc6
* Content: [Build and Release Tasks in Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/tasks?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/process/tasks.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/tasks.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
