### ISSUE TITLE
For SAFe 4.6 - How do you handle ...

### ISSUE THREAD

**Issue by timroden** [MicrosoftDocs/vsts-docs#4816]
Epics at not only portfolio level, but also at solution and program level?
Capabilities at solution level?
Enablers at portfolio, solution and program levels?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c926cb3-ed15-3489-65f8-2a5c1fd129d4
* Version Independent ID: 1b441906-10f0-2ec0-d1aa-d3686ff94146
* Content: [Scaled Agile Framework - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/plans/scaled-agile-framework?view=azure-devops#feedback)
* Content Source: [docs/boards/plans/scaled-agile-framework.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/plans/scaled-agile-framework.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

**Comment by timroden** [comment]
Thanks for your reply.

>It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation
Didn’t see it as such. The documentation is on how to use Azure Devops to implement the SAFe framework but the documentation in my opinion could be improved by  expanding to cover Solution and Full Scale SAFe.

Tim
