### ISSUE TITLE
iOS Publishing Profile

### ISSUE THREAD

**Issue by MouthOfMadness** [MicrosoftDocs/vsts-docs#4823]
For a publishing profile, how do you create the DeviceID in the Apple store when you're using a hosted mac agent?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5891d09-bbcf-012e-483d-795eb4b469e5
* Version Independent ID: be1f16ef-ea88-ee8e-fa90-61b5228dc454
* Content: [Install Apple Provisioning Profile task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/install-apple-provisioning-profile?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/install-apple-provisioning-profile.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/install-apple-provisioning-profile.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @DavidStaheli
* Microsoft Alias: **dastahel**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

**Comment by MouthOfMadness** [comment]
Yeah, if only there were a work around that was documented for the hosted mac agents, the existing documentation just makes a lot of assumptions that you've got a mac.

**Comment by WilliamAntonRohm** [comment]
Thanks for the suggestion! The product teams aren’t always watching this repository, so to make sure it gets in front of them for triage, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
