### ISSUE TITLE
Preserve timestamps

### ISSUE THREAD

**Issue by ni-maxkoehler** [MicrosoftDocs/vsts-docs#4827]
Currently the files within the artifact zip file all contain the same timestamp.
Is there a way to preserve the timestamps using publish and download artifacts step?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 861ce7a5-4fa4-55f1-2c97-46a9cc6a2f66
* Version Independent ID: bdf954b9-9bbe-8b34-b674-71ad8153519d
* Content: [Publish and consume artifacts in pipelines - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/artifacts/pipeline-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/pipeline-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @alexmullans
* Microsoft Alias: **amullans**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
