### ISSUE TITLE
Interactive authentication dialog doesn't appear when using .net core

### ISSUE THREAD

**Issue by chris9263** [MicrosoftDocs/vsts-docs#4832]
I've been trying to get VssClientCredentials in a .net core console app with no luck. The interactive login window does not appear. On the other hand, If i run the same code and packages in a .net framework console app it works as expected and the login window appears. Any idea what the problem could be?

Console App running on .net core 2.2 also tried running core 2.0
Microsoft.VisualStudio.Services.InteractiveClient: Tried with both 16.143.2 and 16.153.0-preview
 
Here is the code i am trying:

static async Task Main(string[] args)
        {
            Uri _uri = new Uri("https://dev.azure.com/{orgName}");

            VssClientCredentials creds = new VssClientCredentials(new WindowsCredential(true),
                                                 new VssFederatedCredential(true),
                                                 CredentialPromptType.PromptIfNeeded);

            VssConnection vssConnection = new VssConnection(_uri, creds);
            await vssConnection.ConnectAsync();
            
        }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 413163f0-28c3-a2a7-d626-fcb81bcb2257
* Version Independent ID: 57c127da-2b1e-d29e-9abb-a3c258762ccf
* Content: [.NET Client Libraries for Azure DevOps Services (and TFS)](https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/dotnet-client-libraries?view=azure-devops#feedback)
* Content Source: [docs/integrate/concepts/dotnet-client-libraries.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/concepts/dotnet-client-libraries.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

**Comment by StingyJack** [comment]
For anyone finding this issue and wanting this to work as well, here is the "[feature request](https://developercommunity.visualstudio.com/t/interactive-authentication-for-api-client-via-brow/702258)"

Though, I am at a loss to understand how something being broken by a newer version of a platform component requires a new feature to get fixed rather than a defect/bug report.
