### ISSUE TITLE
What python versions are available?

### ISSUE THREAD

**Issue by ikamensh** [MicrosoftDocs/vsts-docs#4834]
I am interested in what choice of python versions do I have, and can I run pipeline on minor versions, e.g. 3.7.3 vs 3.7.2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ca42420-9324-1988-16bd-501be69e278d
* Version Independent ID: 400c0122-a0cc-bb52-b6cc-8aa93ff2c47a
* Content: [Build and test Python apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/python?view=azure-devops#feedback)
* Content Source: [docs/pipelines/languages/python.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/languages/python.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thomps23
* Microsoft Alias: **dastahel**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

**Comment by WilliamAntonRohm** [comment]
@ikamensh -- Ilya, please see https://github.com/MicrosoftDocs/vsts-docs/issues/5516#issuecomment-529515334
