### ISSUE TITLE
Modifying manifests

### ISSUE THREAD

**Issue by sadedil** [MicrosoftDocs/vsts-docs#4838]
Is there any way to modifying K8s manifest files during execute pipeline? For example, I want to override LoadBalancerIP of a K8s Service or replicas of a K8s deployment manifest according to environment?

This is my sample scenario:
=================

Manifest files in the source repo:
manifests/deploy.yaml
manifests/service.yaml

For the Test environment:
----------------------------
Change LoadBalancerIp to 'x.x.x.x' in manifests/service.yaml
Change replicas to '1' in manifests/deploy.yaml

For the QA environment:
----------------------------
Change LoadBalancerIp to 'y.y.y.y' in manifests/service.yaml
Change replicas to '3' in manifests/deploy.yaml

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcbb25d1-a706-e8fc-61e4-d5b86aa54f47
* Version Independent ID: 5634d9dd-fd92-761c-24b8-5e32ed6c6c35
* Content: [Deploy to Kubernetes task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/kubernetes?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/kubernetes.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/kubernetes.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbarsin
* Microsoft Alias: **shasb**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
