### ISSUE TITLE
Access to pipeline variables

### ISSUE THREAD

**Issue by jonhoo** [MicrosoftDocs/vsts-docs#4841]
I want to write a pipeline definition (specifically, a reusable template) that will _not_ run a job if a given variable has not been set for the pipeline. Something along the lines of:
```
condition: and(succeeded(), ne('', ${{ parameters.token }}))
```
where the user may pass in:
```
parameters:
  token: $(TOKEN_SECRET)
```
where `TOKEN_SECRET` here is a variable that is defined in the web UI as a _secret_ pipeline variable. If the secret variable is available (i.e., we are not in testing a PR, or secrets in PRs is enabled), then the job should run. Otherwise, it should not.

Currently, this does not work. I get the error
```
Unrecognized value: '$'.
```
when trying to parse the condition. I have also tried
```
parameters:
  token: variables['TOKEN_SECRET']
```
but this value appears to always be empty, even when secrets are supposed to be available.

I suspect that the reason for all of this is that variables are not generally available at the "planning stage", or whatever it is called, only at runtime. However, it seems like an exception should be possible for pipeline-defined variables?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f151218-9a11-0078-e038-f96198a76143
* Version Independent ID: 09c4d032-62f3-d97c-79d7-6fbfd89910e9
* Content: [Conditions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/process/conditions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/conditions.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by cowboyhackr** [comment]
Same issue.

**Comment by jonhoo** [comment]
For what it's worth, I ended up using [this unfortunate workaround](https://github.com/jonhoo/rusty-pipes/blob/7355feae87c32bb28ded7fdcf46167e89ff86587/azure/coverage.yml#L10-L25).

**Comment by msebolt** [comment]
@jonhoo Thank you for the feedback.

Secrets are covered in https://docs.microsoft.com/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#secret-variables.

I'll take a look at adding a note or work-around.

**Comment by jonhoo** [comment]
@msebolt I saw that page, but as far as I can tell it does not address any of the points from my original post? If it does, could you please point me at the relevant text?

**Comment by msebolt** [comment]
Sorry for the delay on this.

@jonhoo I was only referring to the documentation that would state exceptions to using secrets.

Assigning to author.

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
