### ISSUE TITLE
Access to stage information

### ISSUE THREAD

**Issue by jonhoo** [MicrosoftDocs/vsts-docs#4842]
Is there a way to get access to per-stage information, like the name of the current stage?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

**Comment by jonhoo** [comment]
No, I believe this specifically is something that should be documented in the build variables section if it is possible.

**Comment by NenoLoje** [comment]
@jonhoo, I think you are looking for `$(System.StageName)` and `$(System.StageDisplayName)`.

**Comment by NenoLoje** [comment]
Added #5393 to get those documented.
