### ISSUE TITLE
Creator role not mentioned

### ISSUE THREAD

**Issue by unnity** [MicrosoftDocs/vsts-docs#4855]
On Azure DevOps instance, at the project scope we can also add members with creator role who then can create and view agent pools, but cannot manage or use them. Please add to the documentation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4409a9cb-8448-edd6-da0a-243e5601aa3e
* Version Independent ID: ec15f71a-a76d-c3f9-1d31-832f92183ef4
* Content: [Agents pools - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/pools-queues?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/pools-queues.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/pools-queues.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@unnity  Thank you for the feedback.

The **Creator** role you describe is already mentioned [here](https://docs.microsoft.com/en-us/azure/devops/organizations/security/about-security-roles?view=azure-devops), though you are correct in stating that this role is not available from the **Agent pools** tab.

Since this non-document related I'm closing the issue.  Please direct all product issues to the [Azure DevOps forum](https://developercommunity.visualstudio.com/spaces/21/index.html).
