### ISSUE TITLE
Add "az rest"

### ISSUE THREAD

**Issue by algattik** [MicrosoftDocs/vsts-docs#4860]
Could we add documentation about using the new "rest" module in Azure CLI, for example, the following call works:
```
az rest --resource '499b84ac-1321-427f-aa17-267ca6975798' --method GET --uri 'https://dev.azure.com/&lt;myorg&gt;/_apis/projects?api-version=2.0'
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 294772ce-58a0-bb83-8927-3e69beca39df
* Version Independent ID: d9c4a4b3-3abf-d738-369e-fff8532e9dd9
* Content: [Guidance for authentication](https://docs.microsoft.com/en-us/azure/devops/integrate/get-started/authentication/authentication-guidance?view=azure-devops#feedback)
* Content Source: [docs/integrate/get-started/authentication/authentication-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/get-started/authentication/authentication-guidance.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @algattik, Thanks for your request. I've created a user story to capture updating this doc and will keep you posted. Thanks again!

**Comment by chcomley** [comment]
Hi @algattik, Here's a link to reference materials for `az rest`. I believe this may be the only product documentation on it. This reference is missing long-summary information, which might have some of the details that you're looking for. In order to get that, you'll need to install the CLI and run `az rest -h` for the full helpfile. Hope this helps! Please let me know if you have any questions and thanks for your feedback!
