### ISSUE TITLE
Using Build.ArtifactStagingDirectory in a Matrix Build also using PublishPipelineArtifact

### ISSUE THREAD

**Issue by RehanSaeed** [MicrosoftDocs/vsts-docs#4868]
My NuGet packages are in the `/home/vsts/work/1/Windows` folder where `Windows` is a matrix name (I'm running the build section of my pipeline on Windows, Mac and Linux but want to publish the NuGet packages from my Windows build).

The docs talk about using the `$(Build.ArtifactStagingDirectory)/*.nupkg` path to pass to `NuGetCommand@2`. However, this points to the `/home/vsts/work/1/a` folder.

Is the `$(Build.ArtifactStagingDirectory)` variable wrong because I'm using a matrix build? Is it wrong because I'm using the `PublishPipelineArtifact@0` task to publish my .nupkg's? Here [is a link to my azure-pipelines.yml file](https://github.com/RehanSaeed/Schema.NET/blob/master/azure-pipelines.yml).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11ed58a1-5819-f3a4-c674-dafcdbd56fbc
* Version Independent ID: d68aca4d-3fd3-1864-09f5-6060295e0399
* Content: [Publishing to NuGet feeds - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/nuget?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/artifacts/nuget.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/nuget.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thomps23
* Microsoft Alias: **amullans**

**Comment by WilliamAntonRohm** [comment]
Thanks for your questions. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your questions: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
