### ISSUE TITLE
Could you please elaborate on the buildContext

### ISSUE THREAD

**Issue by Lybecker** [MicrosoftDocs/vsts-docs#4878]
What is it? What is the default value: **? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9dbf88-7e55-d427-145e-d36b04fb197f
* Version Independent ID: a3f30c00-817c-9c05-7a57-3f2bf618821e
* Content: [Docker task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/build/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/docker.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thomps23
* Microsoft Alias: **shasb**

**Comment by yzorg** [comment]
I hit this today as well.  It is very common for buildContext to need to be set to non-default value.  

The default buildContext (the `Dockerfile` directory if empty) will fail for a Dockerfile generated by Visual Studio for C# project that references another project in the solution.  In this case you have to set buildContext to nearest shared parent folder, which is the buildContext used by Visual Studio when building locally.  For me, when VS runs `docker build` locally the dockerfile is the 1st argument and buildContext is last argument.

`docker build -f "c:\source\FooSln\FooProject\Dockerfile" ... "c:\source\FooSln"`

For many C# projects the buildContext should be set to the the path to the .sln file in your git repo.

My team has one project that references projects outside the solution folder.  In this case keep moving up until you reach a "common parent" folder.  For us this is the root of the git repository.

If this is covered in the dotnet core docs or Visual Studio Docker docs then a link to this topic in those docs might be helpful.

**Comment by shashankbarsin** [comment]
@Lybecker The docker build command builds Docker images from a Dockerfile and a “context”. A build’s context is the set of files located in the specified PATH or URL. The build process can refer to any of the files in the context. For example, your build can use a `COPY` instruction to reference a file in the context.

It's advised to author a .dockerignore file to filter out the files and folders that should not be taken into account in the build context. This way the build context only contains the files and folders it really needs. This will help reduce the size of the file sent to docker daemon during build.

@yzorg The default value is set based on the most common scenario associated with most users using the Docker task. The input exists so that this default value can be overridden for edge cases such as the one mentioned by you. About including links to documentation for specific languages and projects, we wanted to keep the documentation generic and language agnostic

**Comment by Lybecker** [comment]
I'm curious why this is not captured in the actual documentation in stead of this comment/github issue?
