### ISSUE TITLE
create a measure - get the minutes for changing the states

### ISSUE THREAD

**Issue by SimonaMargarint** [MicrosoftDocs/vsts-docs#4891]
https://docs.microsoft.com/en-us/azure/devops/report/powerbi/analytics-views-create?view=azure-devops

Hi team

I want to create a measure in PowerBi to show me the minutes of a workitem has been changed from a state to another.
For the moment i can only see by days.

is there a way to calculate the minutes - time stamps from moving from one sub-state to another?

Thanks
SImona

**Comment by WilliamAntonRohm** [comment]
@SimonaMargarint Thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  
[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
[https://www.stackoverflow.com](https://www.stackoverflow.com) 
[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 
As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
