### ISSUE TITLE
How can I use Visual Studio 2019 with Linux container?

### ISSUE THREAD

**Issue by WeihanLi** [MicrosoftDocs/vsts-docs#4894]
I wanna use windows to build a nuget package and there's some tests need redis, I'm trying to use a redis sidecar container to run the test, seemed can not use linux container by default. I'm using the microsoft hosted agent `windows-2019`,
got an error as follows:

```
no matching manifest for windows/amd64 10.0.17763 in the manifest list entries
latest: Pulling from library/redis
##[error]Docker pull failed with exit code 1
```

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 7d1c794c-d676-fc7e-758e-3464f16a1554
* Version Independent ID: 941de04a-2d34-ec82-8612-00e4070de673
* Content: [Service Containers - Azure Pipelines & TFS](https://docs.microsoft.com/zh-cn/azure/devops/pipelines/process/service-containers?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/service-containers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/service-containers.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @dakale
* Microsoft Alias: **dakale**

**Comment by WeihanLi** [comment]
Is therer a complete example for using service container?

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
