### ISSUE TITLE
Display in Dashboard

### ISSUE THREAD

**Issue by tphillips77** [MicrosoftDocs/vsts-docs#4907]
The chart that is displayed here, how can I have that display on a dashboard?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4914adf-b6bb-f209-d08e-88d35ff8ea78
* Version Independent ID: b00bc0d2-4eb7-d154-425c-48022ce41b4b
* Content: [Adjust work to fit sprint capacity - Azure Boards and TFS](https://docs.microsoft.com/en-us/azure/devops/boards/sprints/adjust-work?view=azure-devops#feedback)
* Content Source: [docs/boards/sprints/adjust-work.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/sprints/adjust-work.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
