### ISSUE TITLE
Build Pipeline issue with publishtests

### ISSUE THREAD

**Issue by josealania** [MicrosoftDocs/vsts-docs#4909]
Hello,

As you could see in the following image, line 599 says: ##[warning]No test results found to publish.

while if you see line 586 says: Test Run Successful.

Any hint for this issue?

![image](https://user-images.githubusercontent.com/52972855/61422195-45d8a280-a8d0-11e9-879e-26ea7429d333.png)

Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
