### ISSUE TITLE
How to change NDK version for Android.

### ISSUE THREAD

**Issue by lmylr** [MicrosoftDocs/vsts-docs#4912]
How to change NDK version for Android.

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
