### ISSUE TITLE
'Date' field?

### ISSUE THREAD

**Issue by Javerages** [MicrosoftDocs/vsts-docs#4913]
Hi, in my PowerBI analytics report there is a 'date' field. 
What does this represent? 
Am I correct to assume this is an interval measured state of a workitem?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dffb618e-12c7-e97d-f16d-f240003d7b97
* Version Independent ID: d51da12d-861d-c804-ba13-74f3a8769779
* Content: [Reportable fields reference - TFS](https://docs.microsoft.com/en-us/azure/devops/reference/xml/reportable-fields-reference?view=azure-devops#feedback)
* Content Source: [docs/reference/xml/reportable-fields-reference.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/reference/xml/reportable-fields-reference.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

**Comment by Javerages** [comment]
In the meanwhile I figured it out. Shouldn't there be documentation on this field?
