### ISSUE TITLE
Solution Filters

### ISSUE THREAD

**Issue by MatthewSteeples** [MicrosoftDocs/vsts-docs#4917]
Is it possible to build/load solutions based on a solution filter file (slnf) rather than a full solution?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f86c97-f534-50ad-bfb1-a2cf78c7af94
* Version Independent ID: acea40e3-512b-4d9a-9389-71b8b24327be
* Content: [Visual Studio Build build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/visual-studio-build?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/build/visual-studio-build.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/visual-studio-build.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

**Comment by marchy** [comment]
This IS a documentation issue?
Is this crucial feature used by monorepos supported or not on Azure Pipelines?

**Comment by WilliamAntonRohm** [comment]
@marchy -- Marcel, thank you for your follow-up.  Please consider this resource in addition to the ones mentioned above:
- [Azure DevOps Services](https://azure.microsoft.com/support/devops/)
