### ISSUE TITLE
User can commit with any name

### ISSUE THREAD

**Issue by athakkar9033** [MicrosoftDocs/vsts-docs#4931]
I have cloned Azure DevOps Repository in local directory. I have installed Tortoise git. Now I have edited username as 'xxxxxxxxxx' in tortoise git's global config file. I have edited any code file and commit&push it from tortoise git. When I see commit in Azure DevOps Repository user name is 'xxxxxxxxxx'. How Can I solve this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e47a3960-103f-0974-47db-9c90e2523447
* Version Independent ID: efaf6896-060c-2021-0c8b-5a95b1896eed
* Content: [Author names in Git - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/git-names?view=azure-devops#feedback)
* Content Source: [docs/repos/git/git-names.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/git-names.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
