### ISSUE TITLE
How to pass version from build output to universal pkg?

### ISSUE THREAD

**Issue by justin-parus** [MicrosoftDocs/vsts-docs#4942]
For example, the build pipeline im using writes a file with the version. Can the custom version field take a file path from the build drop and read that value?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 405dfb6a-2f3d-1d74-2d28-d00be3bb069d
* Version Independent ID: d446b533-c215-6302-3df2-93b1ffd936df
* Content: [Publish and download Universal Packages in pipelines - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/universal-packages?toc=%2Fazure%2Fdevops%2Fartifacts%2Ftoc.json&view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/artifacts/universal-packages.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/universal-packages.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @alexmullans
* Microsoft Alias: **amullans**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
