### ISSUE TITLE
Configure pr trigger but failed for "GitHub Could not create service hooks subscription"

### ISSUE THREAD

**Issue by qyxxxigd** [MicrosoftDocs/vsts-docs#4976]
When I tried to configure the pr trigger for my release pipeline, I got the error "GitHub Could not create service hooks subscription Unable to configure a service on the selected GitHub repository. GitHub returned the error 'Resource not accessible by integration'." However, I have already set the personal access code in Azure DevOps which provides required Github permissions. How to deal with this problem?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cbb2877-5e10-4065-e3c6-7883e9df4b3c
* Version Independent ID: 58122a19-2258-3cf3-8335-74bb0dad892f
* Content: [Deploy pull request builds - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/deploy-pull-request-builds?view=azure-devops)
* Content Source: [docs/pipelines/release/deploy-pull-request-builds.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/deploy-pull-request-builds.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @raiyanalam
* Microsoft Alias: **moala**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
