### ISSUE TITLE
What variable should I use for finding the dacpac folder?

### ISSUE THREAD

**Issue by RubixRevenge** [MicrosoftDocs/vsts-docs#498]
What variable should I use for finding the dacpac folder? The "Visual Studio" build tool doesn't find the dacpac by dropdown, so it's always an iterative exercise to find where the dacpac actually is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Build variables](https://docs.microsoft.com/en-us/vsts/build-release/concepts/definitions/build/variables?view=vsts&tabs=batch)
* Content Source: [docs/build-release/concepts/definitions/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/concepts/definitions/build/variables.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **alewis**

**Comment by RubixRevenge** [comment]
I'm in the build process, using "Publish Build Artifacts".

There is a field called "Path to Publish". 

In the meantime, I think I found the correct variable -- `$(build.sourcesdirectory)` --  but I still had to fill in the rest of the path manually: `$(build.sourcesdirectory)/AltEdCertification/AltEdCertification.Database/bin/Release/AltEdCertification.Database.dacpac`

To me, `build.sourcesdirectory` was non-intuitive because I had to dig through the weeds to find it, and the default variable supplied by "Publish Build Artifacts" is `$(build.artifactstagingdirectory)`, which does not contain the dacpac file at all.

I still don't know if use of `build.sourcesdirectory` is the best approach. It would have been nice to be able to find this file by dropdown in `Path to Publish`, but that seems more of a developer task than a documentation task. As far as documentation is concerned, it would be really helpful if the method to find a dacpac file is clearly stated in an obvious place.

**Comment by vijayma** [comment]
Thanks for clarifying. The location of the dacpac file depends on your msbuild arguments (you might be using VS Build or MS Build task for this). You can either set the arguments to these tasks, or use "Copy files" task to make sure that your dacpac file in the artifact staging folder. For example, see the inputs to build/copy tasks when you create a new definition and select .Net desktop template or ASP.NET template.

Or, if you already know the location of the dacpac file relative to your source code folders, you can take help from the "..." next to the 'path to publish' input, and select that folder. You are right that you won't see the dacpac file in this case, since the file explorer you get here is from your version control system and not from your build output.

**Comment by RubixRevenge** [comment]
Use of the "Copy Files" task worked for me. I tried to attach screenshots, but the UI won't let me. ("Something went wrong and we can't process that file").  So I'll have to stick with verbal descriptions.

- Copy Files
-- Source Folder: [blank]
-- Contents: `**/*.dacpac`
-- Target Folder: `$(build.artifactstagingdirectory)`

- Publish Build Artifact
-- Path to Publish: `$(build.artifactstagingdirectory)/[path to dacpac as exists in source files]`

Build and deploy worked correctly.
