### ISSUE TITLE
My Organization side menu doesn't change

### ISSUE THREAD

**Issue by draco961** [MicrosoftDocs/vsts-docs#4985]
I have change the name of my organization so that work, I can access to it.

The problem, When I am at the root of Azure Dev Ops, on the left side nav, we can see all our organisation and the old organisation name with old url is still present.

**Comment by WilliamAntonRohm** [comment]
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here. 

Here are a couple of options where you can look for suggestions: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
