### ISSUE TITLE
Access method for both CI pipelines AND release pipelines?

### ISSUE THREAD

**Issue by GregDomzalski** [MicrosoftDocs/vsts-docs#4991]
> The Azure Pipelines GitHub App is the recommended authentication type for continuous integration pipelines. For release pipelines that are triggered by changes to a GitHub repository, use OAuth or personal access token authentication.

We're interested in using Azure Pipelines for both Continuous Integration and Release Pipelines based on our GitHub repositories. What is the recommended way to do this? Is using the GitHub app sufficient? Why is OAuth or PAT recommended for Release pipelines and not the GitHub app?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfba9a21-e0f9-4fc6-43fc-bfdc51af31d3
* Version Independent ID: d93c7852-ce63-a6d0-417a-45f8cf2fc522
* Content: [Build GitHub repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#where-to-install-the-github-app)
* Content Source: [docs/pipelines/repos/github.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/repos/github.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @DavidStaheli
* Microsoft Alias: **dastahel**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
