### ISSUE TITLE
Views and Complete graphs

### ISSUE THREAD

**Issue by jrdodds** [MicrosoftDocs/vsts-docs#4994]
How are views and Complete graphs expected to work together?

If I use a @Release view, then I need to promote all dependencies to the Release view including packages from an upstream source like NuGet.org.

If I have a version of a package in the Release view and start a new version in the Prerelease view but both versions share a common dependency, how can I have a complete graph in both the Release and Prerelease views?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a891e9b-bf26-ea09-1da3-ebe3e57b7e26
* Version Independent ID: bf53c51c-c1c1-1931-44ef-81433746e5ec
* Content: [Views on Azure DevOps Services feeds](https://docs.microsoft.com/en-us/azure/devops/artifacts/concepts/views?view=azure-devops-2019)
* Content Source: [docs/artifacts/concepts/views.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/concepts/views.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

**Comment by jrdodds** [comment]
The documentation should explain how views and complete graphs are used together.
