### ISSUE TITLE
Incorrect statement about Basic licenses able to create test plans

### ISSUE THREAD

**Issue by mirlenbrink** [MicrosoftDocs/vsts-docs#4997]
There is a note within the first section of the page that states "Note: Stakeholders cannot create or manage test plans. You must have at least Basic access."  This is not true, however, as you must have Basic + Test Plans access to create/manage test plans.

"**Note:** Stakeholders cannot create or manage test plans. You must have at least Basic access."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8e2cb79-709d-972b-6747-6d26c965fb2a
* Version Independent ID: d512ea69-a97a-e5ff-a804-6691c5dfe1e6
* Content: [Create test plans and suites - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/create-a-test-plan?view=azure-devops#feedback)
* Content Source: [docs/test/create-a-test-plan.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/create-a-test-plan.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
That doc has been updated to say that "Note: Stakeholders cannot create or manage test cases. You must have at least Basic access." since basic can create test cases, and basic + test to create test plans.

https://docs.microsoft.com/en-us/azure/devops/test/create-a-test-plan?view=azure-devops#access-level
