### ISSUE TITLE
No Documentation about icons

### ISSUE THREAD

**Issue by JGCreator** [MicrosoftDocs/vsts-docs#4998]
There is not documentation about the string value necessary for icons that are available to the controll.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 858abbbf-8855-9792-37a1-db36cd6559a4
* Version Independent ID: a66a1023-f365-b5ed-678f-634bb7c9b908
* Content: [Use the TreeView Control](https://docs.microsoft.com/en-us/azure/devops/extend/develop/ui-controls/treeviewo?view=azure-devops)
* Content Source: [docs/extend/develop/ui-controls/treeviewo.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/ui-controls/treeviewo.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Thanks for your feedback, @JGCreator. I've created a user story to capture this and will be in touch. Thanks again!

**Comment by chcomley** [comment]
Hi @JGCreator, Since this issue was created, there have been two links added to the article for more information. They are as follows: [API Reference](https://docs.microsoft.com/en-us/azure/devops/extend/reference/client/controls/tree?view=azure-devops) and [Azure DevOps Extension SDK](https://developer.microsoft.com/en-us/azure-devops/develop/extensions). Closing this issue, however If these don't help you, please do @mention me.
