### ISSUE TITLE
Condition based on path

### ISSUE THREAD

**Issue by ADringer** [MicrosoftDocs/vsts-docs#5006]
Is it possible to have a condition based on the paths, similar to `Trigger`? Within my pipeline, I only want to run a particular job if a certain folder has changed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f151218-9a11-0078-e038-f96198a76143
* Version Independent ID: 09c4d032-62f3-d97c-79d7-6fbfd89910e9
* Content: [Conditions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/conditions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/conditions.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by niheinba** [comment]
Very interested in this as well. I came here for exactly this question.

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

**Comment by Poltergeisen** [comment]
If it's a possibility wouldn't it be nice if it was documented?

**Comment by Poltergeisen** [comment]
Just wanted to add another 2 cents. The links you sent are for azure devops but I'm looking for TFS 2017 help with conditional builds based on paths for gated checkins. The first place I thought to look would be the documentation but it's not very apparent whether or not TFS 2017 supports this functionality.
