### ISSUE TITLE
Template Parameter Condition Example is Wrong

### ISSUE THREAD

**Issue by davidtom** [MicrosoftDocs/vsts-docs#5015]
The example given under "Use a template parameter as part of a condition" shows a template variable of `false` being compared to the string 'true' in the condition. This implies that strings are coerced to booleans, or vice versa. However, when I just ran a similar condition comparing `false` and 'false', the result was not equal and the step ran.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f151218-9a11-0078-e038-f96198a76143
* Version Independent ID: 09c4d032-62f3-d97c-79d7-6fbfd89910e9
* Content: [Conditions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/conditions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/conditions.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by juliakm** [comment]
@davidtom Sorry for the delay on this. It looks like the issue is that you do not need to have the single quotes. If  `doThing: false`:
This will be false:
`condition: and(succeeded(), eq('${{ parameters.doThing }}', true))`
This will be true:
`condition: and(succeeded(), eq('${{ parameters.doThing }}', false))`
