### ISSUE TITLE
Looking for an environment variable Agent.Status or something  similar

### ISSUE THREAD

**Issue by arroyc** [MicrosoftDocs/vsts-docs#5042]
Looking for Agent.Status or something like which will tell if an agent is enabled or offline/disabled

**Comment by nschonni** [comment]
How would a variable work, since you only see those if the agent is running/running a job?
This might be a related API https://docs.microsoft.com/en-us/rest/api/azure/devops/distributedtask/agentclouds/get?view=azure-devops-server-rest-5.0

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
