### ISSUE TITLE
Planned work items not showing in few iterations

### ISSUE THREAD

**Issue by abdullahfahmi1991** [MicrosoftDocs/vsts-docs#5057]
I'm having an issue where planned work items is not showing on Velocity charts if the work items are moved to next iterations due to incomplete in initial iterations. Is thia behaviour expected?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a948662-d534-bb71-a6b8-ce6d884b0ebb
* Version Independent ID: f065bef6-017a-2615-3292-4ca5787f8458
* Content: [Configure the Velocity widget based on Analytics data - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/team-velocity?view=azure-devops#feedback)
* Content Source: [docs/report/dashboards/team-velocity.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/dashboards/team-velocity.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
