### ISSUE TITLE
Video capture is inconsistent

### ISSUE THREAD

**Issue by igor-teresco** [MicrosoftDocs/vsts-docs#5066]
Hi,
I've setup VS Test task in pipeline with video capture as per this article and while I'm keeping RDP connection open, tests are running and videos are recorded nice.
Once I do place agent session in disconnected state on console with recommended tscon tool, tests are running but video records contain only desktop image. Length of videos is corresponding to test duration, however no visual changes beside mouse cursor changing shape from time to time.
Please advise were to seek for help with this issue :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c96ae1b3-ab4c-540e-c4ca-79075f55f202
* Version Independent ID: c7b3e395-c55e-51a1-0f7e-8f5fb0430ee8
* Content: [Configure for UI testing - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/ui-testing-considerations?view=azure-devops&tabs=nunit#capture-video)
* Content Source: [docs/pipelines/test/ui-testing-considerations.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/test/ui-testing-considerations.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @PBoraMSFT
* Microsoft Alias: **pbora**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

**Comment by ShreyasRmsft** [comment]
Please file the issue on https://github.com/microsoft/azure-pipelines-tasks/issues and tag it with Area: Test
