### ISSUE TITLE
Insufficient documentation for "Build reason"

### ISSUE THREAD

**Issue by gabog** [MicrosoftDocs/vsts-docs#5074]
Where can I find more details on how to use the "Build reason" field? 
The values in the dropdown don't help a lot, for example, what is "Batched continuous integration"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60bb57a0-57b6-f33c-40f0-44e2c83d124c
* Version Independent ID: c7df5fe8-17e2-43ac-d7db-d0a1eb5c40bc
* Content: [Supported event types for notifications subscriptions - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/notifications/oob-supported-event-types?view=azure-devops#feedback)
* Content Source: [docs/notifications/oob-supported-event-types.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/notifications/oob-supported-event-types.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
