### ISSUE TITLE
Service Hooks - Triggered on multiple repos but not all

### ISSUE THREAD

**Issue by jbburf** [MicrosoftDocs/vsts-docs#5079]
Hi,

Is there a way to trigger a hook on a number of repo's - not just a single repo or changes to all repos?

I'm setting up slack hooks to show notifications in channels for new PRs but our project has grown and we now have four distinct teams. Changing the notifications from any repo to repos associated with specific teams has now become a challenge without the ability to select multiple repos in the hook. Is this function hidden somewhere or on a roadmap for development?

Thanks in advance!

- Ben

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

**Comment by jbburf** [comment]
Thanks for the reply @WilliamAntonRohm, I was asking here since I didn't know if this was possible and I couldn't find it in the documentation. I'll open the same question in the other channel since it isn't supported per your response above.
