### ISSUE TITLE
bad source pattern in C++ example for Classic editor ?

### ISSUE THREAD

**Issue by nicos99** [MicrosoftDocs/vsts-docs#5098]
In § 'Example: Assemble C++ artifacts into one location and publish as an artifact' the Contents pattern in Classic editor ("/$(BuildConfiguration)//?(*.exe|*.dll|*.pdb)") is not the same as in YAML ("**/$(BuildConfiguration)/**/?(*.exe|*.dll|*.pdb)") --&gt; why?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7175ebdc-0bba-7e00-d113-036a5cffe5fa
* Version Independent ID: 149ab9f4-0b7d-97e7-6cf5-1b54fd04c63c
* Content: [Publish and consume build artifacts in builds - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/build-artifacts?view=azure-devops&tabs=classic)
* Content Source: [docs/pipelines/artifacts/build-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/build-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

**Comment by nicos99** [comment]
I've just edited the description because the were a display issue with '*' char
