### ISSUE TITLE
Output variables using YAML

### ISSUE THREAD

**Issue by cosminstirbu** [MicrosoftDocs/vsts-docs#5111]
Hi,

With the visual designer you can set the Reference name in the Output Variables section and then you'll be able to use the following variables:

reference_name.provisioningProfileUuid	
reference_name.provisioningProfileName	

It's not clear if these can be used with YAML.

Thanks,
Cosmin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5891d09-bbcf-012e-483d-795eb4b469e5
* Version Independent ID: be1f16ef-ea88-ee8e-fa90-61b5228dc454
* Content: [Install Apple Provisioning Profile task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/install-apple-provisioning-profile?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/install-apple-provisioning-profile.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/install-apple-provisioning-profile.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @DavidStaheli
* Microsoft Alias: **dastahel**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
