### ISSUE TITLE
Deployment group with one server

### ISSUE THREAD

**Issue by sweinstock** [MicrosoftDocs/vsts-docs#5127]
If I need to deploy to only one server (no database server, no multiple servers), does it make sense to use a deployment group or am I going about it the wrong way?

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
