### ISSUE TITLE
No way to update the state on original work item when updating the copy

### ISSUE THREAD

**Issue by theCorb1nator** [MicrosoftDocs/vsts-docs#5129]
Hi,

We are using this copy work item approach to work across projects. 

The situation is one of our clients has their own project on our Azure Devops Organisation in order to isolate their work items from our core development.

The current process is : 
* Their test team creates a work item on their project
* We create a copy of the work item into our core project and assign it a sprint

The problem is that when we update the state on the work item in our core project the movement does not reflect on the original work item in the isolated project. this looks to the test team as if there is no movement on items.

is there a way to achieve this without updating the state manually on both items?

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
