### ISSUE TITLE
How can I use an older version of ruby?

### ISSUE THREAD

**Issue by ChrisCAdsk** [MicrosoftDocs/vsts-docs#5136]
The documentation specifies &gt;= 2.4 in a comment, as a hint towards the supported versions of Ruby.
I have a case where I want to use Ruby 2.3.3 (x64), how can I install this version on a Microsoft hosted agent?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02568f8b-6928-c8f1-178a-79e4cb0d93e2
* Version Independent ID: 1107622c-4165-dcff-741a-279757b35323
* Content: [Use Ruby Version task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/use-ruby-version?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/tool/use-ruby-version.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/tool/use-ruby-version.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @DavidStaheli
* Microsoft Alias: **dastahel**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
