### ISSUE TITLE
Nothing that I run executes inside the container. https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops&tabs=yaml

### ISSUE THREAD

**Issue by tomingoglia** [MicrosoftDocs/vsts-docs#5139]
Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by WilliamAntonRohm** [comment]
@tomingoglia -- please provide more context around the general task.

**Comment by tomingoglia** [comment]
Hi @WilliamAntonRohm...sorry about the message above.

Below is the page to the docs:
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops&tabs=yaml

It says that you can run commands  inside the container. Would this be the same as docker exec ...?

So...for example, if we wanted to execute an ls or do a cp to copy files to the image. I can't seem to run any docker command or get anything to run in the context of the container that is running. The container does load as expected based on the logs.

Tom

**Comment by WilliamAntonRohm** [comment]
@tomingoglia -- Tom, thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
 
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
