### ISSUE TITLE
Multiple Conditions

### ISSUE THREAD

**Issue by Yonnatan** [MicrosoftDocs/vsts-docs#5145]
Is it possible to create a custom condition with multiple conditions? 
for example , run the task if source branch = A  or source branch = B ?

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
