### ISSUE TITLE
When should we create a new feed?

### ISSUE THREAD

**Issue by gojanpaolo** [MicrosoftDocs/vsts-docs#5155]
We are a team of around 10 developers. I'm not sure when we should create a new feed. I'm thinking a single feed for all our projects would be enough and is simple. What scenarios should we consider to create a new feed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3db27124-fabe-5ab3-0f2e-e866cabff257
* Version Independent ID: c64aad85-16eb-919a-aff1-34f350065019
* Content: [What are feeds?](https://docs.microsoft.com/en-us/azure/devops/artifacts/concepts/feeds?view=azure-devops)
* Content Source: [docs/artifacts/concepts/feeds.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/concepts/feeds.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by msebolt** [comment]
@gojanpaolo Thank you for the question.

Since the feed is a package located per web URL as opposed to file share, it may or may not make logical sense depending on what the team's network options are.

For instance, a feed would be recommended if or when networked file shares are unavailable or if the package needs to be publicly available.
