### ISSUE TITLE
How so skip stage if already deployed version is higher or based on other condition?

### ISSUE THREAD

**Issue by FixRM** [MicrosoftDocs/vsts-docs#5156]
Lets say we have multi-stage pipeline with continuous deployment. New release is continuously rolling out over stages/environments, but we found bug in previous version and need to rollout a fix immediately. Some of the environments are already upgraded to newer version, and some - not. Let's say database is affected so we cannot deploy hotfix release to this environments. How can we skip some stages/environments and continue normal rollout after that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4266f72c-c774-0046-4593-d01eb775d3c3
* Version Independent ID: f20827aa-a6c5-96a8-5969-e576ffbc2e38
* Content: [Stages in Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/stages?view=azure-devops&tabs=classic)
* Content Source: [docs/pipelines/process/stages.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/stages.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
