### ISSUE TITLE
What does "Authorize resources" do?

### ISSUE THREAD

**Issue by JoeBengalen** [MicrosoftDocs/vsts-docs#5157]
After getting the unauthorized error for a secure file I am offered to "Authorize resources". What does this actually mean? After clicking I do not see any changes in the "Security" panel of the secure file.
Can I see (and revoke) somewhere which pipelines are authorized for given secure file? If not it kinda defeats the purpose of the finer grained access control I guess. I might just as well enable "Authorize for use in all pipelines"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee4ec9d0-e0d5-4fb4-7c3e-b84abfa290c2
* Version Independent ID: 3e2b80d9-30e5-0c48-49f0-4fcdfedf5eee
* Content: [Resources - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops#feedback)
* Content Source: [docs/pipelines/process/resources.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/resources.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
