### ISSUE TITLE
What are the required permissions for user to edit Service hooks?

### ISSUE THREAD

**Issue by BrightRan** [MicrosoftDocs/vsts-docs#5167]
What are the required permissions for user to edit Service hooks?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 274c7cc8-3496-59a2-b9ca-43da778b1b62
* Version Independent ID: ae4f66ff-46a6-5b1c-365b-0d869d66cd93
* Content: [Service hooks consumers for Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/service-hooks/consumers?view=azure-devops)
* Content Source: [docs/service-hooks/consumers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/service-hooks/consumers.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
