### ISSUE TITLE
Support wild-card for appFile on AppCenterTest

### ISSUE THREAD

**Issue by stakemura** [MicrosoftDocs/vsts-docs#5170]
AppCenterDistribute@3 supports wild-card for appFile.
On the contrary, AppCenterTest@1 couldn't use wild-card.
Would you like to support this feature?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad0bff55-744d-06c4-d6da-595e6d5d6e94
* Version Independent ID: 4fc5c777-ec33-38fd-0c56-6c6038e9ac40
* Content: [App Center Test task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/app-center-test?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/test/app-center-test.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/test/app-center-test.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @PBoraMSFT
* Microsoft Alias: **pbora**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
