### ISSUE TITLE
Visual Studio 2019

### ISSUE THREAD

**Issue by czf** [MicrosoftDocs/vsts-docs#5182]
Is the visual summary of the differences between the files still relevant in Visual Studio 2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8bb12a7-a20c-1dd5-bca0-4873f7ab9e36
* Version Independent ID: 360739fd-e98a-535f-9872-ed58ece28194
* Content: [Get your code reviewed with Visual Studio - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/tfvc/get-code-reviewed-vs?view=azure-devops)
* Content Source: [docs/repos/tfvc/get-code-reviewed-vs.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/tfvc/get-code-reviewed-vs.md)
* Product: **devops**
* Technology: **devops-code-tfvc**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
