### ISSUE TITLE
Can you add custom default filters

### ISSUE THREAD

**Issue by bbulldis** [MicrosoftDocs/vsts-docs#5186]
We want to be able to filter on area path as we manage multiple backlogs. Is there a way to add another "default" filter like you have for Types, Assigned to, States, Tags, Iterations? So can we add a "Area Path" somehow? This is for a self hosted instance. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5017884-bcc0-3fa7-6bfd-73bb04ab7524
* Version Independent ID: cadea453-739a-6498-268a-ad3391a4f65b
* Content: [Filter your Kanban board - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/boards/filter-kanban-board?view=azure-devops#feedback)
* Content Source: [docs/boards/boards/filter-kanban-board.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/boards/filter-kanban-board.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
