### ISSUE TITLE
Docker Host

### ISSUE THREAD

**Issue by trajano** [MicrosoftDocs/vsts-docs#5187]
in V1 there's a capability that would allow us to use a remote docker host so we can do `docker stack deploy`.  In V2 there's some code referencing DOCKER_HOST and there's a ContainerConnection class that seems to allow for the connection.  However, I can't seem to find it in this documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9dbf88-7e55-d427-145e-d36b04fb197f
* Version Independent ID: a3f30c00-817c-9c05-7a57-3f2bf618821e
* Content: [Docker task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/docker.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thomps23
* Microsoft Alias: **shasb**

**Comment by trajano** [comment]
This is the variable that I can't find an equivalent to in V2

https://github.com/microsoft/azure-pipelines-tasks/blob/bb6d7930e92175e756ec7a3af4bb730c4878813e/Tasks/DockerV1/task.json#L332-L338

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
