### ISSUE TITLE
Limit modification permissions on non-owners

### ISSUE THREAD

**Issue by thoaingan** [MicrosoftDocs/vsts-docs#519]
I'd like to prevent non-owners from modifying queries, and I cannot figure out how to do so. If I do not set the "Contribute" right, users cannot save to any shared folders. If I set the "Contribute" right, the users can both save to folder and edit everyone else's queries. If I set the explicit "Deny" on a query, it will prevent everyone, INCLUDING the owner from modifying it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6aa6277f-7ea0-4d36-4adb-67c517430a9e
* Version Independent ID: 07ff2d9f-4386-8315-945c-7fd15d5bcad7
* Content: [Set query permissions](https://docs.microsoft.com/en-us/vsts/work/track/set-query-permissions?view=vsts#set-permissions-on-a-new-query-folder)
* Content Source: [docs/work/track/set-query-permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/work/track/set-query-permissions.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@thoaingan - Hi. The only way to prevent non-owners from modifying queries is to set up a set of folders in which you define the permissions for that folder - or for a specific query, getting as granular as you need to.  There is no way to universally set the permissions so that a non-owner of a query can't modify it.
