### ISSUE TITLE
Can The free tier run a self hosted job in parallel with a free hosted agent?

### ISSUE THREAD

**Issue by damiensawyer** [MicrosoftDocs/vsts-docs#5191]
Hi, 
I just set up a self hosted build server to augment the 1800 free minutes we get on the free hosted agent. 

It appears to me that the system is only scheduling one of them at a time. I would have expected that I could have used both in parallel for free. 

Is this not the case?

If not, if I purchase a single parallel job license (about US15 / month from memory?), will that allow me to run the two agents concurrently?

Thanks :-)

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
