### ISSUE TITLE
same build number for all builds

### ISSUE THREAD

**Issue by pratik11jain** [MicrosoftDocs/vsts-docs#5200]
Hi I am creating the build number in a bash script as follows :

TAG="manual.$BUILD_BUILDNUMBER"

echo "##vso[build.updatebuildnumber]$TAG"

i still get the same build number for multiple subsequent builds

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
