### ISSUE TITLE
Add UI_UX issue in sprint

### ISSUE THREAD

**Issue by aa3507943** [MicrosoftDocs/vsts-docs#5208]
Hi, 
Can I add UI_UX issues in sprints?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4880004e-aae6-a8c7-1aa2-218b6fb00b71
* Version Independent ID: c6e35d98-3b07-2881-536d-0174a71be14d
* Content: [Assign backlog items to a sprint - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/sprints/assign-work-sprint?view=azure-devops#feedback)
* Content Source: [docs/boards/sprints/assign-work-sprint.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/sprints/assign-work-sprint.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
 
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
