### ISSUE TITLE
Errors in start script (Windows)

### ISSUE THREAD

**Issue by biste5** [MicrosoftDocs/vsts-docs#5211]
The `start.ps1` script provided by this article contains some issues:

- Line 18: 
```csharp
if (-not(Test-Path Env:AZP_WORK))
```
is the correct predicate for the condition. The bash script does so indeed.

- Lines from 29 to 56:
As the script runs every time a container is started, the package could be already on the machine, and it could be already configured. In this scenario, with the provided script quite some warnings are showing on the console because the .zip package and then its extracted content is already present on the machine

In [this Gist](https://gist.github.com/biste5/52ffc894aceeddc287d43b534bf80c93) my own corrected version based on the above

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31d4f6c-d16d-2ba1-1294-6aa94e328046
* Version Independent ID: 88aec599-4410-697d-1002-1c41b1c17bb6
* Content: [Running a self-hosted agent in Docker - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/docker.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliobbv
* Microsoft Alias: **juliobv**

**Comment by juliobbv** [comment]
Hi @biste5,

Thanks for opening this issue! I have a PR up to fix the predicate on line 18. Good catch.

Regarding the second point: to simplify the guide, the script was written with the assumption that the base container image doesn't contain an agent package already configured. This is because in the usual case, the customer is using a YAML build, which requires the latest version of the agent available for the Azure DevOps organization.

Thanks,
Julio

**Comment by tonkon** [comment]
The error is still there if no Env:AZP_WORK is provided. Should test both Env:AZP_WORK and $Env:AZP_WORK.

```
if (Test-Path Env:AZP_WORK) {
    if (-not (Test-Path $Env:AZP_WORK)) {
        New-Item $Env:AZP_WORK -ItemType directory | Out-Null
    }
}
```
