### ISSUE TITLE
WIQL query for pull requests

### ISSUE THREAD

**Issue by APIWT** [MicrosoftDocs/vsts-docs#5218]
Hello! How do I write a WIQL query that can retrieve a list of open pull requests with a specific tag? We want to create a dashboard widget from this information.

Thanks!

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
