### ISSUE TITLE
Workflow transition restriction

### ISSUE THREAD

**Issue by kubsztal** [MicrosoftDocs/vsts-docs#5242]
Hello,

how can I restrict workflow transitions that for example one could change the state from New to Active, but changing from New directly to Resolved, thus bypassing Active, would be forbidden?

https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/customize-process-workflow

**Comment by msebolt** [comment]
@kubsztal Thank you for the question.

Manually this isn't feasible, however for a custom approach you can use the **Work item updated** service hook, see [WebHooks](https://docs.microsoft.com/azure/devops/service-hooks/services/webhooks?view=azure-devops).

There you would need to run a service that compares the work-item state.  PowerShell's a good candidate for this since you can then use the [Azure CLI work-item](https://docs.microsoft.com/cli/azure/ext/azure-devops/boards/work-item?view=azure-cli-latest) command.

**Comment by kubsztal** [comment]
Thanks, I will check this!
