### ISSUE TITLE
Documentation on configuring authentication for a web application

### ISSUE THREAD

**Issue by CoolDadTx** [MicrosoftDocs/vsts-docs#5247]
This task seems to be the only task (compared to IIS Web App Deploy) that allows you to specify the supported authentication options (IIS Authentication) for a web app. However the documentation indicates that these settings only work for web sites, not web apps. If you set the configuration type to IIS Web App then the option to configure authentication goes away.

How can this task be used to set the IIS Authentication settings for a web application (not a site) in IIS. All of our internal sites are configured to use Win auth at the application level while the default website (under which they are hosted) only has anonymous configured. Clearly IIS supports this but we cannot figure out how to get it to work with this task.

We are currently using IIS Web App Deploy and it has the same issue. So even a solution involving WebDeploy would be sufficient.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 244121ae-5de4-14cd-a9c3-d9cda5ad0a3b
* Version Independent ID: 313238b7-d67b-bc60-1188-cbe305179600
* Content: [IIS Web App Manage task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/iis-web-app-management-on-machine-group?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/deploy/iis-web-app-management-on-machine-group.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/iis-web-app-management-on-machine-group.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
