### ISSUE TITLE
When a deploy task fails with "No package found with specified pattern"  there is no other information.

### ISSUE THREAD

**Issue by shindigo** [MicrosoftDocs/vsts-docs#5256]
My deploy task is failing with "No package found with specified pattern", but the logs do not show what the "specified pattern" is, or the folder that is being searched with the pattern.  It would make the process more transparent if these were shown in the log.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e834fd0-59c9-3f45-a09d-88571d94c62e
* Version Independent ID: b798ba39-ef08-55eb-3fa0-731782a1d7e0
* Content: [Troubleshoot builds and releases - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting?view=azure-devops)
* Content Source: [docs/pipelines/troubleshooting.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/troubleshooting.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thomps23
* Microsoft Alias: **chrispat**

**Comment by WilliamAntonRohm** [comment]
@shindigo, it looks like you have product feedback rather than documentation feedback. If you are looking for functionality that isn’t currently provided by the product, please use our “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this works in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) page.​ 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
