### ISSUE TITLE
Are these supposed to display visual representations in build/release pipeline UI?

### ISSUE THREAD

**Issue by frackham** [MicrosoftDocs/vsts-docs#5263]
Does not do so in Release pipeline. If not, is there any additional way to provide visual feedback for a devops pipeline outcome other than task names?

Also, based on this this seems deprecated: https://github.com/microsoft/azure-pipelines-tasks/issues/1867 ? Some screenshots or details would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16bf0bbb-8b63-6384-aa33-b5b1e2b8cfe3
* Version Independent ID: f4da8dbd-a02f-bbdf-2cf2-60e081339237
* Content: [Logging commands - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands?view=azure-devops&tabs=bash#feedback)
* Content Source: [docs/pipelines/scripts/logging-commands.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/scripts/logging-commands.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thomps23
* Microsoft Alias: **phwilson**

**Comment by frackham** [comment]
To clarify:
- When using vso variables per https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/scripts/logging-commands.md 
- ...and these are included in inline Powershell scripts in a Release pipeline.
- ...no visual indicator shows in the UI.

Variables set and can retrieved correctly. There does not seem to be a way of visually showing a list of green ticks (for example) for successfully completed substeps, meaning that you have to split the script to show item-level user feedback (which results in a huge pipeline).

**Comment by MattT95** [comment]
I am also having a similar confusion to that mentioned by @frackham. 

The ##vso[task.logdetail] entries are being removed from the log output in Azure Pipelines, but I am seeing no visual change to the build log UI for my pipeline runs. Is this still supported in the latest UI?

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
