### ISSUE TITLE
Allow at queue time missing YAML example

### ISSUE THREAD

**Issue by trajano** [MicrosoftDocs/vsts-docs#5271]
It's missing a YAML example for  https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#allow-at-queue-time

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#allow-at-queue-time)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by fmms** [comment]
I would have very much expected myself that variables to be set at build time -- which means easily configurable parameters be the user executing the pipeline could be exposed via YAML. However, I have reached the conclusion that this is not missing in the documentation but totally missing in the product.

I think it is very strange to define the whole pipeline as code and then for approvals and build time parameters to go to the Web UI.

@MSFT could you please explain why some options are not exposed in YAML and make this then clear in the documentation otherwise everyone will just expect this.

Thanks

**Comment by ChrisGibson1982** [comment]
Hey @vtbassmatt , do you know if the below has/is being implemented?

https://github.com/microsoft/azure-pipelines-yaml/blob/master/design/runtime-parameters.md

**Comment by vtbassmatt** [comment]
@ChrisGibson1982 in progress right now. I'm not sure if we'll have it out this sprint or if it will be one more.

**Comment by ChrisGibson1982** [comment]
@vtbassmatt  Brill, thanks for the update

**Comment by kitingChris** [comment]
is there an update? This concept would be a great enhancement!

**Comment by vtbassmatt** [comment]
Apologies, this took longer than expected. New ETA is mid-January.

**Comment by vtbassmatt** [comment]
This isn't a doc issue, the feature doesn't exist right now. Closing, and we'll definitely update the docs when the new feature is available.
