### ISSUE TITLE
Unable to turn preview features off

### ISSUE THREAD

**Issue by dougbu** [MicrosoftDocs/vsts-docs#5277]
Once the "new me" feature is enabled, it doesn't appear possible to get back. Worse, the https://docs.microsoft.com/en-us/azure/devops/project/navigation/preview-features?view=azure-devops page has no useful information once a user profile is in this state. Please update the documentation.

I'm not sure where to report the problem with being locked into "new me" and other preview features. This is a big deal because I had the "multi-stage pipelines" feature enabled and that disables many features, including "Retry" of build pipelines.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4f95345-6686-8e29-ff3f-cbea4a6eb24d
* Version Independent ID: 695d975e-ea9b-139b-4f98-f9655a751f59
* Content: [Turn preview features on or off - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/project/navigation/preview-features?view=azure-devops)
* Content Source: [docs/project/navigation/preview-features.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/navigation/preview-features.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by Danlewis3** [comment]
Same issue

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 

Also, it looks like you've encountered an issue with the product itself. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.

**Comment by Danlewis3** [comment]
Documentation is still wrong though

**Comment by dougbu** [comment]
What @Danlewis3 said is 100% correct. You're documenting a feature that's unavailable if you turn the "New Me" feature on. If there's no workaround, the least you could do is acknowledge the problem on the https://docs.microsoft.com/en-us/azure/devops/project/navigation/preview-features?view=azure-devops page.

**Comment by WilliamAntonRohm** [comment]
@clisc -- thank you for clarifying.

**Comment by clisc** [comment]
Related to #5601

**Comment by KathrynEE** [comment]
@dougbu , @clisc - I'm closing this issue as it is related to internal features that aren't yet available to the General Public as noted here: https://developercommunity.visualstudio.com/content/problem/733283/cannot-disable-preview-features.html.  As regards some features not being documented in the Preview features article, we are working on updates. Sometimes the information is made available.
