### ISSUE TITLE
Include in public extensions when released as GA feature

### ISSUE THREAD

**Issue by andrewconnell** [MicrosoftDocs/vsts-docs#5282]
The docs say that pipeline decorators are an op-in preview feature ATM that can only be used in private extensions & explicitly shared with organizations. When the feature reaches GA, is the plan to make them public?

**Scenario:** I have an collection of similar tasks in an extension that require a specific utility is installed. Today, each task checks if the utility is already installed (*e.g. by another task from my same collection of tasks*) previously on the current agent. If not, it downloads the installer & installs it. The logic is in a centralized codebase, but each task has to trigger the run & check... 

If pipeline decorators can be included in public exemptions, then I can move all this logic repeated in each step into a decorator so that when someone uses any task from my collection, after installing, it can conditionally check “are any of the dependent tasks used in this job?” and if so, it checks if the utility is already installed... if not, it downloads & installs it at the start of the job.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0704e7ce-a2bb-7ccd-4ad4-2c6ad55bc8f4
* Version Independent ID: 4efcddb9-864d-f895-8122-451c1045b272
* Content: [Pipeline decorators](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-pipeline-decorator?toc=%2Fazure%2Fdevops%2Fextend%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fextend%2Fbreadcrumb%2Ftoc.json&view=azure-devops#feedback)
* Content Source: [docs/extend/develop/add-pipeline-decorator.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/add-pipeline-decorator.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @stephenmichaelf
* Microsoft Alias: **stfrance**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
 
In addition, the product teams aren’t always watching this repository, so to make sure it gets in front of them for triage, please [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.
