### ISSUE TITLE
Error for set a variable in script

### ISSUE THREAD

**Issue by StephaneD62** [MicrosoftDocs/vsts-docs#5288]
The doc says that for set variables in scripts, we should use :
echo '##vso[task.setvariable variable=sauce]crushed tomatoes'

If we do that the variable 'sauce' will not have the value "crushed tomatoes" but "crushed tomatoes'" with a simple quote at the end.

The correct syntax is : 
echo ##vso[task.setvariable variable=sauce]crushed tomatoes
without the simple quote

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cpowershell&viewFallbackFrom=vsts#feedback)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by sebastiendan** [comment]
A kind of related issue I noticed:
- If I set the variable with `echo '##vso[task.setvariable variable=sauce]$myVar'` then $(sauce) equals the content of myVar while the $SAUCE environment variable equals the "$myVar" string
- If I use double quotes instead of single ones (`echo "##vso[task.setvariable variable=sauce]$myVar"`), both variables equal the content of myVar
