### ISSUE TITLE
How to register an OAuth 2.0 app in Azure DevOps on-premise?

### ISSUE THREAD

**Issue by ggbt** [MicrosoftDocs/vsts-docs#5295]
The `Authorize access to REST APIs with OAuth 2.0` document listed under `Azure DevOps Server 2019` describes the steps to be taken to register an OAuth 2.0 app.
The first step is to register an app here: https://app.vsaex.visualstudio.com/app/register

My question is, how do I register an OAuth 2.0 app for Azure DevOps Server? For an on-premise installation. And what are the oauth urls used for an on-premise installation? 

Also, is the Git REST API (https://docs.microsoft.com/en-us/rest/api/azure/devops/git/?view=azure-devops-rest-5.1) available in the on-premise version of Azure DevOps?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac47cbcf-45ed-81aa-b532-e7ad0046658e
* Version Independent ID: 7aa1f60e-069f-3d62-5cac-b65e4b1116ef
* Content: [Authorization using OAuth 2.0](https://docs.microsoft.com/en-us/azure/devops/integrate/get-started/authentication/oauth?view=azure-devops-2019#register-your-app)
* Content Source: [docs/integrate/get-started/authentication/oauth.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/get-started/authentication/oauth.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @ggbt, I've reached out to our PM and will be in touch as soon as possible. Thanks for reaching out!

**Comment by govert-co-co** [comment]
We would very much like to know this as well. Due to various reasons it's impossible for us to migrate to the Microsoft hosted version of Azure DevOps / TFS / VSTS / VSO.

**Comment by chcomley** [comment]
I hear you, @govert-co-co...stand by and I hope you're having a great day. I've re-reached out. :)

**Comment by chcomley** [comment]
I have info for you! Please see the [Q&A ](https://docs.microsoft.com/en-us/azure/devops/integrate/get-started/authentication/authentication-guidance?view=azure-devops#q-is-this-guidance-only-for-azure-devops-services-or-is-this-also-relevant-for-on-prem-tfs-users) where it states that **this is not supported for on-premises**.
As for your second question, please filter the docs for the Server version you are using. That way you'll know if an API is supported for on-premises or not.
Here's where you can select the version from the dropdown menu:
![select-version-from-dropdown-menu](https://user-images.githubusercontent.com/35748196/64558349-7c430480-d2f8-11e9-93e9-d415b91e95fa.png)

Thanks! Let me know if you have any further questions.

**Comment by govert-co-co** [comment]
Hi @chcomley, thanks for the information, effort and quick response, much appreciated. However, I *did* use that version filter dropdown. I selected TFS 2018, as you can see in this link: https://docs.microsoft.com/en-us/azure/devops/integrate/get-started/authentication/oauth?view=tfs-2018
![afbeelding](https://user-images.githubusercontent.com/36270645/64591988-4e6ac800-d3ab-11e9-9f1a-ec35553ebf7a.png)

Would you like me to open a separate issue to fix the documentation?

**Comment by chcomley** [comment]
Hi @gover-co-co, I'm adding  @mattcooper to assist you. Thanks very much.

**Comment by chcomley** [comment]
Hi @gover-co-co, If the article doesn't apply to the version you've selected, a banner appears, telling you that the requested page isn't available for that version. The purple banner wasn't present in your screenshot, I've realized. 
![image](https://user-images.githubusercontent.com/35748196/64731666-7f73f700-d496-11e9-83a4-58a38f8af892.png)
You're redirected to the newest product version that the page is for, and that can be confusing. So, I've published an addition to the article, a NOTE that appears for all versions of the documentation. This should go live sometime this afternoon, however here's the note:
_"NOTE: The following guidance is intended for Azure DevOps Services users, since OAuth 2.0 is not supported on Team Foundation Server or Azure DevOps Server. Client Libraries are a series of packages built specifically for extending TFS functionality. For on-premises users, we recommend using [Client Libraries](../../concepts/dotnet-client-libraries.md), Windows Auth, or [Personal Access Tokens (PATs)](PATs.md) to authenticate on behalf of a user._
Sorry for any confusion and thanks so much for your feedback!
