### ISSUE TITLE
Batch is blocking trigger new build with pending approval

### ISSUE THREAD

**Issue by raphaelquati** [MicrosoftDocs/vsts-docs#5308]
If batch is enabled, and a pipeline is waiting for a approval, it doesn't trigger a new execution. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b067a175-f640-7503-9c1e-f0130c6dbeda
* Version Independent ID: ff743c7b-a103-eae6-4478-62ba995a4b36
* Content: [Checks - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/checks?view=azure-devops#feedback)
* Content Source: [docs/pipelines/process/checks.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/checks.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbansal
* Microsoft Alias: **shashban**

**Comment by shashban** [comment]
@raphaelquati I would like have a better understanding of the issue you are facing.
Could you please confirm the following?
- You have a pipeline with 2 stages. The second stage deploys to an environment.
- Approvals are configured on the environment and trigger is configured to batch (has batch: true)
- With this, you are observing that a run was created for the first commit, and that it waits for an approval before the second stage
- For subsequent commits that happen, no run is created till the first run completes.
This is expected as batching hold new runs to be created when an existing run is in progress. Can you elaborate on your requires scenario and we could talk about how to address the same?

**Comment by sgissinger** [comment]
In Classic Release (Designer) for a given Stage we were able to configure "Deployment queue settings" selecting one value :
- Deploy all in sequence
- Deploy latest and cancel the others
With 'Deploy latest and cancel the others', when a Stage is waiting for an approval, if a new Release for the same Stage occured, it cancels the Stage which was waiting and then, the new Stage waits for the approval instead.
Currently YAML Pipelines Stages seems to work like 'Deploy all in sequence' which waits for the approval before allowing other commits to trigger the pipeline

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
