### ISSUE TITLE
Nuget Packages.lock.json for solution

### ISSUE THREAD

**Issue by PaulVrugt** [MicrosoftDocs/vsts-docs#5321]
How does the caching work for solution restores? Generating a lock file is done by enabling the RestorePackagesWithLockFile option in the project file, but that generates separate lock files for each project. Do i need to cache them all separately? Or is there a way to combine the lock files?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c20289-dab2-7a6e-4f63-4b30eaff2c71
* Version Independent ID: d75cc196-90c1-8291-9907-ff405bde4edf
* Content: [Pipeline caching - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/caching/index?view=azure-devops)
* Content Source: [docs/pipelines/caching/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/caching/index.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @willsmythe
* Microsoft Alias: **wismythe**

**Comment by PaulVrugt** [comment]
any info about this? We would really like to try the caching feature, but we need some clarification about solution level caching. Adding separete caching tasks for 50 project lock files doesn't really seem viable

**Comment by michaelstaib** [comment]
@Paul you have to specify the key with a relative path and collect all of the lock files:

nuget | **/packages.lock.json

**Comment by baywet** [comment]
packages.lock.json cause a lot of issues if you're on a different platform between the dev machines and the ci agents (eg windows vs linux). It'll keep complaining that sha's are different.
project.assets.json are only generated when the restore happens, and because the path only accepts a path and not a glob pattern it can be a lot of work to go cache/restore those before the cache of the packages' binaries.
I ended up using `nuget | **/*.csproj`, it's not ideal but works ok for the purpose.
You still need to execute the dotnet restore after in order to generate the project.assets.json required for the build to work and can't skip the restore like you'd do with npm using a cache hit variable.

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).

**Comment by sebastian-xitaso** [comment]
To anyone stumbling upon this later, here's the current documentation from [Microsoft Learn | Cache NuGet packages
](https://learn.microsoft.com/en-us/azure/devops/pipelines/artifacts/caching-nuget?view=azure-devops)

```yaml
variables:
  NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages

- task: Cache@2
  displayName: Cache
  inputs:
    key: 'nuget | "$(Agent.OS)" | **/packages.lock.json,!**/bin/**,!**/obj/**'
    restoreKeys: |
       nuget | "$(Agent.OS)"
       nuget
    path: '$(NUGET_PACKAGES)'
    cacheHitVar: 'CACHE_RESTORED'
```

Note that this solves two problems mentioned here:

1. The sha being different on Linux/Windows is solved by the `"$(Agent.OS)"` part making the cache operating-system-aware.
2. The `**/packages.lock.json` collects the contents of all  `packages.lock.json files and combines them into a single key.

Note that you can't rename the `NUGET_PACKAGES` variable. See this [blog post](https://blog.leem.dev/debugging-a-failing-nuget-package-cache-task-in-azure-devops-pipelines) referencing [this GitHub comment.](https://github.com/MicrosoftDocs/azure-devops-docs/issues/6281#issuecomment-615437074)
