### ISSUE TITLE
How to prevent release creation for Pull Requests?

### ISSUE THREAD

**Issue by erinha** [MicrosoftDocs/vsts-docs#5324]
I have a build pipeline that produces an artifact only if the Build.Reason is NOT PullRequest. I have a CI triggered release deployment from that build pipeline. It is failing deployment when it completes due to a PR trigger because there is no artifact present. I have the Pull Request trigger DISABLED on the Release deployment pipeline. What else should I be doing to prevent the release creation??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9e313c5-9120-9172-bc27-c21d10fcd5ae
* Version Independent ID: 1a837182-591f-3cbc-1632-7b50d857b13c
* Content: [Release triggers for stages, branches, and pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/triggers?view=azure-devops)
* Content Source: [docs/pipelines/release/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/triggers.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
