### ISSUE TITLE
Moving a page in the hierarchy may break links

### ISSUE THREAD

**Issue by Bafff** [MicrosoftDocs/vsts-docs#5354]
Now we see this warning in the article:

> Moving a page in the hierarchy may break links to it from other pages. You can always fix the links manually after you move. Reordering a page within a hierarchy has no impact on page links.

As I can see now when I rename/move a page in Azure DevOps it's trying to change all the links in my project for me.

Is this warning still relevant? Maybe there is some blog/wiki article so we can read about considerations when renaming wiki pages - what can go wrong? For example, as I know - all links in comments (that were just introduced but I think they would not support this feature anyway) would break if I rename a wiki page.

Anything else? It is very important for us and I don't think that only for us because it is so awful when I move something and a lot of links will be broken after that and you even don't know where are they.

Thanks!

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: d7892ee5-8b56-bd95-29bb-41ebb8a8bd7e
* Version Independent ID: eccf0785-0968-d6a2-d29e-0c4796aa165c
* Content: [Add, edit, reorder and manage wiki pages in Azure DevOps - Azure DevOps](https://docs.microsoft.com/ru-ru/azure/devops/project/wiki/add-edit-wiki?view=azure-devops)
* Content Source: [docs/project/wiki/add-edit-wiki.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/add-edit-wiki.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by adramasu** [comment]
Hey @Bafff
When pages are created/renamed, it takes some time to index the results. If the same page is moved/renamed immediately, the "Move page" functionality might not be able to detect that. So, this message is still relevant in such cases.

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
