### ISSUE TITLE
Setting key vault secret fails on pipeline

### ISSUE THREAD

**Issue by andreujuanc** [MicrosoftDocs/vsts-docs#5359]
If i do via pipelines: az keyvault secret set --vault-name 'keyvayultname' --name 'somename' --value 'somevalue'"
It fails saying: ERROR: Parameter 'secret_name' must conform to the following pattern: '^[0-9a-zA-Z-]+$'.

But if i copy paste that into the portal's azure cli it works.

I'm starting to think that this is a version thing.

Any ideas?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8de3304e-98f9-bac0-3ccc-c65f68a89e87
* Version Independent ID: 8fb2f6a9-545d-dff1-ff86-974694a85054
* Content: [Azure CLI task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-cli?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/deploy/azure-cli.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-cli.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @ushan
* Microsoft Alias: **UshaN**

**Comment by Jacob-Nelson-mscst** [comment]
My work around was to add a power shell script to the repo that would creat or update my key vault secrets. To execute that script during the release I added a power shell script task with the file path to my script in the repo. I had to use a service principle and the connectAzAccount command within the script to access the subscription. 

you could add these variables as arguments to the power shell script task in the release as well and store the variables in the release definition.

	$passwd = ConvertTo-SecureString <your password string> -AsPlainText -Force
	$pscredential = New-Object System.Management.Automation.PSCredential(<your app name or id>, $passwd)
	$tenantId = <your tenant id>
	Connect-AzAccount -ServicePrincipal -Credential $pscredential -Tenant $tenantId

#whatever code you're running ....

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
