### ISSUE TITLE
Provide details on execution scenarios.

### ISSUE THREAD

**Issue by pjshah70** [MicrosoftDocs/vsts-docs#537]
It doesn't tell simple thing, What happen if file mentioned to copy is not found.
 - Is it going to fail and throw error?
 - Is it going to continue and show error in execution log?
 - Is it going to continue without message?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81f02378-b85b-d3a4-d3c8-f07d935367da
* Version Independent ID: fab57f76-35d2-4024-6f7f-1740d7b24743
* Content: [Copy Files](https://docs.microsoft.com/en-us/vsts/build-release/tasks/utility/copy-files?view=vsts#feedback)
* Content Source: [docs/build-release/tasks/utility/copy-files.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/tasks/utility/copy-files.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **alewis**

**Comment by TMattes** [comment]
We are using the copy files task in many of our build and release definitions (TFS 2017.2 / 2018.2 on premise). When nothing is copied (for example due to pattern issues) or a file to be copied is not found, there should at least be a warning and a "partially succeeded" build out of the task, so that there is not the illusion of everything being alright.

**Comment by vtbassmatt** [comment]
I'm updating the docs to note the behavior under these two circumstances. Changing the task's behavior is out of scope for this docs repo. You can file an issue at https://github.com/Microsoft/vsts-tasks/issues to request a behavior change (though it's unlikely since this would be a breaking change).
