### ISSUE TITLE
Classic view in example shows duplicate/empty content

### ISSUE THREAD

**Issue by Rauell** [MicrosoftDocs/vsts-docs#5370]
The example's classic view seems to have some rendering errors. I'm seeing repeated &lt;tr&gt; &lt;td&gt; elements when I switch to the classic view.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a79d17fd-6e65-d8f0-ea05-f62d68456474
* Version Independent ID: 3f7338a7-aae7-b6b6-3291-5c985c6fa6f3
* Content: [Command Line task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/command-line?view=azure-devops&tabs=classic#feedback)
* Content Source: [docs/pipelines/tasks/utility/command-line.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/command-line.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
