### ISSUE TITLE
Missing output

### ISSUE THREAD

**Issue by MisinformedDNA** [MicrosoftDocs/vsts-docs#5396]
Can you explain why some commands, such as `Install-Module -Name SqlServer -Scope CurrentUser -Force`, display no output in the logs, even with `system.debug` enabled? I have to append `-Verbose` sometimes to see the output, but that is different than the behavior I'm seeing locally.

Locally, `$VerbosePreference` is set to `SilentlyContinue` (same as what I'm seeing in Azure DevOps).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e444c2-69c6-4d71-6fd0-94d0f4097d3a
* Version Independent ID: 3a727833-1cc3-c2fb-c5b3-22605eee2721
* Content: [PowerShell task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/powershell.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/powershell.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
