### ISSUE TITLE
Security Through Obscurity: Exposed PAT

### ISSUE THREAD

**Issue by SudoBrendan** [MicrosoftDocs/vsts-docs#5405]
The example has a security flaw: the PAT located at `${AZP_TOKEN_FILE}` is accessible from builds/releases run on these agents (even though the path is "masked" from pipelines by unsetting the envvar... the file is there and can be manipulated by pipelines) - this is especially dangerous because there's a default file... people with bad intentions can run `cat /azp/.token` and likely have manage rights to the pool the agent is in. Yikes.

Any ideas on how to resolve this? Let's chat it out :)

1. Why are administrative tokens written to files accessible by pipelines?
1. Why, by default, are jobs run on the agent executed as root and not some other unprivileged user?

I feel like setting up and installing the agent can happen as `root`, but that final line should exec as a different user, but I don't know what kinds of privileges `./bin/AgentService.js` requires or what it does, I see no docs for that...

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31d4f6c-d16d-2ba1-1294-6aa94e328046
* Version Independent ID: 88aec599-4410-697d-1002-1c41b1c17bb6
* Content: [Running a self-hosted agent in Docker - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/docker.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliobbv
* Microsoft Alias: **juliobv**

**Comment by SudoBrendan** [comment]
So, I burned some time on this... appears that proper user setup bypasses this flaw. I would post my updated file, but I've refactored it so heavily with custom logic it doesn't even resemble the base anymore... Here's the logic you need to patch this security flaw and prevent your agents from accessing the admin PAT or running root tasks in pipelines:
1. `Dockerfile` edits:
   - Create a new user with a RUN command (below refered to as ${USER})
     - Note that for docker (-in-docker) support, you'll need to set up some group memberships to access the `/var/run/docker.sock` socket...
   - while it might seem odd, run start.sh as ROOT (we still need to install the agent and chown/chmod stuff)
1.  `start.sh` edits:
    - run a `chmod 600 "${AZP_TOKEN_FILE}"` after that file's creation
    - add a `chown -R ${USER} /azp/agent` command before running the agent (note that this will exclude `/azp/.token` -- for obvious reasons, ensure you don't set `${AZP_TOKEN_FILE}` to some path starting with `/azp/agent`)
    - change the last line (line that runs the agent) to `su - ${USER} -c "exec /azp/agent/externals/node10/bin/node /azp/agent/bin/AgentService.js interactive"` (full paths!!)
    - aside from this, ensure all the tools you're installing alongside this base image can be accessed and executed by ${USER}... this might include running installers AS ${USER} (things like NVM/NPM, etc)

Hope this helps other teams.

As an aside... I really wish MSFT would just own this code as an official docker image so users could share a common and secure base image and just issue a `docker pull` to fix; instead, hundreds (thousands?) of admins will have to modify their own custom agents if they want this security patch... the next security patch that inevitably arises will have the same problem as this one. It's a tragedy that `microsoft/azdo-agent` suddenly fell out of flavor with over ***10 million pulls*** - you left your customers in a pretty bad way with that choice.

**Comment by junkiebev** [comment]
@SudoBrendan - If `${AZURE_TOKEN_FILE}` should be immutable, `chmod 400` (or `chmod 440` if it needs to be read by the root group) might be a better option.

**Comment by SudoBrendan** [comment]
Good call. Confirmed this. Use 400!

**Comment by segraef** [comment]
What about a simple `rm filename` after the pipeline agent got configured?

**Comment by SudoBrendan** [comment]
That might work - I figured that considering how much effort went into ensuring that file's existence in the script, the agent needed it there; definitely worth testing! I do know that the agent has some callbacks to AzDo during it's lifetime; re-establishing connections, unregistering itself, etc... maybe it loads the token into memory at some point? Maybe not?

**Comment by kirkone** [comment]
Hi @SudoBrendan,
you got some good points.
I started a new project when the `microsoft/azdo-agent` was deprecated here:
https://github.com/codez-one/docker-azure-pipelines-agent

I think the same about the absense of a maintained Image for this use case. It is not at the same level as the old Microsoft repo but I think it is a good start.

Deleating the token can become a bit tricky because you might not be able to unregister the agent anymore.

It would be nice if you can help me to implement the user isolation into this project

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
