### ISSUE TITLE
conditions won't resolve more then 1 variables

### ISSUE THREAD

**Issue by DerekLiang** [MicrosoftDocs/vsts-docs#5423]
Here is the code I expected it be working. 
```yml
- task: xxxx
  ...
  condition: and(ne(variables['config'], 'test'), ne(variables['name'], 'form'))
```

Here is the log in pipeline. It seems the second variables doesn't resolve. 
```
Evaluating: and(ne(variables['config'], 'test'), ne(variables['name'], 'form'))
Expanded: and(ne('test', 'test'), ne(variables['name'], 'form'))
Result: False
```
I switched the order of the of the variables. The following was the output.
```
Evaluating: and(ne(variables['name'], 'form'), ne(variables['config'], 'test'))
Expanded: and(ne('form', 'form'), ne(variables['config'], 'test'))
Result: False

```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f151218-9a11-0078-e038-f96198a76143
* Version Independent ID: 09c4d032-62f3-d97c-79d7-6fbfd89910e9
* Content: [Conditions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/conditions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/conditions.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
Thanks for your feedback. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
