### ISSUE TITLE
How long do Pipeline Artifacts persist for?

### ISSUE THREAD

**Issue by matthewfcarlson** [MicrosoftDocs/vsts-docs#5434]
Do they have a lifetime? Do they need to cleaned up manually? Can we set how long they'll last for?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 861ce7a5-4fa4-55f1-2c97-46a9cc6a2f66
* Version Independent ID: bdf954b9-9bbe-8b34-b674-71ad8153519d
* Content: [Publish and consume artifacts in pipelines - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/artifacts/pipeline-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/pipeline-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by WilliamAntonRohm** [comment]
Thanks for your questions. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

**Comment by hdiass** [comment]
Why is this closed ? I can't see any documentation regarding this question anywhere..what is the pricing on the pipeline artifacts ?
