### ISSUE TITLE
Why would retaining version control history not be recommended? 

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/vsts-docs#5443]
Losing change history that can help you understand why or how something was made so that you can make the appropriate changes just because there are technical differences between how the two programs store information seems like a needless and terrible suggestion. Unless the truth is that the migration tool just cant migrate history reliably.

If I migrate (not that I ever want to use something more difficult), would the tool be able to bring the history over completely and correctly? Or would it sometimes fail?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d24126ce-abfc-07d0-ceea-51534f745e55
* Version Independent ID: 60861ae7-4b6d-e360-8ab7-28b276326569
* Content: [Import repositories from TFVC to Git - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/import-from-tfvc?view=azure-devops)
* Content Source: [docs/repos/git/import-from-TFVC.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/import-from-TFVC.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **atinb**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

**Comment by StingyJack** [comment]
No, I'm questioning what looks like a poor recommendation.

**Comment by StingyJack** [comment]
@WilliamAntonRohm

**Comment by WilliamAntonRohm** [comment]
@apawast -- Apeksha, can you shed some light on @StingyJack's questions?

@StingyJack -- Andrew, please [submit your product feedback here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

**Comment by StingyJack** [comment]
It's not product feedback, and I'm well aware of how to report that. 
This feedback is regarding specific documentation.

**Comment by jpalvis86** [comment]
@StingyJack have you look at [this section of the documentation](https://docs.microsoft.com/en-us/azure/devops/learn/git/centralized-to-git#migrating-history)? 
It gives more details about why migrating history might be challenging.

I haven't performed a migration yet but our team is currently planning how to do so.

**Comment by StingyJack** [comment]
That doc should be linked to the recommendation. I would argue several points on it, especially "relative rarity.

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).

**Comment by StingyJack** [comment]
@mijacobs - this is a question about a recommendation in the docs. I don't care where you source the answer from, but this ain't a product question.

**Comment by StingyJack** [comment]
@mijacobs  - are you a bot? You repeat things like a bot does. And you never address the question directly, also like a bot does. 

The advice at question is counter to the fact that there is a [tool which does this rather easily](https://docs.microsoft.com/en-us/azure/devops/learn/git/migrate-from-tfvc-to-git) and neatly and renders the [advice at the end of this section](https://docs.microsoft.com/en-us/azure/devops/learn/git/centralized-to-git#migrating-history) moot.  

Reopen this issue, because you didn't take the time to read it before closing, and because the advice given is bad advice for anyone. Keep your change history as much as is possible. Losing it removes the context we sometimes need to troubleshoot or change code correctly.
