### ISSUE TITLE
Comments in analytics views 

### ISSUE THREAD

**Issue by cxputcm** [MicrosoftDocs/vsts-docs#5451]
Hello,

this feature seems to work fine with powerbi, but I seem to be missing the ability to pull comments for work items. Any ideas ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 508bfe7d-16cf-7b44-53a7-26a9f9563be8
* Version Independent ID: f365dd42-530f-e145-5dd3-28420237bc7b
* Content: [What are Analytics views? - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/powerbi/what-are-analytics-views?view=azure-devops)
* Content Source: [docs/report/powerbi/what-are-analytics-views.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/powerbi/what-are-analytics-views.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
