### ISSUE TITLE
Hockey App mentioned

### ISSUE THREAD

**Issue by josersleal** [MicrosoftDocs/vsts-docs#5458]
Hockey App mentioned and redirects to a page on app insights.
Also inst Hockey App being replaced?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 878f028a-4418-1f6c-bf27-d469b249b621
* Version Independent ID: 7209b942-b6ab-e9f6-6cfd-bd5d89ea9aa8
* Content: [Tools and clients that connect - Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/user-guide/tools?view=azure-devops)
* Content Source: [docs/user-guide/tools.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/user-guide/tools.md)
* Product: **devops**
* Technology: **devops-new-user**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
