### ISSUE TITLE
Sprint efforts not adding up 

### ISSUE THREAD

**Issue by pingyin97** [MicrosoftDocs/vsts-docs#5461]
The way I have my process for boards set up is there are milestones which can be broken down into deliverables and the deliverables can be further be broken down into tasks. If I enter a certain amount of hours for efforts(customized field) in tasks they add up properly in the deliverables. The issue is that deliverable efforts are not adding up into the milestones. Is there any way to fix this issue? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a197bf55-89c7-682d-bb1c-e82bec732349
* Version Independent ID: 5aa2afac-cb82-3f72-643c-25a0173cce98
* Content: [Understand how work items are used to track user stories, issues, bugs, features, and epics - Azure Boards and TFS](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/about-work-items?view=azure-devops&tabs=agile-process#feedback)
* Content Source: [docs/boards/work-items/about-work-items.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/work-items/about-work-items.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
