### ISSUE TITLE
Getting Complete Commit Messages to be displayed

### ISSUE THREAD

**Issue by PierreC2** [MicrosoftDocs/vsts-docs#5467]
In the Commit History page, if you hover the mouse over a commit message, you see a tool tip ending with [Click message to see more] but if you click on the link, you are presented with the commit's files differences but you cannot  view the complete commit message.  I am missing something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6de6ffd-afcc-17f9-8e89-6845c0a5bd6c
* Version Independent ID: caea7004-b42b-9084-befc-6b33168570b4
* Content: [View commit history - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/commit-history?view=azure-devops#feedback)
* Content Source: [docs/repos/git/commit-history.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/commit-history.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sancha**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
