### ISSUE TITLE
Adding secrets during the release...

### ISSUE THREAD

**Issue by subashsivaji** [MicrosoftDocs/vsts-docs#5474]
Following is a scenario release pipeline,
1. azure key vault task
2. deployment task X
3. az keyvault secret set --vault-name 'ContosoKeyVault' --name 'StorageConnection' --value 'Pa$$w0rd'
4. deployment task Y
5. deployment task Z
......
Will my secret "StorageConnection" be available for deployment task Y and Z automatically? Or should add another azure key vault task after step 3 to get the latest available list of secrets?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69ff8e50-4187-3622-1beb-155f006af5f5
* Version Independent ID: bc56fa96-bded-95f8-39a4-a9e5242db1bf
* Content: [Azure Key Vault task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-key-vault?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/deploy/azure-key-vault.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-key-vault.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by N-Usha** [comment]
Please add another instance of keyvault task if you need the tasks Y & Z to use latest downloaded secret fetched from the Azure Key vault. Alternatively, if all of the above mentioned tasks are in the same job, please refer to [this doc](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#set-in-script) to define a variable that it can be consumed by one of the subsequent steps in the pipeline.

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
