### ISSUE TITLE
PR Trigger for all Release branches on Azure Git Repo

### ISSUE THREAD

**Issue by baoduy** [MicrosoftDocs/vsts-docs#5491]
Hi **AzureDevOps**

Let's say I defined an PR build for code review purposes and would like to trigger for all Pull Request for all Branches which contains **_Release** in its name for Azure Git Repo. How could I config the trigger for this purpose.

_Thanks
Duy_

**Comment by msebolt** [comment]
@baoduy  Thank you for the question.

You should use:

```
trigger:
  branches:
    include:
    - *_Release
```

See topic [wildcards](https://docs.microsoft.com/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#wildcards) for more information.

**Comment by baoduy** [comment]
Hi @msebolt 
Thanks for your reply, the configuration you provided perfectly work for CD build, once the PR merged to a Release branch the build will be triggered and deploy the changes to the environments. This I already used for my CD builds.

However, My question is related to the PR build instead which I would like to apply the Code quality scan for all PR before it got approved and merged to Release branches and could help to prevent merge if any code changes do not pass the quality scan.

I found that we can use Build Validation feature to do this. However, this feature is applying at the branch level. So whenever the new Release Branch created we need to config the Build Validation for that Release Branch. It quite manual and may cause a potential issue when the code merged to Release Branch without quality scan because our developer forgot to apply the Build Validation when creating a new release branch.

It useful if Build Validation can be applied at the Repository level. So that we can apply to all PR of all Release Branches.

Looking forward to your reply.
Thanks
Duy

**Comment by msebolt** [comment]
@baoduy  Thank you for the response.


It looks like the only alternative is to create a [custom service hook](https://docs.microsoft.com/en-us/azure/devops/service-hooks/?toc=%2Fazure%2Fdevops%2Fservice-hooks%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fservice-hooks%2Fbreadcrumb%2Ftoc.json&view=azure-devops) triggered by the `Code pushed` event which would include a call to a [REST API PR Status](https://docs.microsoft.com/rest/api/azure/devops/git/pull%20request%20statuses?view=azure-devops-rest-5.1).  This is really the only way to customize the built-in branch policy features.

Otherwise, this sounds like a good candidate for **Suggest a Feature** on [Azure DevOps UserVoice](https://developercommunity.visualstudio.com/topics/Azure+DevOps.html).

**Comment by baoduy** [comment]
Hi @msebolt 
Thanks for your suggestion. I will go for Suggest a Feature on Azure DevOps UserVoice.

**Comment by msebolt** [comment]
Sounds good, thank you for moving the issue.
