### ISSUE TITLE
Is there any Rest Client to obtain Agent Details?

### ISSUE THREAD

**Issue by PramodMn007** [MicrosoftDocs/vsts-docs#5496]
I'm working on a extension to provide details of all Agent Pools and Agents , Though we can achieve this using Rest API's , I'm wondering whether I can achieve this using Rest Client?

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
