### ISSUE TITLE
upstream sources advantages vs republished sources?

### ISSUE THREAD

**Issue by bbarry** [MicrosoftDocs/vsts-docs#5498]
We have a business need to manually approve every (external) upstream change before we start using it and only allow our developers to use an approved whitelist of packages and versions. 

The two ways I can see to do this are either:

1. disable all pipelines and halt all development, enable an upstream source and pull the new package through and then disable it; making sure no additional upstream packages were pulled while the source was enabled
2. not use upstream sources but instead republish all packages manually (ongoing work will not be impacted while package approvals occur)

Am I missing something? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5f022df-36c3-34b1-cac1-ac33995a7d73
* Version Independent ID: 9634b0c8-7b14-4453-2c04-aedabbf331f1
* Content: [Upstream sources](https://docs.microsoft.com/en-us/azure/devops/artifacts/concepts/upstream-sources?view=azure-devops)
* Content Source: [docs/artifacts/concepts/upstream-sources.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/concepts/upstream-sources.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
