### ISSUE TITLE
What python versions are available?

### ISSUE THREAD

**Issue by altendky** [MicrosoftDocs/vsts-docs#5516]
https://github.com/MicrosoftDocs/vsts-docs/issues/4834

I did see above where the question is not answered.  The documentation should list what versions can be specified and what you will get when you specify them.  For example, what will pypy3 get you?  How about py3.7?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e765cfad-8ab9-443a-1171-5af81a31252f
* Version Independent ID: 8ff69d93-0128-dbeb-9d63-45266ed73020
* Content: [Use Python Version task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/use-python-version?view=azure-devops)
* Content Source: [docs/pipelines/tasks/tool/use-python-version.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/tool/use-python-version.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @brcrista
* Microsoft Alias: **brcrista**

**Comment by brcrista** [comment]
There's a link on the Use Python Version page:

> Available Python versions on Microsoft-hosted agents can be found [here](https://docs.microsoft.com/azure/devops/pipelines/agents/hosted?view=azure-devops#software).

The exact Python versions vary slightly depending on the image, so we list the exact versions along with the software for each image.

**Comment by brcrista** [comment]
I agree this could be more clear, but I'm leaving for vacation later this week and I don't think I have the time to get to it anytime soon..  If you have an idea on how to improve it, feel free to submit a PR!

(We wouldn't want to exhaustively list the Python versions here because it would probably get out-of-date quickly.)

**Comment by brcrista** [comment]
@WilliamAntonRohm can you please assign to @leantk?

**Comment by leantk** [comment]
@altendky like Brian mentioned we have the link to the different hosted agent images and then from there you can drill down into the specific one you are using and see the versions there. Is there more information that you would like to see in the list of version info? Is there a way we could make it clearer? We don't have the direct version info on this page just because it's hard to keep the information up-to-date in multiple places and we use those individual image pages as the source of truth
