### ISSUE TITLE
Using variables from variable groups backed by key-vault in this task

### ISSUE THREAD

**Issue by Bhsha** [MicrosoftDocs/vsts-docs#5519]
Can I use variable from variable group backed by key-vault in one of the task parameter? Currently I am getting empty value for the variable. Is this not supported? One thing to mention I am using this task in build pipeline.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89bc6da4-5a1e-5989-f4f0-27465953b5fd
* Version Independent ID: fd12f976-5d3b-3b1b-3d0a-a0bf2a60c961
* Content: [Invoke HTTP REST API task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/http-rest-api?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/utility/http-rest-api.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/http-rest-api.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
