### ISSUE TITLE
Removing secure file

### ISSUE THREAD

**Issue by padmick** [MicrosoftDocs/vsts-docs#556]
I want to overwrite a secure file but that doesn't seem to be possible. Is there anywhere on VSTS I can remove a secure file so I can upload a new version?

Padraic Wade

**Comment by padmick** [comment]
any updates on this?

**Comment by mlearned** [comment]
@padmick sorry I missed the reply here, can you elaborate on what you mean by "secure file?" .. I'm assuming you mean you have some secrets inside a file that you want to permanently purge out that file in version control correct? Are you using Git or TFVC with VSTS?  The problem here will be history and you'll need to purge it.  See this article here https://help.github.com/articles/removing-sensitive-data-from-a-repository/  if its TFSVC (not Git)  you can use the destroy command https://docs.microsoft.com/en-us/vsts/tfvc/destroy-command-team-foundation-version-control?view=vsts
