### ISSUE TITLE
Ignoring of files within folder exclusion

### ISSUE THREAD

**Issue by NoMercy82** [MicrosoftDocs/vsts-docs#5563]
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/file-matching-patterns?view=azure-devops

Hi, I have the below:

API/web.connections.config
API/web.config
API/thing.txt

Web/app.js
Web/bundle.js

I want to delete (match) everything except:

API/web.connections.config
Web/app.js

So in this case the below would be deleted:

API/web.config
API/thing.txt
Web/bundle.js

I have tried to below pattern matches:

```
**
!API/web.connections.config
!Web/app.js
--------------
API/**
!API/web.connections.config
Web/**
!Web/app.js
--------------
API/*
!API/web.connections.config
Web/*
!Web/app.js
--------------
API/*
!API/*.connections.config
Web/*
!Web/*app.js
--------------
API/*
API/!*.connections.config
Web/*
Web/!*app.js
```

Every single one of these examples matches on everything and deletes them all. Would you be able to document the correct way of doing something such as the above? It would help me greatly.

Thanks

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
