### ISSUE TITLE
Secure files can be exported to artifact and then download in drop

### ISSUE THREAD

**Issue by maaarcus** [MicrosoftDocs/vsts-docs#5566]
#### Steps to reproduce in Azure Pipeline:
1. Download security file to azure hosted agent
2. Copy the task to artifact staging directory
3. Publish the artifact

#### The tasks to archive the secure file:

- task: DownloadSecureFile@1
  inputs: secure_file_name

- task: CopyFiles@2
  inputs:
    contents: 'secure_file_name'
    sourceFolder: secure_file_name_location
    targetFolder: '$(build.artifactStagingDirectory)'

- task: PublishBuildArtifacts@1

After the pipeline has finished running, the secure file can be downloaded by anyone by going to the pipeline's "summary" > "Build artifacts published" > "drop" > "download"

The secure files are usually certificates/private ssh key. Which post a security risk. Adding a passphrase to them could solve the issue, but I expect secure files are secure in a way that it can only access by the hosted agent. May I know if the behavior is intended?

**Comment by WilliamAntonRohm** [comment]
@maaarcus, thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.

**Comment by maaarcus** [comment]
@WilliamAntonRohm Thank you for your prompt reply. Added more information for the issue. Please let me know if further explanation is needed.

**Comment by WilliamAntonRohm** [comment]
@maaarcus -- It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

You're welcome to [submit this as a product bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
