### ISSUE TITLE
Build vs Pipeline

### ISSUE THREAD

**Issue by mikeblakeuk** [MicrosoftDocs/vsts-docs#5570]
Please explain when we should use DownloadBuildArtifacts and when we should use DownloadPipelineArtifacts with the pros can cons. thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0a16bcf-af6c-e278-f0a6-8ec95012ce4a
* Version Independent ID: ae442106-33b3-786f-2158-34eed3fed6e0
* Content: [Download Build Artifacts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-build-artifacts?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/download-build-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/download-build-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by davestephens** [comment]
I find it somewhat surprising that there's no mention of this in the docs!

**Comment by HahnNovari** [comment]
I was unable to get "DownloadBuildArtifacts" to work in my yaml pipeline; however, "DownloadPipelineArtifacts" worked on my first attempt. Could be a PICNIC error on my end for BuildArtifacts.

**Comment by ashokirla** [comment]
BuildsArtifacts are the old way to storing your artifacts. Going forward we recommend you to use pipeline artifacts. 

If you have published your artifacts using PublishBuildArtifacts task, then you need to use DownloadBuildArtifacts task to download them.
However if you have used PublishPipelineArtifacts task (or `-publish` simply) then you can use DownloadPipelineArtifacts task (or `- download` simply)

**Comment by davestephens** [comment]
It would be worth documenting this, in the time I've spent looking through
the docs this is the first time I've heard that pipeline artifacts are the
way forward...

**Comment by ashokirla** [comment]
We have already documented here: https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml#migrating-from-build-artifacts

**Comment by bmargula** [comment]
My understanding here is that it's deprecated in favour of DownloadPipelineArtifact. Why do we now get a warning on Azure DevOps to now use the other way again? 

"DownloadPipelineArtifact (DownloadPipelineArtifact)

Please use Download Build Artifact task for downloading Build Artifact type artifact. https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-build-artifacts?view=azure-devops"

**Comment by sgerace** [comment]
@bmargula We also started seeing a few of these warnings a few days ago:

![Screen Shot 2020-05-04 at 9 06 52 AM](https://user-images.githubusercontent.com/1239058/80968950-d7c18580-8de6-11ea-854c-4db4299f90bc.png)

We were originally confused by the warnings (as you were), until we realized that we were using the `PublishBuildArtifacts@1` task in a few places in our pipeline (we were using `PublishPipelineArtifact@1` everywhere else) due to lack of support for publishing artifacts to the same folder from multiple build steps (see microsoft/azure-pipelines-tasks#12480). As such, the warning was there to simply indicate that we should be using `DownloadBuildArtifacts@0` to download artifacts published with `PublishBuildArtifacts@1` and (similarly) we should use `DownloadPipelineArtifact@2` to download artifacts published with `PublishPipelineArtifact@1` (we were using `DownloadPipelineArtifact@2` everywhere, even the ones that were being published with `PublishBuildArtifacts@1`).

After we switched everything the few situations that were using `PublishBuildArtifacts@1` to use `DownloadBuildArtifacts@0` (to match how they were being published), the warnings went away in our pipeline runs.

**Comment by bmargula** [comment]
Thank you @sgerace for the detailed explanation!

We are using the  _publish_ keyword which is supposedly the shortcut for the [Publish Pipeline Artifact](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml ) task.

When downloading we use the _download_ keyword which is supposedly the shortcut for the [Download Pipeline Artifact](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#download) task.

Based on your explanation this should fit together, yet there is still this warning displayed.
