### ISSUE TITLE
How to set mtouch arguments on Xamarin.iOS task

### ISSUE THREAD

**Issue by BrightRan** [MicrosoftDocs/vsts-docs#5583]
On VS can add mtouch arguments to "Additional mtouch arguments" in the project iOS Build settings by right-clicking the project in the solution explorer and selecting Properties.
But how can we do this on Xamarin.iOS task? Is the Arguments option of this task can work for this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d91aa34-87c4-d934-28e2-456eac57432d
* Version Independent ID: 5725c1ab-d894-f79c-f7e0-0c5b8b5cca56
* Content: [Xamarin.iOS build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/xamarin-ios?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/xamarin-ios.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/xamarin-ios.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @DavidStaheli
* Microsoft Alias: **dastahel**

**Comment by damphyr** [comment]
To my knowledge, all you have to do is add the arguments to your .csproj file and call the corresponding build configuration in the Xamarin.iOS task.
Since the task calls msbuild, any options persisted in the project will be used when building.

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
