### ISSUE TITLE
Configuring Option of what to pull into on Pull request

### ISSUE THREAD

**Issue by bbulldis** [MicrosoftDocs/vsts-docs#5585]
You mention it is advised to work within topic branches, but I had For a forked repo when working within topic branches, we first want to pull into the forked repos master, then (in a separate pull), pull the forked repos master back to the upstream master. Is there a way to change what the default Pull into is so it defaults to the same repo master rather than the upstream fork?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 240f15e3-daf9-78f8-7423-cc17490ee401
* Version Independent ID: 3f1934d0-75c4-56b3-32d5-676b7fbe70b7
* Content: [Fork your repository - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/forks?view=azure-devops&tabs=visual-studio)
* Content Source: [docs/repos/git/forks.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/forks.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
