### ISSUE TITLE
Error while downloading artifact from master branch on pull request

### ISSUE THREAD

**Issue by vsalvino** [MicrosoftDocs/vsts-docs#5588]
When trying to download a pipeline artifact from our master branch (when running the pipeline in a different branch) this normally works fine. However, if the pipeline is run as the result of a GitHub pull request from a branch on a forked repo, then trying to download the pipeline artifact from the master branch throws an error:

`The container #### could not be found.`

Project: https://github.com/coderedcorp/coderedcms/
Example behavior on pull request: https://dev.azure.com/coderedcorp/coderedcms/_build/results?buildId=463&view=logs&j=d08edeab-482a-5e5e-4bc9-95c4a2546f71&t=ab750f80-2887-52b1-f5f8-72d9100884bf&l=10

I suspect that the download artifact task is trying to download from a branch on the forked repository, rather than the master branch of the source repository. Not sure how to specify otherwise though.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b03d67d0-8738-72e6-dbe7-324c1784d4fc
* Version Independent ID: bbb4d774-cd98-3ecb-7ccf-5f49e6f2b425
* Content: [Download Pipeline Artifact task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-pipeline-artifact?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/utility/download-pipeline-artifact.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/download-pipeline-artifact.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @willsmythe
* Microsoft Alias: **wismyth**

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
