### ISSUE TITLE
How to assign the licence?

### ISSUE THREAD

**Issue by grahambunce** [MicrosoftDocs/vsts-docs#5594]
So I've enabled the trial, but when I come to add a user the only access level options I can see are "Basic", "stakeholder", "visual studio subscriber". Shouldn't I also see "basic + test plans"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73fdf4b3-7ff5-f9ab-d28c-45e804b314de
* Version Independent ID: e916c6aa-2ca5-1517-614c-091fb5b7572b
* Content: [Buy Basic + Test Plans access - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/billing/buy-basic-plus-test-plans?view=azure-devops)
* Content Source: [docs/organizations/billing/buy-basic-plus-test-plans.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/billing/buy-basic-plus-test-plans.md)
* Product: **devops**
* Technology: **devops-billing**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by grahambunce** [comment]
Update: the only way to get the option is to pay for the license up-front in the dev ops billing UI... but then I don't get the 30 days free trial.

**Comment by drewbren** [comment]
Sorry for the confusion. During the trial, all your Basic users will have access to Basic + Test Plans. You only need to assign Basic + Test Plans to users you have decided to pay for. It is true that once you have paid for Basic + Test Plans, you can't start a trial for it. That's a limitation of our system today. If you'd like us to reset it for you, send me an email at Andrew dot Brenner at Microsoft dot com.

We're very shortly (in the next couple weeks) going to be moving to a model where you pay for the users you assign, rather than the licenses you purchase. This workflow should be much less confusing once those changes are live. 

Here's how it will work...
1. You will have to start a trial before you buy. 
2. Once you start a trial your Basic users will have access to Test Plans, but you'll also be able to assign Basic + Test Plans to the users you know will need ongoing access.
3. When the trial expires, we'll charge you only for the users you have explicitly assigned Basic + Test Plans

Let us know if you have feedback or questions (either here or directly by email)

Thanks,
-Andrew

**Comment by chcomley** [comment]
Hi @grahambunce, With Andrew's clarification provided, I'm closing this issue, but please let us know if you have any further questions.
