### ISSUE TITLE
Mention of users

### ISSUE THREAD

**Issue by kbaleta** [MicrosoftDocs/vsts-docs#5597]
We can currently mention anyone from Azure AD. Is it possible to only mention users who have access to Azure DevOps?

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
