### ISSUE TITLE
Can we run this on onprem agents

### ISSUE THREAD

**Issue by CGCampbell07** [MicrosoftDocs/vsts-docs#5605]
I am trying to set it up to run on my onprem agents but its ignoring my yaml pool info and using what is in the pipeline. i modified it to use my docker pool but i need to tell it to run on a specific agent as there are containers running on this machine so i am not sure if i am doing something wrong in the yaml.

![image](https://user-images.githubusercontent.com/9217087/64900161-e7703c00-d654-11e9-8819-b40b082d3bc8.png)

this is what my yaml file looks like and everything bold i just renamed 

pool:
  Name: Docker
  Demands:
  - Agent.Name -equals **ServerName**

container:
  image: **dockerdemo**.azurecr.io/win19/npm:latest
  endpoint: Azure East US Infrastructure

steps:
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      workingDir: '$(Build.SourcesDirectory)/Projects/ui'
      verbose: false
      customRegistry: useFeed
      customFeed: '**custom feed guid**'

**Comment by msebolt** [comment]
@CGCampbell07  Thank you for the question. 

It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. 

Here are a couple of options where you might consider asking your question:

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
