### ISSUE TITLE
Hotfix Question

### ISSUE THREAD

**Issue by murraj** [MicrosoftDocs/vsts-docs#5618]
This question is with regards to the "Releasing Hotfixes" section of the following article about the Azure DevOps Release Flow process: https://docs.microsoft.com/en-us/azure/devops/learn/devops-at-microsoft/release-flow#releasing-hotfixes.

The article mentions that hot fixes are done in branches of master and then cherry-picked to the release being hot fixed (such as releases/M129). My question is what do you do if the area that needs to be hot fixed has already been touched by another commit that is for a future release (such as releases/M130) that is now in master? If I apply a fix to master and then cherry-pick it to M129, won't the other changes that were applied for M130 to the same code also be cherry-picked?

Thank you.

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
