### ISSUE TITLE
Is it possible to create server jobs?

### ISSUE THREAD

**Issue by htho** [MicrosoftDocs/vsts-docs#5628]
From the description I can not tell if it is even possible to create own server jobs. Is it possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14955ee9-29f2-46fe-3a8d-a42666f53ffc
* Version Independent ID: 5d417cd0-a671-ee30-8fca-5f8b0addd328
* Content: [Develop a web extension for Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/extend/get-started/node?view=azure-devops)
* Content Source: [docs/extend/get-started/node.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/get-started/node.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @willsmythe
* Microsoft Alias: **wismythe**

**Comment by Sirlupinwatson1** [comment]
Hi, What you mean by own server jobs ? You mean a bot is taking an action to do something ? You can do what you want its possible with the command line

**Comment by htho** [comment]
My issue is about [build tasks](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/tasks?view=azure-devops&tabs=yaml) in the azure build pipeline.
I found a document that describes how to create server tasks. maybe it should be referenced from here?

https://github.com/Microsoft/azure-pipelines-tasks/blob/master/docs/authoring/servertaskauthoring.md

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
