### ISSUE TITLE
Filter the displayed values in this widget

### ISSUE THREAD

**Issue by StarWars999123** [MicrosoftDocs/vsts-docs#5629]
Is it possible to filter the displayed values displayed in this graph? 
We have several test runs on that release pipeline. Some of them get triggered by our developers to proof, that they did not harm the system. However, when we want to analyse and display the results, it would be helpful to filter results with wildcards/regular expressions. Only the non-developer-releases shall get displayed. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 842d348f-ed5b-d310-952e-619b506d849c
* Version Independent ID: 7cbd9754-3e44-bf5d-800a-369cee2f80be
* Content: [Configure the Test results trend widget (Advanced) - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/configure-test-results-trend?view=azure-devops)
* Content Source: [docs/report/dashboards/configure-test-results-trend.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/dashboards/configure-test-results-trend.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
