### ISSUE TITLE
Host dialog. Full screen and titlebar

### ISSUE THREAD

**Issue by Varujik** [MicrosoftDocs/vsts-docs#5631]
Hello. I have two questions related to docs.

Link: [Host dialogs](https://docs.microsoft.com/en-us/azure/devops/extend/develop/using-host-dialog?view=azure-devops)

There is told nothing about how to show this host dialog in fullscreen mode, like height and width - 100%. Fortunately, providing parameters like that:

`var dialogOptions = {
                title: null,
                width: "100%",
                height: 5000, (height 100% is not working here)
                buttons: null
              };
dialogService.openDialog(contributionId, dialogOptions);`

So we are using something like hack, providing height as 5000, and iframe wrapper has max-height property, which makes our modal really full screen.

The second thing, which I can't solve, how hide this noisy title header in modal? I mean div with class "ui-dialog-titlebar" which takes too much space of dialog. Providing title as null has no effect.

Thanks.

**Comment by WilliamAntonRohm** [comment]
@Varujik -- thanks for your questions. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your questions:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

@chcomley -- please consider adding this information to the documentation.
