### ISSUE TITLE
Unable to share or conditionally execute stages in Multistage Yaml

### ISSUE THREAD

**Issue by elamathiJv** [MicrosoftDocs/vsts-docs#5633]
Hi Team,

Kudos to the new efforts on the development of  Mulitstage YAML pipelines.

**Requirement:**
We have a requirement to differentiate different codes and environments present in the same repo in different directory and execute the respective environment/ code's stages

**Tried Ideas:**
1. _**Using Build tags in stage conditions (as in classic)**_ 
  a)Not able to access or use it as a variable in pipelines 
  b)Unable to use build tags as a condition parameters for stages in Multistage YAML pipelines.
2. _**Using a global variable -> overwrite the values in initial stages -> Executes the stage conditions using the global variable**_ 
  a) Unable to overwrite a variable in the task - not possible
  b) Setting variable inside the task -scope limited to job - Cannot be shared across stages.
  c) Unable to set and pass variables across stages

**Current Workaround**
We are currently using the below strategy to achieve our requirement using YAML pipelines ,
1. Assigning appropriate build tags in the initial stage
2. Created stages for every type and env combination
3. Have an initialising job in every state which reads build tags and create an job output variable
4. Deployment jobs are executed based on the job output variable from the previous job.
5. Drawbacks:
   a) Repetition of same init job in all potential stages to set the conditional variables
   b) Traceability is bad as the conditions are executed at Jobs level and not in the Stage level

We would like to know if there's any possible way to :
1) Share variables across stages
2) Using build tags as Stage conditions
3) Overwrite global variables.

Thanks,
Elamathi

**Comment by msebolt** [comment]
@elamathiJv Thank you for the question.

It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation.

Here are a couple of options where you might consider asking your question:

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

For any issues involving a referenced Microsoft Docs topic, please comment below.
