### ISSUE TITLE
using $apply in $expand expression

### ISSUE THREAD

**Issue by angelwang** [MicrosoftDocs/vsts-docs#5655]
Hello,
I am getting below error when I tried to implement this chart, I am using Azure Devops Server 2019, is this not supported?

DataSource.Error: OData: Request failed: The remote server returned an error: (400) Bad Request. (VS403483: The query specified in the URI is not valid: Term '( $apply=filter(WorkItemType eq 'Product Backlog Item') /groupby((StateCategory), aggregate(Effort with sum as TotalEffort)) )' is not valid in a $select or $expand expression..)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8719e400-4445-59a4-c68e-628243710c36
* Version Independent ID: d6a76999-81c0-33cb-47a5-9ca4d8be80c3
* Content: [Feature Progress rollup sample Power BI report - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/powerbi/sample-boards-featureprogress?view=azure-devops&tabs=powerbi#feedback)
* Content Source: [docs/report/powerbi/sample-boards-featureprogress.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/powerbi/sample-boards-featureprogress.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@angelwang  Thank you for your question. 

It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. 

Here are a couple of options where you might consider asking your question:

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

To get this issue to the product team, please use [Azure DevOps UserVoice](https://developercommunity.visualstudio.com/topics/Azure+DevOps.html).
