### ISSUE TITLE
Release after Release

### ISSUE THREAD

**Issue by shachar-kindite** [MicrosoftDocs/vsts-docs#5660]
Is it possible to trigger a release after another release has completed successfully? 
for example: release to prod after release to test was successful

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9e313c5-9120-9172-bc27-c21d10fcd5ae
* Version Independent ID: 1a837182-591f-3cbc-1632-7b50d857b13c
* Content: [Release triggers for stages, branches, and pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/triggers?view=azure-devops#feedback)
* Content Source: [docs/pipelines/release/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/triggers.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
After stage trigger does that. Are you looking to trigger some other pipeline based on stage completion

**Comment by shachar-kindite** [comment]
Thanks, for the quick reply. "after stage trigger" is not good for me, I'll explain: I have a multi-stage release pipeline for my Test environment and I have another multi-stage release pipeline for my Production environment. What I want is to make sure the Production release can be initiated only if a Test release had been successful. The way I thought I could achieve that is by using the "New Release Triggers" like when a Build pipeline finishes than a new release is created, so do the same but with another Release pipeline instead of a Build pipeline.

**Comment by kestasjas** [comment]
My wish list: I want to deploy Test project (Smoke Test) Release after API from another pipeline Release successful deployment. Release triggered by another Release.

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
