### ISSUE TITLE
Details on adding multiple permission bits is unclear

### ISSUE THREAD

**Issue by ChrisGibson1982** [MicrosoftDocs/vsts-docs#5662]
The line **Here, --allow-bit/--deny-bit could be a single permission bit or addition of multiple permission bits.** is unclear.  Do you just add the permission bits together to get the value you want? 

 e.g if you apply a value of 7 for Releasemanagement, would you be able to view, edit and delete releases?  

Some examples would be really helpful

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fcd5139-c761-93cb-62b1-f0730f36cc39
* Version Independent ID: 1d6cbfd9-c560-9275-f5fb-4a753e28a40a
* Content: [Manage security permissions using Azure DevOps CLI - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/cli/permissions?view=azure-devops)
* Content Source: [docs/cli/permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/cli/permissions.md)
* Product: **devops**
* Technology: **devops-ref**
* GitHub Login: @KathrynEE
* Microsoft Alias: **geverghe**

**Comment by ishitam8** [comment]
Hi @ChrisGibson1982 ,

Thank you for the feedback. I will update the documentation and help text for the command with few examples. I am opening an [issue](https://github.com/Azure/azure-devops-cli-extension/issues/795)  in our extension repo. You can track the bug there. 


To answer your question, if you pass allow-bit as 7 to Release management permission ,  you will be able to **view, edit and delete releases.**
Or you if you just want to give **view** permission you can pass allow-bit as 1.
So, allow-bit can be a single integer denoting only one permission bit value or it could be an addition of multiple permission bits to modify multiple permission types. The reason addition of bits was provided so that user can modify multiple permission bits in as single command instead of calling same command multiple times.

`az devops security permission update --namespace-id c788c23e-1b46-4162-8f5e-d7585343b5de  --subject <USER_ID/GROUP_DESCRIPTOR> --token <SECURITY_TOKEN> --allow-bit 7 --deny-bit 8`

This will give the user permission to view edit and delete edit release pipeline( 7 = 1 + 2 + 4) permissions and would take away the permission to manage release approvers (i.e 8).

**Comment by ChrisGibson1982** [comment]
Thanks @ishitam8, just one more point, can you skip numbers?  e.g. if i wanted to allow user to only view or delete releases could i set 6 as the allow bit?  (Sorry i couldn't think of a better example)

**Comment by ishitam8** [comment]
@ChrisGibson1982  , 
Yes, you can skip numbers as well. 
The allow-bit would necessarily be the addition of only those permission numbers/types for which you want to explicitly allow permissions for.

**Comment by ChrisGibson1982** [comment]
@ishitam8  Cheers

**Comment by ishitam8** [comment]
@ChrisGibson1982 , I am glad that your issue is resolved. 

I don't think I've enough permission to close the bug.
@KathrynEE , could you please close this.

**Comment by mengyang88** [comment]
@ishitam8 
Could you please tell us how to get the --token <SECURITY_TOKEN>

**Comment by ishitam8** [comment]
@mengyang88  , You can refer to this [document](https://docs.microsoft.com/en-us/azure/devops/cli/security_tokens?view=azure-devops) for more detials on security tokens.
