### ISSUE TITLE
Ability to add more required reviewers once PR starts?

### ISSUE THREAD

**Issue by cdietschrun** [MicrosoftDocs/vsts-docs#5670]
We have a common case where we have a PR that has default required reviewers set from branch policies. Once the review starts, the reviewers decide that they would like to add another person that is required, based on their intuition, and not just based on path or file name filters.

This doesn't seem possible as when the user adds a new reviewer, it always seems to go into optional reviewers, and there's no way to "promote" that reviewer to required.

Is this possible and we're missing it, or is it something that would have to be added?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cd986e0-608c-1d8c-6faf-ecdb12e10bc6
* Version Independent ID: d60c996e-187e-dd6b-7f3a-dd056a1603f4
* Content: [Protect your Git branches with policies - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-policies?view=azure-devops#automatically-include-code-reviewers)
* Content Source: [docs/repos/git/branch-policies.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/branch-policies.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
