### ISSUE TITLE
$(System.TeamFoundationServerUri) is not evaluatable.

### ISSUE THREAD

**Issue by oleksandr-bilyk** [MicrosoftDocs/vsts-docs#5673]
$(System.TeamFoundationServerUri) should be evaluated as the URL of the service connection in TFS or Azure Pipelines. 
I have created custom agentless task. In task.json I attempt to send $(System.TeamFoundationServerUri) with many other variables. All other variables (e.g. System.TeamFoundationCollectionUri) are evaluable exception of System.TeamFoundationServerUri. How it may be?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 611642f0-881f-10b9-ae94-3c562001d1f0
* Version Independent ID: 41efb94b-4c7a-64a3-b23b-70c8634ae727
* Content: [Release variables and debugging - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=azure-devops&tabs=batch)
* Content Source: [docs/pipelines/release/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by WilliamAntonRohm** [comment]
@oleksandr-bilyk -- Oleksandr, thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by nishubansal** [comment]
@oleksandr-bilyk - $(**System.TeamFoundationServerUr**i)  variable is not supported in Agentless task. Please use **System.TeamFoundationCollectionUri** variable instead.
