### ISSUE TITLE
Specific branch for second repo

### ISSUE THREAD

**Issue by fleed** [MicrosoftDocs/vsts-docs#5702]
How do I set a specific branch name for additional git repos?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 800c5477-b39f-48e6-6f9c-aa7994b2ec2a
* Version Independent ID: db9e2e97-d44d-734e-6a6f-b01f60f01c95
* Content: [Options for Git repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/pipeline-options-for-git?view=azure-devops)
* Content Source: [docs/pipelines/repos/pipeline-options-for-git.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/repos/pipeline-options-for-git.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by sphanley** [comment]
Since the docs say to clone a second branch by simply running the `git clone` command via a script, you'd do it the same way as cloning a specific branch manually through git -- there's nothing Azure Devops specific at play. Per [this Stack Overflow answer](https://stackoverflow.com/a/1911126/3486353), here's example syntax: 

> git clone --single-branch --branch \<branchname\> \<remote-repo\>
