### ISSUE TITLE
Can I call functions from one Powershell task in a different task?

### ISSUE THREAD

**Issue by henry-padilla** [MicrosoftDocs/vsts-docs#5709]
I would like to get some modularity to these deployment pipelines. Is there a way I can import functions in one step and then use them in other steps? I'd rather not have different copies of the same functions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77731c06-e4fd-8125-0daf-870c9ccedd3f
* Version Independent ID: 0d5c338d-80f9-c64e-b675-bf7b4eb8e32b
* Content: [Use a PowerShell script to customize your build pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/scripts/powershell?view=azure-devops)
* Content Source: [docs/pipelines/scripts/powershell.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/scripts/powershell.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
