### ISSUE TITLE
Preview APIS specified in documentation not available on TestManagementHttpClient class

### ISSUE THREAD

**Issue by rob2244** [MicrosoftDocs/vsts-docs#5710]
I am trying to use the preview apis for creating test plans, test suites and test cases in a .net standard 2.0 library project. I have the latest version of the Microsoft.TeamFoundation.Server.Client and Microsoft.VisualStudio.Services.Client installed:

![image](https://user-images.githubusercontent.com/26353604/65435979-600e8f80-ddef-11e9-9341-27d1ab48e924.png)

But the APIS specified by the documentation do not appear to be on the class:
![image](https://user-images.githubusercontent.com/26353604/65436111-9b10c300-ddef-11e9-8106-ed0721bbf24b.png)

![image](https://user-images.githubusercontent.com/26353604/65436170-b7acfb00-ddef-11e9-8db9-02f3ccd2e280.png)

I don't think I'm missing any using statement. Additionally I went to the TestManagementHttpClient class definition looking for the preview methods and didn't find them there.

Thanks.

**Comment by rob2244** [comment]
It appears like the method exists on TestCompatHttpClientBase but intellisense is not picking it up. Additionally it is marked as obsolete in that class:

**Comment by WilliamAntonRohm** [comment]
@rob2244 -- thank you for your feedback.  Please send me a link to that article and I will look into this issue.

**Comment by rob2244** [comment]
@WilliamAntonRohm Here is a [link](https://docs.microsoft.com/en-us/dotnet/api/microsoft.teamfoundation.testmanagement.webapi.testmanagementhttpclient?view=azure-devops-dotnet) to the documentation. Thank you very much for the prompt response. If you could direct me to the correct nuget packages to use for the 5.1 preview apis I would appreciate it, as I have had to fall back on manually calling the rest endpoints.

**Comment by msebolt** [comment]
@rob2244  Since this is a preview version it's likely some`TestHttpClientBase` features are still unavailable.

Perhaps try using a [TestPlanHttpClient](https://docs.microsoft.com/dotnet/api/microsoft.visualstudio.services.testmanagement.testplanning.webapi.testplanhttpclientbase.createtestplanasync?view=azure-devops-dotnet-preview) until the build is released?

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by ashukum-msft** [comment]
@rob2244 : You were facing this issue, because CreateTestPlanAsync is inside Microsoft.VisualStudio.Services.TestManagement.TestPlanning.WebApi.dll and it was not getting shipped in net standard 2.0 of version of the Microsoft.TeamFoundation.Server.Client nuget package. We have fixed this issue. Could you please try after installing latest nuget package? 
**Note:** This method CreateTestPlanAsync exist in TestPlanHttpClientBase.

**Comment by jereesh** [comment]
> @rob2244 : You were facing this issue, because CreateTestPlanAsync is inside Microsoft.VisualStudio.Services.TestManagement.TestPlanning.WebApi.dll and it was not getting shipped in net standard 2.0 version of the Microsoft.TeamFoundation.Server.Client nuget package. We have fixed this issue. Could you please try after installing latest nuget package?
> **Note:** This method CreateTestPlanAsync exists in TestPlanHttpClientBase.

I have the same issue I am using the latest stable version of Microsoft.TeamFoundation.Server.Client (16.153.0) But still it is not available. I am trying to use TestPlanHttpClient class
