### ISSUE TITLE
How do you deal with product versioning?

### ISSUE THREAD

**Issue by o-o00o-o** [MicrosoftDocs/vsts-docs#5713]
I have used GitFlow and GitVersion and while there is a bit more merging going on there - the GitVersion capability was really nice.

GitVersion doesn't seem to work with Release Flow as the Release Branches never get merged back into Master (and that would need an additional merge) - which is a shame

So how do you manage your version increments?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7f4784d-1539-adc9-68e1-036cfc004722
* Version Independent ID: d02a6a52-e736-b411-b2f8-5be08ad3f5a0
* Content: [How We Use Git at Microsoft - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/learn/devops-at-microsoft/use-git-microsoft)
* Content Source: [docs/devops-at-microsoft/use-git-microsoft.md](https://github.com/MicrosoftDocs/devops-learn-pr/blob/live/docs/devops-at-microsoft/use-git-microsoft.md)
* Product: **devops**
* Technology: **devops-learn**
* GitHub Login: @SamGu
* Microsoft Alias: **samgu**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
