### ISSUE TITLE
WebApp deployment to Windows docker

### ISSUE THREAD

**Issue by jjindrich** [MicrosoftDocs/vsts-docs#5717]
Hi, I'm missing deployment on WebApp Windows Container. Please when will be added ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 593c3abc-7b38-6673-62b6-7787d0dda4dd
* Version Independent ID: cbb2b875-b220-596c-7b4d-c2cf6c644335
* Content: [Deploy a Docker container app - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/cd/deploy-docker-webapp?view=azure-devops&tabs=dotnet-core)
* Content Source: [docs/pipelines/apps/cd/deploy-docker-webapp.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/apps/cd/deploy-docker-webapp.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
