### ISSUE TITLE
History or Git gc limits?

### ISSUE THREAD

**Issue by thatnerdyguy** [MicrosoftDocs/vsts-docs#5725]
Are there limits in place for how long closed pull requests are held? Indefinitely? Once the request is merged (let's say via Squash), you can still see the original commits in the pull request itself, however will those ever go away as part of a server side git gc? Or can we act as though those can be treated as fixed history, to be looked at months, or perhaps years, later?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 028e7b61-62e4-a10e-e420-3535f7843f0e
* Version Independent ID: 1a6fdbe7-5ba4-a7f8-1b2e-271289a7b9fd
* Content: [Review and merge code with pull requests - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/pull-requests?view=azure-devops#feedback)
* Content Source: [docs/repos/git/pull-requests.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/pull-requests.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
