### ISSUE TITLE
API based callback approval 

### ISSUE THREAD

**Issue by ed-sparkes** [MicrosoftDocs/vsts-docs#5731]
We have a separate system for release / change management, as part of our build process we create a ticket in that system and then once it is approved manually in that system we would like a callback as a check rather than manual check so the other system can tell azure pipelines that the promotion to the environment is approved. Is this on the roadmap at all?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b067a175-f640-7503-9c1e-f0130c6dbeda
* Version Independent ID: ff743c7b-a103-eae6-4478-62ba995a4b36
* Content: [Pipeline deployment approvals - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/approvals?view=azure-devops#feedback)
* Content Source: [docs/pipelines/process/approvals.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/approvals.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbansal
* Microsoft Alias: **shashban**

**Comment by mthouser77** [comment]
Just to comment.  Where this becomes important is in the new Multi-stage pipelines using YAML config as code. i assume the OP is probably referring to this capability as part of the new YAML pipelines, and not the legacy Build / Release one.  Is this on the roadmap?

**Comment by WilliamAntonRohm** [comment]
@ed-sparkes, @mthouser77 -- Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
