### ISSUE TITLE
Publish Universal Package to Public Artifact Feed

### ISSUE THREAD

**Issue by Wenish** [MicrosoftDocs/vsts-docs#5754]
So today there is no option for publishing Universal Package to a Artifact public feed.
Is this just a bug in my Organisation?
Is this a planned feature or not at all?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77bcd39f-91ab-bb93-40fc-dd4fc5f2374f
* Version Independent ID: c228aece-669a-57d6-b3ed-d427586f8a61
* Content: [Publish and then download a Universal Package](https://docs.microsoft.com/en-us/azure/devops/artifacts/quickstarts/universal-packages?view=azure-devops&tabs=azuredevops#feedback)
* Content Source: [docs/artifacts/quickstarts/universal-packages.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/quickstarts/universal-packages.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by Wenish** [comment]
@chasewilson any update?

**Comment by chasewilson** [comment]
@Wenish, thanks for the question. Currently, Universal Packages are not supported in public feeds. I'm not entirely sure on the reasoning behind this.

**Comment by Wenish** [comment]
@chasewilson any plans to enroll this feature?
it would be the reason for me to use devops artifactory.

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
