### ISSUE TITLE
Generated server id doesn't match what is advised in the azure artifacts packaging page

### ISSUE THREAD

**Issue by SirAlvarex** [MicrosoftDocs/vsts-docs#5758]
Love this tool.  It will help us tremendously, as the auto-authenticate of the maven task requires the root POM to have all upstream registries.  Plus, this will be great for our Docker authentication.

However, the generated ID in the settings.xml is just the name of the artifact stream you are attaching to.  The snippet in the packaging UI has a schema of dev-azure-com-${ORG}-${PACKAGESTREAM}.  Since our engineers will be leveraging the UI a lot, this causes drift with what we have in our poms.xml to support both CI and local building.  Currently we rely on text replacement commands ran immediately after the authenticate task.

Is there a way to specify the name of the ID we will generate?  Or, is there a different standard you are expecting poms to follow so that we can have the repository contain two IDs?  Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 652905ce-af26-dbea-9207-c11cd3bd0064
* Version Independent ID: 6558ec51-b1b5-15d8-0d46-1214f4038de1
* Content: [Maven Authenticate task (for task runners) - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/maven-authenticate?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/package/maven-authenticate.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/package/maven-authenticate.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
