### ISSUE TITLE
How do I set up a condition to exclude certain types of commits from triggering a build?

### ISSUE THREAD

**Issue by sujayvsarma** [MicrosoftDocs/vsts-docs#5765]
My scenario is specific to GitHub-hosted projects. 

I have set up an Azure DevOps Pipeline that builds and deploys a GitHub-hosted project to an Azure Web App. But the build fires for anything that is checked in to the branch. For example, if I update the `readme.md` file! I don't want that to happen. 

How do I set up exclusion conditions in Azure DevOps?

NOTE: I do not know any YAML. So if you are providing those as instructions, please provide complete information and the actual statements to put in. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#tags)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@sujayvsarma -- Sujay, thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
