### ISSUE TITLE
When I reference a task in a pull request description it doesn't have a mention in the task itself.

### ISSUE THREAD

**Issue by johnthcall** [MicrosoftDocs/vsts-docs#5769]
Sometimes we will create a task related to manual cleanup that needs to be done when a PR is deployed. If I mention it in the discussion it gets a mention on the task but when I reference it in the description it doesn't.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22780209-b809-62af-1d6e-ed4c91db867a
* Version Independent ID: 1d6afe6e-6420-2395-0e0b-05902572f7ab
* Content: [Use ID to link work items in discussions & pull requests - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/notifications/add-links-to-work-items?toc=%2Fazure%2Fdevops%2Fboards%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fboards%2Fbreadcrumb%2Ftoc.json&view=azure-devops)
* Content Source: [docs/notifications/add-links-to-work-items.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/notifications/add-links-to-work-items.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@johnthcall -- John, it looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here. 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
