### ISSUE TITLE
How do I find what I'm using storage on?

### ISSUE THREAD

**Issue by MatthewSteeples** [MicrosoftDocs/vsts-docs#5780]
Our tenant is using 1090 (!!!) gb of Azure Artifacts. How can I find out where that space has gone so I can remove it? We've stopped using it as a NuGet cache, and have merely 3 of our own packages published (which probably totals about 30mb).

It would be useful if the docs showed where this number came from, so we could work on reducing it. Support don't seem to be able to tell us anything

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5531731-8bd5-b178-9307-f01b3d2f23b3
* Version Independent ID: 8dea3b69-ad79-5045-3820-4a83a0bc4ce0
* Content: [Start Using Azure Artifacts.](https://docs.microsoft.com/en-us/azure/devops/artifacts/start-using-azure-artifacts?toc=%2Fazure%2Fdevops%2Forganizations%2Ftoc.json&bc=%2Fazure%2Fdevops%2Forganizations%2Fbreadcrumb%2Ftoc.json&view=azure-devops)
* Content Source: [docs/artifacts/start-using-azure-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/artifacts/start-using-azure-artifacts.md)
* Product: **devops**
* Technology: **devops-artifacts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
