### ISSUE TITLE
Does it support full semver spec including pre-release labels?

### ISSUE THREAD

**Issue by dazinator** [MicrosoftDocs/vsts-docs#5789]
As per title - this document specifically mentions semver and 3 numeric components. Does it fully support semver spec includijng pre-release labels?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 405dfb6a-2f3d-1d74-2d28-d00be3bb069d
* Version Independent ID: d446b533-c215-6302-3df2-93b1ffd936df
* Content: [Publish and download Universal Packages in pipelines - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/universal-packages?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/artifacts/universal-packages.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/universal-packages.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by dazinator** [comment]
It seems yes but the prereiease label must be lowercase, and build metadata isnt supported.

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
