### ISSUE TITLE
Create release after PR has been completed

### ISSUE THREAD

**Issue by garethmonk** [MicrosoftDocs/vsts-docs#5804]
Hi,

Is there a way to only trigger a release once a pull request has been approved or completed?

We don't want to deploy artifacts that have failed a code review (for example).

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cbb2877-5e10-4065-e3c6-7883e9df4b3c
* Version Independent ID: 58122a19-2258-3cf3-8335-74bb0dad892f
* Content: [Deploy pull request builds - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/deploy-pull-request-builds?view=azure-devops)
* Content Source: [docs/pipelines/release/deploy-pull-request-builds.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/deploy-pull-request-builds.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @raiyanalam
* Microsoft Alias: **moala**

**Comment by raiyanalam** [comment]
Hi,
   Once the pull request is merged to a target branch, lets say master, a commit is created in the master. So you can have a trigger set up on the master branch. This will trigger a pipeline run only when the code is merged after approval.

Hope this helps.

**Comment by ol-vrobison** [comment]
I've have this issue. I want to deploy the code to the first pipeline stage for testing after the PR review is done for hotfixes but before the merge to master occurs, and defer the merge until the testing on the test environment is done .It would be ideal if the pipeline would look at the PR request status from GitHub  and defer deploy if it has not passed the review requirement.

**Comment by McFixitMan** [comment]
I have this issue as well.
I originally had a trigger on my branch for CI/CD, but have decided to make a passing build required for pull requests to be completed. Once this was set up I found that I'd be running a build pipeline after the **creation** of a PR (to verify successful build in order to complete the PR), and essentially running the same build pipeline after the PR was completed (because of the CI trigger on the branch). 
At first I thought that pull request triggers would be the solution to my problem, but I don't want to trigger a release until the PR is actually completed.

Is there any workaround for this case besides running pipelines multiple times or manually creating releases?
