### ISSUE TITLE
Permently delete git repository without projects

### ISSUE THREAD

**Issue by pokke123** [MicrosoftDocs/vsts-docs#5805]
Is there any way to permently delete a git repository without the need of the project.

I already have deleted the projects and they are not in the database any more.
however the git repositorys stil are. how can these be deleted

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
