### ISSUE TITLE
Extremly important to lock labels

### ISSUE THREAD

**Issue by semilej** [MicrosoftDocs/vsts-docs#5806]
It must be a way in TFS to lock a label to a changeset within a TFS project/Database.  This is a security issue 
If the label is changed you loose  your reference to to the source code used. Then you might end up in serious problems when you shall maintain the release fir bug corrections in the future.  So, Is this not possible, i.e. to lock a label ???? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66afe74b-6887-286e-d354-9225575260b1
* Version Independent ID: 5e8e06f6-8494-408c-fcb4-d3f98580f92e
* Content: [Use labels to take a snapshot of your files - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/tfvc/use-labels-take-snapshot-your-files?view=azure-devops#feedback)
* Content Source: [docs/repos/tfvc/use-labels-take-snapshot-your-files.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/tfvc/use-labels-take-snapshot-your-files.md)
* Product: **devops**
* Technology: **devops-code-tfvc**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
