### ISSUE TITLE
When can we add "... Azure Web Apps, virtual machines, databases..." to environments?

### ISSUE THREAD

**Issue by ChrisGibson1982** [MicrosoftDocs/vsts-docs#5807]
[Enter feedback here]
The first line of the article states that environments "...Kubernetes clusters, Azure Web Apps, virtual machines, databases..." however the article then goes on the state that only Kubernetes is currently supported.  Do we have a date for when the other resource types are going to be available or can you change the first line to reflect the current functionality?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77d95db6-9983-7346-d0eb-4b7443e4e252
* Version Independent ID: 0a22cccc-318d-592f-d1ab-09ec01d88087
* Content: [Environment - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments?view=azure-devops)
* Content Source: [docs/pipelines/process/environments.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/environments.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by WilliamAntonRohm** [comment]
@ChrisGibson1982 -- Chris, thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 

 
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by lgmorand** [comment]
I think the question is quite valid. the documentation is unclear. it says we can setup a group of resources within an "environment" but then that only AKS can be added.
Same issue in the product, you can create an empty ENV OR a AKS env, but once the empty ENV created, you can only add AKS

**Comment by RoopeshNair** [comment]
We are currently working on adding support for Virtual Machines, it will be available in ~2-3 months. We will follow up with most of the Azure resources including WebApps, soon after that.

**Comment by sarahannnicholson** [comment]
+1 for azure webapps in the environments. This would be awesome! :)
