### ISSUE TITLE
How can we have one manifest for multiple tasks

### ISSUE THREAD

**Issue by eric-labelle** [MicrosoftDocs/vsts-docs#5810]
In the documentation for Multiple Version Layout (https://docs.microsoft.com/en-us/azure/devops/extend/develop/integrate-build-task?view=azure-devops#multiple-version-layout) there is only one manifest, for multiple tasks with multiple versions. How is this possible?
I'm trying to get all my tasks flat level like the MS repository (https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks) but not so sure how they achieve this structure and where are their manifest since they do not seem to be in the repository.

Thanks

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 

 
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by eric-labelle** [comment]
Well not really.. I'm trying to understand how to make it work as it is documented on the manifest page I linked. There's 2 tasks with 2 versions each but only one manifest
