### ISSUE TITLE
Select branch to build

### ISSUE THREAD

**Issue by LukaszGrela** [MicrosoftDocs/vsts-docs#5815]
I'm looking for a solution to change default branch based on variable, this is possible with the TFVC source but I can't find it with this one (Azure Repos GIT). Is it possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b846aea-82f7-a988-67d8-1b5e74b61ed2
* Version Independent ID: 2d632729-bb33-c0a0-c996-e1d8e86c2e23
* Content: [Build Azure Repos Git repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/repos/azure-repos-git.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/repos/azure-repos-git.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
