### ISSUE TITLE
Outbound IP - service connections

### ISSUE THREAD

**Issue by ryanps1** [MicrosoftDocs/vsts-docs#5818]
Hi,

I have a service connection connecting to third party services which are IP restricted, I have whitelisted the four /24's provided on the documentation but unfortunately this is still being denied. Is it possible to provide a list of what the possible IP addresses may be so that I can look to whitelist these?

**Comment by msebolt** [comment]
@ryanps1  Thank you for the question.

Please refer to this [latest post on IP rules](https://devblogs.microsoft.com/devops/new-ip-firewall-rules-for-azure-devops/) and comment below if there are any questions.

**Comment by ryanps1** [comment]
Hi @msebolt 

Thanks for the reply. I had indeed whitelisted those IP Addresses, however, when attempting to configure the service connection I can see that this request is originating from: 40.81.159.67.

**Comment by msebolt** [comment]
@ryanps1  Sorry you're still having issues.

Which documentation are you referring to?  Have you opened all IPs listed in the topic [Migration import](https://docs.microsoft.com/azure/devops/migrate/migration-import?view=azure-devops)?

I can assign this to an author though you should probably [start a ticket](https://developercommunity.visualstudio.com/spaces/21/index.html) also since this involves a product issue.

**Comment by ryanps1** [comment]
Hi @msebolt - I haven't purely because I'm not sure that this will be a complete list as it's not solely relevant to the topic at hand, happy to raise a ticket though for further clarification - thanks.

**Comment by msebolt** [comment]
@ryanps1  No problem, a ticket with the product team is more likely to provide an immediate resolution.  If you want a better instruction set please comment below some details as to the type of setup you need (or the closest article that exists currently) and I can assign this to the author.

**Comment by msebolt** [comment]
Closing the issue now, for a related issue see https://github.com/MicrosoftDocs/vsts-docs/issues/5928.
