### ISSUE TITLE
No docs on how to use task groups in multi-stage pipelines

### ISSUE THREAD

**Issue by estensen** [MicrosoftDocs/vsts-docs#5820]
We have a fairly complicated blue-green deploying strategy which we have bundled together in task groups. I would like to re-use this in all my multi-stage pipelines without copy-pasting a lot of code. Is this possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 521b594c-dbb9-54d5-f56f-00e2f5fa1d92
* Version Independent ID: 509d3e4e-23db-8493-e1a6-acb67ec47e81
* Content: [Customize your pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/customize-pipeline?view=azure-devops#feedback)
* Content Source: [docs/pipelines/customize-pipeline.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/customize-pipeline.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by estensen** [comment]
Are task groups renamed to [templates](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates) for multi-stage pipelines?

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
