### ISSUE TITLE
None of these agents are in the selection list anymore

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/vsts-docs#5826]
I have things like 
```
macOS 10.1.3
etc...
vs2017-win2016
win 1803
windows 2019
```
Why did that change and what should I pick for VS 2019 now?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4409a9cb-8448-edd6-da0a-243e5601aa3e
* Version Independent ID: ec15f71a-a76d-c3f9-1d31-832f92183ef4
* Content: [Agents pools - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/pools-queues?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/agents/pools-queues.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/pools-queues.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@StingyJack Thank you for the question.

Please use either `windows-latest` or `windows-2019` (refer to [Microsoft agents](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#use-a-microsoft-hosted-agent)).

**Comment by StingyJack** [comment]
Great. Now please add the useful part back to those names so I (or anyone else) don't have to go look it up. Why add confusion where there wasn't any?

**Comment by msebolt** [comment]
@StingyJack This is a good question for the [azure-pipelines-image-generation repo](https://github.com/Microsoft/azure-pipelines-image-generation/issues)?

**Comment by StingyJack** [comment]
@msebolt - this is the same complaint but for a different docs page

**Comment by steved0x** [comment]
@StingyJack The names to choose for the VM images in YAML or classic editor are listed [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#use-a-microsoft-hosted-agent) on the Microsoft-hosted agents page and linked from the Agent Pools topic [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/pools-queues?view=azure-devops&tabs=yaml#choosing-a-pool-and-agent-in-your-pipeline) in this new section I added. However, when I went to find this example so I could provide it here, it took me a few moments to find it (and I am the one that added it :) ) So I agree it is not very discoverable. 

How about if we took the table that is on the Microsoft-hosted agents page [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#use-a-microsoft-hosted-agent) and included it in this list on this topic (Agent Pools) - so that way the info is right there and readers wouldn't have to click around to find it on a different page?

**Comment by steved0x** [comment]
I just found this: https://github.com/microsoft/azure-pipelines-image-generation/issues/1287

Unsure how that will be addressed but I'll make it as easy to find in the docs as I can.

**Comment by StingyJack** [comment]
Ty @stevedox, hopefully it's a bug or mistake and we don't have any further action.

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).

**Comment by StingyJack** [comment]
@mijacobs - did you update the documentation regarding this? There would normally be some PR or commit attached
