### ISSUE TITLE
npmAuthentication task fail randomly

### ISSUE THREAD

**Issue by memao** [MicrosoftDocs/vsts-docs#5831]
The authentication for a registry outside of our org goes wrong randomly. 

On azure hosted agents, we are using npm authentication task and npm service connection to do the authentication.  Normally, if things goes right, this step would find the correct username and password for the feed. However, randomly, this step gets back a authToken which is wrong for the feed! 
Why does this happen? How do I fix it?

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
