### ISSUE TITLE
"select accounts" ?

### ISSUE THREAD

**Issue by spashx** [MicrosoftDocs/vsts-docs#5836]
Could you please describe more precisely what do you mean by "select accounts of Azure DevOps Services" ? The Hosted XML seems not to be available by default.
regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cdffff7-f341-d9af-a26e-ebf755b3769a
* Version Independent ID: 7aea2747-67f8-4256-722a-740cb3677aca
* Content: [Hosted XML process model - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/hosted-xml-process-model?view=azure-devops#feedback)
* Content Source: [docs/organizations/settings/work/hosted-xml-process-model.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/work/hosted-xml-process-model.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@spashx 	- Thank you for your inquiry.  I'm updating the text to reflect the following: 

**Feature availability**:  The Hosted XML process model is only supported for organizations that have been migrated to Azure DevOps Services using the [TFS Database Import Service](https://aka.ms/TFSDataImport). 

The Hosted XML process model  was created to support organizations who wanted to be on Azure DevOps Services but needed the ability to customize the work tracking process which wasn't supported at that time by the cloud service, or Inherited process model. Since then, the Inherited process model supports most of the customization features supported on-prem. The option to use the Hosted XML process model is only available to those organizations that migrated previously from TFS to the cloud.
