### ISSUE TITLE
Azure DevOps Pipeline Environment - Resource limit of 10

### ISSUE THREAD

**Issue by razidare** [MicrosoftDocs/vsts-docs#5854]
Hello,

Our team is trying to offer a self-servicing platform, where developers can create their own Kubernetes namespaces and destroy them, on demand.

This requires creating a **Resource** inside an Azure DevOps **Environment** and we have scripted this.  The issue is that we have hit a limit of 10 resources/environment and can't create any more. 

Is there a way to lift this limitation of 10 resources per Environment, or to at least increase/double it?

Thank you

**Comment by msebolt** [comment]
@razidare  Thank you for the question.

It sounds like you're hitting the 10 parallel jobs constraint (see [Azure DevOps pricing](https://azure.microsoft.com/en-us/pricing/details/devops/azure-devops-services/)) in which case the you'll need to purchase additional jobs.

**Comment by msebolt** [comment]
Closing this issue now, please comment below if there are questions.

**Comment by razidare** [comment]
@msebolt

I was referring to the Azure Pipelines limit of 10 resources/Environment. Not to the agents concurrent job limits.

We have enabled the preview feature "Multi-stage pipelines" for our organisation and now our menu features "pipelines" and "environments" instead of "builds" and "releases".

The "Environment" menu can contain "Resources" which ATM support only AKS namespaces. There is a hard limit of 10 resources/environment. Can this be increased?

**Comment by msebolt** [comment]
@razidare  Apologies for the confusion, assigning one of the AKS authors now.

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
