### ISSUE TITLE
CSMFile format

### ISSUE THREAD

**Issue by rathishrms** [MicrosoftDocs/vsts-docs#5856]
i have my ARM templates stored in Azure Git repos and want to use it with Azure template deployment task  in my multistage YAM pipeline. As this is just IaC i am only doing release and no build. I get an error saying ""Error: Could not find any file matching the template file pattern"
 what is the format to point to my template. I am pointing as below - this is the folder path of my template inside my repo. Any help is much appreciated and also please add this to this page.

csmFile: 'AzureResourceGroup/resourcegroup.deploy.json'
csmParametersFile: 'AzureResourceGroup/resourcegroup.parameters.json'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a59ea95e-b51a-e529-37a8-215e383c9a0b
* Version Independent ID: f1afdb0e-f090-3193-9bb8-ce5952016768
* Content: [Azure Resource Group Deployment task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/azure-resource-group-deployment.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-resource-group-deployment.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by tfosmark** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
