### ISSUE TITLE
Is it possible to use this with Azure notebook?

### ISSUE THREAD

**Issue by ShujiMIYOSHI** [MicrosoftDocs/vsts-docs#5882]
I'm finding a solution to use git with Azure AD on Azure notebook.
Is Git Credential Manager the solution about this ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c2f260d-9321-d669-172d-01289c233263
* Version Independent ID: 14e9ae18-df9d-7555-902c-3e8b4c2b2f22
* Content: [Connect to your Git repos using credential managers - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/set-up-credential-managers?view=azure-devops#feedback)
* Content Source: [docs/repos/git/set-up-credential-managers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/set-up-credential-managers.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@ShujiMIYOSHI Thank you for the question, pleasae consider starting an issue in [azure-docs issues](https://github.com/MicrosoftDocs/azure-docs/issues) also.

For now, you could try installing the credential manager from within the [Azure notebook terminal](https://docs.microsoft.com/azure/notebooks/configure-manage-azure-notebooks-projects#configure-the-project-environment), and see if it supports git authentication as basic configuration (see [this post](https://medium.com/@dadbrains/integrating-azure-notebooks-jupyter-notebooks-with-github-fd847e941e4)) is already supported.

Assigning this to the author for further details.

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
