### ISSUE TITLE
AppSettings in Azure pipeline for Function app

### ISSUE THREAD

**Issue by sunnyhay** [MicrosoftDocs/vsts-docs#5897]
Hello,

  I try to build a pipeline to deploy an Azure function app. I notice the "appSettings" param only accepts key-value pairs in the YAML file. I'm referring to this page: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-function-app?view=azure-devops. I wonder whether a JSON/YAML file can be used to populate the AppSettings for any function app deployment.
  Thank you.

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
