### ISSUE TITLE
Please explain the concept of multiple pipelines in the azure-pipelines.yml file somewhere

### ISSUE THREAD

**Issue by cawoodm** [MicrosoftDocs/vsts-docs#5947]
Since all examples use a single trigger: - develop it is not clear how to have different pipelines for different branches.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f94a6e7d-3cb5-790c-2b8b-c09abd1de3f6
* Version Independent ID: a0d381e1-07ad-9191-4697-6faf600a7bd8
* Content: [Use Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started/pipelines-get-started?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/get-started/pipelines-get-started.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/get-started/pipelines-get-started.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by damccorm** [comment]
Hey @cawoodn - this is documented [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml#examples) - basically you can just set a condition on different tasks or jobs using `Build.SourceBranch`.

I'm going to close since I don't think there's any action for us on our end here.
