### ISSUE TITLE
Changing a work item State when a field has changed

### ISSUE THREAD

**Issue by PouyaPanahy** [MicrosoftDocs/vsts-docs#5948]
Hi,
I can add a Rule to a Work Item template so that some action happen as a result of a change on a field.
What I would like is that when a user changes a given field, the work item instance should move to a specific state in my workflow.

Is it possible to change the 'State' of the workflow using a Rule?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 715eca62-8a31-4163-c27b-f5e71d781982
* Version Independent ID: 06dc711f-1946-29e9-aece-75af903da09b
* Content: [Customize the workflow of an inherited process - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/work/customize-process-workflow?view=azure-devops)
* Content Source: [docs/organizations/settings/work/customize-process-workflow.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/settings/work/customize-process-workflow.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
