### ISSUE TITLE
Pipeline Triggers Pipeline Support?

### ISSUE THREAD

**Issue by cawoodm** [MicrosoftDocs/vsts-docs#5951]
Is it possible for a successful pipeline (running on one agent) to trigger another pipeline (running on a different agent). If not, how would one use a YAML pipeline to deploy to different servers?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 

 
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
