### ISSUE TITLE
Can the same PAT be used to configure and register multiple agents?

### ISSUE THREAD

**Issue by cawoodm** [MicrosoftDocs/vsts-docs#5952]
&gt; When using PAT as the authentication method, the PAT token is only used during the initial configuration of the agent.
This would indicate the PAT is used for registration and then not stored and used again. Is this really so?

I ask because when we tried to use the same PAT for 2 agents the original agent stopped working (not authorized).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43799c5d-2f13-cc76-a1c0-a3f850e16d4e
* Version Independent ID: 97a5b73f-faf7-f9c0-9269-fc79984616d6
* Content: [Deploy a Azure Pipelines agent on Windows - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops)
* Content Source: [docs/pipelines/agents/v2-windows.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/v2-windows.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@cawoodm Sorry for the long delay, quick question - did the first agent that you registered with the PAT get going successfully, and processed some builds, and then only stopped working after you registered the 2nd agent (using the same PAT)? Since the PAT is only used during agent setup, if the first agent did get going successfully, then the issue would be caused by something else other than the reuse of the PAT for registering the 2nd agent (which I am checking to see if that is supported, my guess would be yes, and if you were in fact able to register 2 agents using the same PAT that would seem to confirm that)

Were you able to resolve the first agent? Here is some more information about agents authorization:

https://github.com/Microsoft/azure-pipelines-agent/blob/master/docs/design/auth.md

**Comment by cawoodm** [comment]
Ooooh, it's a while back so I can't recall exactly. The problems we are seeing with agents now seem to be related to the flaky updater so I've posted the following issue:
https://github.com/microsoft/azure-pipelines-agent/issues/2567
