### ISSUE TITLE
YAML support for Multiplier from a Build Variable

### ISSUE THREAD

**Issue by davidknise** [MicrosoftDocs/vsts-docs#5981]
In our Classic pipelines, we specificy $(Configuration) as a multiplier which defaults to all of our potential configurations. Sometimes, we just want to run a smaller subset of those configurations, so we set the build variable on queue to something smaller.

With the Matrix approach here, it seems as though we are stuck hard coding all of the values? Is there a way that we can specify a Matrix job using a multiplier from YAML?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=example#feedback)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by msebolt** [comment]
@davidknise Thank you for the question, assigning this to the author for comment.

**Comment by asapelkin** [comment]
You can pass json string to the matrix
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml
`matrix will accept a runtime expression containing a stringified JSON object.`
Json can be made from string variable in run time by bash/ps script

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
