### ISSUE TITLE
Using these librairies behind a proxy

### ISSUE THREAD

**Issue by BiribiriJaNai** [MicrosoftDocs/vsts-docs#6003]
Hi, is there any documentation on how to use these libraries behind a proxy?
I already opened a issue [here](https://github.com/microsoft/azure-devops-dotnet-samples/issues/230)... Do I really have to contact a PM each time I need an answer?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa8505e8-cef0-fee8-866a-e000058ac233
* Version Independent ID: d6858ee2-4282-b4e1-fb3b-e8b531b950b7
* Content: [.NET Client Library Samples for Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/integrate/get-started/client-libraries/samples?view=azure-devops#feedback)
* Content Source: [docs/integrate/get-started/client-libraries/samples.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/get-started/client-libraries/samples.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @BiribiriJaNai, Thanks for reaching out. I’m only aware of this [generic guidance](https://docs.microsoft.com/en-us/azure/devops/organizations/security/allow-list-ip-url?view=azure-devops), but it doesn’t really talk about our dotnet clients. If we did have a generic doc on auth in client libraries, we'd only include the calls client auth makes and any known limitations.

Does your corp proxy require authentication? If so, it's possible the request from the client isn't able to authenticate with the proxy because it's trying to authenticate using the provided basic creds (i.e. PAT), which obviously won't work because your corp proxy won't understand our PAT tokens. We suggest using [Fiddler](https://www.telerik.com/fiddler) to watch the interact and see exactly where the request is failing.

Does this information help? Thanks again.

**Comment by chcomley** [comment]
@BiribiriJaNai, I'm closing this issue, but if you do have any questions, please @mention me. Thank you!
