### ISSUE TITLE
Conditions evaluated after approvals

### ISSUE THREAD

**Issue by tesharp** [MicrosoftDocs/vsts-docs#6006]
To stop every push to trigger a deployment we added conditions to deployment job to only run in master. However looks like conditions are evaluated after checks, so after approval it runs conditions and then stop deployment since condition is false. Could it check condition first to check if this job should even run?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b067a175-f640-7503-9c1e-f0130c6dbeda
* Version Independent ID: ff743c7b-a103-eae6-4478-62ba995a4b36
* Content: [Pipeline deployment approvals - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/approvals?view=azure-devops)
* Content Source: [docs/pipelines/process/approvals.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/approvals.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbansal
* Microsoft Alias: **shashban**

**Comment by msebolt** [comment]
@tesharp  Thank you for the question, assigning this to the author for comment/review.

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).

**Comment by mboutet** [comment]
@tesharp, did you create a bug or an idea for that?
