### ISSUE TITLE
Download as zip ignores submodules

### ISSUE THREAD

**Issue by alexwiz91** [MicrosoftDocs/vsts-docs#6060]
It appears that Download as Zip will ignore submodules that are in a Git repo. Is there any chance that in the future this will also download all of the submodules as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35cd88fb-ff0f-5c7a-4c69-e3bb850836b4
* Version Independent ID: d29e4f48-37d9-c581-0fc5-91cc6829df1b
* Content: [Browse repos, files, branches, pushes, commits, pull requests - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/public/browse-code-public?view=azure-devops#feedback)
* Content Source: [docs/organizations/public/browse-code-public.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/public/browse-code-public.md)
* Product: **devops**
* Technology: **devops-public-projects**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
