### ISSUE TITLE
Keys No Longer Work

### ISSUE THREAD

**Issue by pegues** [MicrosoftDocs/vsts-docs#6072]
I've been struggling with getting a git clone to work across SSH for a couple weeks, and it seems as though a growing number of people are having the same problem. I use putty plink with Git Bash, and this has worked for ages for managing my private keys when needed. About 6 months ago this stopped working for Azure DevOps. The problem is not with my keys as they all continue to work with Github and Bitbucket.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64e85ff9-9add-d15c-e92f-02d7dd05e0f2
* Version Independent ID: 0cbd7427-6acd-3cfc-1a3b-8bf5ca60f3bd
* Content: [Connect to your Git repos with SSH - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/use-ssh-keys-to-authenticate?view=azure-devops#feedback)
* Content Source: [docs/repos/git/use-ssh-keys-to-authenticate.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/use-ssh-keys-to-authenticate.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21). 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
