### ISSUE TITLE
Tooling to quickly design WIT forms?

### ISSUE THREAD

**Issue by chekm8** [MicrosoftDocs/vsts-docs#6076]
I am working on porting custom WIT forms to the "new form" format.

Is there WYSIWYG tooling to be able to quickly visualize the custom work item form changes?  It is tedious to use witadmin to import changes, validate the page, make additional changes etc.  I didn't see anything in this article that talks to tooling to be able to design the forms easily.

https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/reference/xml/weblayout-xml-elements.md

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 

Also, the product teams aren’t always watching this repository, so to make sure your suggestion gets in front of them for triage, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
