### ISSUE TITLE
How do you setup notifications for builds regardless of their status when using yaml workflows?

### ISSUE THREAD

**Issue by xt0rted** [MicrosoftDocs/vsts-docs#6085]
Something changed with this integration and I no longer get notifications when builds complete. I'm guessing this is a result of using yaml workflows which give you multiple options to pick from but no matter what configuration I pick I still don't receive notifications that my builds have completed (failed or success). All I want is a simple "a build happened" message like I used to get.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99a6f5aa-7e92-a028-d13e-e1e4b7fede86
* Version Independent ID: be7e5d7c-0033-6b72-4bd1-809f7d1894aa
* Content: [Azure Pipelines with Slack - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/integrations/slack?view=azure-devops)
* Content Source: [docs/pipelines/integrations/slack.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/integrations/slack.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @atinb
* Microsoft Alias: **atinb**

**Comment by dmitrybelyakov** [comment]
Same here, we are creating a pipeline using the DevOps UI but there is no way to subscribe to "Build completed". This used to work just recently but doesn't work any longer. The only events we can subscribe to now are: Run state approval change, Run stage state change, Run stage waiting approval, Run state changed. So as you can see, Build Completed is gone from the list.

**Comment by msebolt** [comment]
@xt0rted  Thank you for the feedback.

This sounds like a product issue and should be directed to the product team.

Please use **Report a problem** in the [Azure DevOps community](https://developercommunity.visualstudio.com/topics/Azure+DevOps.html) and link back to this issue.

**Comment by atinb** [comment]
@xt0rted 
Most likely you have turned on Multi stage pipelines from the Preview features (as below)

![MultiStagePipelines](https://user-images.githubusercontent.com/12844776/67377820-e3183680-f5a3-11e9-83de-e3023dff2a9e.png)

With multi-stage pipelines, the Build completed event is replaced by the 4 events you mention below. You can subscribe to “Run State Changed” event which will give you the same behavior as Build Completed event or if you turn off the preview flag, you will get back the Build completed event in the list.
Thanks!

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).

**Comment by rageshm110** [comment]
I am getting the same issue. The yml based build is not triggering any state change to the slack channel which I created yesterday. The build complete notification is still triggering to another channel where I had configured the notification earlier.

**Comment by rageshm110** [comment]
Reported at https://developercommunity.visualstudio.com/content/problem/872077/azure-devops-slack-integration-build-notification.html
