### ISSUE TITLE
Dynamically instantiate vsts agent containers

### ISSUE THREAD

**Issue by aelray** [MicrosoftDocs/vsts-docs#6089]
Hello,
is there a way to dynamically create vsts agent docker containers on demand if the queue is filling up?

BR,
Adel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31d4f6c-d16d-2ba1-1294-6aa94e328046
* Version Independent ID: 88aec599-4410-697d-1002-1c41b1c17bb6
* Content: [Running a self-hosted agent in Docker - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops)
* Content Source: [docs/pipelines/agents/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/docker.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@aelray  Thank you for the question, assigning this to the author for review.

Have tried using the [Bash](https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash?view=azure-devops) or [Command-line task](https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line?view=azure-devops&tabs=yaml) to run the agent via `docker` command?

**Comment by aelray** [comment]
@msebolt No I haven't tried using the Bash or the Comman-line task. So your idea is to configure a pipeline which instantiates a self-hosted agent in Docker when a build is queued?

**Comment by msebolt** [comment]
Yes, first check if the `docker run` syntax (see [docker run](https://docs.docker.com/engine/reference/run/)) runs from the command line.

Then, add the command to a **Bash** or **Command-line** task for local machines.

For remote machines you might need to use a script with either the [SSH](https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/ssh?view=azure-devops) or [PowerShell on remote machines](https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/powershell-on-target-machines?view=azure-devops) task (Windows).

**Comment by aelray** [comment]
@msebolt Thank you for the idea, but it seems kind of uncomfortable because you have to manage the instances. It would be nice if there would be some kind of mechanism as in [Gitlab](https://docs.gitlab.com/runner/configuration/autoscale.html).

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
