### ISSUE TITLE
Rationale for inability to define an ENTRYPOINT on Linux containers?

### ISSUE THREAD

**Issue by Adnn** [MicrosoftDocs/vsts-docs#6091]
This page states the following among the linux requirements:

> The Azure Pipelines system requires a few things in Linux-based containers:
> * ...
> * Does not define an ENTRYPOINT

This last point seems extremely restrictive: its is a very widespread pattern in Linux based images to rely on the following in their dockerfile:

    ENTRYPOINT ["/docker-entrypoint.sh"]

This script is usually responsible for the initial setup of the container to make it usable.

Then the container can be started with a default `CMD`, or with a command line value overriding this `CMD`. 

Why is such a stringent limitation in place? Can it be worked around? (i.e., how to make sure to run the initial container configuration?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3339a2e0-be29-1363-f588-b231d4472c02
* Version Independent ID: 72dd11a3-704d-d0fd-6dfa-cf49f3352de3
* Content: [Container Jobs in Azure Pipelines and TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/process/container-phases.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/container-phases.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thomps23
* Microsoft Alias: **macoope**

**Comment by msebolt** [comment]
@Adnn  Thank you for the question, assigning this to the author for review.

For the limitation concern and/or anything else that involves the product team, please use **Report a problem** or **Suggest a feature** in the [Azure DevOps Community](https://developercommunity.visualstudio.com/spaces/21/index.html) and link back to this issue.

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
