### ISSUE TITLE
missing how to reference step output from a job from a different stage

### ISSUE THREAD

**Issue by drdamour** [MicrosoftDocs/vsts-docs#6100]
i'm not sure it's psossible but the examples include how to reference output vars from other jobs, other matrix/slice jobs, but they don't mention how to reference output from another stage's job output.  Is that supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@drdamour  Thank you for the question.

Currently it's only possible by using [multi-job output variables](https://docs.microsoft.com/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#set-a-multi-job-output-variable).

There's a good post on this [here](https://stackoverflow.com/questions/57485621/share-variables-across-stages-in-azure-devops-pipelines).

**Comment by drdamour** [comment]
@msebolt i didn't understand your response, you say it's possible, but then link to a stack item that says it's NOT possible.  Is it possible or not?  with the multi-job where you specify the job name, what if two different stages have the same job?

**Comment by drdamour** [comment]
looks like it still does NOT work across stages https://github.com/microsoft/azure-pipelines-tasks/issues/4743#issuecomment-539585951 or at least i'm not the only one confused

**Comment by msebolt** [comment]
I misread the StackOverflow post, this only works between Jobs but not between Stages.

**Comment by drdamour** [comment]
does it warrant a note in this doc that you can't use values across stages?

**Comment by msebolt** [comment]
Possibly, I'll assign this to the author for review.

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).

**Comment by drdamour** [comment]
@mijacobs dont think you read the thread. The outstanding question is if the inability to reference output bars across stages is not yet possible

**Comment by drdamour** [comment]
@mijacobs  can you revisit please?

**Comment by mijacobs** [comment]
@juliakm Can you take a look? This issue was originally tagged as a product-question but it looks like a doc enhancement.

**Comment by juliakm** [comment]
@drdamour Thanks for flagging this. I've added a line to [Set a multi-job output variable](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#set-a-multi-job-output-variable) stating that multi-job output variables will only work for jobs in the same stage. 

The workaround for now is to persist the variable in an artifact.

**Comment by drdamour** [comment]
@juliakm workaround is not viable if you want to use the value as a condition of the stage.

And if you use a deployment job you can only skip a stage prior to approval.  Very sad
