### ISSUE TITLE
Publish third party tool (Static Analysis results) results to Azure Devops

### ISSUE THREAD

**Issue by nareshsudhaakar** [MicrosoftDocs/vsts-docs#6103]
Gentlemen's,

Do we've a provision to publish a third party commercial static analysis results (HTML/PDF/XML) to Azure Devops? If so, could you kindly help me in guiding the steps?

**Comment by WilliamAntonRohm** [comment]
@nareshsudhaakar, thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 

Also, thanks for the suggestion! The product teams aren’t always watching this repository, so to make sure it gets in front of them for triage, please [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here. 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
