### ISSUE TITLE
YAML pipeline report status

### ISSUE THREAD

**Issue by Gijsreyn** [MicrosoftDocs/vsts-docs#6110]
The report deployment status badge is not available for YAML based pipelines. 

My expectation would be that when performing a "build" stage in YAML, that this is reported back after the build is success. Yet only when the whole pipeline is finished, only this is placed on the work items. 
Releases aren't even available. Is there any documentation available?

**Comment by WilliamAntonRohm** [comment]
@Gijsreyn -- Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.

**Comment by Gijsreyn** [comment]
@WilliamAntonRohm 
Thank you for your response. 

On the release pipeline the "Report deployment status to Boards" is available. So when having for example these stages:

![image](https://user-images.githubusercontent.com/26114636/67456028-b4e03880-f62f-11e9-92ef-ef2903a62db2.png)

We first have our building stage that produces the artifact. I selected the "Automatically link work items included in this run", but this is only set when all stages are finished. In our case we also have an extra check on environment. Conclusion, our users aren't notified on the boards itself if it is released to test nor even to production. It only says that the build succeeded. Is this option already available for YAML?

**Comment by WilliamAntonRohm** [comment]
@Gijsreyn -- thank you for clarifying.  This appears to be a product-related issue, rather than a documentation issue.  The product teams aren’t always watching this repository, so to make sure it gets in front of them for triage, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21). 

Also, you may find additional information here:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 

If you have in mind a specific article in our documentation, please let me know.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
