### ISSUE TITLE
Bulk add with excel problem

### ISSUE THREAD

**Issue by okutbay** [MicrosoftDocs/vsts-docs#6112]
I'm using excel to bulk add my features and product backlog items. But when adding a product backlog item as child of a feature system creates the link with "dublicate" link type by default as far as i see. I could not find a way to fix it or adding with a different link type. Help needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 505849d3-01c8-a2cd-dc6c-271dd1120e2d
* Version Independent ID: 577fc252-60e4-f670-bb92-6bdbcb7d5c69
* Content: [Bulk modify work items using Microsoft Excel - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/office/bulk-add-modify-work-items-excel?view=azure-devops#feedback)
* Content Source: [docs/boards/backlogs/office/bulk-add-modify-work-items-excel.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/office/bulk-add-modify-work-items-excel.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by okutbay** [comment]
![image](https://user-images.githubusercontent.com/30014/67403130-339a8e80-f5ba-11e9-9046-d187d8f5d461.png)

![image](https://user-images.githubusercontent.com/30014/67403303-63e22d00-f5ba-11e9-8f4c-a086067eb00f.png)

**Comment by WilliamAntonRohm** [comment]
Thanks for your feedback. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your questions: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 

 
I am closing this issue now.  You are welcome to @ mention me for any followup, including possible documentation updates.  We hope to hear from you again.

**Comment by okutbay** [comment]
Thanks for your reply. I just wanted an extension on document related to this problem.
