### ISSUE TITLE
Double-quote error

### ISSUE THREAD

**Issue by vanbroup** [MicrosoftDocs/vsts-docs#6121]
The double-quote error as shown in the example is shown when importing a CSV with newlines and quotes exported by Excel for Office 365.

I find it strange that it's not possible to import a CSV file that is generated by Excel.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4296d1cc-f211-9d17-d97f-2b0858fdea7d
* Version Independent ID: cc66dfee-adde-cdfb-b3f5-5d58d89d3c81
* Content: [Import work items from a csv file through the web - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/import-work-items-from-csv?view=azure-devops#feedback)
* Content Source: [docs/boards/queries/import-work-items-from-csv.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/queries/import-work-items-from-csv.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@vanbroup  Thank you for the feedback.

There is a similar issue currently active with the product team posted [here](https://developercommunity.visualstudio.com/content/problem/782030/error-tf401232-when-importing-csv-of-work-items.html).  If this describes what you're experiencing please add a comment there and/or link back to this issue.

Also, an Excel work-around has been posted [here](https://developercommunity.visualstudio.com/content/problem/308154/is-there-any-way-to-import-the-work-items-from-a-e.html), please see if this can be used in the interim.

**Comment by vanbroup** [comment]
Thanks, they look to have fixed the double quote manually, this is not really an option with hunderds of records.

The plugin work-around is an option and this seams to work (when you have administrator rights and don't mind to make your excel a little unstable).

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or a question specific to your scenario or implementation, or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
