### ISSUE TITLE
Azure SQL Database deployment VSTS TASK : Error Message : System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: One or more errors occurred. when Task is configured with "AADAuthenticationIntegrated"

### ISSUE THREAD

**Issue by kohithms** [MicrosoftDocs/vsts-docs#6146]
Hi Team,

We are using Azure SQL Database deployment VSTS TASK in the pipeline. When we are using the SQL server credentials its started working. When we switch to "**aadAuthenticationIntegrated**" system is throwing error. 

**Error Message**: System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: One or more errors occurred.

Could you kindly share the way to implement the option of "aadAuthenticationIntegrated" 

**Reference links followed :** 
https://docs.microsoft.com/en-us/azure/devops/pipelines/targets/azure-sqldb?view=azure-devops

**Comment by WilliamAntonRohm** [comment]
@kohithms -- Thank you for your feedback. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 

I am closing this issue now.  You are welcome to @ mention me for any followup, and if the documentation needs to be updated.
We hope to hear from you again.
