### ISSUE TITLE
Can't have two resources under the same environment with the same namespace

### ISSUE THREAD

**Issue by balteravishay** [MicrosoftDocs/vsts-docs#6150]
When trying to create two k8s resources, under the same environment, referencing different clusters with the same namespace getting an error for:  "Resource 'namespace' already exists in current environment".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7730ae4d-4101-9c83-1823-4ff43ff161ce
* Version Independent ID: 20a7e263-4819-783e-c984-c4f3b459e22f
* Content: [Environment - Kubernetes resource - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments-kubernetes?view=azure-devops)
* Content Source: [docs/pipelines/process/environments-kubernetes.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/environments-kubernetes.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbarsin
* Microsoft Alias: **shasb**

**Comment by msebolt** [comment]
@balteravishay  Thank you for the feedback, I will assign this to the author for review.

Please note that for feature requests and/or product limitations, items need to be submitted to the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) for the product team to assess.

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or a question specific to your scenario or implementation, or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
