### ISSUE TITLE
make a note this isn't supported in yaml yet

### ISSUE THREAD

**Issue by drdamour** [MicrosoftDocs/vsts-docs#6166]
AFAIK this still is not supported in yaml, can a note be added with a link to an issue to track?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1c633b9-c8b2-e05d-de2c-7754894d28fd
* Version Independent ID: df031b76-0fe7-e138-dd36-2736757a97fd
* Content: [Manual Intervention task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/manual-intervention?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/manual-intervention.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/manual-intervention.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment]
@drdamour  Thank you for the feedback, assigning this to the author to review and confirm.

**Comment by drdamour** [comment]
@msebolt @RoopeshNair any update on this one?

**Comment by RoopeshNair** [comment]
Created [PR#726](https://github.com/MicrosoftDocs/azure-devops-docs-pr/pull/726) for doc update

**Comment by MarkIannucci** [comment]
@RoopeshNair, I wanted to revisit this thread; thank you for getting the document updated.  

From reading #4362, you stated that the functionality may be 4-5 months out in [September](https://github.com/MicrosoftDocs/vsts-docs/issues/4362#issuecomment-533177379), and then 8 weeks later, you stated the [same timeframe](https://github.com/MicrosoftDocs/vsts-docs/issues/4362#issuecomment-558565264).  

Can you add this to the [Azure DevOps feature timeline](https://docs.microsoft.com/en-us/azure/devops/release-notes/features-timeline)?  My hope is that if this functionality gets added to the feature timeline, Microsoft will announce it in the release notes when your team gets it done and we'll be able to refactor our releases away from the environments workaround and instead use the manual intervention task in yaml.

If you're wondering about our use case, we're hoping to use a multi-stage yaml release pipeline to track the deployment of upgrades to our electronic medical record system.  These deployments involve updating proprietary software which use different deployment strategies based on when our vendor originally released the software.  We may attempt to use environment approvals as a workaround, but we expect the yaml will be quite ugly given the many steps we have.  We also expect that using environments as manual interventions in Azure DevOps will be somewhat confusing since we currently think of environments as places where dev, test, and production happen.

**Comment by drdamour** [comment]
@MarkIannucci FWIW i've been using the environemnts as approval and it's pretty rough going if you want do things conditionally. It appears the current behaviour is that if ANY job in a stage references an environment then the whole stage is approved or not approved.  that combined with the inability to pass data between stages (for the most part) means you can't conditionally run a stage that targets an environment.  The workarounds are very rough...

**Comment by MarkIannucci** [comment]
@drdamour , thank you for piping up on this.  We spent a little bit of time attempting to get the environment approval functionality to try to work in place of the manual intervention task and agree with your assessment that the workarounds are indeed very rough.  

As such, we're going to stick with the classic pipelines until the manual intervention task functionality is available in multi-stage yaml pipelines.  Hopefully that functionality will come quickly because not being able to version the pipeline with the code is an unfortunate limitation in the classic pipelines.
