### ISSUE TITLE
REST API for Library

### ISSUE THREAD

**Issue by bakgaard** [MicrosoftDocs/vsts-docs#6173]
Is there an API for updating the Library's variables?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2fe2521-cc98-8946-89b4-5a8199a6d898
* Version Independent ID: dbc4b6cf-ddb1-ac16-c634-eaf15072e111
* Content: [Library for Azure Pipelines and Team Foundation Server - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/index?view=azure-devops#security)
* Content Source: [docs/pipelines/library/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/index.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
