### ISSUE TITLE
Trying to use output variables from tasks in the same job

### ISSUE THREAD

**Issue by Lizzie42** [MicrosoftDocs/vsts-docs#6174]
In my custom extensions I'm trying to use output variables from one task in another with the $(firstTask.variableName) format in a downstream task.  The input fields don't throw errors when I type this format in, however, when I try to save & queue my pipeline, I get this error: 

The pipeline is not valid. Job Job_1: Step input variableName references $(firstTask.variableName) which could not be found.

Any ideas?

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
