### ISSUE TITLE
Error while running Linux self-hosted agent as non-root user

### ISSUE THREAD

**Issue by hajtomoto** [MicrosoftDocs/vsts-docs#6178]
Is it possible to start self-hosted agent as a non-root user?
e,g. changing user in Dockerfile like this:
USER docker
CMD  ["./start.sh"]

or changing it within the "start.sh" script:
sudo -u docker bash << EOF
exec ./externals/node10/bin/node ./bin/AgentService.js interactive
EOF

I do not want to run as ROOT for security reasons, I need to start Build Agent as non-root user.

I tried both these methods and getting errors, e.g:

_"Unhandled Exception: System.UnauthorizedAccessException: Access to the path '/azp/agent/_diag/Agent_20191029-160306-utc.log' is denied"_

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
