### ISSUE TITLE
Missing operators under filters

### ISSUE THREAD

**Issue by rwronsky** [MicrosoftDocs/vsts-docs#6182]
Hi,
I’ve set up the burnup analytics widget but for some reason the only operators exposed are = and &lt;&gt;. 
This is the case for standard fields as well as custom ones which is quite limiting. 
I noticed on the examples there are more that I can uses regularly similar to using the queries. 
Is there a way to enable others such as “contains” etc...
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9d627b9-9aa8-c52c-3178-cffbefe9727a
* Version Independent ID: 31967bb3-2635-da97-782c-641f432750f7
* Content: [Configure Burndown & Burnup widgets - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/configure-burndown-burnup-widgets?view=azure-devops#feedback)
* Content Source: [docs/report/dashboards/configure-burndown-burnup-widgets.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/dashboards/configure-burndown-burnup-widgets.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 

 
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
