### ISSUE TITLE
Unable to Use Private Feeds in Build Pipelines

### ISSUE THREAD

**Issue by mfj082** [MicrosoftDocs/vsts-docs#6185]
After the update on 10/27 we are no longer able to create organization level artifacts which was expected as part of Microsoft's change. However, due to this change the only feeds that we can publish to are organizational level feeds (which we are no longer able to create). I am assuming we could also publish to public feeds but I do not want a public project or feed. Any feed that is created now after the update is not found by the build pipeline since it is a project specific feed. I am getting the following error even though the feed exists and I can select it from the dropdown in the classic view (and yaml as well).

![feed-publish-error](https://user-images.githubusercontent.com/43255452/67813181-81a20d00-fa66-11e9-8830-572f1a74b91e.png)

This exact process worked before the update and now we cannot use the private project feeds. Please help as this has broken our workflow for releases.

**Comment by WilliamAntonRohm** [comment]
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21). 

Also, you may find answers here:

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 

 
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
