### ISSUE TITLE
Need APIs to add and remove user defined capabilities to self hosted agents

### ISSUE THREAD

**Issue by vemulavenkatesh** [MicrosoftDocs/vsts-docs#6205]
We have a pool of ~100 self hosted agents with a set of user defined capabilities based on the version of our product installed on the agent and a release pipelines that can update the version of the product on the agent machines. We need to remove capabilities on the agent while updating the agent and add the new capability after updating the agent. Are there any APIs to add and remove user defined capabilities to self hosted agents which can be leveraged in our release pipelines. Currently we are manually removing and adding the capabilities after our release pipeline succeeds.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47625b86-abd5-ee15-6d61-8bcf81861b96
* Version Independent ID: be9a6174-a69b-7aed-d584-5f602fcc5eb4
* Content: [Azure Pipelines Agents - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/agents.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/agents.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@vemulavenkatesh Thank you for the question.

Please refer to the [Agent REST API](https://docs.microsoft.com/rest/api/azure/devops/distributedtask/agents?view=azure-devops-rest-5.1) and comment below any additional questions.

**Comment by msebolt** [comment]
Closing the issue now, please add additional comments below.

**Comment by joseq-terawe** [comment]
even in looking at "Agent REST API" link. still not able to patch an updated custom object to add a userCapabilities section with value.

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).

**Comment by mdrakiburrahman** [comment]
For anyone that runs into this, there's a creatively documented solution here:

https://blogs.blackmarble.co.uk/rfennell/programmatically-adding-user-capabilities-to-azure-devops-agents/
