### ISSUE TITLE
How to enable Test Management in our project?

### ISSUE THREAD

**Issue by FredConklin** [MicrosoftDocs/vsts-docs#6220]
I see from the closed issue that this should be available -  Is it available upon request? What steps do we need to see it in our Azure DevOps Services project?  (Today is October 31 2019 and it appears that it is available to some accounts.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8dfb3bf-8cce-7ad8-b2c6-40d6c2b9d441
* Version Independent ID: 53e2d39d-6808-70d5-9c26-bc4c5bb109e3
* Content: [Flaky test management - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/flaky-test-management?view=azure-devops#feedback)
* Content Source: [docs/pipelines/test/flaky-test-management.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/test/flaky-test-management.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 

 
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
