### ISSUE TITLE
Filters for individuals?

### ISSUE THREAD

**Issue by mack0196** [MicrosoftDocs/vsts-docs#6262]
Today I can filter for pull requests for groups set as reviewers. 
When will the feature allow me to filter on individuals in reviewer filed of the pull request?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fd5671b-b7b8-9acb-c195-7897fec3538b
* Version Independent ID: ff894c1b-f2f7-581d-94b4-dbc77d80ad6d
* Content: [Create a service hook for Azure DevOps Services and TFS with Slack](https://docs.microsoft.com/en-us/azure/devops/service-hooks/services/slack?view=azure-devops#feedback)
* Content Source: [docs/service-hooks/services/slack.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/service-hooks/services/slack.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by msebolt** [comment]
@mack0196 Thank you for the feedback.

Unfortunately we are unable to handle product requests in this forum, instead please use the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html).

For product team involvement, please see if [this post](https://developercommunity.visualstudio.com/idea/447657/ability-to-filter-any-query-or-dashboard-by.html) addresses the issue, then either vote, add comment, or re-post.

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or a question specific to your scenario or implementation, or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
