### ISSUE TITLE
Project level permissions clarification

### ISSUE THREAD

**Issue by melezhik** [MicrosoftDocs/vsts-docs#6263]
Hi!

My scenario:

1. I am the member of project Foo admins ado group - `[Foo]\Project Administrators`. 

I assume that that Ado group has administrator privileges for _all_ the project's Ado security tokens ( Library, Git Branches and so )

2. I accidentally **removed all the permissions** from project Library security token using Azure devops RestAPI:

```
POST https://dev.azure.com/mycompany/_apis/accesscontrollists/b7e84409-6553-448a-bbb2-af228e07cbeb?api-version=5.1

{

"value": [
    {
      "inheritPermissions": false,
      "token": "Library/$project_id",
      "acesDictionary": {
            "some-security-descriptor": {
          "descriptor": "some-security-descriptor",
          "allow": 0,
          "deny": 63
        }
        }
      }
    }
 ]
}

```

3. I end up losing access  to the project Library. Because permissions were effectively erased for ALL the users. I can't either manage Library permissions any longer ( neither through web UI or az cli or Rest API ) nor create new variable groups.

---

Why can't restore my permissions, because I am still a member of project admins group and I _assume_ that I can change back any permissions related changes related to _the_ project.

**Comment by melezhik** [comment]
For me it boils down to the fact that higher level hierarchy privileges ( which is a being a project level administrator ) should allow to changes lower level privileges ( which is a project's Library ).  It least that impressions I bore from reading security permissions documentation - https://docs.microsoft.com/en-us/rest/api/azure/devops/security/?view=azure-devops-rest-5.1

**Comment by msebolt** [comment]
@melezhik Thank you for the feedback.

Please see if [this issue](https://developercommunity.visualstudio.com/idea/681695/enable-project-administrators-to-view-team-member.html) addresses the problem, then vote, comment, and/or link back to this issue.

**Comment by melezhik** [comment]
@msebolt  I've just read this, no it does not. It's a different issue.

**Comment by msebolt** [comment]
@melezhik  Thank you for the update.

Your options are then to either:

- File a new issue with the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html)
- Find a related article and have it assigned to the author

Apologies for not having a better solution, we are just unable to accommodate product issues and/or support requests in this forum.

**Comment by melezhik** [comment]
@msebolt , thank you. ticket created
https://developercommunity.visualstudio.com/content/problem/810100/project-level-permissions-clarification.html

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or a question specific to your scenario or implementation, or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
