### ISSUE TITLE
Path filters improvements

### ISSUE THREAD

**Issue by Weiman74** [MicrosoftDocs/vsts-docs#6265]
For CI trigger, it doesn't seem to possible to include/exclude based on file extension. For example exclude *.build.
This would be greatly appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@Weiman74 Thank you for the feedback.

Unfortunately the feature is not yet supported, refer to [this work-around](https://stackoverflow.com/questions/55731861/exclude-file-types-in-ci-triggers-on-azure-devops-pipelines-builds).

For it's current status with the product team, please see [this issue](https://developercommunity.visualstudio.com/idea/366363/support-wildcards-in-trigger-path-filters-1.html) in the **Azure DevOps community**.

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or a question specific to your scenario or implementation, or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).

**Comment by msebolt** [comment]
Closing the issue now, please add additional questions below.

For further reference:

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
