### ISSUE TITLE
Release pipeline in code

### ISSUE THREAD

**Issue by aleksmark** [MicrosoftDocs/vsts-docs#6267]
Is it possible to define release pipelines in YAML file?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63234ade-28cc-02fc-a319-42e3491da601
* Version Independent ID: 7ccbfe96-d61e-8bf2-de22-61150d648abd
* Content: [Release pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/?view=azure-devops)
* Content Source: [docs/pipelines/release/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/index.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment]
@aleksmark  Thank you for the question.

This feature has been released in the preview version.

Please refer to [this post](https://devblogs.microsoft.com/devops/whats-new-with-azure-pipelines/) and comment below if there are additional questions.

**Comment by aleksmark** [comment]
@msebolt thank you for quick response.

My question was regarding these release pipelines 
https://docs.microsoft.com/en-us/azure/devops/pipelines/release/?view=azure-devops

![image](https://user-images.githubusercontent.com/14918537/68250956-6dd84700-0022-11ea-9435-4176d566feb5.png)

**Comment by msebolt** [comment]
Sure, no problem.  I'll go ahead and assign this to the author for review.

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
