### ISSUE TITLE
Created work item does not have a link to the Wiki page

### ISSUE THREAD

**Issue by bcjmk** [MicrosoftDocs/vsts-docs#6272]
When I create a task from the wiki page, the text on the Wiki is replaced with the Work Item link. Unfortunately, in the Work Item there is no corresponding link back to the associated Wiki page, much less back to the specific link. Is it possible to create the 2-way links automagically?
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bb2f69a-9f0c-3e46-42a4-45027afd8ef4
* Version Independent ID: 244bbebf-40f4-8ee3-14c6-86c5f8e7f99b
* Content: [Create and embed a work item from wiki - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/create-embed-wit-from-wiki?view=azure-devops#feedback)
* Content Source: [docs/project/wiki/create-embed-wit-from-wiki.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/create-embed-wit-from-wiki.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@bcjmk -- here are a couple of options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 

Also, it looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21). 

@chcomley -- please look into this issue.

**Comment by chcomley** [comment]
Hi @bcjmk, Thanks for reaching out. I believe it's an unimplemented feature rather than a bug. 
I'm not aware of any plans to automatically create a Wiki page link within the work item to the Wiki page...when the user mentions a work item in a wiki page. I'd recommend that you [submit your idea](https://visualstudio.microsoft.com/vs/support/#talktous).
