### ISSUE TITLE
Publish pipeline artifacts in to a single folder with multiple pusblish jobs when using multiplier on a variable

### ISSUE THREAD

**Issue by bganapa** [MicrosoftDocs/vsts-docs#6274]
I have a publish pipeline artifact like below
steps:
- task: PublishPipelineArtifact@1
  displayName: 'Save Package'
  inputs:
    targetPath: 'src/StackAdmin/$(ServiceName)/bin/'
    artifact: StackPackages

I have a multiplier on the variable ServiceName.  So multiple builds and and publish pipeline artifacts are being kicked off. 

The pipeline  fails with the following
Artifact StackPackages already exists for build 39.

This means that StackPackages folder already exists as another publish pipeline artifact has already created this folder. This happens as I have the Multiplier on the variable ServiceName. What I really want is to publish all the artifacts in to a single folder named StackPackages. Is there a way to achieve that? Thanks for your pointers.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41baa0b5-175c-a697-4b7d-c150259c6e6b
* Version Independent ID: 75085b15-1acc-526a-0495-74a13c42c1d5
* Content: [Publish Pipeline Artifacts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-pipeline-artifact?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/utility/publish-pipeline-artifact.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/publish-pipeline-artifact.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @willsmythe
* Microsoft Alias: **wismyth**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
