### ISSUE TITLE
Guidance for multi-platform builds?

### ISSUE THREAD

**Issue by craigktreasure** [MicrosoftDocs/vsts-docs#6284]
Our build uses the matrix build strategy to run multiple builds in parallel. Is there guidance on how to configure a cache in this scenario?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c20289-dab2-7a6e-4f63-4b30eaff2c71
* Version Independent ID: d75cc196-90c1-8291-9907-ff405bde4edf
* Content: [Pipeline caching - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/caching/?view=azure-devops#q--a)
* Content Source: [docs/pipelines/caching/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/caching/index.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @willsmythe
* Microsoft Alias: **wismythe**

**Comment by WilliamAntonRohm** [comment]
@craigktreasure -- Craig, thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 

 @willsmythe -- Will, please look into this issue.

**Comment by justhchung** [comment]
Thank you for your feedback. 
We are closing this issue and directing you to seek an answer through our support web site: [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).
