### ISSUE TITLE
Is there a predefined variable for a build pipeline's "default branch for manual and scheduled builds"?

### ISSUE THREAD

**Issue by edgariscoding** [MicrosoftDocs/vsts-docs#6286]
I need to be able to reference the "default branch for manual and scheduled builds" instead of the build.sourceBranchName because this variable changes if the build is queued by a PR.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#systemdebug)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
@edgariscoding -- Edgar, thanks for your question. Here are a couple of options where you may find answers: 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 

@juliakm -- Julia, please look into this issue.

**Comment by damccorm** [comment]
Hey edgariscoding - we don't get/expose that data anywhere. If you need it, you can [query the GitHub API for it](https://stackoverflow.com/questions/16500461/how-do-i-find-the-default-branch-for-a-repository-using-the-github-v3-api) if its a GitHub repo. This also tends to be a static value, so you're probably also safe just storing it as a variable in your YAML.

I'm going to close since the docs are correct here.
