### ISSUE TITLE
Document of Custom Task creation using Powershell Module

### ISSUE THREAD

**Issue by shivakumarg06** [MicrosoftDocs/vsts-docs#6293]
Hi Team, 

I am very new to this Custom task Platform, I have referred multiple Node Modules based Custom Task, are there any documents for creating Custom Tasks using Powershell Module and debug on local

**Comment by msebolt** [comment]
@shivakumarg06 Thank you for the question.

Please refer to the [Build Node.js apps](https://docs.microsoft.com/azure/devops/pipelines/ecosystems/javascript?view=azure-devops) and [Node tool installer task](https://docs.microsoft.com/azure/devops/pipelines/tasks/tool/node-js?view=azure-devops) tutorials and post any questions or missing items below.  

We are always welcome to new ideas and suggestions.

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
