### ISSUE TITLE
Does the API still work with Azure DevOps Server 2019

### ISSUE THREAD

**Issue by StavroulaSsi** [MicrosoftDocs/vsts-docs#6294]
Hi, 
Does the API still works with VS2019 and Azure DevOps Server 2019? I am quite confused after reading this page and this article: https://devblogs.microsoft.com/devops/announcing-the-deprecation-of-the-wit-and-test-client-om-at-jan-1-2020-2/

So, can we upgrade to 2019 first and replace the API by the REST calls afterwards?

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58fa4b52-1f5c-11c5-329b-2526613833fa
* Version Independent ID: 6d1fb152-1612-a0ec-06fc-4ea2e2135541
* Content: [Deprecation of the Work Item Tracking (WIT) and Test Client OM - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/wit-client-om-deprecation?view=azure-devops#feedback)
* Content Source: [docs/integrate/concepts/wit-client-om-deprecation.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/concepts/wit-client-om-deprecation.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **liho**

**Comment by msebolt** [comment]
@StavroulaSsi  Thank you for the question.

The SOAP calls should still be functional, though no longer supported, and you will have issues trying to use Visual Studio against functionality marked obsolete, see [this post](https://stackoverflow.com/questions/10608309/disabling-obsolete-error-in-c-sharp), so I would avoid upgrading the DLLs until you are ready to migrate. 

Assigning this to the author for further confirmation.

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
