### ISSUE TITLE
Is the key added to SSH agent?

### ISSUE THREAD

**Issue by Adnn** [MicrosoftDocs/vsts-docs#6296]
The page does not give details regarding how is the private key actually deployed on the instance running the `SSH Key task`.

Is it made available via ssh-agent? (which would be invaluably useful for agent forwarding in subsequent steps)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ce9d017-fc43-c904-d94b-87cf91265ffc
* Version Independent ID: ecf3b0b7-6c2c-1cd9-33a9-2cf562932e2b
* Content: [Install SSH Key task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/install-ssh-key?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/install-ssh-key.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/install-ssh-key.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @DavidStaheli
* Microsoft Alias: **dastahel**

**Comment by msebolt** [comment]
@Adnn  Thank you for the question.

This topic is currently under discussion in https://github.com/MicrosoftDocs/vsts-docs/issues/5327.  

Please refer there for more information on how keys are added and for pending updates to the documentation.

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).

**Comment by dermaaarkus** [comment]
@msebolt actually the question is not discussed in #5327 please reopen the issue

**Comment by msebolt** [comment]
@dermaaarkus Apologies for the delay.

One of the items listed in the referenced issue states `sshKeySecureFile - this is a secret/file, how to securely reference this?` which is along the same lines.

Please comment there if you'd like additional information to be added.
