### ISSUE TITLE
Copy folders or multiple files ?

### ISSUE THREAD

**Issue by CmdrGravyWork** [MicrosoftDocs/vsts-docs#6298]
It says that you can't use wildcards so does this means it's only capable of copying single files and not, for example, folders full of files ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 622daa35-c6a1-dac3-17ee-3f9308fc60cd
* Version Independent ID: 2c28a59b-8ef5-d7ab-46a6-58748ec552f5
* Content: [Azure File Copy task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-file-copy?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/deploy/azure-file-copy.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/azure-file-copy.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment]
@CmdrGravyWork Thank you for the question.

Both files and folders are supported, but you must explicitly set the path without use of wildcards.

Lack of wildcards is a known limitation in Azure DevOps, see [this post](https://developercommunity.visualstudio.com/idea/366363/support-wildcards-in-trigger-path-filters-1.html) as an example and for current status with the product team.

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
