### ISSUE TITLE
Outdated part about default permission

### ISSUE THREAD

**Issue by kolodziejczyk0** [MicrosoftDocs/vsts-docs#6306]
The part "When you add members to projects, one of the following permissions is automatically assigned:
Basic access, if you have seats available.
Stakeholder access, if you don't have available seats."
is no longer true. Right now, there is no limit on the seats available and the default access can be chosen from dropdown in the billing configuration for organization.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f798c7a-540e-3df7-985d-f1a52a53231e
* Version Independent ID: fe9362a5-871d-9150-6e39-1e29d150f169
* Content: [Add members, contributors to projects - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/add-team-members?view=azure-devops#feedback)
* Content Source: [docs/organizations/accounts/add-team-members.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/add-team-members.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @kolodziejczyk0, That’s correct! The only caveat is whether or not billing is set up…

**If you don’t have billing setup**
Basic is assigned until you run out

**If you do have billing setup**
Basic is assigned only if your default access level is set to Basic (otherwise Stakeholder)

I'll make this clear in the doc, thanks so much for your feedback!
