### ISSUE TITLE
Is it possible to associate methods in code to test cases using Visual Studio Code?

### ISSUE THREAD

**Issue by alexpercont** [MicrosoftDocs/vsts-docs#6311]
Hello. I see that the documentation is really good and covers associating code with test cases using Visual Studio.

Is it possible to do the same with Visual Studio Code? possibly with Azure Repos extension or any other VSC extension?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d8a7e40-73d6-795f-7b8c-77104ef606e8
* Version Independent ID: 8f15995b-bd94-8d9f-1e8b-82f1f364d221
* Content: [Associate automated tests with test cases - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/associate-automated-test-with-test-case?view=azure-devops&viewFallbackFrom=vsts#feedback)
* Content Source: [docs/test/associate-automated-test-with-test-case.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/associate-automated-test-with-test-case.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@alexpercont -- Alex, thank you for your positive feedback. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your questions: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by SHarrySeldon** [comment]
@WilliamAntonRohm 
Hello! 
Case is still relevant. As I understand there is no feature that replicates associating code(auto tests) with manual test cases  functionality. Is there any workaround? 
Sorry if it's off topic here

**Comment by WilliamAntonRohm** [comment]
@SHarrySeldon -- thank you for your question.  Please consider this resource:
- [Azure Q & A](https://docs.microsoft.com/en-us/answers/products/azure?product=all)

You are welcome to [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.

cc @steved0x for awareness
