### ISSUE TITLE
Separate stages for build and test

### ISSUE THREAD

**Issue by spottedmahn** [MicrosoftDocs/vsts-docs#6329]
It seems that this doc page is combining building and testing in a **single stage**.  That doesn't seem optimal to me.  Upon further researching I found this:

>Stages are the major divisions in a pipeline: "build this app", "run these tests", and "deploy to pre-production" are good examples of stages.

Source: [YAML schema reference -> Pipeline structure](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#pipeline-structure)

---

How about separating the building and testing into different stages on this doc page?  Thoughts?  💭

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec716c61-248c-75c9-2bc7-262749cc7421
* Version Independent ID: 45f47edc-e800-2c42-416a-92cd93c9e892
* Content: [Build, test, and deploy .NET Core apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core?view=azure-devops#run-your-tests)
* Content Source: [docs/pipelines/ecosystems/dotnet-core.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/ecosystems/dotnet-core.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@spottedmahn  Thank you for the feedback, assigning this to the author for review.

**Comment by damccorm** [comment]
Hey @spottedmahn thanks for the feedback! Its definitely true that stages can be used for this kind of divide and this often makes sense, especially as your pipeline becomes more complex (e.g. I might want to build on one platform and test on 3 others, so I can't run all of my steps in a single job). In general, though, its equally valid to build and test in a single job.

For the sake of simplicity, most of our docs try to demonstrate a minimal number of concepts to accomplish the task - that way if you're a beginner and you just want to learn about building/testing .NET Core apps, you don't have to also learn about stages if you don't want to. Additionally, it just keeps it smaller/easier to focus on the key concepts. For those reasons, I think it probably makes sense to keep this demonstration to a single job.

I'm going to close this one since the documentation is correct here, thank you for your suggestion though

**Comment by spottedmahn** [comment]
Hi @damccorm 👋

>For the sake of simplicity, most of our docs try to demonstrate a minimal number of concepts to accomplish the task

Fair enough, I get it, makes sense.  Appreciate the thoughtful response, thanks 😃.
