### ISSUE TITLE
Can't Connect to Azure DevOps with Proxy

### ISSUE THREAD

**Issue by paliotti** [MicrosoftDocs/vsts-docs#6333]
Tried running the command from [here ](https://docs.microsoft.com/en-us/azure/devops/repos/git/require-branch-folders?view=azure-devops&tabs=browser&viewFallbackFrom=vsts) but I keep getting the error:

> TF400324: Team Foundation services are not available from server https://dev.azure.com/ORG-DEVOPS.
> Technical information (for administrator):
>   Unable to connect to the remote server

**Comment by msebolt** [comment]
@paliotti  Thank you for the question.

Please refer to the following posts on [StackOverflow](https://stackoverflow.com/questions/36109895/tf400324-team-foundation-services-are-not-available-from-server-server-collect/48618076) and [MSDN](https://social.msdn.microsoft.com/Forums/en-US/756079b0-d102-4c11-9985-43df1e61e3f2/tf400324-team-foundation-services-are-not-available-from-server?forum=tfsadmin) for possible solutions.

Unfortunately, since this isn't an issue with the documentation, your options for support are limited to:

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you feel this is an issue with the product itself, please submit your bug [here](https://developercommunity.visualstudio.com/content/problem/post.html?space=21) for feedback from the product team.

**Comment by msebolt** [comment]
Closing the issue now, please comment below if there are any further concerns.
