### ISSUE TITLE
TFS 2018 Package Feed SemVer 2.0 Metadata Not Supported

### ISSUE THREAD

**Issue by StephenRSkinner** [MicrosoftDocs/vsts-docs#6334]
I created issue [#6062](https://github.com/MicrosoftDocs/vsts-docs/issues/6062), but it was closed for "lack of information" The title of that and this issue explains exactly what the problem is. 

Please fix the package feed in TFS 2018 so it doesn't blow up on packages that contain SemVer 2.0 metadata, when the feed is configured as a passthrough for NuGet.

**Comment by WilliamAntonRohm** [comment]
@StephenRSkinner -- please clarify your feedback.  Is this a product issue or a documentation issue?  
If it's a product issue, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21). 

If documentation, please add a link to that article.

**Comment by StephenRSkinner** [comment]
In my comment above:

Please fix the package feed in TFS 2018 so it doesn't blow up on packages that contain SemVer 2.0 metadata, when the feed is configured as a passthrough for NuGet.

The evidence, posted in my original issue #6062, clearly states that the package feed gives the following error when you reference a package with SemVer 2.0 Metadata in the version:

The package is invalid: The package version had build metadata. We do not support versions with build metadata.

Even gave an example nuget package: nuget.frameworks.5.0.0.nupkg

I'm confused why people are unable to read these things and understand that this is problem with the TFS 2018 package feed that I'm asking to be resolved.

**Comment by WilliamAntonRohm** [comment]
This repo (vsts-docs) is only for documentation issues, and you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure your suggestion gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21). 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
