### ISSUE TITLE
Team Tab in Microsoft Project not available after installing Azure DevOps Office® Integration 2019

### ISSUE THREAD

**Issue by fgudelj** [MicrosoftDocs/vsts-docs#6338]
Hi all,

I am not seeing Team Tab in MS Project :(

Following office pack is installed:

- Office 365 Pro Plus
- Microsoft Project Online Desktop client.

I have tried re-installing office, as well as Ms Project - no success. I have even isntalled Visual Sturio Enterprise 2019, and still it is not showing.. 

But, I have seen it at colleagues computer that works, and I am not able to figure out why is on his computer working, and on mine not.. Coudl you please heeelp!! 

Thanks!

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
