### ISSUE TITLE
Bugs Managed with Tasks - Not Showing in Annotations

### ISSUE THREAD

**Issue by CyricPL** [MicrosoftDocs/vsts-docs#6342]
I have a project with "Bugs managed as tasks," and I want to add them to the annotations on the Stories board, but only Tasks and Tests appear as options on the board.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c14dbd1f-9b2f-c50a-456b-7efbe9a76d33
* Version Independent ID: fe725f5c-4074-5bea-38c7-ad9e8b8600a7
* Content: [Setup your Backlogs & Boards to display the user stories, issues, tasks, or work item types you want - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/set-up-your-backlog?view=azure-devops#feedback)
* Content Source: [docs/boards/backlogs/set-up-your-backlog.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/set-up-your-backlog.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
@CyricPL -- thank you for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 

 @KathrynEE -- please look into this potential documentation issue.

**Comment by KathrynEE** [comment]
@CyricPL - Thank you for your inquiry. If your team is configured to Show **Bugs managed as tasks**, then you should be able to add them from the Kanban board from any work item type that appears there. 

![image](https://user-images.githubusercontent.com/10856840/70832038-f035f280-1da8-11ea-9467-51a3678f5a35.png)

Once you add the tasks, bugs, or tests - the annotations should automatically  appear. 
![image](https://user-images.githubusercontent.com/10856840/70832518-1c9e3e80-1daa-11ea-9c6d-726b75589f7c.png)

If no bugs are defined - then the annotation for them doesn't appear. 

If this isn't your experience, please reach out to our support team:  [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

I'm closing this issue as there is no documentation update to address
