### ISSUE TITLE
SCVMM Integration network virtualization / boundary VM

### ISSUE THREAD

**Issue by LukasK07** [MicrosoftDocs/vsts-docs#635]
When using network virtualization for hosting an environment and using a boundary vm for connectivity to VMs the boundary is created fine but not registered into DNS. Netbios is not working in my environment due to seperated subnets.

Do i really need the boundary vm or is tfs able to use hyper-v integrated remote powershell?
Do i need to domain join the boundary vm manually or register into dns by script?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 089ea08c-cf03-4fd4-1690-e2540c5ef0f8
* Version Independent ID: 22a07881-4e4a-f531-59ed-dfe0eec4de82
* Content: [Create a virtual network for build-deploy-test scenarios](https://docs.microsoft.com/en-us/vsts/build-release/actions/virtual-networks/create-virtual-network?view=vsts)
* Content Source: [docs/build-release/actions/virtual-networks/create-virtual-network.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/actions/virtual-networks/create-virtual-network.md)
* Service: **unspecified**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed your question on to the product team and let you know the response.

**Comment by RoopeshNair** [comment]
@ashokirla  - can you please take a look?

**Comment by mijacobs** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
