### ISSUE TITLE
Build.ArtifactStagingDirectory incorrect explanation about contents

### ISSUE THREAD

**Issue by Londovir** [MicrosoftDocs/vsts-docs#6353]
In the documents above, for Build.ArtifactStagingDirectory it states that the contents of the directory are purged before each new build and that you do not have to clean it yourself. However, as I was developing a YAML file to use for our one project in-house, where we were using this folder to compile the output files that would eventually get pushed into an artifact, a 2nd build attempt immediately failed during the "Initialize Job" step of the pipeline because "The directory is not empty."

Thus, is seems like it is not necessarily true that the directory is purged, and you do in fact have to clean it yourself or a second pipeline build will fail.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ffebdc8-521c-44b5-cde4-4abdc1bd6f18
* Version Independent ID: dc0effda-6d93-62aa-64c5-4e6f283b0826
* Content: [Predefined variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/build/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@Londovir  Thank you for the feedback, assigning this to the author for review.

**Comment by juliakm** [comment]
I'm working on getting clarification from the product team on how this should work.

**Comment by AndrewCraswell** [comment]
Actually more clarification is needed. I'm having difficulty understanding where artifacts are being downloaded to. I see that by default a job I have is downloading pipeline artifacts that were published in a previous stage. But no matter which path variables I use it seems to say it can't find the files. At a loss, and I see lots of questions on the web where people are having similar issues.

**Comment by juliakm** [comment]
@Londovir I just emailed you. We have a developer that wants to look into your issue in more detail. We're wondering if the initialization error you're seeing is part of the problem. Under normal circumstances, $(Build.ArtifactStagingDirectory) should be where your artifacts go before they are published and should be purged.  

I'm closing this issue for now since it's looking like it is not a docs problem. 

@AndrewCraswell What type of artifact are you trying to publish? If it is .Net, you might find [this section of the .Net article](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core?view=azure-devops#package-and-deliver-your-code) helpful. A lot of people have also found [this Learn module](https://docs.microsoft.com/en-us/learn/modules/manage-build-dependencies/) useful for understanding artifacts better.

**Comment by Chaouki-Tiouassiouine** [comment]
@juliakm it is not fully clear yet. The question here is, is the $(Build.ArtifactStagingDirectory) getting cleaned when a specific run has finished? If that is the case we could safely assume that a next run will work with an empty/clean $(Build.ArtifactStagingDirectory)
