### ISSUE TITLE
SCVMM Integration - Not using differencing disks

### ISSUE THREAD

**Issue by LukasK07** [MicrosoftDocs/vsts-docs#636]
We tested scvmm integration with tfs 18. 

Our scvm template is configured for using differencing disks, in a normal deployment scvmm uses those differencing disks based on a shared vhdx.
Tfs 2018 does not uses differencing disks

Instead it is copying the whole disk and creating a differencing disk inside the vm folder.

**Comment by RoopeshNair** [comment]
@ashokirla  - can ypu please take a look?

**Comment by thomps23** [comment]
@RoopeshNair Did you team have a chance to triage this experience?

**Comment by ashokirla** [comment]
@LukasK07 : As part of SCVMM extension for Build and Release, we provide support for deploying the VMs. The extension uses SCVMM commandlets to deploy the VMs based on the template/VHDx provided. If the SCVMM commandlets support deploying VMs based on differencing disks, you can achieve the same from the extension. You can use "Run SCVMM commands" action in SCVMM task.

**Comment by mijacobs** [comment]
It looks like the question has been answered. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. If this scenario continues to be an issue, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
