### ISSUE TITLE
Folder paths based trigger

### ISSUE THREAD

**Issue by t-my** [MicrosoftDocs/vsts-docs#6384]
[Enter feedback here]

In classic pipelines, is triggering based certain folder possible like in YAML using: 

``` 
 paths:
    include:
      - folder/*
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70217fc0-8411-04b1-d448-d013398c5ac8
* Version Independent ID: ed92b98e-2d6f-8dfb-9319-85c825b2cb30
* Content: [Release triggers for stages, branches, and pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/triggers?view=azure-devops)
* Content Source: [docs/pipelines/release/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/triggers.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment]
@t-my  Thank you for the question.

Since the question concerns product-related implementation, please move this issue to either:

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

Alternatively consider using one of the code repos, such as [azure-pipelines-tasks](https://github.com/microsoft/azure-pipelines-tasks/issues) for implementation advice from the product team.
