### ISSUE TITLE
Explain when and why you would want to set forceRepoUpdate = true

### ISSUE THREAD

**Issue by IanKemp** [MicrosoftDocs/vsts-docs#6385]
Setting `forceRepoUpdate = true` calls `pod repo update` before `pod install`. But on a standard (clean) pipeline environment, there will be no CocoaPods spec repo, so `pod install` will need to download it, effectively calling `pod repo update` anyway. Therefore, what is the need for `forceRepoUpdate = true`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e3b5771-0481-f31f-2cbb-46b43a5e7d47
* Version Independent ID: 1bb92b88-9afe-368e-989c-6976228972e9
* Content: [CocoaPods task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/cocoapods?view=azure-devops)
* Content Source: [docs/pipelines/tasks/package/cocoapods.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/package/cocoapods.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @DavidStaheli
* Microsoft Alias: **dastahel**

**Comment by msebolt** [comment]
@IanKemp Thank you for the question.

Since this question isn't an issue with the documentation, but more specific to the code itself, please refer to:

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
- [Azure DevOps community](https://developercommunity.visualstudio.com/topics/Azure+DevOps.html)

Alternatively, move the issue to the [azure-pipelines-tasks](https://github.com/microsoft/azure-pipelines-tasks/issues) repo for the product team engagement.
