### ISSUE TITLE
New Az  Powershell module is available on the Microsoft Hosted Agents?

### ISSUE THREAD

**Issue by aku-p** [MicrosoftDocs/vsts-docs#6401]
[Enter feedback here]
I have verified the installed software/packages from the [link](https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/win/Vs2019-Server2019-Readme.md). No were mentioned Az module is available. Is Az module made available on the microsoft hosted agents? If not from when it will be avaialble

Thanks,
@kup

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99af681d-41ad-da15-0b72-08b5cd5a11ac
* Version Independent ID: 2fa0df36-a437-8cbb-b019-b49b31b1e116
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/hosted.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@aku-p -- Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

 
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
