### ISSUE TITLE
Kanban Board Test Status

### ISSUE THREAD

**Issue by OrigPSJ** [MicrosoftDocs/vsts-docs#6402]
Is there an ETA for when tests cases created outside the Kanban board would be visible on the board? I have a number of cases which may be applicable to current and future stories - I'd like to add them via the  "tested by" link so they can be quickly tracked 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91132cbe-8fd9-d73e-a1b7-d122022c9413
* Version Independent ID: a0dd8148-d039-af4b-ef5d-735fa32a3fb3
* Content: [Add, run, and update inline tests - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/boards/add-run-update-tests?view=azure-devops)
* Content Source: [docs/boards/boards/add-run-update-tests.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/boards/add-run-update-tests.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 

Also, the product teams aren’t always watching this repository, so to make sure your suggestion gets in front of them for triage, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
