### ISSUE TITLE
External users when backed by Azure and not backed

### ISSUE THREAD

**Issue by spottedmahn** [MicrosoftDocs/vsts-docs#6419]
There seems to be a difference when adding users when backed by Azure AD and not backed by Azure AD.

For example, I have a business and personal account, XXXXXXX@XXXamerica.com, and when backed by Azure AD adding my email uses my business account.  When not backed by Azure AD, Azure DevOps uses my personal account.

What about documenting that behavior?

Thoughts? 💭

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6db4fba-7322-16bc-3431-6b8f933a84bf
* Version Independent ID: a20bd1b0-06d7-8f49-30d2-25c5e188b674
* Content: [Add, invite external users, guest users to your organization - Azure DevOps Services](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/add-external-user?view=azure-devops&tabs=current-page#prerequisites)
* Content Source: [docs/organizations/accounts/add-external-user.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/accounts/add-external-user.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @spottedmahn, Thanks for reaching out. (I've edited your original text to eliminate the PII.) 
We recommend using a different email/UPN for your personal and business accounts, rather than using the same, even though it's allowed. We’ve seen customers having challenges with disambiguating between their business and personal accounts when the email/UPN is the same. 
I'm adding a note to the article, stating the same. Please let me know if you have any further questions. Thank you!
