### ISSUE TITLE
server URL for mscodehub

### ISSUE THREAD

**Issue by palladia** [MicrosoftDocs/vsts-docs#6440]
Followed directions for Self-hosted Linux agent...

Our project is on mscodehub, so PAT had to be created on https://mscodehub.visualstudio.com/{Project Name}.  I downloaded the agent tar.gz file, unpacked it, and ran config.sh.  But when it asks for server URL, I couldn't get it to accept my mscodehub.visualstudio.com address, nor the suggested dev.azure.com address.  

The log file shows that GET request failed with status of "Not Found".  What URL should I use?

**Comment by msebolt** [comment]
@palladia  Thank you for the feedback, we're sorry you're experiencing issues.

The issue was reported previously [here](https://developercommunity.visualstudio.com/content/problem/444257/unable-to-access-devazurecom.html), please see if this addresses the problem.

If not, you'll need to report this to the product team using **Report a problem** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) and link back to this issue.

**Comment by msebolt** [comment]
Closing now, please comment below if there are any further issues.
