### ISSUE TITLE
Nothing happens when I run Update All Agents

### ISSUE THREAD

**Issue by santoorman** [MicrosoftDocs/vsts-docs#645]
the agent is not updating.  It is currently on version 2.122.1, but the latest version is 2.133.3, when I click Update All Agents, nothing happens, it does not get updated.  Can you please include how to update it manually?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 484c5e2e-c729-e707-e2c3-dfe3c2e83083
* Version Independent ID: 083a5e47-e47a-9d7c-b351-ee7409cd8aa9
* Content: [How do I make sure I have the latest v2 agent version?](https://docs.microsoft.com/en-us/vsts/build-release/concepts/agents/_shared/v2/qa-agent-version?view=vsts)
* Content Source: [docs/build-release/concepts/agents/_shared/v2/qa-agent-version.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/concepts/agents/_shared/v2/qa-agent-version.md)
* Service: **unspecified**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by steved0x** [comment]
@elbatk Can you take a look and reassign if required?

**Comment by elbatk** [comment]
Uhm I think this may be Andy's, not sure of his GitHub ID.

**Comment by ChristofferGersen** [comment]
I had the same problem with version 2.122.1. As a partial workaround I did an update to TFS 2018 Update 2 and the "Update All Agents" option did update the agent to 2.131.0. It still isn't 2.133.3, but it is good enough for me, since I only required 2.129.0 for SChannel support in git. After the update the download agent link changed to https://go.microsoft.com/fwlink/?linkid=872265, which also downloads version 2.131.0, in case anyone prefers to give that a go before updating TFS. In that case you could probably run `config remove` on the old agent and after replacing all the files configure the new agent again as you normally would.

**Comment by chrisrpatterson** [comment]
@santoorman are you on TFS or VSTS?  If you are on TFS then you are going to be locked to the version of the agent that shipped with that version of TFS.

**Comment by elbatk** [comment]
Closing this issue due to lack of response. If you have a product issue, the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html) would be best!
