### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by KarenELove0202** [MicrosoftDocs/vsts-docs#6472]
I have entered load behavior = 3 on each entry in the registry - still does not load the team ribbon each time

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf4c6dd3-d2d2-0d41-9958-d3f7d85b5c05
* Version Independent ID: e5e4a28f-30b8-0dab-b94b-d94fe6d341fe
* Content: [TFS-Office integration issues - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/backlogs/office/tfs-office-integration-issues?view=azure-devops#feedback)
* Content Source: [docs/boards/backlogs/office/tfs-office-integration-issues.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/backlogs/office/tfs-office-integration-issues.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@KarenELove0202 Thank you for the feedback.

Unfortunately, since this forum is for documentation only, our support options are limited.

Please use **Report a problem** to move this issue to the [Azure DevOps community](https://developercommunity.visualstudio.com/topics/Azure+DevOps.html) for feedback from the product team.
