### ISSUE TITLE
Npm Build is failing with Hosted agent "vs2017-win2016" was working correctly with VS 2017 

### ISSUE THREAD

**Issue by ankitvarmait** [MicrosoftDocs/vsts-docs#6473]
Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by ankitvarmait** [comment]
WE had pipeline with with host agent Vs 2017 was working correctly now after changing the host to "vs2017-win2016" it started failing... 

Now we can not find vs2017 anywhere., It is blocking all work. Please let us know the solution..

1. Created self hosted agent, then npm build works.
2. Not work with new agent.
3. Was working correctly with vs2017 agent.


--Error: 
##[error]Error: Npm failed with return code: 3221226505

We also update node sass and all packages still the issue. 
Please revert vs2017 agent back

**Comment by WilliamAntonRohm** [comment]
@ankitvarmait -- thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing.  

Also, you may have encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.
