### ISSUE TITLE
A teammate cannot see or reuse service connections...

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/vsts-docs#6482]
... for a new release task that are already setup on another release task in the same release pipeline environment agent.

Is this what is intended to happen? We end up peppering our network admin team with permission updates every time we need a service connection.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72b90dd0-49f9-4ed4-3010-9a64dde6ae5a
* Version Independent ID: 6e679d50-4e94-eee3-8793-af884cc909ca
* Content: [Service connections in Azure Pipelines & TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/library/service-endpoints.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/service-endpoints.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
Service connection is way to store your secrets. For example, you can setup a service connection to Production subscription. By default these service connections are available to the creator/owner. You need to explicitly share it with your team using the Security tab for Service connections. This is by design to prevent unintended use of production secrets by other users

**Comment by StingyJack** [comment]
@RoopeshNair  A service connection doesn't have any secrets. It's a subscription and resource group for me as it is in the depicted example. There is no mention of "secrets". 

Team members that can create service connections in the same project cannot see each other's service connections, and this reality conflicts with this documentation, with the result being that the docs are in error (reality wins). Reopen this issue until the documentation is updated to match reality.

**Comment by RoopeshNair** [comment]
@StingyJack  -  In order to connect to an Azure subscription and deploy, the task needs Service Principal(SPN) and Key (secret/password). The Service Connection UI auto generates an SPN and Key on behalf of logged in user. It is not auto-shared to the team. It is by design. If you need your teammates to use your SPN to deploy it on your behalf, you'd have to share it explicitly. Please note the deployments are tracked against the SPN (created on your behalf).

**Comment by StingyJack** [comment]
[This whole section](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#secure-a-service-connection) is contradictory to what you are saying. It says administrators can see and define service connections and users can use ones already created. That would be what we expect, because it is less complicated and doesn't require duplication of work.

Both ways make sense for opposite extremes  (except the part about a non interactive service connection/account/principal really being some users account. How did service accounts get forgotten?!? ). Your explanation of how it works describes the "enterprise level of complexity" extreme that requires either enterprise levels of resources and coordination to utilize or a single engineer that doesn't work on a team or have to share DevOps responsibilities. For small/medium/less than enterprise size teams, service connections are a drag.

**Comment by RoopeshNair** [comment]
@StingyJack  -  It is not contradicting, you will have to assign "user" role to your teammates, if they are to use your "personal" connections. Yes, it is a "enterprise level of ~complexity~ security". Let's say the connection is for production subscription, would the subscription owner by default share it with everyone or would be selective about who can deploy to it. In our designs, we default it to be secure.  I understand it is adding an additional step for the user.
