### ISSUE TITLE
Agent Vs Deployment Pool

### ISSUE THREAD

**Issue by rameshrc** [MicrosoftDocs/vsts-docs#6483]
I have confusion over agent pool and deployment pool. I am installing standalone installer into the machines. Then run tests on UI Tests on it. 
I install product using Deployment pool through Release, but there is no option to "Run on multiple agents in parallel" just like "Run on Agent" task has.
Can a machine to be registered to both Agent and Deployment pool? Currently I see no way .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4409a9cb-8448-edd6-da0a-243e5601aa3e
* Version Independent ID: ec15f71a-a76d-c3f9-1d31-832f92183ef4
* Content: [Agents pools - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/pools-queues?view=azure-devops&tabs=yaml%2Cbrowser#feedback)
* Content Source: [docs/pipelines/agents/pools-queues.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/pools-queues.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
