### ISSUE TITLE
[Azure Devops] Rollout deployment timeout setting

### ISSUE THREAD

**Issue by mo-saeed** [MicrosoftDocs/vsts-docs#6490]
Hello,

Currently our pipeline fails due to timeout in the deploy step of KubernetesManifest task.

when running kubectl rollout status command:
```
##[error]error: deployment "XXXX" exceeded its progress deadline
```
Is there way to have a setting to increase the timeout, i believe it's 2 minutes by default.

**Comment by tfosmark** [comment]
@mo-saeed Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
