### ISSUE TITLE
Where is the reference documentation for the Cache@2 task?

### ISSUE THREAD

**Issue by mahilleb-msft** [MicrosoftDocs/vsts-docs#6510]
I'm missing a page under Reference &gt; Tasks &gt; .. that would describe the Cache@2 task, is this still coming?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c20289-dab2-7a6e-4f63-4b30eaff2c71
* Version Independent ID: d75cc196-90c1-8291-9907-ff405bde4edf
* Content: [Pipeline caching - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/caching/?view=azure-devops)
* Content Source: [docs/pipelines/caching/index.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/caching/index.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by damccorm** [comment]
Thanks for your feedback - I'm taking a look!

**Comment by damccorm** [comment]
Hey @mahilleb-msft it looks like this section does what you're asking for - https://docs.microsoft.com/en-us/azure/devops/pipelines/caching/?view=azure-devops#using-the-cache-task - is there any specific info you think its missing?

**Comment by mahilleb-msft** [comment]
thanks @damccorm .. Usually there's something like for example https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/maven?view=azure-devops under the "Reference > Tasks" section, which has like an overview on just the "schema" if you will...

**Comment by damccorm** [comment]
Ah, I see - that makes sense, I'll look at adding that. Thanks for the suggestion!

**Comment by mahilleb-msft** [comment]
thanks @damccorm

**Comment by damccorm** [comment]
Thank you for your feedback. 
I've added a doc which should roll out shortly

In the meantime - this is the yaml snippet:
```YAML
# Cache
# Cache files between runs
- task: Cache@2
  inputs:
    key: 
    path: 
    #cacheHitVar: # Optional
    #restoreKeys: # Optional
```

And here's the descriptions:
<table>
<thead>
<tr>
<th>Argument</th>
<th>Description</th>
</tr>
</thead>
<tr>
<td>Key (unique identifier) for the cache</td>
<td>
<p>This should be a string that can be segmented using '|'. File paths can be absolute or relative to $(System.DefaultWorkingDirectory).</p>
</td>
</tr>
<tr>
<td>Path of the folder to cache</td>
<td>
<p>Can be fully qualified or relative to $(System.DefaultWorkingDirectory). Wildcards are not supported. [Variables](https://go.microsoft.com/fwlink/?LinkID=550988) are supported.</p>
</td>
</tr>
<tr>
<td>Cache hit variable</td>
<td>
<p>Variable to set to 'true' when the cache is restored (a cache hit), otherwise set to 'false'.</p>
</td>
</tr>
<tr>
<td>Additional restore key prefixes</td>
<td>
<p>Additional restore key prefixes that are used if the primary key misses. This can be a newline-delimited list of key prefixes.</p>
</td>
</tr>

I'm going to close since this should roll out soon and there's no further work on our end.

**Comment by mahilleb-msft** [comment]
Thanks!
