### ISSUE TITLE
Compile into container and extract artifacts

### ISSUE THREAD

**Issue by simardst** [MicrosoftDocs/vsts-docs#6521]
Is there a way to compile into a container (docker) and extract the build artifacts?  I'm lokking for a recipe that would work with 
Azure DevOps Microsoft-hosted agents.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9dbf88-7e55-d427-145e-d36b04fb197f
* Version Independent ID: a3f30c00-817c-9c05-7a57-3f2bf618821e
* Content: [Docker task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/build/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/docker.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbarsin
* Microsoft Alias: **shasb**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
