### ISSUE TITLE
create secret tls

### ISSUE THREAD

**Issue by katlimruiz** [MicrosoftDocs/vsts-docs#6525]
I am trying to install ambassador and enable https.
I'm using this command that does work in command line, but since I want to use in azure-pipelines.yml and I need to use this task 
to accomplish (since this task encapsulates, user, account, etc).

kubectl create secret tls tls-cert --cert=cert.pem --key=key.pem

How can I do it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcbb25d1-a706-e8fc-61e4-d5b86aa54f47
* Version Independent ID: 5634d9dd-fd92-761c-24b8-5e32ed6c6c35
* Content: [Kubectl task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/kubernetes?view=azure-devops#secrets)
* Content Source: [docs/pipelines/tasks/deploy/kubernetes.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/kubernetes.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by katlimruiz** [comment]
I already saw that kubectl create secret tls tls-cert --cert=cert.pem --key=key.pem, it is a special syntax and by doing a generic command it works.

          - task: Kubernetes@1
            displayName: kubectl create secret for certificates
            inputs:
              connectionType: Azure Resource Manager
              azureSubscriptionEndpoint: xxx
              azureResourceGroup: xxx
              kubernetesCluster: xxx
              command: create
              arguments: secret tls tls-cert --cert=$(System.DefaultWorkingDirectory)/xxx.crt --key=$(System.DefaultWorkingDirectory)/xxx.key

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
