### ISSUE TITLE
Gradle Task : Cannot enable jacoco tests coverage with Kotlin dsl gradle

### ISSUE THREAD

**Issue by Tetradeus** [MicrosoftDocs/vsts-docs#6527]
When enabling jacoco with gradle kotlin dsl if fails because it looks at build.gradle file instead of build.gradle.kts file.

Here is the error : 
```
##[warning]Unable to append code coverage data: Error: File or folder doesn't exist: /home/vsts/work/1/s/build.gradle
##[warning]Failed to enable code coverage: Unable to append code coverage data: Error: File or folder doesn't exist: /home/vsts/work/1/s/build.gradle
```

**Comment by WilliamAntonRohm** [comment]
@Tetradeus Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.

**Comment by Tetradeus** [comment]
When configuring the gradle task in Azure Devops, if you enable Jacoco code coverage tool, and you also use kotlin dsl build, it fails with the previous error.

<img width="337" alt="image" src="https://user-images.githubusercontent.com/1665874/70091635-d7954200-161c-11ea-9201-fa462c8e622c.png">

**Comment by WilliamAntonRohm** [comment]
@Tetradeus -- thank you for clarifying. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
