### ISSUE TITLE
Cachine

### ISSUE THREAD

**Issue by dci-aloughran** [MicrosoftDocs/vsts-docs#6532]
I noticed on azure artifacts repo that pip always returns a max_age of 0, and there's not a reference in the Cache@2 task for how to cache python dependencies.  Is this functionality you'll be bringing in soon?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ca42420-9324-1988-16bd-501be69e278d
* Version Independent ID: 400c0122-a0cc-bb52-b6cc-8aa93ff2c47a
* Content: [Build and test Python apps - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/python?view=azure-devops#feedback)
* Content Source: [docs/pipelines/ecosystems/python.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/ecosystems/python.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
