### ISSUE TITLE
Azure Active Directory - switch directory

### ISSUE THREAD

**Issue by kardinal3000** [MicrosoftDocs/vsts-docs#6541]
Hello guys,

I have two azure AD`s also I use azure DevOps service and I need to switch directory. 

I read the article [Switch to another Azure Active Directory](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/change-azure-ad-connection?view=azure-devops) all is clear. 
All requirements were met according the link

- **AAD-1** has a user  test@domen.com, Type member, CUID (ea08550-7a3d-4c8e-bcfe-d93e2a2ce9e4)
- **AAD-2** has a user  test@domen.com, Type member, CUID (ju8ecb48-b974-4959-8735-43a9e5297ec7)
- User (test@domen.com) is a part of **Project Collection Administrator** group (in Organization settings). 

I login to my Azure Devops organization and I have tried to switch directory from AAD-2 to AAD-1.

  I get this:

```
Your organization "Name" failed to connect to the AAD-1 Azure Active Directory.

The requesting identity (CUID 336fb57e-ec04-7fa6-be8d-254f4fb6c641) does not have permission to access the tenant (e440184-c314-4dc9-wd344- a4112eq5621e).
```
Obviously there is not enough rights to this CUID (336fb57e-ec04-7fa6-be8d-254f4fb6c641)
My question.  

What is that **identity CUID** (336fb57e-ec04-7fa6-be8d-254f4fb6c641)???

I have tried to search this ID in a both AADs and couldn't find anything. 
Could you please help me to understand what I missed.

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 

 
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
