### ISSUE TITLE
Environments and approval

### ISSUE THREAD

**Issue by fleed** [MicrosoftDocs/vsts-docs#6543]
What's the client to use to get information about environments? How to programmatically approve a pending deployment?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 413163f0-28c3-a2a7-d626-fcb81bcb2257
* Version Independent ID: 57c127da-2b1e-d29e-9abb-a3c258762ccf
* Content: [.NET Client Libraries for Azure DevOps Services (and TFS) - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/dotnet-client-libraries?view=azure-devops&viewFallbackFrom=vsts)
* Content Source: [docs/integrate/concepts/dotnet-client-libraries.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/concepts/dotnet-client-libraries.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by fleed** [comment]
Hi @WilliamAntonRohm 
Implementing it would be the second step.. but the initial issue is that I cannot find the documentation for the REST endpoint, if it exists.
The Environments are part of the current version of Azure DevOps, so if the endpoint is not yet available, I would expect mentioning it in the docs.

**Comment by WilliamAntonRohm** [comment]
@fleed -- thank you for clarifying.

@chcomley -- please look into this potential documentation issue.

**Comment by chcomley** [comment]
Hi @fleed, I've added a link in the article to the [REST API Reference](https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-5.1). Since you're talking about releases and environments, I assume you're looking for this document in particular: [Releases - Get release environment]
(https://docs.microsoft.com/en-us/rest/api/azure/devops/release/releases/get%20release%20environment?view=azure-devops-rest-5.1). 

Please @ mention me if you have any further questions, thanks so much!

**Comment by fleed** [comment]
Thank you, @chcomley!
