### ISSUE TITLE
Additional change request parameters based on Variables

### ISSUE THREAD

**Issue by acds** [MicrosoftDocs/vsts-docs#6548]
Is it expected that the Additional Change Request Parameters setup will parse the value and replace $(variables) with their values prior to submission and mapping into ServiceNow or can one only add static values?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d07f29c5-affb-47bb-5f68-fc49e691c741
* Version Independent ID: 661d3781-8784-868d-261f-1e994a154a35
* Content: [Control deployments by using ServiceNow - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/approvals/servicenow?view=azure-devops)
* Content Source: [docs/pipelines/release/approvals/servicenow.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/release/approvals/servicenow.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbarsin
* Microsoft Alias: **shashban**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
