### ISSUE TITLE
Command  by Azue CLI 

### ISSUE THREAD

**Issue by akramaskar77** [MicrosoftDocs/vsts-docs#6549]
I Have Problem . this page dos't open with me, Is there any way by AZURE CLI to do that ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b302bb93-a2be-c9b9-964e-e0ec3141a32b
* Version Independent ID: afa29749-f96f-1e18-4cb7-5c860a8099ae
* Content: [Change the number of paid users for an extension - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/billing/change-number-paid-extension-users?view=azure-devops#feedback)
* Content Source: [docs/organizations/billing/change-number-paid-extension-users.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/billing/change-number-paid-extension-users.md)
* Product: **devops**
* Technology: **devops-billing**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
