### ISSUE TITLE
Unable to import work items with the new view

### ISSUE THREAD

**Issue by Nirmalkmr** [MicrosoftDocs/vsts-docs#6550]
I am unable to import work items as a csv file(exported from another Azure DevOps Server)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8390e96-a029-2729-2f34-fc57f2f5e131
* Version Independent ID: 03e58d17-8cd0-0dd7-2a08-6f3e9ddc27ac
* Content: [View or run a query - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/view-run-query?tabs=browser&view=azure-devops#feedback)
* Content Source: [docs/boards/queries/view-run-query.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/queries/view-run-query.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
