### ISSUE TITLE
Problem with proxy

### ISSUE THREAD

**Issue by MTomBosch** [MicrosoftDocs/vsts-docs#6554]
Hi
My agents are running behind a local CNTLM proxy running on port 3128.
When this task is executed I always get the following error message: 
##[error]Error: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:3128

Does this task not support a proxy setup for the agent?

The version of the task is: 1.156.1

Thank you

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 2a5f8376-3654-0ed4-d9f8-d15f28350783
* Version Independent ID: f393daba-6515-6c26-71ac-b557e8c8dad1
* Content: [Download Secure File task - Azure Pipelines](https://docs.microsoft.com/de-de/azure/devops/pipelines/tasks/utility/download-secure-file?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/utility/download-secure-file.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/download-secure-file.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
