### ISSUE TITLE
Getting all Project notifications, rather than specific Team Sprint notifications

### ISSUE THREAD

**Issue by LukeSchmidtPwC** [MicrosoftDocs/vsts-docs#6567]
I have configured the connecter to only process Work Item Updates for a specific Team Sprint, however I am still getting notifications for ALL other sprints, how can I properly configure it for a specific Team Sprint? 

I notice when I finish the configuration, the description of the connecter says "for any area path in &lt;Project Name&gt;", even though I have specified a specific team sprint.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cddc0ae-93af-297c-2e71-334143ebee1e
* Version Independent ID: cb76e516-8471-c3e1-45f4-0a20a223f32a
* Content: [Create a service hook Microsoft Teams - Azure DevOps Services, TFS 2017](https://docs.microsoft.com/en-us/azure/devops/service-hooks/services/teams?view=azure-devops)
* Content Source: [docs/service-hooks/services/teams.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/service-hooks/services/teams.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by msebolt** [comment]
@LukeSchmidtPwC Thank you for the feedback.

Since this is more of an issue geared towards the product, please move this [here](https://developercommunity.visualstudio.com/spaces/21/index.html).

Alternatively you'll need to create and adjust a custom service hook using the:

```
"supportedScopes": [
        "project",
        "collection"
      ],
```

...section of the [Event Types](https://docs.microsoft.com/rest/api/azure/devops/notification/event%20types?view=azure-devops-rest-5.1) to [create your own subscription](https://docs.microsoft.com/rest/api/azure/devops/notification/subscriptions/create?view=azure-devops-rest-5.1).

**Comment by LukeSchmidtPwC** [comment]
Okay thanks for the heads up - closing this now.
