### ISSUE TITLE
Publishing Test Results in Azure Pipelines gives invalid character error on Windows agent

### ISSUE THREAD

**Issue by Divya1388** [MicrosoftDocs/vsts-docs#6583]
Configured a pipeline to test and publish results. The test is scripted in go to test a terraform Plan output. The output is converted to Junit format using github.com/jstemmer/go-junit-report
when running the tasks:
go get -u github.com/jstemmer/go-junit-report
go test -v -timeout 60m 2>&1 | go-junit-report > report.xml
and Publish test results
The pipline passes but the publish test result task give the following error
##[warning]Failed to read D:\a\1\go\src\s***\CentralUS\Global\VirtualNetwork\test\report.xml. Error : '.', hexadecimal value 0x00, is an invalid character. Line 2, position 1..
No build level attachments to publish.
Finishing: Publish Test Results D:\a\1\go\src\s**\report.xml

The above error does not occur when using linux agents or linux containers

**Comment by msebolt** [comment]
@Divya1388 Thank you for the feedback.

According to [this post](https://stackoverflow.com/questions/11036799/hexadecimal-value-0x00-is-a-invalid-character) `0x00` is an illegal character in XML.

Please refer to https://github.com/jstemmer/go-junit-report/issues/99 for status on the **go-junit-report** process, though Windows has had issues also, see [here](https://stackoverflow.com/questions/55871020/why-do-i-get-error-hexadecimal-value-0x00-is-an-invalid-character-line).



Unfortunately, since this is a documentation forum our support options are limited.  You will need to start an issue [here](https://developercommunity.visualstudio.com/topics/Azure+DevOps.html) for feedback from the product team.

**Comment by MaurGi** [comment]
@msebolt what if it's inside a CDATA section? That should be allowed?

**Comment by WilliamAntonRohm** [comment]
@MaurGi -- Mauro, thank you for your follow-up question.

- https://en.wikipedia.org/wiki/Valid_characters_in_XML
