### ISSUE TITLE
Auto Service Connection Inheritance

### ISSUE THREAD

**Issue by thisispaulsmith** [MicrosoftDocs/vsts-docs#6589]
What tasks support service connection inheritance? This page shows KubernetesManifest task inheriting from the environment. We're trying HelmDeploy task and it doesn't pick up any connection? Can't find any more specific documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77d95db6-9983-7346-d0eb-4b7443e4e252
* Version Independent ID: 0a22cccc-318d-592f-d1ab-09ec01d88087
* Content: [Environment - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments?view=azure-devops#feedback)
* Content Source: [docs/pipelines/process/environments.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/environments.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@thisispaulsmith Thank you for the feedback.

A [similar issue](https://developercommunity.visualstudio.com/content/problem/623161/kubernetes-service-connection-failes-on-helm-upgra.html) is currently active.  Also see if [this article](https://jessicadeen.com/how-to-deploy-to-kubernetes-using-helm-and-vsts/) offers any further guidance.

Unfortunately since this is a documentation forum, our support options are limited.  For better feedback directly from the product team, please start an issue [here](https://developercommunity.visualstudio.com/spaces/21/index.html).
