### ISSUE TITLE
Make 'Define' standard selected option at testcase overview

### ISSUE THREAD

**Issue by boydkronenberg** [MicrosoftDocs/vsts-docs#6617]
I work extensively in the 'Define' tab. Every time I reopen the testplan via my bookmark (/_testManagement?_a=tests&Length=2&planId=2291) and navigate to my testcase folder (static suite), the tab 'Execute' is standard selected.
 
When I open/doubleclick a testcase to edit it, it opens 'Execution history for test case:'
I expect/want to open the testcase editor itself (non-grid view).

Can this be changed? Configurable maybe?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c520dee-1218-777e-7405-551623817c03
* Version Independent ID: 82b5d172-ae1a-2b4c-82ac-595cd7609d3c
* Content: [New test plans page - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/new-test-plans-page?view=azure-devops#feedback)
* Content Source: [docs/test/new-test-plans-page.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/new-test-plans-page.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @ravishan-msft
* Microsoft Alias: **ravishan-msft**

**Comment by msebolt** [comment]
@boydkronenberg Thank you for the feedback.

You can refer to a [similar post](https://developercommunity.visualstudio.com/content/problem/359308/can-i-get-test-cases-outcome-results-as-a-field-in.html), which allows you to use [Dashboards](https://docs.microsoft.com/azure/devops/report/dashboards/overview?view=azure-devops) to see if this helps solve your problem.  

Please note since this a documentation forum our support options are limited.

For further feedback from the product team start an issue [here](https://developercommunity.visualstudio.com/spaces/21/index.html)
