### ISSUE TITLE
Question about "ReRun Failed Jobs"

### ISSUE THREAD

**Issue by SirAlvarex** [MicrosoftDocs/vsts-docs#6676]
Is there a syntax that can be used to run past successful jobs when executing "rerun failed jobs"?  An example use case is when tests require a setup stage, then a second job uses a matrix strategy to run tests in parallel.

In our case, it's provisioning test hardware to then validate against contracts we have for expected functionality.

Currently with our configuration only the failed step is run which means we need to do a completely new deploy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7458d5b2-1bb7-7d87-7ce6-2b0c430b0155
* Version Independent ID: edf5bbd3-a3f0-5426-e985-31290f8afd05
* Content: [YAML schema - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#job)
* Content Source: [docs/pipelines/yaml-schema.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/yaml-schema.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 

 
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by lindhe** [comment]
@SirAlvarex Did you figure this out? I'm also wondering...

**Comment by BastienPerdriau** [comment]
@SirAlvarex Same question than @lindhe
