### ISSUE TITLE
How can I get git commit from which the artifacts is built?

### ISSUE THREAD

**Issue by JiandongRuan** [MicrosoftDocs/vsts-docs#6681]
"Release Pipeline" can set variable $(Release.Artifacts.{alias}.SourceVersion), the git commit from which the artifact is built. How can I get the same information in the YAML pipeline?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 861ce7a5-4fa4-55f1-2c97-46a9cc6a2f66
* Version Independent ID: bdf954b9-9bbe-8b34-b674-71ad8153519d
* Content: [Publish and consume artifacts in pipelines - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/artifacts/pipeline-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/pipeline-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by JiandongRuan** [comment]
It is documentation issue. pipeline artifact variable is important information related to how one can consume pipe artifacts. It is very difficult to google the information. At this page, you should at least at a cross-reference to the section about those "resources.pipeline.XXX" variables in https://docs.microsoft.com/en-us/azure/devops/release-notes/2019/pipelines/sprint-160-update

**Comment by jarodsmk** [comment]
@JiandongRuan - did you ever come right?
