### ISSUE TITLE
Decorator not triggered on Deployment

### ISSUE THREAD

**Issue by hbuckle** [MicrosoftDocs/vsts-docs#6706]
Decorators are not being triggered for `Deployment` jobs in the new yaml pipelines, is this intentional?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0704e7ce-a2bb-7ccd-4ad4-2c6ad55bc8f4
* Version Independent ID: 4efcddb9-864d-f895-8122-451c1045b272
* Content: [Pipeline decorators - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-pipeline-decorator?view=azure-devops)
* Content Source: [docs/extend/develop/add-pipeline-decorator.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/extend/develop/add-pipeline-decorator.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by msebolt** [comment]
@hbuckle Thank you for the feedback.

Unfortunately, since this is a documentation forum, our support options are limited.

Please start a thread in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) for feedback from the product team.

For additional support options, see:

- [Azure DevOps Support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

@vtbassmatt

**Comment by madhuv-msft** [comment]
@hbuckle We are yet to implement decorators for Deployment type jobs. we do not have any ETA on when this can be available. once we have this feature we will update the [document](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-pipeline-decorator?view=azure-devops).

CC: @chshrikh

**Comment by RoopeshNair** [comment]
[Decorator support for deployment jobs](https://docs.microsoft.com/en-us/azure/devops/release-notes/2020/sprint-163-update#use-pipeline-decorators-to-inject-steps-automatically-in-a-deployment-job) was recently rolled out (Jan 13th 2020). Can you please try and re-open, if you are still facing the issues.
