### ISSUE TITLE
Deployment status without using the Release Pipeline

### ISSUE THREAD

**Issue by johnnykang** [MicrosoftDocs/vsts-docs#6730]
Hi,

Is there any way to publish the deployment status without using the Release Pipeline? Perhaps using Devlops CLI to publish a deployment status to a workitem.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 462be419-4cfd-4bfc-06cc-45800c0d888b
* Version Independent ID: 95cb8a7d-c61d-dfac-403f-12fe40ba1c49
* Content: [Link work items to deployments - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/work-items/work-item-deployments-control?view=azure-devops#feedback)
* Content Source: [docs/boards/work-items/work-item-deployments-control.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/work-items/work-item-deployments-control.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by msebolt** [comment]
@johnnykang  Thank you for the feedback.

Unfortunately, we are unable to resolve support requests in this forum.

If you feel this is an issue with the product itself, you can get feedback from the product team by moving the issue [here](https://developercommunity.visualstudio.com/spaces/21/index.html).

Otherwise, for additional support options, please see:

- [Azure DevOps Support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

@KathrynEE

**Comment by msebolt** [comment]
Closing the issue now, please comment below if there are any questions.
