### ISSUE TITLE
How access variables specific to a variable group, When Imported multiple variable groups with same variable names.

### ISSUE THREAD

**Issue by v-avirao** [MicrosoftDocs/vsts-docs#6732]
What happens when two variable groups having same variable are imported in a stage.
For Eg: Group1 has variable "variable1" and Group2 also has "variable1" and I am referring both the groups in one stage. How to access Group1.Variable1 ?
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=classic%2Cbatch#feedback)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

**Comment by theyetiman** [comment]
This isn't an implementation question, this is a precedence question that should be explained in the docs....

If there are multiple variable groups included which have variables with the same name, in what order of precedence are they evaluated?
