### ISSUE TITLE
Classic Editor

### ISSUE THREAD

**Issue by yorhpokie** [MicrosoftDocs/vsts-docs#6743]
How to specify multiple repos in the Classic Editor in Azure DevOps?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a0499c0-bd1c-47a0-b472-54a5d6c159b4
* Version Independent ID: ec3feae0-4f23-68ab-6307-75fde645468a
* Content: [Check out multiple repositories in your pipeline - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops#feedback)
* Content Source: [docs/pipelines/repos/multi-repo-checkout.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/repos/multi-repo-checkout.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@yorhpokie Thank you for the question.

Since this is product-related it would best be served by the product team, please move the issue [here](https://developercommunity.visualstudio.com/spaces/22/index.html).

Please see [this post](https://developercommunity.visualstudio.com/content/problem/610934/long-term-support-for-classic-editor.html) for an example on classic editor support.

@steved0x

**Comment by msebolt** [comment]
Closing the issue now, please comment below if there are any questions.
