### ISSUE TITLE
New TFS is very buggy

### ISSUE THREAD

**Issue by Nikababy01** [MicrosoftDocs/vsts-docs#6750]
The new updates now, when copy in grid, does not copy text correctly, causing text to overlap. Can no longer copy and paste text to next test lines when inside a test case. Test cases now open in Execute mode, which causes confusion if you are trying to make changes to the test scripts. These new tabs are very inconvenient. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c520dee-1218-777e-7405-551623817c03
* Version Independent ID: 82b5d172-ae1a-2b4c-82ac-595cd7609d3c
* Content: [New test plans page - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/new-test-plans-page?view=azure-devops#feedback)
* Content Source: [docs/test/new-test-plans-page.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/new-test-plans-page.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @ravishan-msft
* Microsoft Alias: **ravishan-msft**

**Comment by WilliamAntonRohm** [comment]
@Nikababy01, thank you for your feedback.

It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.
