### ISSUE TITLE
Daily interval not working on Mondays

### ISSUE THREAD

**Issue by Bouke** [MicrosoftDocs/vsts-docs#6761]
I have a scheduled CI build with the definition below. It should run at midnight on Mon-Thu. However the observed frequency is Tue-Thu, skipping Monday. This behaviour is not expected and also not correct.
```
- cron: "0 0 * * 1-4"
  branches:
    include:
    - master
  always: true
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?tabs=yaml&view=azure-devops#scheduled-triggers)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
