### ISSUE TITLE
Use YAML for CD

### ISSUE THREAD

**Issue by obeyda** [MicrosoftDocs/vsts-docs#6782]
Wasn't it possible to use the same pipeline YAML definition to do both CI & CD instead of using the classic release pipelines? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 079492cb-bdc3-7ba6-8581-dd76391cda4f
* Version Independent ID: 81e719d4-b127-fa41-4cf2-421e91b9d4be
* Content: [Canary deployment strategy for Kubernetes deployments - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/kubernetes/canary-demo?view=azure-devops#feedback)
* Content Source: [docs/pipelines/ecosystems/kubernetes/canary-demo.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/ecosystems/kubernetes/canary-demo.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @shashankbarsin
* Microsoft Alias: **shasb**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

**Comment by obeyda** [comment]
my issue is with the documentation.

[in this section](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/kubernetes/canary-demo?view=azure-devops#deploy-canary-stage) we could've used yaml pipelines instead of the classic editor. i suggest to mark this section as **(Classic)** and add another section that explains how to do canary deploys with yaml config

**Comment by WilliamAntonRohm** [comment]
@obeyda -- Obeyda, thank you for clarifying.

@shashankbarsin -- Shashank, please look into this issue.

**Comment by shashankbarsin** [comment]
The documentation has been written using classic release pipelines instead of the YAML pipelines as manual intervention (used in this end to end guide) is not available in YAML pipelines yet. This feature is in the roadmap for YAML pipeline and updates to this end-to-end guide are planned along with the release of this feature.
