### ISSUE TITLE
Not compatible with Asp.Net Core 3 

### ISSUE THREAD

**Issue by arlind-shkrela** [MicrosoftDocs/vsts-docs#6791]
This package is not compatible with Asp.Net Core 3 web api. Only .net framework :/.
When it this feature may come ?

**Comment by arlind-shkrela** [comment]
Quick describe: 
I am working on an custom web api project with asp.net core 3.0. The goal is to connect with FTS 2013 to create/update/event listener work items.
I was trying to install : 

> Microsoft.TeamFoundationServer.ExtendedClient -Version 16.153.0

I prompt me with the following waring 

> Warning	NU1701	Package '**Microsoft.AspNet.WebApi.Core 5.2.3**' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.0'. This package may not be fully compatible with your project.

Thanks

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
