### ISSUE TITLE
ADO - Repo - WebHooks Not keeping settings

### ISSUE THREAD

**Issue by bobbymcgill** [MicrosoftDocs/vsts-docs#6792]
**Problem Description:** Webhook settings are not being saved correctly.

**Problem Details:**
We have a project with several repos in it. We would like to set up Web Hooks for individual repos when a Pull Request is updated/completed.

When creating the web hook, I select the <optional> repo that I want. However, as soon as I hit save, the web hook reverts to the <ANY> repo setting.

Screenshot 1 (WebHook1.png) Shows selecting the trigger, specific repo, and specific change I want to use. (I am choosing a repo - I don't want "ANY"!)
![WebHook1](https://user-images.githubusercontent.com/3823872/71595264-80419f00-2b00-11ea-9ac6-416c68c1b941.png)

Screenshot2 (WebHook2.png) defines the api and authentication - no problems here.
![Webhook2](https://user-images.githubusercontent.com/3823872/71595315-a7986c00-2b00-11ea-8fb8-f310985bb2ff.png)

Screenshot3 (WebHook3.png) shows that it doesn't matter what repo I choose - it is applied against any branch on any repo. Even though I specifically selected the repo I want in step 1.
![Webhook3](https://user-images.githubusercontent.com/3823872/71595399-06f67c00-2b01-11ea-8824-9034bcbd8b94.png)

**Comment by msebolt** [comment]
@bobbymcgill Thank you for the feedback.

Unfortunately, since this is the documentation forum our support options are limited.

Please start an issue [here](https://developercommunity.visualstudio.com/spaces/21/index.html) (or let us know and we can start an issue for you) and provide a link back to the information you provided above.

There the product team will provide a fix and we can update the documentation accordingly.

**Comment by bobbymcgill** [comment]
Thank you for the link. I have opened an issue there: https://developercommunity.visualstudio.com/content/problem/876334/webhook-settings-not-being-saved.html

Closing issue here. Thanks.
