### ISSUE TITLE
Change/update the used account

### ISSUE THREAD

**Issue by Expecho** [MicrosoftDocs/vsts-docs#6798]
I created several integrations a while ago. Suddenly I get the message "This connection has to be removed and recreated.".  Please tell me there is a way to update the used account instead of having to delete and recreate all the integrations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cddc0ae-93af-297c-2e71-334143ebee1e
* Version Independent ID: cb76e516-8471-c3e1-45f4-0a20a223f32a
* Content: [Create a service hook Microsoft Teams - Azure DevOps Services, TFS 2017](https://docs.microsoft.com/en-us/azure/devops/service-hooks/services/teams?view=azure-devops)
* Content Source: [docs/service-hooks/services/teams.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/service-hooks/services/teams.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by msebolt** [comment]
@Expecho  Thank you for the feedback.

Unfortunately, since this is a documentation forum our support options are limited.

Please start an issue [here](https://developercommunity.visualstudio.com/spaces/21/index.html) (or let us know and we can start one for you) and provide a link back to this issue.  

There the product team can diagnose the problem and, if needed, issue a fix and we will update the article accordingly.

For further support options, please also refer to:

- [Azure DevOps Support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by msebolt** [comment]
Closing this issue now, please comment below if there are additional questions.
