### ISSUE TITLE
Is there a way to ignore (rather than "skip") a stage?

### ISSUE THREAD

**Issue by abelfiore** [MicrosoftDocs/vsts-docs#6799]
Is it possible to have a stage be completely ignored (rather than skipped) - as if it wasn't even in the yaml - for certain conditions? For example, I would never want a stage to run (deploy to production) if a change was made on a certain branch (develop). I only want to see stages that apply to that branch (in this case, maybe a deploy to a DEV and/or QA environment). Other than creating multiple yaml pipelines, which are triggered differently based on branch, is there a way to do this using one yaml pipeline? The bottom line is that I don't want the pipeline UI in Azure DevOps to show stages that make no sense for certain branches. And I don't want to have to maintain multiple pipelines to accomplish this. Can this be done?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4266f72c-c774-0046-4593-d01eb775d3c3
* Version Independent ID: f20827aa-a6c5-96a8-5969-e576ffbc2e38
* Content: [Stages in Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/stages?view=azure-devops&tabs=yaml)
* Content Source: [docs/pipelines/process/stages.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/stages.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@abelfiore  Thank you for the feedback.

Unfortunately, since this is a documentation forum our support options are limited.

Instead, please use **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) for advice from the product team on how best to resolve this issue and/or improve stage building process.

For additional support options, please refer to:

- [Azure DevOps Support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

@juliakm

**Comment by msebolt** [comment]
Closing this issue now, please comment below if there are additional questions.
