### ISSUE TITLE
NPM Version

### ISSUE THREAD

**Issue by garfbradaz** [MicrosoftDocs/vsts-docs#6808]
Is there a way to set the `npm` version to use?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7bfc2f5-379f-d59f-93bc-f4204f8c3ba3
* Version Independent ID: f5c906e7-29b7-c93e-84a6-3e04aba2bba4
* Content: [Node.js Tool Installer task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/node-js?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/tool/node-js.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/tool/node-js.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by msebolt** [comment]
@garfbradaz Thank you for the question.

Please refer to [this post](https://developercommunity.visualstudio.com/content/problem/243765/node-tool-installer-doesnt-install-proper-npm-vers.html) to see if using the NPM task to set version information can solve your issue.

Otherwise this can be addressed by the product team by starting an issue [here](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by msebolt** [comment]
Closing this issue now, please comment below if there are additional questions.
