### ISSUE TITLE
Auto delete source branch if pull request was ok

### ISSUE THREAD

**Issue by jbruns2019** [MicrosoftDocs/vsts-docs#6814]
[Enter feedback here]
Unless I am blind, it would be nice to see a check box or default setting in ADO repos that would automatically delete the source branch on a successful pull request to master.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 028e7b61-62e4-a10e-e420-3535f7843f0e
* Version Independent ID: 1a6fdbe7-5ba4-a7f8-1b2e-271289a7b9fd
* Content: [Review and merge code with pull requests - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/pull-requests?view=azure-devops)
* Content Source: [docs/repos/git/pull-requests.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/pull-requests.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@jbruns2019 Thank you for the feedback.

Since this is an issue with the product itself, to make sure it gets in front of the right people, please start a thread [here](https://developercommunity.visualstudio.com/spaces/21/index.html) to submit the suggestion.

For additional support options or work-arounds, please refer to:

- [Azure DevOps Support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

@apawast

**Comment by msebolt** [comment]
Closing this issue now, please comment below if there are additional questions.
