### ISSUE TITLE
YAML-based creation of Environment Resource

### ISSUE THREAD

**Issue by daveneeley** [MicrosoftDocs/vsts-docs#6815]
"You can use a Pipeline to create, and deploy to environments as well. To learn more, see the how to guide"

This seems to be true in only a very limited sense. If I supply `environment: newenv.someresource`, and then run the pipeline, the empty environment will be created, but the pipeline will fail because the resource `someresource` does not exist. The example following this quote works because `environment: 'smarthotel-dev'` does not specify an resource. However, the how-to guide uses the resource notation and at this time the only available option to create resources within an Environment is to reverse-engineer the UI.

https://developercommunity.visualstudio.com/content/problem/820737/rest-apis-for-environments-and-its-resources-multi.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77d95db6-9983-7346-d0eb-4b7443e4e252
* Version Independent ID: 0a22cccc-318d-592f-d1ab-09ec01d88087
* Content: [Environment - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments?view=azure-devops)
* Content Source: [docs/pipelines/process/environments.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/environments.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@daveneeley Thank you for the feedback, assigning this to the author for review.

**Comment by RoopeshNair** [comment]
You can create an environment from YAML, However, adding resource to the environment is not supported in YAML. Adding resources needs lot more details for example - credentials to connect etc. 

From YAML, you can target the environment or a specific resource. When you create an environment from YAML dynamically, since there are no resources you can only refer to environment. If the resources are added to the environment then you can target the the specific resource from YAML deployment job with `environment: <environment name>.<resource name>`

**Comment by andrewsuiter** [comment]
@RoopeshNair is there any API documentation on environments/approval checks?

**Comment by RoopeshNair** [comment]
Not yet, since the service is still in preview and the endpoints might change, APIs aren't published.

**Comment by Nirav-Bhadradiya** [comment]
@RoopeshNair How can i check if my API check on environment is failing or passing ? it keeps waiting for it to pass when doing a build. There should be some way to check what happened to my REST API call.
