### ISSUE TITLE
Deleting Service Connection makes pipeline non-saveable and breaks it!

### ISSUE THREAD

**Issue by rtaylor72** [MicrosoftDocs/vsts-docs#6829]
I had an existing pipeline that was working fine until I attempted to add a NuGet push command.
Repo steps:
#1. Add NuGet push command to pipeline (create a new Service Connection) and save it.
#2. Disable task and save it.
#3. Goto "Service Connections" under "Project Settings" and delete Service Connection.
#4. Go back to pipeline, try and save it. Will get the following error:
`The pipeline is not valid. Job Job_1: Step DotNetCoreCLI input externalEndpoint references service connection <cs_guid> which could not be found. The service connection does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz.`

Try and delete it, or choose another (existing or newly created) and you will get this error:
`The pipeline is not valid. Job Job_1: Step  input externalEndpoint references service connection <cs_guid> which could not be found. The service connection does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz.`

So now I have a pipeline that cannot be ran nor saved.

Robert

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee4ec9d0-e0d5-4fb4-7c3e-b84abfa290c2
* Version Independent ID: 3e2b80d9-30e5-0c48-49f0-4fcdfedf5eee
* Content: [Resources - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops#feedback)
* Content Source: [docs/pipelines/process/resources.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/resources.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@rtaylor72  Thank you for the feedback.

Please note, in the documentation forum our support options are limited.

First, check if any of the following posts can address the issue:

- https://developercommunity.visualstudio.com/content/problem/290393/build-error-the-pipeline-is-not-valid.html
- https://developercommunity.visualstudio.com/content/problem/538709/build-task-failed-the-pipeline-is-not-valid-job-ph.html
- https://stackoverflow.com/questions/58285661/the-service-connection-does-not-exist-or-has-not-been-authorized-for-use

Otherwise, you will need to start a thread [here](https://developercommunity.visualstudio.com/spaces/21/index.html) where the product team can get involved.

For additional support options, refer to:

- [Azure DevOps Support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by msebolt** [comment]
Closing the issue now, please comment below if there are any questions.
