### ISSUE TITLE
cant disable certain notifications

### ISSUE THREAD

**Issue by dnewby-allegion** [MicrosoftDocs/vsts-docs#6839]
Hey we have one notification that is grayed out. It is enabled, but grayed out so it can't be disabled. How to fix that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3fac729-92a7-0f85-3e28-3a2515b77fca
* Version Independent ID: 3038ace1-8e10-9d2f-5e8b-2d883d4dd718
* Content: [View subscribed notifications - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/notifications/unsubscribe-default-notification?view=azure-devops#feedback)
* Content Source: [docs/notifications/unsubscribe-default-notification.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/notifications/unsubscribe-default-notification.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by msebolt** [comment]
@dnewby-allegion Thank you for the feedback.

Unfortunately, since this is the documentation forum our support options are limited.

Some similar examples have been previously reported [here](https://developercommunity.visualstudio.com/content/problem/630722/cannot-disable-notification-devops.html) and [here](https://developercommunity.visualstudio.com/content/problem/630425/notification-settings-not-editable.html).

Please review and use [this link](https://developercommunity.visualstudio.com/content/problem/post.html?space=21) to start an issue with the product team.

**Comment by msebolt** [comment]
Closing the issue now, please comment below if there are any questions.
