### ISSUE TITLE
Why is it that Stakeholders can be given access to a Project Wiki but not a Code Wiki?

### ISSUE THREAD

**Issue by drk-mtr** [MicrosoftDocs/vsts-docs#6934]
This inconsistency makes no sense whatsoever.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17e7fef2-40df-4923-e62e-74ac556cbc6a
* Version Independent ID: af9269b4-1db4-df1f-2520-78ad20baf17b
* Content: [Get started with Stakeholder access - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/get-started-stakeholder?view=azure-devops&tabs=agile-process)
* Content Source: [docs/organizations/security/get-started-stakeholder.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/get-started-stakeholder.md)
* Product: **devops**
* Technology: **devops-new-user**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
@drk-mtr -- thank you for your feedback.  It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.
