### ISSUE TITLE
tfs 2015 does not trigger build when using ssh

### ISSUE THREAD

**Issue by palcarlsen** [MicrosoftDocs/vsts-docs#698]
On TFS 2015 pushing from ssh does not trigger automatic builds. Builds are triggered using http. I can see my commits in the history same as commits made using http, but only http commits trigger the automatic build. 

---
#### Dokumentinformasjon

⚠ *Ikke rediger denne delen. Den kreves for koblingen docs.microsoft.com ➟ GitHub-problem.*

* ID: 64e85ff9-9add-d15c-e92f-02d7dd05e0f2
* Version Independent ID: 0cbd7427-6acd-3cfc-1a3b-8bf5ca60f3bd
* Content: [Connect to your Git repos with SSH](https://docs.microsoft.com/nb-no/vsts/git/use-ssh-keys-to-authenticate?view=vsts)
* Content Source: [docs/git/use-ssh-keys-to-authenticate.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/git/use-ssh-keys-to-authenticate.md)
* Service: **unspecified**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by congyiwu** [comment]
IIRC, earlier TFS releases did not properly publish push events for SSH.  This should have been fixed in later releases (although off the top of my head, I don't remember which one)

**Comment by thomps23** [comment]
Please accept our apology for the significant delay in addressing this issue.

It looks like you're working through an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
