### ISSUE TITLE
Could not able to run web application in visual studio

### ISSUE THREAD

**Issue by vasumsit** [MicrosoftDocs/vsts-docs#6987]
Hi All,

We have moved to TFS to GIT recently, We have able to clone and create repository. But when i try to run the project visual studio, could not able run. it is just started debug mode and stopping using IIS express.

the same project is working fine without Git and in TFS. try multiple options, nothing is working.

Could you please help me on this

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 

 
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
