### ISSUE TITLE
Do not allow build if another build is failed

### ISSUE THREAD

**Issue by olsh** [MicrosoftDocs/vsts-docs#699]
Is it possible to prevent a build if another build is failed?

Use case:
I have a build which runs unit tests, code analysis and so on (this build is started after each push to a repository).
And another build which pushes packages to Octopus deploy and runs integration tests (this build is started manually).

I want to prevent the second build if the first one is failed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f151218-9a11-0078-e038-f96198a76143
* Version Independent ID: 09c4d032-62f3-d97c-79d7-6fbfd89910e9
* Content: [Conditional task expressions](https://docs.microsoft.com/en-us/vsts/build-release/concepts/process/conditions?view=vsts#job-status-functions)
* Content Source: [docs/build-release/concepts/process/conditions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/concepts/process/conditions.md)
* Service: **unspecified**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by tlemke11** [comment]
I am also trying to figure out if this is possible. Have you had any luck?

**Comment by vijayma** [comment]
Two options -

- Model the second build's process as a second phase in the first build. Make the second phase conditional on the success of the first phase.
- Make the second build trigger upon completion of the first build using build completion trigger.

Note that in both the above options, the second process runs automatically if the first one succeeds. I did not understand what the issue is if the second build is triggered manually.

**Comment by olsh** [comment]
Hi @vijayma,

I don't want to run the second build automatically, because it's very expensive, it's a long-running build. So your solution doesn't work for me.

> I did not understand what the issue is if the second build is triggered manually.

I want to prevent accidentally pushing the broken code to a server if the first build (unit tests, static code analysis) is failed.

**Comment by ahmadyo** [comment]
where is 'build completion trigger'?

**Comment by mchelen** [comment]
Is there some way to cancel previous builds if a new build is queued? For example, if I push a new commit to `develop` branch I want a build to kick off, but if I push 4 new commits in quick succession then only the last one should get built.

**Comment by br549times3** [comment]
I want to know the same.  I have a CI build triggered automatically, but I have a scheduled build happening daily that also deploys the installation packages.  I want the scheduled build not to start if the CI build is failing.

**Comment by mijacobs** [comment]
It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
