### ISSUE TITLE
Getting error as “Invalid staging table x_mioms_azpipeline_change_request_import”

### ISSUE THREAD

**Issue by Kattesang** [MicrosoftDocs/vsts-docs#7004]
I have configured Deployment gates with service now change management in my Azure Devops release pipeline. When I trigger the release pipeline, I was ended with the error "Invalid table". Below is the log. Please let me know the solution to this issue.
![log](https://user-images.githubusercontent.com/320905/72776118-00a67c00-3c37-11ea-8e84-9dc9520b9847.png)

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
