### ISSUE TITLE
output path using vsbuild@1

### ISSUE THREAD

**Issue by greengumby** [MicrosoftDocs/vsts-docs#7007]
Hi,

I have set an output path in the Active(Debug) x64 configuration to bin\x64\debug however building through the azure pipeline using the correct platform and configuration seems to drop the x64 from the path.

Any ideas?

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
