### ISSUE TITLE
resourees:pipeline:triggers vs pipeline nameing only in webui

### ISSUE THREAD

**Issue by cpolzer** [MicrosoftDocs/vsts-docs#7020]
Hello!
If we get the option to trigger pipelines based on the names of other pipelines, then probably we should be enabled to set those piepline names from within our YAML definitions? I know, there has been some requests in the Azure DevOps Community which where closed down... but now it really makes sense to make the YAML a first class citizen?

Regars and thanks a lot for the great work!
Christian

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5673ec1-c7d1-e0ac-043a-8fc3d5b226a9
* Version Independent ID: b4872831-51c0-6cf8-1c56-de20beb38a80
* Content: [Build pipeline triggers - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/build/triggers.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/build/triggers.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by msebolt** [comment]
@cpolzer  Thank you for the feedback.

The issue you describe is product-related and needs to be addressed by the product team [here](https://developercommunity.visualstudio.com/content/idea/post.html?space=21).

You can also refer to this [recent post](https://developercommunity.visualstudio.com/content/problem/437066/cannot-set-pipeline-name-with-yaml-file-in-azure-d.html).

The post was likely closed due to inactivity, so continued commenting there will have it re-opened.

**Comment by msebolt** [comment]
Closing this issue now, thank you for contacting Microsoft.
