### ISSUE TITLE
Dynamic secure file name

### ISSUE THREAD

**Issue by yairhdz** [MicrosoftDocs/vsts-docs#7029]
I´m trying to download secure files dynamically using a variable on secureFile input but it is not working. For example:

- task: DownloadSecureFile@1
  name: caCertificate
  displayName: 'Download CA certificate'
  inputs:
    secureFile: '$(SecureFile.Name)'

Is this possible?

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
