### ISSUE TITLE
Authentication best practices?

### ISSUE THREAD

**Issue by shawnpaige** [MicrosoftDocs/vsts-docs#704]
If we have multiple Zendesk users, should we:

1. Share a common Personal Access Token across all users?
2. Have each user create their own Personal Access Token?

Thanks,
Shawn

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1646acb-1bd0-d506-fe70-1b749cccbbc4
* Version Independent ID: 89aa9387-8ce6-9877-8e90-5f7c655b4b77
* Content: [Zendesk with VSTS](https://docs.microsoft.com/en-us/vsts/service-hooks/services/zendesk?view=vsts)
* Content Source: [docs/service-hooks/services/zendesk.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/service-hooks/services/zendesk.md)
* Service: **unspecified**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hey @shawnpaige , thanks for the question. Adding @willsmythe from the product team that can probably answer this for ya!

**Comment by thomps23** [comment]
Please accept our apology for the significant delay in addressing this issue.

It looks like you're working through an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
