### ISSUE TITLE
Azure DevOps GitHub Account

### ISSUE THREAD

**Issue by sajisV5Framework** [MicrosoftDocs/vsts-docs#7047]
While creating the Azure Devops Project , the git hub connection is linked .
But Under the "Repos" view it is not well synced with the github account , it does not show all the branches, so far only the master branches.

And I am getting the following pop-up if I try to connect to git-hub account from project setings

![GitHubConnections](https://user-images.githubusercontent.com/57762124/73024105-30b77000-3e2d-11ea-8738-b12d982d6521.PNG)

**Comment by msebolt** [comment]
@sajisV5Framework  Thank you for the feedback.

Unfortunately in the documentation forum our support options are limited to the examples in the articles only.

If you think this is a product-related issue, please start a ticket [here](https://developercommunity.visualstudio.com/spaces/21/index.html) for the product team to get involved.

Otherwise, for additional support options see:

- [Azure DevOps Support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by msebolt** [comment]
Closing the issue now.  Please comment below if there are any questions.
