### ISSUE TITLE
Removing VM Resource from Environment

### ISSUE THREAD

**Issue by juanjosemino** [MicrosoftDocs/vsts-docs#7057]
Hi MS! Is there a way to remove a VM resource from an Environment once registered?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91d0d31f-81ee-c024-db7e-daddbf525f71
* Version Independent ID: 330f1649-386c-d0aa-5f96-b8343a1480d3
* Content: [Environment - Virtual machine resource - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments-virtual-machines?view=azure-devops#feedback)
* Content Source: [docs/pipelines/process/environments-virtual-machines.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/environments-virtual-machines.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by msebolt** [comment]
@juanjosemino  Thank you for the question.

This issue is a good example of a feature suggestion that needs feedback solicited from the product team.

Please start a thread [here](https://developercommunity.visualstudio.com/content/problem/post.html?space=21), or let us know and we can start one for you.

@juliakm

**Comment by msebolt** [comment]
Closing this issue now.
