### ISSUE TITLE
Run tests parallely on agents in agentpool with different run settings

### ISSUE THREAD

**Issue by sudgarre** [MicrosoftDocs/vsts-docs#7067]
We have setup a agentpool with 3 agents tagged to it for running tests in parallel. We would like to  use various input values for .runsettings file to override test run parameters (overrideTestrunParameters) & distribute our test runs on various agents. e.g.,

Lets assume that the agentpool P1 have associated agents A1, A2, A3.
We need agent A1 to configure a test run parameter executeTests = Functionality1, agent A2 to configure a test run parameter executeTests =  Functionality2 etc.,

Please let us know if it is possible to use executionPlan with options Multiagent or Multi Configuration to achieve it.

**Comment by msebolt** [comment]
@sudgarre Thank you for the question.

Please refer to [run tests in parallel](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/parallel-testing-vstest?view=azure-devops) for further reference.

Note that since this is the documentation forum, our support options are limited to article examples only.

For product-related issues and/or new features, get feedback from the product team [here](https://developercommunity.visualstudio.com/spaces/21/index.html).

Otherwise, for additional support options please see:

- [Azure DevOps Support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by msebolt** [comment]
Closing this issue now.
