### ISSUE TITLE
Aborted tests availability

### ISSUE THREAD

**Issue by FredVaugeois** [MicrosoftDocs/vsts-docs#7079]
What is the ETA for the aborted tests availability? I am currently evaluating if I should use an external test manager such as Allure (which provides an easier way to differentiate a failed test from an error) and this is the one feature that I need for it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94cca257-5f81-190e-b50c-7b7f69217234
* Version Independent ID: 1d84dc61-a8bb-b45a-6c93-5bec211c19a5
* Content: [Review test results - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/review-continuous-test-results-after-build?view=azure-devops#feedback)
* Content Source: [docs/pipelines/test/review-continuous-test-results-after-build.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/test/review-continuous-test-results-after-build.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vinojos
* Microsoft Alias: **vinojos**

**Comment by msebolt** [comment]
@FredVaugeois Thank you for the question.

Assigning this to the author for further review.

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by FredVaugeois** [comment]
@WilliamAntonRohm My question was basically if it was possible for you to provide the ETA of the feature in the documentation instead of "this feature is not yet supported". I will ask my question on Stack Overfow, but I'm just saying this for people to avoid asking each time they come up with this issue.
