### ISSUE TITLE
Work Items created from a Template inherit links from a ticket on the Kanban board

### ISSUE THREAD

**Issue by spikeyrichie** [MicrosoftDocs/vsts-docs#7082]
Step 1) Create a New Bug template where you only specify Iteration Path, Repro Steps & System Info

![image](https://user-images.githubusercontent.com/2125462/73276530-be55df80-41e0-11ea-97df-1ad869799245.png)

Step 2) From a Kanban board with a Story present, click the + to create a new Bug linked to the Story. The new Bug has a Parent link to the Story it's raised under

Step 3) Now from within the new Bug, click ... top-right, Templates , New Bug

![image](https://user-images.githubusercontent.com/2125462/73276713-037a1180-41e1-11ea-89c7-69e2dd8abf05.png)

Note that the new Bug created from the Template link has the same parent Story as the Bug created in step 2. I would expect the New Bug template to create a new Bug with only Iteration Path, Repro Steps and System Info present.

**Comment by WilliamAntonRohm** [comment]
@spikeyrichie Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing.  

Also, it looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.

**Comment by spikeyrichie** [comment]
@WilliamAntonRohm please define 'Topic'.

**Comment by msebolt** [comment]
@spikeyrichie Thank you for the feedback.

The work item templates are more designed to pre-populate the values of an existing work item, not create a new one.

If you need a to customize the actual work item, please refer to [custom work item types (WIT)](https://docs.microsoft.com/azure/devops/organizations/settings/work/add-custom-wit).

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
