### ISSUE TITLE
Default Wiki

### ISSUE THREAD

**Issue by jrummell** [MicrosoftDocs/vsts-docs#7088]
How do you set a code wiki as the default wiki? We created a normal wiki, then a code wiki, and we want the code wiki to be the default.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d4fe5c7-0ab6-a0e4-4a6e-f98d0355f49a
* Version Independent ID: ce022fef-054d-cdc2-43e9-a8ee3b8fb592
* Content: [Publish Markdown files from Git repository to wiki - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/publish-repo-to-wiki?view=azure-devops&tabs=browser#feedback)
* Content Source: [docs/project/wiki/publish-repo-to-wiki.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/publish-repo-to-wiki.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
