### ISSUE TITLE
Azure pipeline defaultValue go in overrideParameters after release

### ISSUE THREAD

**Issue by qazinus** [MicrosoftDocs/vsts-docs#7096]
1- Have an release that deploy an arm file that has a parameter that does a concat as a defaultValue
2- Deploy the release
3- The release is deployed sucessfully
4- See the field overrideParameters it now contains the defaultValue than is gonna cause an error
5 - update the value of another paramater in overrideParameters
6- Redeploy
7- There is an error because of the concat

**Comment by WilliamAntonRohm** [comment]
@qazinus Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing.  

Also, it looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.

**Comment by msebolt** [comment]
Closing this now, please comment below if there are further issues.
