### ISSUE TITLE
Associate test from JUnit report etc.

### ISSUE THREAD

**Issue by jimicze** [MicrosoftDocs/vsts-docs#7145]
How can i associate test from JUnit report etc, with testcases in VSTS ? Now, i can link only PBIs, Features, etc. I cant do it directly to testcase itself and track our progress or test runs. I now, that could be done by API right ? So, if i am using Postman or TestCase, i should create API call for each method ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d8a7e40-73d6-795f-7b8c-77104ef606e8
* Version Independent ID: 8f15995b-bd94-8d9f-1e8b-82f1f364d221
* Content: [Associate automated tests with test cases - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/associate-automated-test-with-test-case?view=azure-devops)
* Content Source: [docs/test/associate-automated-test-with-test-case.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/associate-automated-test-with-test-case.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by nheinbaugh** [comment]
Same question. I know (or am confident that the way exists) that I can manipulate test runs through the ADO API, but is the only way for me to associate a test case with the automated test to have my test framework call a helper method that indicates the success or failure of the test?

Is there any other way that I'm missing? It seems like a huge feature gap that JS based tests can't be linked up with ADO even from the XML output of the test framework.

**Comment by msebolt** [comment]
@jimicze Thank you for the question.

For now you'll need to use the API calls to support external frameworks such as JUnit.

Please refer to [this post](https://stackoverflow.com/questions/51181523/vsts-test-junit-and-the-vsts-rest-api) or [this post](https://stackoverflow.com/questions/54690378/run-tests-in-azure-devops-build-pipeline) on current ways to implement such a solution.

Otherwise, please consider suggesting this as a feature to the product team and start a thread [here](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by msebolt** [comment]
Closing this issue now.
