### ISSUE TITLE
Can you mark a pipeline a sucess even if you have a failing step?

### ISSUE THREAD

**Issue by AlverezYari** [MicrosoftDocs/vsts-docs#7146]
I'm curious if its possible to mark a pipeline step as not important enough that it flags the whole build pipeline as a failure it it does happen fail? I know you can mark step success as optional and keep the build going but we've got a linting checker step that we're developing which just happens a on a small section of our project and I'd like to be able to iterate on that step without marking our daily builds as complete failures as I do so.

https://docs.microsoft.com/en-us/azure/devops/pipelines/process/stages?view=azure-devops&tabs=yaml

Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
