### ISSUE TITLE
Unable to select more than 10 reuirements

### ISSUE THREAD

**Issue by KitoCoding** [MicrosoftDocs/vsts-docs#7147]
When trying to Select requirements based off a query, i am unable to select more than 10. Why is that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8e2cb79-709d-972b-6747-6d26c965fb2a
* Version Independent ID: d512ea69-a97a-e5ff-a804-6691c5dfe1e6
* Content: [Create test plans and suites - Azure Test Plans](https://docs.microsoft.com/en-us/azure/devops/test/create-a-test-plan?view=azure-devops#feedback)
* Content Source: [docs/test/create-a-test-plan.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/test/create-a-test-plan.md)
* Product: **devops**
* Technology: **devops-test**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
