### ISSUE TITLE
Can you have the job "skip" instead of "fail" when no resource matches environment filter?

### ISSUE THREAD

**Issue by Sjark** [MicrosoftDocs/vsts-docs#7154]
If I add something like the following in yaml, it will fail if it can't find any resources with the tag taskservice:
```yaml
environment:
      name: ${{ parameters.environmentName }}
      resourceType: VirtualMachine
      tags: taskservice
```
Is there any ways to make it "skip" instead of throwing the following error?:
```
##[error]No resource were found in the environment with ID 13 matching the specified criteria: ResourceId , ResourceName , ResourceType VirtualMachine, Tags taskservice.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77d95db6-9983-7346-d0eb-4b7443e4e252
* Version Independent ID: 0a22cccc-318d-592f-d1ab-09ec01d88087
* Content: [Environment - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/environments?view=azure-devops#feedback)
* Content Source: [docs/pipelines/process/environments.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/environments.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by Sjark** [comment]
If anyone else is having the same issue/need, I have created a feature suggestion [here](https://developercommunity.visualstudio.com/idea/913862/ability-to-have-a-deployment-job-skip-instead-of-f.html).
