### ISSUE TITLE
How to deal with a scenario where VM is behind a proxy, docker is installed in VM and run the self-hosted agent in docker 

### ISSUE THREAD

**Issue by sajisV5Framework** [MicrosoftDocs/vsts-docs#7161]
Thank you for your feedback!

The issues in this repo are for documentation feedback.

If you are submitting your documentation feedback issue directly through GitHub, please provide the URL of the article so we can route the feedback to the correct author.

Please report Azure DevOps or TFS software bugs, feedback, or questions in the [Azure DevOps Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by sajisV5Framework** [comment]
We have tried with the following steps, but failed to run the agent inside the docker.

1. Created a .proxy file and inserted the proxy URL.
2. Build the docker image 
3. Failed with running the docker container which is supposed to act as docker agent.

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 

 
I am closing this issue now.  You are welcome to @ mention me for any followup in the documentation.  We hope to hear from you again.
