### ISSUE TITLE
Can you restore with a Release View of a Nuget feed?

### ISSUE THREAD

**Issue by abelfiore** [MicrosoftDocs/vsts-docs#7164]
Is it possible to use the NuGetCommand to restore packages from a "Release" or "Prerelease" View of a Nuget Feed (from Azure DevOps Artifacts)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fa37a3f-6551-16ad-e164-a4ac522cdaab
* Version Independent ID: a3fd6935-2b99-92ef-4eb3-3249fca01f8a
* Content: [NuGet restore, pack, and publish task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget?view=azure-devops)
* Content Source: [docs/pipelines/tasks/package/nuget.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/package/nuget.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by xaviervv** [comment]
@WilliamAntonRohm How is this not a documentation issue? I have been looking high and low, through the documentation, to find how to connect to a specific view of a feed. I would expect this to be possible, otherwise what is the whole purpose of the view? 
I found documentation on how to create, manage, promote and handle security. I even called the rest api to see if I could get some info that way. 

I would expect to see a section on: How to consume nuget packages from a specific view.

**Comment by xaviervv** [comment]
for other people stumbling onto this
org: https://pkgs.dev.azure.com/{orgname}/_packaging/{feedname}@{viewname}/nuget/v3/index.json
project: https://pkgs.dev.azure.com/{orgname}/{projname}/_packaging/{feedname}@{viewname}/nuget/v3/index.json
