### ISSUE TITLE
Need to fetch intermediate state transitions

### ISSUE THREAD

**Issue by appoosh** [MicrosoftDocs/vsts-docs#7174]
1.	The PBIs getting ‘approved’ by a person other than the PO.
2.	The Test Cases getting ‘validated’ by the creator.
3.	Bugs getting closed by developers.
4.	The Functional PBIs getting to ‘Done’ status by a person other than PO/BA

All these above checks need the full state transition history to be fetched. Is it possible to be filtered out in TFS?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 104a125c-c68d-e4fb-2d6b-ffd8fb7b7462
* Version Independent ID: be4e20fc-72bb-a2a8-a404-8048bd739bf1
* Content: [Query by history - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/history-and-auditing?view=azure-devops&tabs=browser#feedback)
* Content Source: [docs/boards/queries/history-and-auditing.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/queries/history-and-auditing.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
