### ISSUE TITLE
IP whitelist for Service Hooks - Webhooks

### ISSUE THREAD

**Issue by Styxxy** [MicrosoftDocs/vsts-docs#7178]
We would like to add IP restrictions to our service hooks (webhook as an Azure Function). Would the same IP ranges need to be applied to whitelist the incoming requests?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc5a4cfa-aa84-9f0f-55f4-71ec4861c070
* Version Independent ID: d621620a-c924-03b1-8b43-f99c33e58bb8
* Content: [Add IP addresses and URLs to allow list - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/allow-list-ip-url?view=azure-devops)
* Content Source: [docs/organizations/security/allow-list-ip-url.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/allow-list-ip-url.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @chcomley
* Microsoft Alias: **ChComley**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 

I am closing this issue now.  You are welcome to @ mention me for any followup or documentation updates.  We hope to hear from you again.
