### ISSUE TITLE
Code coverage commenting for non-.NET projects

### ISSUE THREAD

**Issue by JohnPhamous** [MicrosoftDocs/vsts-docs#7188]
Hello,

I currently have a React project that uses Jest that exports the code coverage in Cobertura. I'd like to set up the following behavior:

1. For each pull request and subsequent changes, run the pipeline
1. Jest exports the Cobertura code coverage file
1. Run the "Publish code coverage results" step
1. Add comments in the PR about the code coverage results

As of now, the only way I have to seeing the code coverage results for the PR is by clicking on the build then going to the code coverage tab.

**Comment by WilliamAntonRohm** [comment]
Thanks for your feedback. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you may find answers: 

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 

I am closing this issue now.  You are welcome to @ mention me for any followup, including any documentation-related issues.  We hope to hear from you again.
