### ISSUE TITLE
How to choose between runtime variable syntax "macro" and "runtime expression"

### ISSUE THREAD

**Issue by kmathewmk** [MicrosoftDocs/vsts-docs#7195]
Could you please explain in the documentation how to choose between runtime variable syntax "macro" and "runtime expression"? Which is better, in what context and why?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by KerbalSpike** [comment]
I second this! Would be really helpful to know. I noticed that runtime expression doens't work everywhere in place of macro syntax, but don't fully understand why.

**Comment by winstonhenke** [comment]
Also wondering the difference. Was trying to use a runtime expression in a PowerShell script that belonged to a Task Group so it wouldn't show up as a parameter to the Task Group but it doesn't seem to resolve when doing this. The variable is part of a linked variable group which is why I want to use it in but not expose it as an input param

**Comment by winstonhenke** [comment]
To add to my common ^

$(var) works for in that script but $[variables.var] does not
