### ISSUE TITLE
How do you specify multiple paths testResultsFiles

### ISSUE THREAD

**Issue by trajano** [MicrosoftDocs/vsts-docs#7206]
I was trying (and didn't work)
```
testResultsFiles: "**/surefire-reports/TEST-*.xml,**/failsafe-reports/TEST-*.xml"
```

But is there some example especially for integration tests.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 589e076c-9f67-77df-3204-4f549566f21b
* Version Independent ID: 2e51ef13-8fd3-1397-82f0-27c92f1ccee5
* Content: [Maven build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/maven?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/maven.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/maven.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
