### ISSUE TITLE
Select iteration

### ISSUE THREAD

**Issue by EldarAliev** [MicrosoftDocs/vsts-docs#7222]
how to select an iteration in the 'select iteration' field that is only scheduled for the next period.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5430ccc7-e8ea-d02d-b2e9-33b8138338da
* Version Independent ID: 0c0b7f9a-69fe-3edf-6216-a4784d4cb94b
* Content: [View and configure sprint burndown - Azure DevOps](https://docs.microsoft.com/en-gb/azure/devops/report/dashboards/configure-sprint-burndown?view=azure-devops&tabs=remaining-work%2Cmay&source=docs#feedback)
* Content Source: [docs/report/dashboards/configure-sprint-burndown.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/dashboards/configure-sprint-burndown.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
