### ISSUE TITLE
Use a specific version of Node.js globally

### ISSUE THREAD

**Issue by waseem-isaac-BBN** [MicrosoftDocs/vsts-docs#7231]
Can I establish `Node.js tool installer` task globally, For the whole project instead of running it before every pipeline ?

**Comment by WilliamAntonRohm** [comment]
@waseem-isaac-BBN -- Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.

**Comment by waseem-isaac-BBN** [comment]
@WilliamAntonRohm 
The general task : Applying Azure CI/CD over an Angular Project ,
I wonder if I can set The default version of node for the project/azure server , rather than running the mentioned task (`Node.js tool installer`) before each pipeline

**Comment by WilliamAntonRohm** [comment]
@waseem-isaac-BBN -- thank you for clarifying.  Are you reading a specific docs.microsoft.com article?

**Comment by waseem-isaac-BBN** [comment]
@WilliamAntonRohm No .

**Comment by WilliamAntonRohm** [comment]
@waseem-isaac-BBN -- in this case, looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
