### ISSUE TITLE
Cannot change organization location to Australia East  

### ISSUE THREAD

**Issue by thudugala** [MicrosoftDocs/vsts-docs#7242]
Hi. The bot does not show Australia East as target region. Can you help

![image](https://user-images.githubusercontent.com/4112014/74287292-7b723b00-4d8e-11ea-9f7a-5d3d54ad5d61.png)

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
