### ISSUE TITLE
Select Account

### ISSUE THREAD

**Issue by s-bauer** [MicrosoftDocs/vsts-docs#7248]
For Azure AD Authentication there is a query parameter "prompt" which I can set to "select_account", so that the user can choose which account he wants to use for the login. Is this also possible for Azure DevOps? I don't see a nice way of letting the user authenticate with multiple Azure DevOps accounts (in different AAD tenants) without this option!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac47cbcf-45ed-81aa-b532-e7ad0046658e
* Version Independent ID: 7aa1f60e-069f-3d62-5cac-b65e4b1116ef
* Content: [Authorization using OAuth 2.0 - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/integrate/get-started/authentication/oauth?view=azure-devops)
* Content Source: [docs/integrate/get-started/authentication/oauth.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/get-started/authentication/oauth.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
