### ISSUE TITLE
IP addresses of service connections

### ISSUE THREAD

**Issue by aodj** [MicrosoftDocs/vsts-docs#7251]
I'm trying to setup a service connection to my k8s master for GKE but the master node is configured to only accept connections from whitelisted IPs (master authorized networks in Google lingo). What IPs do I need to whitelist to allow the service connection to be permitted to connect?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72b90dd0-49f9-4ed4-3010-9a64dde6ae5a
* Version Independent ID: 6e679d50-4e94-eee3-8793-af884cc909ca
* Content: [Service connections in Azure Pipelines & TFS - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/library/service-endpoints.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/library/service-endpoints.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by RoopeshNair** [comment]
If you are using Microsoft hosted agents, you need to whitelist the [agent ip ranges](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#agent-ip-ranges). For self hosted, it would be your agent host ip address. 
@azooinmyluggage

**Comment by aodj** [comment]
Looking at the referenced file in the article you linked, it's 30000 lines long. My organisation is located in West Europe; am I right in assuming I should white list the IPs under the `AzureCloud.westeurope` group?

For relevance the list of items referencing West Europe is as follows:

```
ApiManagement.WestEurope
AppService.WestEurope
AppServiceManagement.WestEurope
AzureBackup.WestEurope
AzureCloud.westeurope
AzureConnectors.WestEurope
AzureContainerRegistry.WestEurope
AzureCosmosDB.WestEurope
AzureDataLake.WestEurope
AzureIoTHub.WestEurope
AzureKeyVault.WestEurope
AzureMachineLearning.WestEurope
AzureMonitor.WestEurope
BatchNodeManagement.WestEurope
EventHub.WestEurope
HDInsight.WestEurope
MicrosoftContainerRegistry.WestEurope
ServiceBus.WestEurope
ServiceFabric.WestEurope
Sql.WestEurope
Storage.WestEurope
```

**Comment by RoopeshNair** [comment]
@justhchung

**Comment by justhchung** [comment]
@aodj  You need to whitelist all regions in Europe geography which includes North Europe and West Europe. https://azure.microsoft.com/en-us/global-infrastructure/geographies/

Due to capacity restrictions, some organizations in the West Europe regions may occasionally see their hosted agents located outside their expected geography. In these cases, additional IP ranges must be included for regions in the capacity fallback geography. If your organization is in the West Europe region, the capacity fallback geography is France. So you need to whitelist France Central and France South regions.

**Comment by aodj** [comment]
Can you clarify that for me: if I'm wanting to handle deployments from Azure DevOps into my GKE cluster, I need to whitelist over 1000 IP ranges? I used the following `jq` query to get all the `addressPrefixes` from the file linked in the article:

```
[.values[]|select(.name|contains("westeurope", "WestEurope", "northeurope", "NorthEurope"))|.properties.addressPrefixes]|flatten|unique
```

[Here's the list of IPs for reference](https://gist.github.com/aodj/fdd14886bd62521e19248ff5e4044830).

What I need to know is can I just whitelist a subset of the ranges defined in that file, or are you seriously saying that I need to whitelist the IPs listed under `EventHub.WestEurope`, and 
`HDInsight.WestEurope` to allow Azure DevOps to deploy?

**Comment by justhchung** [comment]
@aodj That is correct. If you are using Microsoft hosted agents, you need to whitelist the entire geography with 1,000 IP ranges. If this is a concern, you can use self-hosted agents. 

We are working on elastic self-hosted agent pools where Azure Pipelines can dynamically provision VMs in a customer's subscription. This will have some of the benefits of hosted agents in that Azure Pipelines will manage the lifecycle of these machines. However, since they are in the customer's subscription, they will have more control on the types of machines, images, and networking. Then, customers can whitelist the IP addresses of the elastic self-hosted agents they control. This will be available by Q2 CY2020.
