### ISSUE TITLE
Set a multi-job output variable restricted to YAML?

### ISSUE THREAD

**Issue by nezoic** [MicrosoftDocs/vsts-docs#7252]
"Set a multi-job output variable
You cannot pass a variable from one job to another job of a build pipeline unless you use YAML."

Why? I have several marketplace extensions in my pipeline that do not support YAML but I need to share variables across various stages of my release. Is there any other way to do this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=classic%2Cbatch)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

Also, to make sure it gets in front of the right people, please [submit your issue]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here.
