### ISSUE TITLE
Need a way to query a user for input and use response to set a variable

### ISSUE THREAD

**Issue by ET3117** [MicrosoftDocs/vsts-docs#7257]
Basically, I seek a logical extension of this task that would allow a user to be queried to set the value of a variable at runtime.  This variable would have been predefined and the user could be prompted to set the variable value.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1c633b9-c8b2-e05d-de2c-7754894d28fd
* Version Independent ID: df031b76-0fe7-e138-dd36-2736757a97fd
* Content: [Manual Intervention task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/manual-intervention?view=azure-devops#feedback)
* Content Source: [docs/pipelines/tasks/utility/manual-intervention.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/manual-intervention.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by WilliamAntonRohm** [comment]
Thanks for your feedback. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. You may find answers here:

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 


Also, the product teams aren’t always watching this repository, so to make sure this gets in front of them for triage, please [submit your suggestion]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.
