### ISSUE TITLE
This whole page does not work. Typical...

### ISSUE THREAD

**Issue by maxhoribilis** [MicrosoftDocs/vsts-docs#7259]
I'm not surprised that Microsoft Teams seems to have trouble to talk to Microsoft Visual Studio... 

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 1cddc0ae-93af-297c-2e71-334143ebee1e
* Version Independent ID: cb76e516-8471-c3e1-45f4-0a20a223f32a
* Content: [Create a service hook Microsoft Teams - Azure DevOps Services, TFS 2017](https://docs.microsoft.com/fr-fr/azure/devops/service-hooks/services/teams?view=azure-devops#feedback)
* Content Source: [docs/service-hooks/services/teams.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/service-hooks/services/teams.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chasewilson
* Microsoft Alias: **phwilson**

**Comment by WilliamAntonRohm** [comment]
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here. 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
