### ISSUE TITLE
Updating pre-installed extensions

### ISSUE THREAD

**Issue by evakili** [MicrosoftDocs/vsts-docs#728]
Is there any method to update pre-installed extensions or we should wait until next TFS update/release?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46849bf5-07ed-62cd-66a5-2ebabe449855
* Version Independent ID: d12ad05e-4348-f13a-ea35-7bb4761c3b0b
* Content: [Install extensions for Visual Studio Team Foundation Server (TFS)](https://docs.microsoft.com/en-us/vsts/marketplace/get-tfs-extensions?view=tfs-2018#adding-pre-installed-extensions-first-party)
* Content Source: [docs/marketplace/get-tfs-extensions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/marketplace/get-tfs-extensions.md)
* Service: **unspecified**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by elbatk** [comment]
Hi @evakili , that's a good question. Adding @harishkragarwal from the Marketplace team to see if he has an answer for ya.

**Comment by harishkragarwal** [comment]
Hi @evakili, if your TFS instance is in connected mode i.e. connected to internet then an extension update would automatically reach you with 24 hours. However, if your TFS instance is in disconnected mode, then you can go to Visual Studio Marketplace, check if the desired extension has been updated since you last downloaded it. If yes, then download the extension and manually update your TFS instance with the new version.

**Comment by evakili** [comment]
Thanks @harishkragarwal. But there is no option for downloading pre-installed extensions from marketplace or I couldn't find it.

**Comment by harishkragarwal** [comment]
Hi @evakili, pre-installed extensions cannot be acquired from Marketplace. They are only updated with new updates/releases of TFS.

**Comment by evakili** [comment]
Thank you @harishkragarwal. It's so bad but with fast release cycle of TFS it could be tolerable.
