### ISSUE TITLE
How can I get the output without -o yams/json

### ISSUE THREAD

**Issue by MetelliAndrea** [MicrosoftDocs/vsts-docs#7287]
As mentioned in the title, is possible to specify the common output of kubectl? 

```bash
$ Kubectl get svc -n default 
NAME                                     TYPE           CLUSTER-IP       EXTERNAL-IP      PORT(S)                      AGE
kubernetes                               ClusterIP      10.96.0.1        <none>           443/TCP                      1y
my-nginx-nginx-ingress-controller        LoadBalancer   10.xxx.xxx.xxx   192.168.xxx.xxx   80:30452/TCP,443:30058/TCP   363d
my-nginx-nginx-ingress-default-backend   ClusterIP      10.xx.xx.xx      <none>           80/TCP                       363d
```

is that possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcbb25d1-a706-e8fc-61e4-d5b86aa54f47
* Version Independent ID: 5634d9dd-fd92-761c-24b8-5e32ed6c6c35
* Content: [Kubectl task - Azure Pipelines & TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/kubernetes?view=azure-devops)
* Content Source: [docs/pipelines/tasks/deploy/kubernetes.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/deploy/kubernetes.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @azooinmyluggage
* Microsoft Alias: **atulmal**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
