### ISSUE TITLE
Support for RedHat in Microsoft hosted agent

### ISSUE THREAD

**Issue by jochandy** [MicrosoftDocs/vsts-docs#7291]
Is there a plan to support RedHat in Microsoft hosted agent pool?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99af681d-41ad-da15-0b72-08b5cd5a11ac
* Version Independent ID: 2fa0df36-a437-8cbb-b019-b49b31b1e116
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#feedback)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/hosted.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
