### ISSUE TITLE
How TFS Uses Alternate Credentials？

### ISSUE THREAD

**Issue by xiaofuhub** [MicrosoftDocs/vsts-docs#730]
Why did I fail to access the TFS Server with my Visual Studio account and password（
Without using git-credential-manager.exe）, and I used a backup authentication key to access the TFS Server successfully？

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f8b4989-21f0-53c5-dfce-6d5f1a66b8b2
* Version Independent ID: 2f4419a7-408b-40cd-9190-985a9976d556
* Content: [Authenticate with your Git repos](https://docs.microsoft.com/en-us/vsts/git/auth-overview?view=vsts#alternate-credentials)
* Content Source: [docs/git/auth-overview.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/git/auth-overview.md)
* Service: **unspecified**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by justmarks** [comment]
@Xiaofuhub - we need more information to help diagnose this issue.  Please reach out to support

**Comment by thE-iNviNciblE** [comment]
for example
git cmd:

Username for 'https://xxx.visualstudio.com': xxx@live.de
Password for 'https://xxx@live.de@xxx.visualstudio.com':

login is correct but can't login...

**Comment by dozzlee** [comment]
I have the exact same problem @thE-iNviNciblE  , its a nightmare.

**Comment by dozzlee** [comment]
@thE-iNviNciblE  did you sort it out? If so how did you do it?  Any help is welcome.

**Comment by thomps23** [comment]
Please accept our apology for the significant delay in addressing this issue.

It looks like you're working through an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
