### ISSUE TITLE
Platform "any cpu" needs to be written as "AnyCpu" to work

### ISSUE THREAD

**Issue by Androkai** [MicrosoftDocs/vsts-docs#7310]
Hey guys,

The actual documentation lists the parameters `Win32`, `x86`, `x64` and `any cpu` as valid for the `platform` property. I had to learn that `any cpu` needs to be written without the space like `AnyCpu` to actually work.

Thanks a lot for your hard work on documenting all this stuff.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22342679-18af-7c79-f902-fe9c0bb55379
* Version Independent ID: a8e7c201-6593-458b-5a81-b54e93fde4b5
* Content: [MSBuild build and release task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/msbuild?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/msbuild.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/msbuild.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by Androkai** [comment]
Found the note _"If you are targeting an MSBuild project (.*proj) file instead of a solution, specify AnyCPU (no whitespace)."_ this moment so it is already documented. Sorry ☺

**Comment by larrybud2004** [comment]
I mean, it may be documented, but when a pipeline is created, the default value is "Any CPU" with a space.. They should at least fix THAT!!

**Comment by duaneking** [comment]
Just want to point out respectfully that the Azure DevOps UI actively misrepresents this and gives us the wrong data, by telling us to use values that will not work.

And to be frank, this also means we can use the default variables in pipelines, because the one that MSFT defines and has documented use values that are not compatible with this.


This actively makes using azure less of a Business asset than the competition, because I've never had to waste days of my time following the on-screen instructions in my braille terminal only to be finding that that the UI based documentation LIES to the blind with Google or AWS,
