### ISSUE TITLE
Can I cancel a build using Logging commands in the future?

### ISSUE THREAD

**Issue by doggy8088** [MicrosoftDocs/vsts-docs#7322]
I'd like to cancel a build when my task meet some criteria. Is it possible to have a Logging command like for that? Something like:

```log
##vso[build.complete result=Canceled;]
```

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 16bf0bbb-8b63-6384-aa33-b5b1e2b8cfe3
* Version Independent ID: f4da8dbd-a02f-bbdf-2cf2-60e081339237
* Content: [Logging commands - Azure Pipelines](https://docs.microsoft.com/zh-tw/azure/devops/pipelines/scripts/logging-commands?view=azure-devops&tabs=bash#build-commands)
* Content Source: [docs/pipelines/scripts/logging-commands.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/scripts/logging-commands.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @thomps23
* Microsoft Alias: **phwilson**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 


 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
