### ISSUE TITLE
Condition for ignore task

### ISSUE THREAD

**Issue by timendez** [MicrosoftDocs/vsts-docs#7332]
I want all tasks to behave as normal and not trigger if a previous task failed. However, I want to be able to set a task in the mix where its results do not affect the rest of the build. So if I have:
Task A
Task B
Task C
Task D

If Task B fails, I want Task C to continue, but if Task A fails I want none of the rest of the tasks to run. If Task C fails, I want Task D to not run.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f151218-9a11-0078-e038-f96198a76143
* Version Independent ID: 09c4d032-62f3-d97c-79d7-6fbfd89910e9
* Content: [Conditions - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml#q--a)
* Content Source: [docs/pipelines/process/conditions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/conditions.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by timendez** [comment]
@WilliamAntonRohm it looks to me like the documentation should just show an example for this scenario - are you saying the functionality does not exist?
