### ISSUE TITLE
Number of file changes in the pull request iteration exceeded 100

### ISSUE THREAD

**Issue by buckleyGI** [MicrosoftDocs/vsts-docs#7339]
It seems we are hitting the limit of 100 quit easily. Can we increase the value to 500 or so?

https://docs.microsoft.com/en-us/rest/api/azure/devops/git/pull%20request%20iteration%20changes/get?view=azure-devops-rest-5.1#uri-parameters
$top: The number of changes to retrieve. The default value is 100 and the maximum value is 2000.

![image](https://user-images.githubusercontent.com/2102864/74819566-e37dcf80-5300-11ea-9748-a902764aca39.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aaa4f4c6-0a42-108e-79dd-5724e1049bd5
* Version Independent ID: f4a857d1-78bc-170b-b138-fcf490c85b38
* Content: [Code coverage for pull requests - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/codecoverage-for-pullrequests?view=azure-devops)
* Content Source: [docs/pipelines/test/codecoverage-for-pullrequests.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/test/codecoverage-for-pullrequests.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @PBoraMSFT
* Microsoft Alias: **pbora**

**Comment by ganesp** [comment]
@buckleyGI 
Are you interested in knowing diff code coverage for pull request which has more than 100 files?

Such a big pull requests are generally created while doing integration across branches where diff code coverage is not an interesting metric.
And therefore we put that limit of pull request with max 100 files changed, to ensure we are serving the coverage data to only the relevant pull requests from code coverage perspective.

Please explain your scenario as well, it will help us understand the requirement here.

Just FYI, the following REST API doc you referenced earlier is not related to the question you have:
[https://docs.microsoft.com/en-us/rest/api/azure/devops/git/pull%20request%20iteration%20changes/get?view=azure-devops-rest-5.1#uri-parameters](https://docs.microsoft.com/en-us/rest/api/azure/devops/git/pull%20request%20iteration%20changes/get?view=azure-devops-rest-5.1#uri-parameters)

**Comment by buckleyGI** [comment]
@ganesp 
We have set a policy that the code coverage should be at least 70% for a Pull Request to be completed using the target parameter in the yaml.
It's a way to up our code coverage for new code being integrated in master.

![image](https://user-images.githubusercontent.com/2102864/74838122-497b4e80-5323-11ea-9e19-87fce7a2ce5f.png)

**Comment by ganesp** [comment]
@buckleyGI 
Thanks for the clarification. 
Can you please confirm that it is common for engineers from your team to have pull requests with more than 100 files changed? 
This will help us understand your scenario better.

**Comment by buckleyGI** [comment]
@ganesp  
This is indeed the case. Some of our pull request have more than 100 files. Think of a feature branch that has been out of master for a while. It's not the best practice right? But it's actually even more important to get guaranteed code coverage for these large PR.

**Comment by ganesp** [comment]
@buckleyGI 
Yes, not a best practice. If you have a feature branch, you can define the PR code coverage status/policy on the feature branch directly, instead of accumulating the code coverage debt till you merge to master. 

Measuring coverage on PR with hundreds of files has other issues as well, like which developers would make up for the coverage debt whereas having coverage debt addressed at the beginning (in your case feature branch) keeps your code debt free at any point in time and you do not have to put dedicated effort on adding tests later.

We have new code coverage experiences planned/in preview for Azure Pipelines, and they may be more suited to your needs, I think. NOTE that these reports are not for PR but pipeline runs.

If interested in trying out the new experience, please write to us with your account details to: devops_tools@microsoft.com

Code coverage summary at pipeline run level with list of files where coverage changed from last successful pipeline run:

![image](https://user-images.githubusercontent.com/32353612/75012393-e8c94e80-54a7-11ea-9a44-70f9d2506294.png)

You can browse to individual source code file and see line wise coverage details:

![image](https://user-images.githubusercontent.com/32353612/75012424-f67ed400-54a7-11ea-8e1b-9d81e992ba21.png)

NOTE:
This is supported only in case you use AzureRepos and Visual Studio Coverage format (.coverage)

Upcoming enhancements:
A view for all files for which coverage is collected. We are working on this currently and this will be available in the next iterations.

**Comment by ganesp** [comment]
@buckleyGI 
I have not heard from you yet. 
As mentioned earlier, supporting max 100 files in one PR is our design choice. 
And your requirement aligns with code coverage experience for CI (not PR), so please let us know if you are interested in trying out the new experience for CI builds.

**Comment by buckleyGI** [comment]
@ganesp 
Hi, I thought all was clear. We currently prefer keeping our CI/CD stable so we won't opt in to preview features. We are looking forward to when it comes GA. Thank you

**Comment by mr-panucci** [comment]
Hi,

I just encountered this issue myself and was hoping to find a resolution. We use the code coverage policy as a gateway rule to get into master. It's quite important for us that this can't be bypassed - especially if the author is making poor choices on the size of the PR. This is a way around this check that we hadn't anticipated.

Regarding best practice, in this case the large number of file changes was due to a namespace change and moving of files. This is a small change that affects a large number of files. I don't see this as bad practice and couldn't be broken down further without some unnecessary hacking around. 

What's the reason for the limit? Is it possible to remove at all?

**Comment by cResults** [comment]
We just experienced the same situation as mr-panucci described and we were very disappointed that the protection we thought we had in place could be usurped/bypassed by this type of change.  While this is rather rare, it is still a loop hole where this feature will allow untested code into master or any other branch it is set to run on. 

Regarding arguments made above about who will be responsible for those untested in lines for our case it is very straight forward, the team wanting the PR to be accepted would be the team required to get the necessary lines covered.

@ganesp if you are still looking for someone to test the Pipeline code coverage feature mentioned on Feb 21 we would be will since it appears this feature has not yet been released
![image](https://user-images.githubusercontent.com/5702582/99279087-d47b6d80-27fd-11eb-9622-5fe8dea0e058.png)

If there are steps we need to take to enable this, please let me know.

**Comment by PaulVrugt** [comment]
I agree that the 100 files limit is completely arbitrary and simply skipping the policy if it is exceeded doesn't make sense either.

In our case, we sometimes have PR's with more than 100 files, but our configured code coverage check not all files in the PR are relevant for code coverage

**Comment by zane-woodard-drc** [comment]
What kind of design choice is an arbitrary cutoff of 100 with no configurability? Is this code coverage policy not supposed to work for different teams with different workflows?
If we have the policy enabled on a branch, we're clearly interested in knowing the code coverage status of PRs into that branch -- even if they're large.

Further, this limitation/"design choice" isn't documented anywhere. This should be documented clearly that the ADO code coverage experience doesn't support large PRs so that we know we need to use something else if we need to support large PRs.

**Comment by WilliamAntonRohm** [comment]
@YohanSciubukgian -- Yohan, thank you for your follow-up.  Please add it here:
- [Developer Community](https://developercommunity.visualstudio.com/AzureDevOps)
