### ISSUE TITLE
Is macOS-latest really macOS-10.14? The latest is 10.15

### ISSUE THREAD

**Issue by ajklotz** [MicrosoftDocs/vsts-docs#7343]
Not sure what is really being used when I define macOS-latest in my build yaml

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99af681d-41ad-da15-0b72-08b5cd5a11ac
* Version Independent ID: 2fa0df36-a437-8cbb-b019-b49b31b1e116
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/hosted.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@ajklotz -- Anthony, thank you for your question.  You may find answers here:

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 


 
@steved0x -- Steve, please look into this potential documentation issue.

**Comment by steved0x** [comment]
@ajklotz There is some more information [here](https://devblogs.microsoft.com/devops/azure-pipelines-hosted-pools-updates/) about `macOS-latest` - we are transitioning over so that `macOS-latest` points to the new 10.15. I'm checking right now, and if the switchover has happened, I'll get the article updated. If not, I will continue to monitor this and update the article once the change is complete.

**Comment by steved0x** [comment]
@ajklotz `macOS-latest` now points to `macOS-10.15`, you can verify that by adding a `- script: sw_ver` command to your pipeline, you should get:

```
ProductName: Mac OS X 
ProductVersion: 10.15.3 
BuildVersion: 19D76 
```

I am updating the docs to reflect this. Thank you.
