### ISSUE TITLE
Agent forcely clean repo even if I don't want to

### ISSUE THREAD

**Issue by VerdonTrigance** [MicrosoftDocs/vsts-docs#7360]
When I want to use some of my scripts located at the root repo in different stage (and jobs) all my files are gone. Nowhere telling that agent clean repo AFTER job or stage complete. For example, my build stage checked out files, build, publish artefacts. Then my publish stage is going to consume powershell script that I places in the root but can't find it because it's gone. What the hell I ask? It was never told about it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 800c5477-b39f-48e6-6f9c-aa7994b2ec2a
* Version Independent ID: db9e2e97-d44d-734e-6a6f-b01f60f01c95
* Content: [Options for Git repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/pipeline-options-for-git?view=azure-devops)
* Content Source: [docs/pipelines/repos/pipeline-options-for-git.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/repos/pipeline-options-for-git.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
Sorry for the great delay, and I'm sorry that you ran into trouble. Each job is run on a different agent when using Microsoft-hosted agents, and (depending on how your agent pool is set up) jobs may run on different agents there as well, so that may explain why things appeared to be missing in your subsequent stages/jobs. Let me see if I can find a good place to make a note about this. [Artifacts](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml) is how you can share build outputs and things between different stages of a pipeline. I will update the issue with a link to the doc update.

**Comment by steved0x** [comment]
Fixed in https://github.com/MicrosoftDocs/vsts-docs/commit/adc1e92b91583a1548fe0e0471816ef53430d898#diff-ac0e0c6af13a793fd812015b700b664b
