### ISSUE TITLE
Not working on Azure DevOps Server Version Dev17.M153.5

### ISSUE THREAD

**Issue by surensaluka** [MicrosoftDocs/vsts-docs#7366]
Hi, I get the following error when try to configure via Power BI query.

DataSource.Error: Microsoft.Mashup.Engine1.Library.Resources.HttpResource: Request failed: 
OData Version: 3 and 4, Error: The remote server returned an error: (400) Bad Request.
OData Version: 4, Error: The remote server returned an error: (400) Bad Request.
OData Version: 3, Error: The remote server returned an error: (400) Bad Request.
Details:
    DataSourceKind=OData
    DataSourcePath=http://boardpacdevops/BoardPAC%20Collection/BoardPAC%20UWP/_odata/v3.0-preview/TestPoints

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 624755d0-ee11-e9e4-ea2b-26444f50259d
* Version Independent ID: 02ef07f5-8054-f6a3-9a55-34acd967f10d
* Content: [Manual test progress status sample Power BI report - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/powerbi/sample-test-plans-progress-status?view=azure-devops&tabs=powerbi#feedback)
* Content Source: [docs/report/powerbi/sample-test-plans-progress-status.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/powerbi/sample-test-plans-progress-status.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **shdalv**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 


 
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
