### ISSUE TITLE
How to delete

### ISSUE THREAD

**Issue by Rick-Anderson** [MicrosoftDocs/vsts-docs#737]
See https://github.com/MicrosoftDocs/vsts-docs/issues/581 for a work around.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b03af1d9-4eeb-ac18-d517-a0a44a2478be
* Version Independent ID: 842691c8-8c41-facf-2cff-03542262f2e5
* Content: [Delete a Git repo from your team project](https://docs.microsoft.com/en-us/vsts/git/delete-existing-repo?view=vsts)
* Content Source: [docs/git/delete-existing-repo.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/git/delete-existing-repo.md)
* Service: **unspecified**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by lifeinchords** [comment]
#581 is not working as described, and the issue is closed + locked so posting here.

I created the organization with git, by accident. Then went in and changed it to TFS after it got set up. Well, I thought I was changing it, but it added TFS. Now I have both and I can't delete git.

![screen shot 2018-08-28 at 1 45 03 pm](https://user-images.githubusercontent.com/716168/44740525-abf5e480-aac8-11e8-91b0-85750b820e84.png)

**Comment by MarcoGuzman21** [comment]
I had the same problem…
That happens if you're trying to delete the unique existing repo in your account.
You must create a new repo to be able to delete the older repo.
Sorry my bad English.

**Comment by rootbdfy** [comment]
I have same problem and I have another VSTF repo in this project.
