### ISSUE TITLE
We have a group that has Basic level access. What happens when we add another new user to that group? Will that increase the Basic user count we are paying for in the billing?

### ISSUE THREAD

**Issue by pradeep864** [MicrosoftDocs/vsts-docs#7387]
We have a group that has Basic level access. What happens when we add another new user to that group? Will that increase the Basic user count we are paying for in the billing?

Scenario 1: Lets say we add an Active directory group to the DevOps group and all users have either Subscriber or Basic level access. What happens when we add another new user to the Active directory group? Will a new basic user slot gets added to the billing?

Scenario 2: Lets say we add an Active directory group to the DevOps group and all users have either Subscriber or Basic level access. What happens when we add another new user to the DevOps group rules? Will a new basic user slot gets added to the billing?

https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/assign-access-levels-and-extensions-by-group-membership?view=azure-devops&tabs=preview-page#related-articles

**Comment by WilliamAntonRohm** [comment]
@pradeep864 -- It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few support options that might help you with the issue that you're experiencing:​ 

- If you have a subscription, contact [Visual Studio Subscriptions Support](https://visualstudio.microsoft.com/subscriptions/support/).​ 
- If you are not sure if you have a subscription, sign in to [https://my.visualstudio.com/subscriptions](https://my.visualstudio.com/subscriptions) to see all the subscriptions assigned to your email address.​ 
- If you do not have a subscription, consider using either our [Live Chat]( https://visualstudio.microsoft.com/vs/support/#talktous) (English only) support option for installation issues, or reaching out to us and other Visual Studio developers through our [Visual Studio conversation in the Gitter community](https://gitter.im/Microsoft/VisualStudio).

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by pradeep864** [comment]
@WilliamAntonRohm This is not an issue with the product I am experiencing. This is a question about the group rules and how it behave in different scenarios. I am trying to setup those group rules in my organization and needed some clarification so that I have better understanding on the billing behavior . I saw there were some other questions posted about different scenarios and open this issue. It would be great if you can provide more information on this.

**Comment by WilliamAntonRohm** [comment]
@pradeep864 -- thank you for your explanation.  You may find [this information](https://www.microsoft.com/en-us/download/details.aspx?id=13350) helpful.  Please let me know if otherwise.
