### ISSUE TITLE
Any word on OS update schedules?

### ISSUE THREAD

**Issue by roycornelissen** [MicrosoftDocs/vsts-docs#7399]
Can you provide info on how often hosted agents receive OS-updates?

We recently ran into an issue building a Docker image based on `mcr.microsoft.com/windows/servercore:1809`. It started failing because this image was updated to `10.0.17763.1040` (security patches), but the host was still on `10.0.17763.973`. As of Feb 26th, this is still the case, so we have to pin the version to `10.0.17763.973`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47625b86-abd5-ee15-6d61-8bcf81861b96
* Version Independent ID: be9a6174-a69b-7aed-d584-5f602fcc5eb4
* Content: [Azure Pipelines Agents - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops&tabs=browser#feedback)
* Content Source: [docs/pipelines/agents/agents.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/agents.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 


 
I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
