### ISSUE TITLE
Alpine image support

### ISSUE THREAD

**Issue by d4md1n** [MicrosoftDocs/vsts-docs#7402]
I am trying to use docker:dind image as an agent in order to run integration tests using docker compose

/bin/installDependencies.sh does not support alpine os, how can I find the required dependencies for the agent to run?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31d4f6c-d16d-2ba1-1294-6aa94e328046
* Version Independent ID: 88aec599-4410-697d-1002-1c41b1c17bb6
* Content: [Running a self-hosted agent in Docker - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops)
* Content Source: [docs/pipelines/agents/docker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/docker.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 


 
I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by jakuboskera** [comment]
@WilliamAntonRohm 
What is the current status with supporting Alpine based images in Azure pipelines. It's been a almost 3y from last update...
Thanks

**Comment by WilliamAntonRohm** [comment]
@jakuboskera -- Jakub, thank you for your follow-up.  Please see this comment:  https://github.com/MicrosoftDocs/azure-devops-docs/issues/5714#issuecomment-1373737117.
