### ISSUE TITLE
Where are the dimensions specified?

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/vsts-docs#741]
> The number of lines of code that the team added to files for the dimensions that you specify.

Where do we specify the file types? Because this does not include a bunch of file types that would make this a more complete report. 

These stats also need to report correctly in general. Just because I make a release or feature branch for something does not mean "I" added 150K LOC. Our two TFS servers (2013/2015) report that I have added, deleted, or changed close to 7 million lines of code in 6 years. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8d6516f-5d33-b1e0-3cec-7d4c17dc1b05
* Version Independent ID: a94cbfed-42df-5a32-fa89-29781eec8056
* Content: [Analyze and report on code churn and code coverage - TFS](https://docs.microsoft.com/en-us/vsts/report/sql-reports/perspective-code-analyze-report-code-churn-coverage?view=tfs-2018#lf-content=213447083:773546343)
* Content Source: [docs/report/sql-reports/perspective-code-analyze-report-code-churn-coverage.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/report/sql-reports/perspective-code-analyze-report-code-churn-coverage.md)
* Service: **devops-server**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by StingyJack** [comment]
RE: File Types... 

ZPL, APL, and a few other printer programming languages. We make a lot of label templates that count as "code", and some of them may be of different encoding types.  There are a  handful of other file types for a DSL as well that I dont think are getting counted.

Since we use a common convention across projects, I wrote a SQL script to create a table of the different Trunk, Feature, and Release branches and filter on that to get more realistic numbers. It would have been nice to include some kind of branch lineage in with these stats, but w/e.

> I speculate that they originally envisioned that these actions would involve a separation of duties.

They were (are) thinking "too big". Most places are going to have one or two "tfs admins" who get all the duties of administration and release management.  I dont really want a program to require me to wear yet another hat.

Thanks for the tip on the file extensions, I'll try to get a look at that this week.

**Comment by SamGrantham** [comment]
Hi @StingyJack,

>ZPL, APL, and a few other printer programming languages. We make a lot of label templates that count as "code", and some of them may be of different encoding types. There are a handful of other file types for a DSL as well that I dont think are getting counted.

Let me look at the code and see to what degree we can include and exclude different extensions.  I think @KathrynEE would agree what ever the answer we find it would be good to have that info here.

>They were (are) thinking "too big". Most places are going to have one or two "tfs admins" who get all the duties of administration and release management. I dont really want a program to require me to wear yet another hat.

I don't disagree, there is a constant tension between how much process should be enforced via functionality and most of the time when we make a mistake we course correct in later versions.  The warehouse is one of the more static pieces of the product, you can see almost the entirety of the architecture as early as 2010 version and some of those decisions cause issues to this day.  I'm really excited for the VNext for TFS reporting, it will be very similar to the Preview in place for VSTS, and use AS and PowerBI rather than the current Reporting Stack.  Per the Feature Timeline, at least some of the data will be on that system in the TFS2019 version. (https://docs.microsoft.com/en-us/vsts/release-notes/)

>@SamGrantham - that link takes me to the page where I reported this.

Correct, the Version Control File.File Extension Dimension is what you can add to the pivot in order to filter the report on File Extension...

`The following table describes the dimensions and attributes in the Code Churn perspective. These attributes supplement the Team Project and Date shared dimensions, which Working with Shared Dimensions describes. You can aggregate the measures along each of these attributes. `

I apologize if that isn't what you are asking, did I misread?

**Comment by SamGrantham** [comment]
Hi @StingyJack  and @KathrynEE,

There *is* a way to modify the file types that are treated by the system as "code" in my testing I see that once these are added to the Team Project they flow all the way through to the cube.  Please see: https://docs.microsoft.com/en-us/vsts/tfs-server/admin/manage-file-types?view=tfs-2017#edit-file-type for instructions on how to add a file type.  What this article does not say (and I am adding a comment for it) is that while the behavior of unknown files is same for merging and sharing, only known file types are aggregated in the warehouse, also because it is not clear in that document this must be done via the Team menu in Visual Studio. 

@KathrynEE let me reread both the articles and I will submit some suggested Changes to help clarify this.
