### ISSUE TITLE
Project stats

### ISSUE THREAD

**Issue by EldarAliev** [MicrosoftDocs/vsts-docs#7464]
Hi!
how do I hide 'Project stats' on the front page (Overview\/Summary)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc7a1aaa-9aee-2b23-d77f-634a42c94280
* Version Independent ID: 293f604b-9b00-7758-7645-67a7e296d585
* Content: [Features and services included - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/user-guide/services?view=azure-devops)
* Content Source: [docs/user-guide/services.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/user-guide/services.md)
* Product: **devops**
* Technology: **devops-new-user**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 


 
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by EldarAliev** [comment]
Hello!
The script of my work has nothing to do with this, I just want to remove from the homepage the information I do not need.

**Comment by EldarAliev** [comment]
https://stackoverflow.com/questions/60508260/front-page-hide-project-stats
