### ISSUE TITLE
Link to source code of library

### ISSUE THREAD

**Issue by MattJeanes** [MicrosoftDocs/vsts-docs#7520]
I'm not sure if this because the source is not public but I cannot seem to find anywhere the location of the source code that makes these libraries - I've found a bug I'd like to report in the `Microsoft.VisualStudio.Services.Release.Client` library, and also it would have been useful to help debug the issue I found, had to resort to decompiling the dlls.

All the nuget packages project sites link back to here, does the source exist publically - if so, where?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 413163f0-28c3-a2a7-d626-fcb81bcb2257
* Version Independent ID: 57c127da-2b1e-d29e-9abb-a3c258762ccf
* Content: [.NET Client Libraries - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/dotnet-client-libraries?view=azure-devops#known-issues)
* Content Source: [docs/integrate/concepts/dotnet-client-libraries.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/integrate/concepts/dotnet-client-libraries.md)
* Product: **devops**
* Technology: **devops-ecosystem**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@MattJeanes -- Matt, thank you for your question.  Please [report your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21). 

@chcomley -- Chrystal, please let us know whether these libraries have a public source.

**Comment by chcomley** [comment]
Hi @MattJeanes, The code lives in Azure DevOps and we only release nuget packets and documentation that's auto-generated from the code. You can find some documentation here: https://github.com/MicrosoftDocs/vsts-rest-api-specs. I recommend that you file any issues you find on the dev community portal, as it would likely have to be fixed in the Azure DevOps code base. Hope that's helpful. 
If you have any further questions, feel free to @mention me. Thanks and have a great day.
