### ISSUE TITLE
Microsoft hosted agent IP ranges - West Europe agents sometimes fallback to North Europe

### ISSUE THREAD

**Issue by mohamed-shehata-m** [MicrosoftDocs/vsts-docs#7588]
According to this article "[Agent IP ranges](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops#agent-ip-ranges)",  there is this statement:

> Due to capacity restrictions, some organizations in the Brazil South or West Europe regions may occasionally see their hosted agents located outside their expected geography. In these cases, additional IP ranges must be included for regions in the capacity fallback geography.
If your organization is in the Brazil South region, your capacity fallback geography is United States.
If your organization is in the West Europe region, the capacity fallback geography is France.
Our Mac IP ranges are not included in the Azure IPs above, though we are investigating options to publish these in the future.

We have SQL managed instance and we need to whitelist Azure DevOps IP ranges for database deployment. I whitelisted West Europe & France regions.

I found out that deployment is failing because agents sometimes are located in Ireland. 

Documentation should be updated to include North Europe.

**Comment by steved0x** [comment]
@mohamed-shehata-m I will find out what changed and get this updated to reflect the latest. Sorry that you ran into trouble.

**Comment by steved0x** [comment]
@mohamed-shehata-m I believe I have found the solution, but want to make sure that I am understanding it correctly.

You had a hosted agent in the West Europe region, and you allow-listed the IP addresses in West Europe region, and also the capacity fallback geography of France (France Central region and France south region)?

Then your deployments failed because some of the agents were located in Ireland (North Europe region)?

The guidance for allow-listing IP addresses for hosted agents is to include all of the IP addresses from the regions in your Azure geography. In addition, if your region is Brazil South or West Europe, you must include the IP addresses for all the regions in the fallback geography.

I will add a note to clarify that, and while I can't find a history, I wonder if the [Azure geographies and regions](https://azure.microsoft.com/en-us/global-infrastructure/geographies/) changed since this article was written.

Do I understand correctly? I am going to update that article to clarify and close this issue, but please reactivate it and I have misunderstood and we can take another look at it together.

Thank you.
