### ISSUE TITLE
Extension cannot be found in the marketplace.

### ISSUE THREAD

**Issue by SebastianSchuetze** [MicrosoftDocs/vsts-docs#7604]
It does not show up. Does it even still exist?
https://appsource.microsoft.com/en-us/marketplace/apps?search=marketplace&product=power-bi

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e0c4c36-bf68-3950-e6fa-d1f4ab728f8b
* Version Independent ID: 088e51cc-a926-ffb7-53b9-2f53fdc65d14
* Content: [Extension Statistics Power BI Content pack - Visual Studio Marketplace](https://docs.microsoft.com/en-us/azure/devops/marketplace/extension-statistics-powerbi-contentpack?view=azure-devops)
* Content Source: [docs/marketplace/extension-statistics-powerbi-contentpack.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/marketplace/extension-statistics-powerbi-contentpack.md)
* Product: **devops**
* Technology: **devops-marketplace**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
@SebastianSchuetze -- Sebastian, thank you for your question.  You may find answers here:
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

@chcomley -- Chrystal, please look into this issue.

**Comment by SebastianSchuetze** [comment]
Thanks, @WilliamAntonRohm. I don't think this will help. As it is more a problem that the documentation is referencing an app for Power BI with Visual Studio Marketplace that cannot be discovered in the app store.

**Comment by WilliamAntonRohm** [comment]
@SebastianSchuetze -- Sebastian, thank you for clarifying.

**Comment by chcomley** [comment]
Hi @SebastianSchuetze, I'm looking into this and will be in touch. Thanks for reaching out.

**Comment by pkuma-msft** [comment]
Hey guys, I'm from Visual Studio Marketplace team (we own https://marketplace.visualstudio.com). Our team had published the "Visual Studio Marketplace Extension Statistics" PowerBI content pack couple of years ago.

I just want to clarify here that the issue is not with https://marketplace.visualstudio.com. The issue is that the above content pack can no longer be found in PowerBI store. I remember searching for this content pack at https://msit.powerbi.com few months back and I was able to find the content pack.

We need someone from the PowerBI team to look into this. I had created the below ticket on PowerBI to follow-up on this.

https://community.powerbi.com/t5/Service/Unable-to-find-Visual-Studio-Marketplace-Content-Pack/m-p/980541#M90569

**Comment by chcomley** [comment]
Thank you @pkuma-msft! Since this isn't a content issue, I'm going to go ahead and close this issue, while monitoring the other issue on the community site. Please @mention me if you have any further questions at the moment, @SebastianSchuetze. Thank you!

**Comment by acampbel** [comment]
Hi,
 
I am looking to use this content pack and likewise cant see it. Is it still avaialble or will it be in the future? Note I can't see the support ticket since I dont have a service now account and cant seem to create one either.
 
Thanks,
Andy

@pkuma-msft
