### ISSUE TITLE
Warehouse vs Analytics

### ISSUE THREAD

**Issue by StavroulaSsi** [MicrosoftDocs/vsts-docs#7645]
I have once read in a documentation here that if we want to enable Analytics, we have to disable Warehouse. But I can't find this article anymore. Is this still true? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb71f48d-32a7-5976-f585-902d28d7dc1c
* Version Independent ID: b207b4f0-23b7-33b0-ab44-59b2c6546cd8
* Content: [Install the Analytics extension on Azure DevOps Server - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/report/dashboards/analytics-extension?view=azure-devops-2019)
* Content Source: [docs/report/dashboards/analytics-extension.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/report/dashboards/analytics-extension.md)
* Product: **devops**
* Technology: **devops-analytics**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
@StavroulaSsi -- thank you for your question.  You may find answers here:
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

@KathrynEE -- please look into this issue.

**Comment by KathrynEE** [comment]
@StavroulaSsi - Thank you for your inquiry. No, you don't have to uninstall the warehouse in order to use Analytics.  There are some choices you make when you upgrade or create a new project collection on-premises. To learn more, see [Availability of Inheritance process model for new project collections](https://docs.microsoft.com/en-us/azure/devops/server/upgrade/get-started?view=azure-devops#availability-of-inheritance-process-model-for-new-project-collections).
