### ISSUE TITLE
Links from this page don't resolve to expected content

### ISSUE THREAD

**Issue by michaelrbentley** [MicrosoftDocs/vsts-docs#7652]
When clicking on a link in the index, I'm redirected to a content page that doesn't contain the expected information. For example, I want to know more about "Make requests on behalf of others". The link goes to a page that doesn't tell me anything about the permission I'm keen to know more about. This is one or many examples. Make it simple please. 🙏

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c399d3d3-3442-91a7-eb72-f0451b735cd1
* Version Independent ID: 5c4f77ec-5ef8-afe7-8e96-f1b4238f8f44
* Content: [Permissions and role lookup guide - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/security/permissions-lookup-guide?toc=%2Fazure%2Fdevops%2Fsecurity-access-billing%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fsecurity-access-billing%2Fbreadcrumb%2Ftoc.json&view=azure-devops#feedback)
* Content Source: [docs/organizations/security/permissions-lookup-guide.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/security/permissions-lookup-guide.md)
* Product: **devops**
* Technology: **devops-security**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by KathrynEE** [comment]
@michaelrbentley - Thank you for your inquiry. To gain more information on the definition of a permission, you can  look it up in the [Permissions and groups reference](https://docs.microsoft.com/en-us/azure/devops/organizations/security/permissions). I've updated the link for the one you've mentioned. Most of the links in the Lookup article point you to where you can change the permission.  For the "Make requests on behalf of others" permission - you only should assign this to a service account so that it can perform the necessary operations required of it.
