### ISSUE TITLE
Missing preview features

### ISSUE THREAD

**Issue by ross-bohr** [MicrosoftDocs/vsts-docs#766]
Our VSTS collection is hosted in West Europe Azure region. We have opted in for every preview feature so far, but now these two new preview features: "**Approval gates in releases**" and "**New release progress views**" are **not available** in our "Preview features" menu for our collection. Is this due to the region or a bug ?

**Comment by thomps23** [comment]
Please accept our apology for the significant delay in addressing this issue.

It looks like you're working through an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
