### ISSUE TITLE
How to copy the current value of a field

### ISSUE THREAD

**Issue by ShirmyQ** [MicrosoftDocs/vsts-docs#7711]
When I copy field just like &lt;COPY from="field" field=System.AssignedTo" /&gt; and save the item, it always gets previous value of "System.AssignedTo". but I want its current value. 

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: c1d94b21-0d87-af97-bb99-40595bfb38e2
* Version Independent ID: 0c118aeb-8b37-84a7-1d5c-ac8557258146
* Content: [Define default value or copy a value - TFS](https://docs.microsoft.com/zh-cn/azure/devops/reference/xml/define-default-copy-value-field?view=azure-devops-2019#SaveValue)
* Content Source: [docs/reference/xml/define-default-copy-value-field.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/reference/xml/define-default-copy-value-field.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @mijacobs
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
@ShirmyQ -- thank you for your question. 

In the article's [Syntax](https://docs.microsoft.com/zh-cn/azure/devops/reference/xml/define-default-copy-value-field?view=azure-devops-2019#Syntax) section is a note:
> If the work item is being changed, the COPY or DEFAULT elements rule may select either the current or previous value from the source field.

It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
