### ISSUE TITLE
Dependency Tracker Disable Timeline

### ISSUE THREAD

**Issue by Friedduc** [MicrosoftDocs/vsts-docs#7721]
Unable to disable use of Timeline when changing the default code `"timelineEnabled": true,` to
`"timelineEnabled": false,`. Result is that the Timeline feature remains and its code value reverts back to true.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1714e91-58b6-9911-0da6-7555d09eccb3
* Version Independent ID: 2a317fb7-67cb-a355-8fe2-8cd0e147acdc
* Content: [Plan and track dependencies across teams and organizations using the Dependency Tracker extension - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/boards/extensions/dependency-tracker?view=azure-devops#configure-the-dependency-tracker)
* Content Source: [docs/boards/extensions/dependency-tracker.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/extensions/dependency-tracker.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
