### ISSUE TITLE
Link URLs containing "+" characters do not render properly in the Wiki page

### ISSUE THREAD

**Issue by perharjnk** [MicrosoftDocs/vsts-docs#7722]
Can you please explain how I can somehow get the Wiki page to properly render the links with URLs like "http://mydomain.com/apps/reportforms/reportdetail.aspx?sOoYJ+5BzDYSW7zpg+WYW3wk+G1CnSaicXXZdXvqFXg="? The wiki page replaces the "+" characters in the query string into blank spaces breaking the URL link to the resource. Is there way to escape them? I tried replacing them with %2B but that was rendered as is and the target application did not like that either. Anyway to force the Wiki page to render the "+" character as is?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa622358-f5bb-1f5c-177a-081a37b6acef
* Version Independent ID: 72f7fd16-a822-66c8-3a34-8905645ce5f2
* Content: [Markdown syntax for files, widgets, and wikis - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=azure-devops#feedback)
* Content Source: [docs/project/wiki/markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
