### ISSUE TITLE
Azure Devops Secure FIle

### ISSUE THREAD

**Issue by wamullens** [MicrosoftDocs/vsts-docs#7767]
I've uploaded a secure file and when I try to pull it down using Download Secure File task I'm getting a unauthorized error during the pre-job stage. I've checked the security of the library for secure file, the security for the file itself, the repo security. I'm completely lost, I've tried all the documentation online etc.  

![image](https://user-images.githubusercontent.com/10821007/78037566-bda10d00-7339-11ea-93ac-cb00a460ddf2.png)

![image](https://user-images.githubusercontent.com/10821007/78037639-d14c7380-7339-11ea-9006-51170af7a4a2.png)

**Comment by wamullens** [comment]
![image](https://user-images.githubusercontent.com/10821007/78038301-b0d0e900-733a-11ea-86ac-d23b48344540.png)

**Comment by WilliamAntonRohm** [comment]
@wamullens -- thank you for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around your general task.

**Comment by wamullens** [comment]
Hey William, So we are creating a Release Pipeline in Azure Devops. We have a Powershell script task that calls the secure file that we uploaded. When it does the pre-job to get the secure file it says it's unauthorized...

**Comment by WilliamAntonRohm** [comment]
It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

Thank you for contacting us.
