### ISSUE TITLE
Issues with files that can't be deleted?

### ISSUE THREAD

**Issue by vishnu4** [MicrosoftDocs/vsts-docs#7774]
When i do a build push, i like to delete all the node_modules files from the build before i package it up.  This usually works, although lately i've had an issue with files whose names are too long.  I can set this task to 'continue on error', but while it's trying to unsuccessfully delete, it adds an extra 10 minutes to a process that would usually take less than 1.  Are there any settings or parameters to help speed this process up, or fix the error?  

Example error response:

The path D:\TfsBuildAgents\vsts-agent-win-x64-2.136.1\_work\10\s\CoBRAMVC4Portal\node_modules\.cache\terser-webpack-plugin\content-v2\sha512\fe\67\2ed03bce90a8f29902eccab75b6b2d5b66b05f000f871ec1b9f3f529da2519954f3c8c587f9076972f42cf37bf9c077e958eec6d5bac725e36ac12fdfe2a is too long.
##[error]Error: Failed rmRF: EPERM: operation not permitted, unlink 'D:\TfsBuildAgents\vsts-agent-win-x64-2.136.1\_work\10\s\CoBRAMVC4Portal\node_modules'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cd0e110-4b14-2d96-f28e-d2d2ef53b966
* Version Independent ID: 76cb1df7-c2c5-2de0-fd14-93175838934f
* Content: [Delete Files task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/delete-files?view=azure-devops&source=docs)
* Content Source: [docs/pipelines/tasks/utility/delete-files.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/utility/delete-files.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vtbassmatt
* Microsoft Alias: **macoope**

**Comment by vtbassmatt** [comment]
One thing that may help is not having your agent work directory so deeply nested. If you can reconfigure your agents to use something like `D:\_w`, you're less likely to run into `MAX_PATH` issues.

If you can't reconfigure your agents, the easiest solution is to do this from a script instead of the Delete Files task. Usually if you throw the long path prefix (`\\?\`) on your path, the normal `del` and `rmdir` commands will work. Something like: `del /f/s/q \\?\D:\TfsBuildAgents\vsts-agent-win-x64-2.136.1\_work\10\s\CoBRAMVC4Portal\node_modules.cache\`.

**Comment by vishnu4** [comment]
@vtbassmatt  Thank you, but unfortunately that still doesn't work, and i don't see an easy way to trim the file name at the front in TFS right now.  I'll see if i can find a different solution then.
![SharedScreenshot](https://user-images.githubusercontent.com/1782150/78155302-2350d000-73f2-11ea-9f60-a45b4e580f8d.jpg)
