### ISSUE TITLE
Am not able to DISABLE the Branch Policy, to bypass PULL REQUEST

### ISSUE THREAD

**Issue by ahtesh** [MicrosoftDocs/vsts-docs#7776]
I had set Branch Policy for a GIT Branch. Now, when I remove all the selections of Branch Policy and SAVE, still I see the branch policy symbol (icon) on the branch name. Without a PULL REQUEST, Am not able to PUSH any code into the branch.
Is there no option to PUSH code into the branch, without a PULL REQUEST ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cd986e0-608c-1d8c-6faf-ecdb12e10bc6
* Version Independent ID: d60c996e-187e-dd6b-7f3a-dd056a1603f4
* Content: [Protect your Git branches with policies - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-policies?view=azure-devops#feedback)
* Content Source: [docs/repos/git/branch-policies.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/branch-policies.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
