### ISSUE TITLE
Some of our Webhooks can't see the "Request" "Response" "Event" tab from History

### ISSUE THREAD

**Issue by liagao** [MicrosoftDocs/vsts-docs#7777]
The webhook we can see those information is:  "Build Xap-FastSCD-SyncSubscription"
The webhook we can't see those information is: "Build Xap-IsolateBuildAndValidate-SharedProd"

Could you help to check why we can't see those information bacause we need them to debug some issues. 

Thanks! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4806b641-fdb1-c0e9-081c-c007807c7cdb
* Version Independent ID: f59d8501-1285-be79-b084-8371ed8395bb
* Content: [WebHooks with Azure DevOps Services - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/service-hooks/services/webhooks?view=azure-devops#feedback)
* Content Source: [docs/service-hooks/services/webhooks.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/service-hooks/services/webhooks.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
