### ISSUE TITLE
How to run as a sudo user in MS Hosted agent?

### ISSUE THREAD

**Issue by gdprtcl** [MicrosoftDocs/vsts-docs#7782]
The documentation states that MS Hosted Agent can "Run as an administrator on Windows and a passwordless sudo user on Linux"
How does that work? I get sudo: command not found error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61db3371-6395-88a2-fb78-09f98790ab1b
* Version Independent ID: ef6f1bf7-02b8-9093-b84e-c9bde7d98e57
* Content: [Microsoft-hosted agents for Azure Pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops)
* Content Source: [docs/pipelines/agents/hosted.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/hosted.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
