### ISSUE TITLE
How to prevent overwriting an existing deployment?

### ISSUE THREAD

**Issue by FMauroy** [MicrosoftDocs/vsts-docs#7797]
Hi, in our tests, we have noticed that the deployment template that is generated in this step and used to deploy the module to the edge overwrites the current deployment. Modules I have added by hand before just disappeared. Is there a way to make the system add/update the module definition in the edge deployment configuration? If not, we would need to define the other modules we use in the template, which could be OK for marketplace ones (like OPC Publisher we use everywhere), but for special cases... Also, if we have 2 edge module projects that we want to deploy to the same system, each would overwrite the other. Unless I missed something? Any insight would be appreciated! Thanks beforehand.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d93a0bac-faf1-3c5d-d358-487d3d0d4f9e
* Version Independent ID: 06d36475-d60d-067d-0c12-d5af0ff1d85c
* Content: [Azure IoT Edge task - Azure Pipelines](https://docs.microsoft.com/en-gb/azure/devops/pipelines/tasks/build/azure-iot-edge?view=azure-devops)
* Content Source: [docs/pipelines/tasks/build/azure-iot-edge.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/tasks/build/azure-iot-edge.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

Also, the product teams aren’t always watching this repository, so to make sure it gets in front of them for triage, please [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.

**Comment by FMauroy** [comment]
In fact, layered deployments can be used just for this use case. We use that now with great success!
https://docs.microsoft.com/en-us/azure/iot-edge/module-deployment-monitoring#layered-deployment
HTH
