### ISSUE TITLE
Query by specified date range

### ISSUE THREAD

**Issue by wysockilm** [MicrosoftDocs/vsts-docs#7799]
Trying to create a user story query by specified target date range, but results still display dates outside of range, i.e. items in 2021.  Any suggestions?
Work Item Type = User Story
State = [Any]
Target Date &gt; 1/1/2020
Target Date &lt;= 11/14/2020
Target Date &lt;&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba14ee34-2de7-706f-ae44-be969fde352b
* Version Independent ID: f7ba18e9-42e4-ef07-e36b-377fb787aa72
* Content: [Query by date or current iteration - Azure Boards](https://docs.microsoft.com/en-us/azure/devops/boards/queries/query-by-date-or-current-iteration?view=azure-devops#feedback)
* Content Source: [docs/boards/queries/query-by-date-or-current-iteration.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/boards/queries/query-by-date-or-current-iteration.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
