### ISSUE TITLE
Mermaid diagrams on published wikis working?

### ISSUE THREAD

**Issue by stoune** [MicrosoftDocs/vsts-docs#7807]
Does Mermaid diagrams works on published wikis?
I have tested diagram on provisioned wiki, but it does not appear on published wikis.
If this is expected then it should be mentioned in documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29f1e43f-a069-dd88-7fc7-9cc497fb94f0
* Version Independent ID: c261afa7-6eb7-b3f0-9f92-6d2f3c5ac336
* Content: [Markdown syntax for wikis in Azure DevOps - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-markdown-guidance?view=azure-devops#feedback)
* Content Source: [docs/project/wiki/wiki-markdown-guidance.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/project/wiki/wiki-markdown-guidance.md)
* Product: **devops**
* Technology: **devops-collab**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by WilliamAntonRohm** [comment]
It looks like you've encountered an issue with the product itself, rather than an issue with the documentation. To make sure it gets in front of the right people, please [submit your bug]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21) here. 

Also, here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
