### ISSUE TITLE
how to view build artifacts in Azure devops portal

### ISSUE THREAD

**Issue by pretty25** [MicrosoftDocs/vsts-docs#7812]
The above view in Explore, download, and deploy your artifacts section is no longer valid in current azure pipelines view unless, I am not aware of any other views to look at drop files folder as shown above, so could you please check and advise how can I view this drop as latest in current available Az pipelines job runs ??
thx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7175ebdc-0bba-7e00-d113-036a5cffe5fa
* Version Independent ID: 149ab9f4-0b7d-97e7-6cf5-1b54fd04c63c
* Content: [Publish and consume build artifacts in builds - Azure Pipelines and TFS](https://docs.microsoft.com/en-us/azure/devops/pipelines/artifacts/build-artifacts?view=azure-devops&tabs=yaml#feedback)
* Content Source: [docs/pipelines/artifacts/build-artifacts.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/artifacts/build-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd-artifacts**
* GitHub Login: @ramiMSFT
* Microsoft Alias: **rabououn**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
