### ISSUE TITLE
JSON body for all service connection types?

### ISSUE THREAD

**Issue by mapoitras** [MicrosoftDocs/vsts-docs#7816]
Is it possible to get the json body for all connection types instead of having to do a capture?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 209081c3-76a3-562e-3479-e6b63b7ec2c7
* Version Independent ID: c0be31ee-9568-cddd-2ee4-af196aa318d8
* Content: [Create Service Endpoint using Azure DevOps CLI - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/cli/service_endpoint?view=azure-devops)
* Content Source: [docs/cli/service_endpoint.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/cli/service_endpoint.md)
* Product: **devops**
* Technology: **devops-ref**
* GitHub Login: @KathrynEE
* Microsoft Alias: **gsaral**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by FilBot3** [comment]
Yeah, that bot doesn't really help much with kinds of questions.
