### ISSUE TITLE
Checking out lfs objects on self hosted agent fails

### ISSUE THREAD

**Issue by TclasenITVT** [MicrosoftDocs/vsts-docs#7817]
Hi Azure Devops Team, 
we have a self hosted agent that is unable to checkout git lfs objects but just checking out the git repo works fine. Side note this server also hosts build agents for an on prem azure devops sever these can checkout git lfs objects just fine from the onprem hosted repos. 

```
For the azure devops service repo we get this errror when trying to checkout from git lfs:
fatal: InvalidOperationException encountered.
   Showing a modal dialog box or form when the application is not running in UserInteractive mode is not a valid operation. Specify the ServiceNotification or DefaultDesktopOnly style to display a notification from a service application.
```
Is there a special port we need to open or something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b846aea-82f7-a988-67d8-1b5e74b61ed2
* Version Independent ID: 2d632729-bb33-c0a0-c996-e1d8e86c2e23
* Content: [Build Azure Repos Git repositories - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=classic)
* Content Source: [docs/pipelines/repos/azure-repos-git.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/repos/azure-repos-git.md)
* Product: **devops**
* Technology: **devops-cicd-repos**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
