### ISSUE TITLE
How do you change the default Priority and Severity settings for Bugs?

### ISSUE THREAD

**Issue by TobyMan74** [MicrosoftDocs/vsts-docs#7822]
Priority is set to 2 and Severity is set to 3 by default.  When users forget to update these fields it impacts on our reports.  How do we change the defaults in these fields?  We'd like to set them to 3 and 4 respectively.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1152275-e1e9-cad2-4b6d-e7bab8ed1b74
* Version Independent ID: 231b91a8-c5ac-36db-e2ae-8d837fb70e4b
* Content: [Customize your work tracking experience - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/reference/customize-work?view=azure-devops#feedback)
* Content Source: [docs/reference/customize-work.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/reference/customize-work.md)
* Product: **devops**
* Technology: **devops-agile**
* GitHub Login: @KathrynEE
* Microsoft Alias: **kaelli**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
