### ISSUE TITLE
branch permissions 

### ISSUE THREAD

**Issue by ForBurning** [MicrosoftDocs/vsts-docs#7831]
first i new the master branch, then i create the dev branch from the master branch.
how can i set the users who can read the dev branch and who cannot read the dev branch?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bf345ce-1831-bc64-bc2a-617fb69b3352
* Version Independent ID: 3f1e08ea-3db8-92e8-1873-953d1f026f25
* Content: [Set Git branch security and permissions - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/branch-permissions?view=azure-devops)
* Content Source: [docs/repos/git/branch-permissions.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/branch-permissions.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
