### ISSUE TITLE
Azure Devops MS-hosted agent IP address

### ISSUE THREAD

**Issue by Milanski** [MicrosoftDocs/vsts-docs#7844]
We use Azure DevOps with Microsoft-hosted agents, and because we would like to apply authorized IP ranges for our AKS we need the agent IP addresses. To automate the process in our release pipeline we have included Azure CLI task with the command :
`AGENT_IP=$(curl -s https://ipinfo.io/json | jq -r .ip)`
`az aks update --resource-group  xxx --name yyy --api-server-authorized-ip-ranges ${AGENT_IP}`
All the AGENT_IPs, we are getting from the command line, are not listed in the weekly json file (e.g: 13.74.46.232/32, 40.89.171.234/32).
Even the operation is executed successfully and the AGENT_IP is included in the "apiServerAccessProfile.authorizedIpRanges" section, sometimes we are not able to deploy our microservice to the AKS and we are getting an error: "Unable to connect to the server: dial tcp xx.xx.xx.xx:443: i/o timeout". However sometimes the deployment is successful, even though the AGENT_IP is not listed in your weekly json.

1. Why the IP addresses I am getting, are not in the weekly json file ?
2. Randomly I am able to deploy to AKS ?

**Comment by alibutt30** [comment]
Upvote (+1)

**Comment by WilliamAntonRohm** [comment]
@Milanski -- Milancho, thank you for your feedback. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your questions: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops) 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
