### ISSUE TITLE
VSTS links to this page for information that is not present on thsi page

### ISSUE THREAD

**Issue by Pxtl** [MicrosoftDocs/vsts-docs#7846]
I get this message from VSTS pointing me to this page:
"""
The number of items on your backlog exceeds the configured limit of 500. Your current total is: 537. For more information, click here.
"""

and it takes me here.  THere is no guidance on this page to resolve the issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 993e00a3-b7d1-8095-5960-f6f12e8606a4
* Version Independent ID: e125d539-3678-2ab4-3591-f055e7225cbc
* Content: [Create a project - Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/organizations/projects/create-project?view=azure-devops&tabs=preview-page&source=docs#feedback)
* Content Source: [docs/organizations/projects/create-project.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/organizations/projects/create-project.md)
* Product: **devops**
* Technology: **devops-accounts**
* GitHub Login: @chcomley
* Microsoft Alias: **chcomley**

**Comment by chcomley** [comment]
Hi @Pxtl, Thanks for the heads up on this. This is a link maintained by the product group, rather than documentation group. They'll need to figure out where the information is and update the link within the product. If you wouldn't mind, it'd be great if you could report this [here](https://developercommunity.visualstudio.com/spaces/21/index.html), and then select **Report a problem** >  **Azure DevOps**, and then provide the info. Thanks very much for this. I'm sorry I don't know where the information lies.
