### ISSUE TITLE
Microsoft-hosted agent network capabilities 

### ISSUE THREAD

**Issue by victor-gallet** [MicrosoftDocs/vsts-docs#7849]
Is there a way to control network bandwidth on a Microsoft-hosted agent? Is there any limit on network received and transmitted bytes from the Microsoft-hosted agent?

For example, when we run an Azure Container which contains a database to run tests from a pipeline, we experienced unusually long query response time.   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47625b86-abd5-ee15-6d61-8bcf81861b96
* Version Independent ID: be9a6174-a69b-7aed-d584-5f602fcc5eb4
* Content: [Azure Pipelines Agents - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops&tabs=browser#feedback)
* Content Source: [docs/pipelines/agents/agents.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/agents/agents.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question: 

- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)  
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
