### ISSUE TITLE
Needs VSTS instructions & walkthrough

### ISSUE THREAD

**Issue by jimhess** [MicrosoftDocs/vsts-docs#790]
Needs VSTS instructions & walkthrough

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 159cece6-ada6-e50c-a236-0d49aed6d1be
* Version Independent ID: f6cc8cee-f37e-e738-3143-aa7f185fb461
* Content: [Copy changes to a branch with cherry-pick](https://docs.microsoft.com/en-us/vsts/git/tutorial/cherry-pick?view=vsts&tabs=visual-studio)
* Content Source: [docs/git/tutorial/cherry-pick.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/git/tutorial/cherry-pick.md)
* Service: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@jimhess I agree, I am planning to add VSTS steps to these tutorials in addition to the Visual Studio and Command Line steps. I have got work items on the backlog and I plan do get them done by the end of this summer. Thank you for your feedback!

**Comment by b4tt1enet** [comment]
@steved0x I know you said you were working on adding the VSTS (now Azure DevOps) steps to the [documentation](https://docs.microsoft.com/en-us/azure/devops/repos/git/cherry-pick?view=azure-devops&tabs=visual-studio), but I still don't see it on there. Is this feature even available in Azure DevOps? I see how to cherry-pick from a pull request, but it pulls all the commits from the pull request all the time. Is there a way to "only bring the changes from the commits you select, instead of all the changes in a branch", like the documentation says?

It's been almost a year since this Issue has been closed.

Thanks!
