### ISSUE TITLE
Typo in "Develop a web extension for VSTS" code sample - FIXED

### ISSUE THREAD

**Issue by razvansalajan** [MicrosoftDocs/vsts-docs#826]
I might miss something. Following the steps from the tutorial I don't see the extension in the code tab. It gets installed properly (i.e.: it shows up in the installed extensions within the account). If I add  <"scopes": ["vso.code_manage"],> to the vss-extension.json the extension shows up. Did I miss something or the vss-extension.json file should be updated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14955ee9-29f2-46fe-3a8d-a42666f53ffc
* Version Independent ID: 5d417cd0-a671-ee30-8fca-5f8b0addd328
* Content: [Develop a web extension for VSTS](https://docs.microsoft.com/en-us/vsts/extend/get-started/node?view=vsts)
* Content Source: [docs/extend/get-started/node.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/extend/get-started/node.md)
* Service: **unspecified**
* Product: **devops**
* GitHub Login: @wismythe
* Microsoft Alias: **wismythe**

**Comment by sitwalkstand** [comment]
I've tried adding the vso.code_manage scope and updated the extension, but I am still not seeing the "My Hub" under my Code section.

**Comment by willsmythe** [comment]
Thanks for reporting the problem (and sorry for the trouble).

There is a typo in the sample manifest file shown in the docs (a fix to the docs is underway). In the meantime, you can:

1. Update `vss-extension.json` and replace ms.vss-work-web.code-hub-group with `ms.vss-code-web.code-hub-group` (line 19). This is why the hub is not appearing (the documented target hub group ID is incorrect).
2. Increment the version at the top of the manifest file (e.g. change 1.0.0 to `1.0.1`)
3. Run `tfx extension create` to create a new .vsix
4. From the Marketplace portal, select your extension, click the "...", choose "Update", and browse to your new .vsix file.
5. After a few seconds of verifying, you should see the new version of your extension listed
6. Re-navigate to your project-level experience (the "try it" section, steps 1-3) or just refresh your browser page if you're already there. You should now see the hub.

Note: "scopes" is not required and doesn't impact the visibility of this hub. The problem was an incorrect target hub group ID.

**Comment by elbatk** [comment]
The fix above should take care of the problems you two are having! Closing this issue, feel free to comment if you're still having trouble.
