### ISSUE TITLE
Unable to Download Secure File on a Private Release Agent

### ISSUE THREAD

**Issue by Prashanth-PS** [MicrosoftDocs/vsts-docs#828]
This task is failing on a private agent with the below error: 
##[error]Error: connect ETIMEDOUT 13.107.6.175:443

**Comment by nschonni** [comment]
Think https://github.com/Microsoft/vsts-agent is a better repo to report this

**Comment by Prashanth-PS** [comment]
Though I have raised a ticket with them link: https://github.com/Microsoft/vsts-agent/issues/1574#issuecomment-391155057 
It has been closed saying "@Prashanth-PS please log an issue in VSTS-Tasks repository for task related question. :)"
Please provide a solution at the earliest

**Comment by nschonni** [comment]
Sorry for the bad advice. I think they are probably talking about this repo then https://github.com/Microsoft/vsts-tasks since it looks like this is the task you're talking about https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/DownloadSecureFileV1

**Comment by thomps23** [comment]
Please accept our apology for the significant delay in addressing this issue.

It looks like you're working through an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
