### ISSUE TITLE
Build/Release Retention Policy

### ISSUE THREAD

**Issue by boga5** [MicrosoftDocs/vsts-docs#862]
**When does this Build/Release Retention policy applicable?**
1. Only within VSTS Artifactory?
2. Is it applicable for artifacts on self-hosted Build agents?
3. Is it applicable to the artifacts stored in File Share which we publish?
4. If we publish to a file share, does the artifacts will be saved in VSTS Artifactory? If yes, do these artifacts come under Retention policy?. If no, do these artifacts saved in File share comes under retention policy?

**Few Lame Questions:**
A. Can we see VSTS Artifactory? Or is it just the artifacts which we can view on VSTS Build Definition -> Build Number -> Artifacts tab
B. If we publish the artifacts to Visual Studio Team Services/TFS, do these get saved in VSTS Artifactory?

**Comment by steved0x** [comment]
@alexhomer1 Can you take a look at this one and assign to the right person?

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will pass this on to the product team and update the topic based on their response.

**Comment by mijacobs** [comment]
Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
