### ISSUE TITLE
With VS15.7.1 we can now associate MSTestV2 netcore unit test to test cases through Test Explorer.

### ISSUE THREAD

**Issue by GregoryOtt** [MicrosoftDocs/vsts-docs#898]
Can you clarify the documentation as the assertions below are wrong :
=> Unit tests that use the.NET Core framework cannot be associated with a test case.
=> Tests that use other test frameworks such as Version 2 of the MSTest framework, xUnit, nUnit, Chutzpah, and others cannot be associated with a test case.n

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 168c728f-c654-eff8-b6d3-c7af9e949324
* Version Independent ID: 9005d526-14cc-3170-a9bd-680a4b4eb639
* Content: [FAQs for continuous testing in VSTS and TFS](https://docs.microsoft.com/en-us/vsts/build-release/test/reference-qa?view=vsts#associating-tests-with-test-cases)
* Content Source: [docs/build-release/test/reference-qa.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/test/reference-qa.md)
* Service: **unspecified**
* Product: **devops**
* GitHub Login: @alexhomer1
* Microsoft Alias: **ahomer**

**Comment by shteeven** [comment]
I can confirm. I am able to associate with .Net Core and NUnit. They fail when trying to run from the test plans, but I am able to associate.

**Comment by PBoraMSFT** [comment]
@GregoryOtt - this is not officially supported. The association experience for MSTest v2 and other test types was opened up in VS 15.7 accidentally because of an issue. You will find that as that issue got addressed, the association got blocked again in VS 15.8.
We are working on supporting it officially and is expected to become available in the 15.9 timeframe. At that time, the docs will be updated to reflect the same.

@shteeven - the reason they fail is because it's not supported. See my comments above.

@alexhomer1 - FYI.
