### ISSUE TITLE
Small teams / Azure AD guidance:  Making Azure AD requirements clearer

### ISSUE THREAD

**Issue by cbailiss** [MicrosoftDocs/vsts-docs#903]
For individuals and small orgs who aren't using Azure AD, haven't got TFS and Azure AD sync'd to an on-prem domain, this guide is unclear.  
Especially if the primary way of interacting with VSTS has been using MSA accounts (which was true in my case).
After a lot of reading I still wasn't clear whether I could migrate a non-AD linked TFS Express collection to VSTS using the Migrate tool.  I wanted a high-fidelity import that preserves history.  I wasn't so concerned about identities not being matched.
The "TfsMigrator validate" step (following the example in the PDF on the "Migrate Options" docs page) initially failed with the error "Identity Validation failed, please provide a TenantDomainName".
It was only after I carried out the following steps that I was able to proceed:
1) When validating, specified the tenant as part of the validate command line, e.g.
TfsMigrator validate /collection:http://localhost:8080/tfs/DefaultCollection  /tenantDomainName:david342.onmicrosoft.com
2) Before running the "TfsMigrator prepare" command, set up an user in Azure AD (e.g. david@david342.onmicrosoft.com)
3) Specified the user and region on the prepare command line:
TfsMigrator prepare /collection:http://localhost:8080/tfs/DefaultCollection /tenantDomainName:david342.onmicrosoft.com /accountRegion:WEU
4) At the login prompts thrown up by the TfsMigrator, login as the Azure AD user.

The above needs to be clearer in the documentation.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a35b397-3fe8-122e-042e-280326f88a38
* Version Independent ID: 3e0f0afc-abeb-01be-d767-813cd6ad78db
* Content: [Migration import from TFS to Visual Studio Team Services (VSTS)](https://docs.microsoft.com/en-gb/vsts/articles/migration-import?utm_source=ms&utm_medium=guide&utm_campaign=vstsdataimportguide&view=vsts#generating-sas-key)
* Content Source: [docs/articles/migration-import.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/articles/migration-import.md)
* Service: **unspecified**
* Product: **devops**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by roofers** [comment]
Hi @cbailiss - I'm sorry for the issue that you've run into. The parameter /tenantdomainname should be optional for validate, but that regressed with our latest release to become required. We have a fix in place and are working on getting that fix released ASAP. TfsMigrator will notify you when you run a command if a newer version of the tool is available.

**Comment by SamGrantham** [comment]
Hi @cbailiss and @roofers,

Just to be clear here, ALL high fidelity migrations use AAD.  the Validation step is mostly to ensure that the data-shape of the TFS Instance is compatible with the Import Process and does not require authentication.

However the Prepare step and the Import steps DO require this information.

It is possible to set this up and then to unlink it post import if that is your desire, it is not documented directly because it is not an expected path.

1.	[Set up an AAD Tenant](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-howto-tenant)
2.	Import using the guide and documentation
3.	[Disconnect the VSTS from the Azure AD](https://docs.microsoft.com/en-us/vsts/organizations/accounts/disconnect-organization-from-aad?view=vsts)

**Comment by elbatk** [comment]
This is an older issue and seems like we've got it all figured out! Closing it out for now!
