### ISSUE TITLE
Export current build definition to YAML

### ISSUE THREAD

**Issue by tura08** [MicrosoftDocs/vsts-docs#909]
In the case where one already has a build definition, but would like to use YAML moving forward to maintain the build definition as code, is it possible to export a current build definition to YAML and then place that in the repo?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87686bea-7c46-cd47-d1a9-128e16b63a23
* Version Independent ID: ace78317-e562-e35d-781d-23cd7d2dfff2
* Content: [CI Build in code using YAML](https://docs.microsoft.com/en-us/vsts/build-release/actions/build-yaml?view=vsts#automatically-create-a-yaml-build-definition)
* Content Source: [docs/build-release/actions/build-yaml.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/build-release/actions/build-yaml.md)
* Service: **unspecified**
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by alexkokkinos** [comment]
Yes, it's currently possible.

1. Edit your build definition in VSTS
1. Navigate to the Tasks section
1. Select the entire process or any individual task and click the "View YAML" button on the top right area of the window. The icon looks like a clipboard.

You may need the Build YAML definitions Preview feature to be enabled to see the "View YAML" link in the first place (I'm not 100% on that).

**Comment by tura08** [comment]
Great thanks. I think it would be good to include that in the docs.

**Comment by andyjlewis** [comment]
Yes, and thank you for calling attention to this issue. We've had some big site changes going on that have gotten in the way of some of these kinds of fixes. I'll follow up.

**Comment by richardzone** [comment]
Hey @alexkokkinos, I cannot find the "View YAML button" anymore. 
I've tried both old UI and new preview UI, neither of them has the button.

Could you help me with finding it?

**Comment by ltarjanyi** [comment]
Turn on "Build YAML definitions" preview feature for your organization. Than you will see the "View YAML" link in the pipeline edit view (where define, config the tasks...).

**Comment by attilaszaszlateral** [comment]
On new VSTS accounts, it's no longer possible to create non-Yaml builds! Even if I disable the Build YAML definitions" preview feature. 
Cannot import a previously saved build.
If I create a new YAML build, and cannot add tasks, only have the pipline and the get sources section.
When I select an existing github connection in the sources section, I only have 4 github repos listed, with no possibility to load more. I gues MS QA had only on repo to test with.
Since a couple days, VSTS is a mess.

**Comment by emmakat** [comment]
@alexk any help for issue above?

**Comment by TechnicallyWilliams** [comment]
### Marketplace Tasks in YAML
When configuring a build definition from an existing YAML file, is there anyway to make the need to restore a marketplace task more obvious?  It would also be nice if it auto restored marketplace tasks.

I'm asking because a build definition based on a YAML file that makes any references to a marketplace task that the organization doesn't currently have will throw a "task does not exist" error.

_Thanks_

**Comment by dylanjohnsonsfo** [comment]
Is there any way to view YAML for the release stage? I can see the view YAML for the build but not for release. Would be super handy to be able to do this? Does anyone know how?
