### ISSUE TITLE
The "ASP.NET Core" VSTS build task no longer exists

### ISSUE THREAD

**Issue by craigktreasure** [MicrosoftDocs/vsts-docs#927]
The "ASP.NET Core" VSTS build task no longer exists. What is the proper task and configuration to use when building an ASP.NET Core project to be published to Azure? I have a seen a funky VSBuild task that has a bunch of MSBuild properties specified: /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactstagingdirectory)\\". But, that doesn't use the newer 'dotnet' tooling which would be nice for a cross platform build definition.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78b3a70c-0708-c7dc-4062-a826e2a24cfb
* Version Independent ID: 4f215b90-3712-7cf1-89aa-888f9fd5e7da
* Content: [Quick Start - Build and Deploy a ASP.NET Core app](https://docs.microsoft.com/en-us/vsts/pipelines/archive/apps/aspnet/aspnet-core-from-vsts-to-azure-web-app?view=vsts)
* Content Source: [docs/pipelines/archive/apps/aspnet/aspnet-core-from-vsts-to-azure-web-app.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/pipelines/archive/apps/aspnet/aspnet-core-from-vsts-to-azure-web-app.md)
* Service: **unspecified**
* Product: **devops**
* GitHub Login: @andyjlewis
* Microsoft Alias: **alewis**

**Comment by steved0x** [comment]
I'm not sure what happened Andy, I must have accidentally unassigned you somehow.

**Comment by thomps23** [comment]
Please accept our apology for the significant delay in addressing this issue.

It looks like you're working through an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)
