### ISSUE TITLE
Draw deployment groups and pools schema

### ISSUE THREAD

**Issue by VerdonTrigance** [MicrosoftDocs/vsts-docs#943]
Guys! I still don't understand how these pools and groups works!
I have one single project with many areas that related to real team projects. I have two independent test environment for one area (team) project called qa01 and qa02. I suppose that I may have ONE deployment pool for my VSTS project named Global (that contain all these areas) and MULTIPLE deployment groups in THAT deployment pool. But it always shocked me, when every deployment group creates own pool! WHY? Damn why deployment group always create new pool in same VSTS project??? I dont need multiple pools in my single Global project! I don't planning to share all these pools! 
Someone explain me how all of this works? And the best way is draw the scheme.

**Comment by steved0x** [comment]
@alexhomer1 Can you take a look and provide a few links to @VerdonTrigance - I'm not familiar enough with this documentation area to know if we have a gap, or if they just aren't able to find the right content to answer the question.

**Comment by alexhomer1** [comment]
Thank you for your feedback. I will pass this on to the product team and update the topic based on their response.

**Comment by RoopeshNair** [comment]
- Deployment pools are collection scoped and can share the targets with multiple team projects. 
- Deployment Groups are team project scoped and are backed by a Deployment Pools at the collection.

Deployment group (DG) represents your physical environment viz. UAT, Staging, Production etc. It also the defines the security boundary so that users don't get to deploy, to say production target without appropriate permissions on the DG (for example 'use'). Deployment pools help you to share the DG with multiple team projects if the same set of targets are shared by multiple teams. 

If every new deployment group binds itself to an existing pool, then you no longer have separation of concerns. i.e., every new target added to a new DG bound to an existing pool will be available for all team projects and to all DGs. Meaning dev, qa, and production targets are in a single big pool shared by everyone

**Comment by VerdonTrigance** [comment]
Still don’t understand why DG need a separate pool. Why multiple groups can’t belong one pool?

**Comment by RoopeshNair** [comment]
@VerdonTrigance  - Let's say we have 2 deployment groups `Dev` and `Prod`. Now instead of having independent pools backing them, you have only 1 deployment pool. Now every production machine is available for `Dev` deployment group and vice-versa.  i.e., every dev machine is available in `Prod` deployment group. Hope it helps

**Comment by VerdonTrigance** [comment]
You mean that DG's owner may add machines to his own DG (for example Dev) from Prod DG if both that groups are linked to the same DP, right? Ok, I understand. But let's back to situation where I have two independent QA environments for single project. I have to add my targets to one DP, tag them somehow and then use one DG associated with that DP with my independent releases? Is that possible?
