### ISSUE TITLE
Should group members be able to approve their own PRs?

### ISSUE THREAD

**Issue by sgwatgit** [MicrosoftDocs/vsts-docs#947]
I have "Require a minimum number of reviewers" checked.
I have "Minimum number of reviewers" set to 1.
I do not have "Allow users to approve their own changes" checked.

If I am in a group that automatically added as a required reviewer and I approve the PR, along with another team member, will the PR approval policy be met?

I've noticed when I Approve my own PR it doesn't count towards the 'minimum' required but it does show my group approval as being satisfied.

What are the rules behind this scenario?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cd986e0-608c-1d8c-6faf-ecdb12e10bc6
* Version Independent ID: d60c996e-187e-dd6b-7f3a-dd056a1603f4
* Content: [Protect your Git branches with policies](https://docs.microsoft.com/en-us/vsts/git/branch-policies?view=vsts)
* Content Source: [docs/git/branch-policies.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/git/branch-policies.md)
* Service: **unspecified**
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@sgwatgit Here is the example I am going to add to the article:

The **Allow users to approve their own changes** setting only applies to the **Require a minimum number of reviewers** policy, and doesn't affect other policies such as [Automatically include code reviewers](#require-a-minimum-number-of-reviewers). In the following example, Jamal Hartnett creates a pull request with the following policies configured:

 - **Require a minimum number of reviewers** is configured with two required reviewers.
 - **Allow users to approve their own changes** is not set. 
 - The **Fabrikam Team** group is a required reviewer, and Jamal is a member of that group.

In this example, since Jamal is part of the **Fabrikam Team** group, his **Approve** vote satisfies the required reviewer policy, but the pull request still requires two additional **Approve** votes to satisfy the **Require a minimum number of reviewers** policy, since his vote doesn't count toward that policy because **Allow users to approve their own changes** is not set.

**Comment by sgwatgit** [comment]
@steved0x Thanks, that's definitely a helpful explanation!

**Comment by steved0x** [comment]
@sgwatgit It's live now, thanks for a great question!
