### ISSUE TITLE
Unable to compile .net core 2.1 code with Hosted Linux Preview agent

### ISSUE THREAD

**Issue by allenbrubaker** [MicrosoftDocs/vsts-docs#970]
This task is failing for me:

queue: Hosted Linux Preview
....

bash: |
echo "Restoring nuget packages"
dotnet restore $CSPROJ --configfile ./nuget.config

echo "Compiling source code"
dotnet publish $CSPROJ -c Release -o ./obj/Docker/publish
displayName: Source > Build

The error is:
/usr/share/dotnet/sdk/2.1.101/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.TargetFrameworkInference.targets(135,5): error : The current .NET SDK does not support targeting .NET Core 2.1. Either target .NET Core 2.0 or lower, or use a version of the .NET SDK that supports .NET Core 2.1. [/opt/vsts/work/1/s/src/UL.Movere.CloudPricing.csproj]

**Comment by steved0x** [comment]
@allenbrubaker Sorry that you are running into trouble. The GitHub issues in this repo are to report documentation feedback. What article is associated with this feedback so I can assign it to the right author so they can take a look? Thank you.

**Comment by steved0x** [comment]
I'm closing this issue since it is not associated with a topic. To continue the discussion, please open a new issue that is associated with a topic by browsing to the topic on docs.microsoft.com and choosing **Content feedback** at the bottom. Thank you for your feedback.

![image](https://user-images.githubusercontent.com/1580889/42953695-fd174150-8b48-11e8-94de-26924ca79c71.png)
