### ISSUE TITLE
Change permissions with API

### ISSUE THREAD

**Issue by moshezvi** [MicrosoftDocs/vsts-docs#975]
Is it possible to make changes to the permissions not through tf, but rather through an API? 
Using tf assumes Developer Command Prompt, and is not easily integrated into a development flow. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 330532da-d568-b010-a154-62afb1844e4a
* Version Independent ID: 4efad37d-4ec2-033e-51b1-b9f588e675c6
* Content: [Require branches to be created in folders](https://docs.microsoft.com/en-us/vsts/git/how-to/require-branch-folders?view=vsts&tabs=vsts-tfs-web-portal)
* Content Source: [docs/git/how-to/require-branch-folders.md](https://github.com/MicrosoftDocs/vsts-docs/blob/live/docs/git/how-to/require-branch-folders.md)
* Product: **devops**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by mijacobs** [comment]
Thanks for your question. It looks like your question isn't an issue with the documentation, but an issue or question specific to your implementation or a bug in the product itself. 

For help with a specific task, here are a couple of options where you might consider asking your question:
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If you've encountered an issue with the product itself, to make sure it gets in front of the right people, please [submit your bug here]( https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

If you have an idea for improving the product, please [submit your idea here]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21).
