### ISSUE TITLE
./config.sh: line 29:  6458 Segmentation fault: 11  ./bin/Agent.Listener configure "$@"

### ISSUE THREAD

**Issue by qubuss** [MicrosoftDocs/vsts-docs#986]
Hey I Have problem with configuration tfs on Mac. TFS is running on local server in my company. I try connect with PAT Authentication type. 

Enter (Y/N) Accept the Team Explorer Everywhere license agreement now? (press enter for N) > y

>> Connect:

Enter server URL > https://tfs.company.local
Enter authentication type (press enter for Negotiate) > PAT
Enter personal access token > ****************************************************
Connecting to server ...
./config.sh: line 29:  6458 Segmentation fault: 11  ./bin/Agent.Listener configure "$@"

My Mac OS version = High Sierra 10.13.5

**Comment by steved0x** [comment]
@qubuss Thank you for your feedback. The GitHub issues in this repository are intended to allow readers to submit feedback on our documentation. Can you let me know what topic you were reading when you encountered this issue, so I can route it to the right author? Thank you.

**Comment by nschonni** [comment]
The repo for support of the agents is https://github.com/Microsoft/vsts-agent/issues

**Comment by steved0x** [comment]
I'm closing this issue since it is not associated with a topic. To continue the discussion, please open a new issue that is associated with a topic by browsing to the topic on docs.microsoft.com and choosing **Content feedback** at the bottom. Thank you for your feedback.

![image](https://user-images.githubusercontent.com/1580889/42953695-fd174150-8b48-11e8-94de-26924ca79c71.png)
